# These are example parameters to overwrite for the privatenet cluster.
# Refer to src/app/firedancer/config/default.toml for documentation.

[consensus]
    expected_shred_version = 0
[gossip]
    entrypoints = [] # specify private entrypoints
[funk]
    heap_size_gib = 20
    max_account_records = 1048576
    max_database_transactions = 512
