# These are sample parameters to overwrite to join the testnet cluster.
# Refer to src/app/firedancer/config/default.toml for documentation.

[consensus]
    expected_shred_version = 0
[gossip]
    entrypoints = [
        "entrypoint1.testnet.solana.com:8001",
        "entrypoint2.testnet.solana.com:8001",
        "entrypoint3.testnet.solana.com:8001",
    ]
