[hugetlbfs]
max_page_size = "huge"

[runtime]
heap_size_gib = 4

[runtime.limits]
max_live_slots = 512
snapshot_grace_period_seconds = 15

[layout]
verify_tile_count = 1
exec_tile_count = 1
writer_tile_count = 1

[tiles.shred]
max_pending_shred_sets = 512

[tiles.gui]
enabled = false
max_http_connections = 16
max_websocket_connections = 16
send_buffer_size_mb = 128
