[hugetlbfs]
max_page_size = "huge"

[runtime]
heap_size_gib = 4

[runtime.limits]
max_vote_accounts = 32

[runtime.limits.txncache]
max_live_slots = 512
max_txn_per_slot = 8192
max_txn_per_slot_override = true

[layout]
verify_tile_count = 1
exec_tile_count = 1
writer_tile_count = 1

[tiles.restart]
enabled = false

[tiles.replay]
funk_sz_gb = 20
funk_txn_max = 1024
funk_rec_max = 1048576

[tiles.shred]
max_pending_shred_sets = 512

[tiles.gui]
enabled = false
max_http_connections = 16
max_websocket_connections = 16
send_buffer_size_mb = 128
