#define _GNU_SOURCE
#include "fd_boot_report.h"

#include "../../ballet/pb/fd_pb_encode.h"

/* manually include just fd_features_generated.h so we can get
   FD_FEATURE_SET_ID without anything else that we don't need. */
#define HEADER_fd_src_flamenco_features_fd_features_h
#include "../../flamenco/features/fd_features_generated.h"
#undef HEADER_fd_src_flamenco_features_fd_features_h

#if defined(__x86_64__)
#include <cpuid.h>
#endif
#include <dirent.h>
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>
#include <gnu/libc-version.h>
#include <linux/ethtool.h>
#include <linux/sockios.h>
#include <net/if.h>
#include <sys/ioctl.h>
#include <sys/socket.h>
#include <sys/statvfs.h>
#include <sys/utsname.h>

static int
read_file( char const * path,
           char *       buf,
           ulong        buf_sz,
           ulong *      out_len ) {
  int fd = open( path, O_RDONLY|O_CLOEXEC );
  if( FD_UNLIKELY( fd<0 ) ) { buf[ 0 ] = '\0'; if( out_len ) *out_len = 0UL; return -1; }
  ulong off = 0UL;
  while( off<buf_sz-1UL ) {
    long n = read( fd, buf+off, buf_sz-1UL-off );
    if( FD_UNLIKELY( n<0L ) ) {
      if( FD_LIKELY( errno==EINTR ) ) continue;
      close( fd );
      buf[ 0 ] = '\0'; if( out_len ) *out_len = 0UL;
      return -1;
    }
    if( !n ) break;
    off += (ulong)n;
  }
  close( fd );
  buf[ off ] = '\0';
  if( out_len ) *out_len = off;
  return 0;
}

static int
read_cstr( char const * path,
           char *       buf,
           ulong        buf_sz ) {
  if( FD_UNLIKELY( read_file( path, buf, buf_sz, NULL ) ) ) return -1;
  ulong n = strlen( buf );
  while( n && (buf[ n-1UL ]=='\n' || buf[ n-1UL ]=='\r' || buf[ n-1UL ]==' ' || buf[ n-1UL ]=='\t') ) buf[ --n ] = '\0';
  return 0;
}

static int
read_ulong( char const * path,
            ulong *      out ) {
  char buf[ 64 ];
  if( FD_UNLIKELY( read_cstr( path, buf, sizeof(buf) ) ) ) return -1;
  char * end = NULL;
  ulong v = strtoul( buf, &end, 0 );
  if( FD_UNLIKELY( end==buf ) ) return -1;
  *out = v;
  return 0;
}

static int
read_long( char const * path,
           long *       out ) {
  char buf[ 64 ];
  if( FD_UNLIKELY( read_cstr( path, buf, sizeof(buf) ) ) ) return -1;
  char * end = NULL;
  long v = strtol( buf, &end, 0 );
  if( FD_UNLIKELY( end==buf ) ) return -1;
  *out = v;
  return 0;
}

/* variant index lookup: 1-based position in schema variant order, 0 if
   no match (caller substitutes its unknown/other value) */

static int
variant_idx( char const *         s,
             char const * const * tbl,
             int                  cnt ) {
  for( int i=0; i<cnt; i++ ) if( !strcmp( s, tbl[ i ] ) ) return i+1;
  return 0;
}

/* build info comes from two blobs in the same line format: the
   $(OBJDIR)/info file embedded by fd_log (machine target and extras;
   generated once per build dir so its date and git status go stale on
   incremental builds), and fd_bin_build_info, regenerated by the link
   recipe every time a production binary is relinked (see _make-exe).
   The latter is weak: NULL in binaries linked without it. */

extern char const fd_bin_build_info[] __attribute__((weak));

static char const *
build_info_line( char const * blob,
                 char const * key,
                 char *       out,
                 ulong        out_sz ) {
  out[ 0 ] = '\0';
  char const * p = blob;
  ulong key_len = strlen( key );
  while( *p ) {
    char const * line = p;
    while( *line==' ' ) line++;
    if( !strncmp( line, key, key_len ) ) {
      char const * v = line+key_len;
      while( *v==' ' ) v++;
      ulong n = 0UL;
      while( v[ n ] && v[ n ]!='\n' && n<out_sz-1UL ) { out[ n ] = v[ n ]; n++; }
      out[ n ] = '\0';
      while( n && (out[ n-1UL ]==' '||out[ n-1UL ]=='\r') ) out[ --n ] = '\0';
      return out;
    }
    while( *p && *p!='\n' ) p++;
    if( *p ) p++;
  }
  return out;
}

static ulong
build_timestamp_nanos( char const * blob ) {
  char date[ 64 ];
  build_info_line( blob, "# date", date, sizeof(date) );
  struct tm tm = {0};
  int tzh = 0, tzm = 0; char tzs = '+';
  if( FD_UNLIKELY( 8!=sscanf( date, "%d-%d-%d %d:%d:%d %c%2d%2d",
      &tm.tm_year, &tm.tm_mon, &tm.tm_mday, &tm.tm_hour, &tm.tm_min, &tm.tm_sec, &tzs, &tzh, &tzm )
      && 9!=sscanf( date, "%d-%d-%d %d:%d:%d %c%2d%2d",
      &tm.tm_year, &tm.tm_mon, &tm.tm_mday, &tm.tm_hour, &tm.tm_min, &tm.tm_sec, &tzs, &tzh, &tzm ) ) ) return 0UL;
  tm.tm_year -= 1900; tm.tm_mon -= 1;
  time_t t = timegm( &tm );
  if( FD_UNLIKELY( t==(time_t)-1 ) ) return 0UL;
  long off = (long)tzh*3600L + (long)tzm*60L;
  if( tzs=='-' ) off = -off;
  return (ulong)( (long)t - off )*1000000000UL;
}

static int
build_git_dirty( char const * blob ) {
  char const * p = blob;
  while( *p ) {
    char const * line = p;
    while( *line==' ' ) line++;
    if( line[ 0 ]=='1' || line[ 0 ]=='2' || line[ 0 ]=='u' ) {
      if( line[ 1 ]==' ' ) return 1;
    }
    while( *p && *p!='\n' ) p++;
    if( *p ) p++;
  }
  return 0;
}

static void
collect_os( fd_boot_report_t * r ) {
  struct utsname un;
  if( FD_LIKELY( 0==uname( &un ) ) ) {
    FD_TEST( fd_cstr_printf_check( r->kernel_release, sizeof(r->kernel_release), NULL, "%s", un.release ) );
    FD_TEST( fd_cstr_printf_check( r->kernel_version, sizeof(r->kernel_version), NULL, "%s", un.version ) );
  }

  /* vulnerabilities whose sysfs status reports an active mitigation */
  DIR * vul = opendir( "/sys/devices/system/cpu/vulnerabilities" );
  if( FD_LIKELY( vul ) ) {
    struct dirent * ent;
    while( (ent = readdir( vul )) && r->mitigations_cnt<32UL ) {
      if( ent->d_name[ 0 ]=='.' ) continue;
      char path[ 320 ], status[ 256 ];
      FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "/sys/devices/system/cpu/vulnerabilities/%s", ent->d_name ) );
      if( read_cstr( path, status, sizeof(status) ) ) continue;
      if( strncmp( status, "Mitigation", 10UL ) ) continue;
      fd_cstr_printf( r->mitigations[ r->mitigations_cnt++ ], 33UL, NULL, "%s", ent->d_name );
    }
    closedir( vul );
  }

  char osrel[ 8192 ];
  if( FD_LIKELY( !read_file( "/etc/os-release", osrel, sizeof(osrel), NULL ) ) ) {
    char * saveptr = NULL;
    for( char * line = strtok_r( osrel, "\n", &saveptr ); line; line = strtok_r( NULL, "\n", &saveptr ) ) {
      char * eq = strchr( line, '=' );
      if( !eq ) continue;
      *eq = '\0';
      char * val = eq+1;
      ulong vlen = strlen( val );
      if( vlen>=2UL && val[ 0 ]=='"' && val[ vlen-1UL ]=='"' ) { val[ vlen-1UL ] = '\0'; val++; }
      if(      !strcmp( line, "ID"         ) ) fd_cstr_printf( r->distro_id,         sizeof(r->distro_id), NULL, "%s",         val );
      else if( !strcmp( line, "VERSION_ID" ) ) fd_cstr_printf( r->distro_version_id, sizeof(r->distro_version_id), NULL, "%s", val );
      else if( !strcmp( line, "ID_LIKE"    ) ) fd_cstr_printf( r->distro_id_like,    sizeof(r->distro_id_like), NULL, "%s",    val );
    }
  }

  r->libc_kind = 1; /* glibc: the only supported libc */
  fd_cstr_printf( r->libc_version, sizeof(r->libc_version), NULL, "%s", gnu_get_libc_version() );

  static char const * const machine_tbl[] = {
    "native", "linux_gcc_x86_64", "linux_gcc_zen2", "linux_gcc_zen3", "linux_gcc_zen4",
    "linux_gcc_zen5", "linux_gcc_icelake", "linux_clang_x86_64", "linux_clang_haswell",
    "linux_clang_icelake", "linux_clang_zen2", "linux_clang_zen3", "linux_clang_zen4",
    "linux_clang_zen5" };
  char machine[ 64 ];
  build_info_line( fd_log_build_info, "# machine", machine, sizeof(machine) );
  int mt = variant_idx( machine, machine_tbl, 14 );
  r->build_machine_target = mt ? mt : 15; /* other */

  char extras[ 128 ];
  build_info_line( fd_log_build_info, "# extras", extras, sizeof(extras) );
  FD_TEST( fd_cstr_printf_check( r->build_extras, sizeof(r->build_extras), NULL, "%s", extras ) );

  /* date and dirty state from the link-time blob when this binary has
     one; the build-dir info file goes stale on incremental builds */
  char const * link_info = fd_bin_build_info ? fd_bin_build_info : fd_log_build_info;
  r->build_git_dirty = build_git_dirty( link_info );

#if defined(__clang__)
  r->compiler = 2;
#else
  r->compiler = 1;
#endif
  fd_cstr_printf( r->compiler_version, sizeof(r->compiler_version), NULL, "%s", __VERSION__ );
  r->build_timestamp_nanos = build_timestamp_nanos( link_info );

#if FD_HAS_SSE
  FD_TEST( fd_cstr_printf_check( r->build_features[ r->build_features_cnt++ ], 8UL, NULL, "%s", "sse" ) );
#endif
#if FD_HAS_AVX
  FD_TEST( fd_cstr_printf_check( r->build_features[ r->build_features_cnt++ ], 8UL, NULL, "%s", "avx" ) );
#endif
#if FD_HAS_AVX512
  FD_TEST( fd_cstr_printf_check( r->build_features[ r->build_features_cnt++ ], 8UL, NULL, "%s", "avx512" ) );
#endif
#if FD_HAS_SHANI
  FD_TEST( fd_cstr_printf_check( r->build_features[ r->build_features_cnt++ ], 8UL, NULL, "%s", "shani" ) );
#endif
#if FD_HAS_AESNI
  FD_TEST( fd_cstr_printf_check( r->build_features[ r->build_features_cnt++ ], 8UL, NULL, "%s", "aesni" ) );
#endif
#if FD_HAS_GFNI
  FD_TEST( fd_cstr_printf_check( r->build_features[ r->build_features_cnt++ ], 8UL, NULL, "%s", "gfni" ) );
#endif
}

static char const *
cpuinfo_field( char const * cpuinfo,
               char const * key,
               char *       out,
               ulong        out_sz ) {
  out[ 0 ] = '\0';
  char const * p = strstr( cpuinfo, key );
  if( !p ) return out;
  p = strchr( p, ':' );
  if( !p ) return out;
  p++;
  while( *p==' ' || *p=='\t' ) p++;
  ulong n = 0UL;
  while( p[ n ] && p[ n ]!='\n' && n<out_sz-1UL ) { out[ n ] = p[ n ]; n++; }
  out[ n ] = '\0';
  return out;
}

static void
collect_cpu( fd_boot_report_t * r ) {
  struct utsname un;
  r->cpu_arch = 3; /* unknown */
  if( FD_LIKELY( 0==uname( &un ) ) ) {
    if(      !strcmp ( un.machine, "x86_64"     ) ) r->cpu_arch = 1;
    else if( !strncmp( un.machine, "aarch64", 7 ) || !strncmp( un.machine, "arm", 3 ) ) r->cpu_arch = 2;
  }

# if defined(__x86_64__)
  uint eax, ebx, ecx, edx;
  if( FD_LIKELY( __get_cpuid( 0U, &eax, &ebx, &ecx, &edx ) ) ) {
    char vendor[ 13 ];
    fd_memcpy( vendor,   &ebx, 4UL );
    fd_memcpy( vendor+4, &edx, 4UL );
    fd_memcpy( vendor+8, &ecx, 4UL );
    vendor[ 12 ] = '\0';
    if(      !strcmp( vendor, "GenuineIntel" ) ) r->cpu_vendor = 1;
    else if( !strcmp( vendor, "AuthenticAMD" ) ) r->cpu_vendor = 2;
    else                                         r->cpu_vendor = 3;
  } else r->cpu_vendor = 3;

  if( FD_LIKELY( __get_cpuid( 1U, &eax, &ebx, &ecx, &edx ) ) ) {
    uint base_family = (eax>>8)&0xFU;
    uint ext_family  = (eax>>20)&0xFFU;
    uint base_model  = (eax>>4)&0xFU;
    uint ext_model   = (eax>>16)&0xFU;
    r->cpu_family   = (ushort)( base_family + fd_uint_if( base_family==0xFU, ext_family, 0U ) );
    r->cpu_model_id = (ushort)( base_model | fd_uint_if( base_family==0x6U || base_family==0xFU, ext_model<<4, 0U ) );
    r->cpu_stepping = (uchar)( eax&0xFU );
  }
# endif /* defined(__x86_64__) */

  char cpuinfo[ 16384 ];
  if( FD_LIKELY( !read_file( "/proc/cpuinfo", cpuinfo, sizeof(cpuinfo), NULL ) ) ) {
    char tmp[ 128 ];
    fd_cstr_printf( r->cpu_model_name, sizeof(r->cpu_model_name), NULL, "%s", cpuinfo_field( cpuinfo, "model name", tmp, sizeof(tmp) ) );
    cpuinfo_field( cpuinfo, "microcode", tmp, sizeof(tmp) );
    if( tmp[ 0 ] ) r->cpu_microcode_version = strtoul( tmp, NULL, 0 );
  }

  /* logical count, physical cores and sockets from the sysfs topology */
  ulong  logical = 0UL;
  ulong  pairs[ 4096 ]; ulong pair_cnt = 0UL; /* (package<<32)|core, deduped */
  ulong  pkgs [ 64 ];   ulong pkg_cnt  = 0UL;
  for( ulong cpu=0UL; cpu<4096UL; cpu++ ) {
    char path[ 128 ];
    FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "/sys/devices/system/cpu/cpu%lu/topology/physical_package_id", cpu ) );
    ulong pkg;
    if( read_ulong( path, &pkg ) ) {
      FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "/sys/devices/system/cpu/cpu%lu", cpu ) );
      if( 0!=access( path, F_OK ) ) break; /* end of cpus */
      continue;                         /* offline cpu */
    }
    FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "/sys/devices/system/cpu/cpu%lu/topology/core_id", cpu ) );
    ulong core;
    if( read_ulong( path, &core ) ) continue;
    logical++;
    ulong pair = (pkg<<32) | (core&0xFFFFFFFFUL);
    int seen = 0;
    for( ulong i=0UL; i<pair_cnt; i++ ) if( pairs[ i ]==pair ) { seen = 1; break; }
    if( !seen && pair_cnt<4096UL ) pairs[ pair_cnt++ ] = pair;
    seen = 0;
    for( ulong i=0UL; i<pkg_cnt; i++ ) if( pkgs[ i ]==pkg ) { seen = 1; break; }
    if( !seen && pkg_cnt<64UL ) pkgs[ pkg_cnt++ ] = pkg;
  }
  r->cpu_logical_count       = (ushort)fd_ulong_min( logical,  USHORT_MAX );
  r->cpu_physical_core_count = (ushort)fd_ulong_min( pair_cnt, USHORT_MAX );
  r->cpu_socket_count        = (uchar) fd_ulong_min( pkg_cnt,  UCHAR_MAX );

  ulong v;
  r->smt_active = !read_ulong( "/sys/devices/system/cpu/smt/active", &v ) && v==1UL;

  char buf[ 64 ];
  static char const * const gov_tbl[] = { "performance", "powersave", "ondemand", "conservative", "schedutil", "userspace" };
  r->cpufreq_governor = 7;
  if( !read_cstr( "/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor", buf, sizeof(buf) ) ) {
    int i = variant_idx( buf, gov_tbl, 6 );
    if( i ) r->cpufreq_governor = i;
  }

  static char const * const drv_tbl[] = { "intel_pstate", "intel_cpufreq", "acpi-cpufreq", "amd-pstate", "amd-pstate-epp", "cppc_cpufreq" };
  r->cpufreq_driver = 7;
  if( !read_cstr( "/sys/devices/system/cpu/cpu0/cpufreq/scaling_driver", buf, sizeof(buf) ) ) {
    int i = variant_idx( buf, drv_tbl, 6 );
    if( i ) r->cpufreq_driver = i;
  }

  static char const * const epp_tbl[] = { "performance", "balance_performance", "balance_power", "power", "default" };
  r->cpu_energy_perf_preference = 6;
  if( !read_cstr( "/sys/devices/system/cpu/cpu0/cpufreq/energy_performance_preference", buf, sizeof(buf) ) ) {
    int i = variant_idx( buf, epp_tbl, 5 );
    if( i ) r->cpu_energy_perf_preference = i;
  }

  static char const * const idle_tbl[] = { "intel_idle", "acpi_idle", "none" };
  r->cpu_idle_driver = 4;
  if( !read_cstr( "/sys/devices/system/cpu/cpuidle/current_driver", buf, sizeof(buf) ) ) {
    int i = variant_idx( buf, idle_tbl, 3 );
    if( i ) r->cpu_idle_driver = i;
  }

  /* deepest idle state not disabled */
  for( ulong s=0UL; s<16UL; s++ ) {
    char path[ 128 ];
    FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "/sys/devices/system/cpu/cpu0/cpuidle/state%lu/disable", s ) );
    ulong disabled;
    if( read_ulong( path, &disabled ) ) break;
    if( disabled ) continue;
    FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "/sys/devices/system/cpu/cpu0/cpuidle/state%lu/name", s ) );
    read_cstr( path, r->cpu_max_enabled_cstate, sizeof(r->cpu_max_enabled_cstate) );
  }
}

static void
collect_mem( fd_boot_report_t * r ) {
  char meminfo[ 8192 ];
  if( FD_LIKELY( !read_file( "/proc/meminfo", meminfo, sizeof(meminfo), NULL ) ) ) {
    char tmp[ 64 ];
    cpuinfo_field( meminfo, "MemTotal", tmp, sizeof(tmp) );
    if( tmp[ 0 ] ) r->host_memory_bytes = strtoul( tmp, NULL, 10 )*1024UL;
    cpuinfo_field( meminfo, "MemAvailable", tmp, sizeof(tmp) );
    if( tmp[ 0 ] ) r->host_memory_available_bytes = strtoul( tmp, NULL, 10 )*1024UL;
  }

  ulong max_cpu = 0UL;
  for( ulong node=0UL; node<64UL; node++ ) {
    char path[ 128 ];
    FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "/sys/devices/system/node/node%lu/cpulist", node ) );
    char list[ 16384 ]; /* worst-case alternating cpulist over 1024 cpus */
    if( read_cstr( path, list, sizeof(list) ) ) continue;
    char * saveptr = NULL;
    for( char * range = strtok_r( list, ",", &saveptr ); range; range = strtok_r( NULL, ",", &saveptr ) ) {
      ulong lo, hi;
      if(      2==sscanf( range, "%lu-%lu", &lo, &hi ) ) {}
      else if( 1==sscanf( range, "%lu",     &lo      ) ) hi = lo;
      else continue;
      for( ulong cpu=lo; cpu<=hi && cpu<1024UL; cpu++ ) {
        r->numa_cpu_to_node[ cpu ] = (uchar)fd_ulong_min( node, UCHAR_MAX );
        if( cpu+1UL>max_cpu ) max_cpu = cpu+1UL;
      }
    }
  }
  r->numa_cpu_to_node_cnt = max_cpu;

  char isolated[ 16384 ]; /* worst-case alternating cpulist over 1024 cpus */
  if( !read_cstr( "/sys/devices/system/cpu/isolated", isolated, sizeof(isolated) ) && isolated[ 0 ] ) {
    char * saveptr = NULL;
    for( char * range = strtok_r( isolated, ",", &saveptr ); range; range = strtok_r( NULL, ",", &saveptr ) ) {
      ulong lo, hi;
      if(      2==sscanf( range, "%lu-%lu", &lo, &hi ) ) {}
      else if( 1==sscanf( range, "%lu",     &lo      ) ) hi = lo;
      else continue;
      for( ulong cpu=lo; cpu<=hi && r->isolated_cpus_cnt<1024UL; cpu++ )
        r->isolated_cpus[ r->isolated_cpus_cnt++ ] = (ushort)fd_ulong_min( cpu, USHORT_MAX );
    }
  }
}

static char const *
smbios_string( uchar const * raw,
               ulong         raw_sz,
               uint          idx ) {
  if( !idx || raw_sz<2UL ) return "";
  ulong off = raw[ 1 ]; /* formatted area length */
  for( uint i=1U; off<raw_sz; i++ ) {
    if( i==idx ) return (char const *)( raw+off );
    off += strlen( (char const *)( raw+off ) )+1UL;
    if( off<raw_sz && !raw[ off ] ) break; /* double NUL: end of strings */
  }
  return "";
}

static void
collect_dimms( fd_boot_report_t * r ) {
  for( ulong i=0UL; i<256UL && r->dmi_dimms_cnt<64UL; i++ ) {
    char path[ 128 ];
    FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "/sys/firmware/dmi/entries/17-%lu/raw", i ) );
    uchar raw[ 4096 ];
    ulong raw_sz;
    if( read_file( path, (char *)raw, sizeof(raw), &raw_sz ) ) break;
    if( raw_sz<2UL ) continue;
    ulong fmt_len = raw[ 1 ]; /* formatted area; raw_sz also spans the string table */
    if( fmt_len>raw_sz || fmt_len<0x17UL ) continue; /* need through the speed word */

    ulong size_bytes = 0UL;
    uint  size_w = (uint)raw[ 0x0C ] | ((uint)raw[ 0x0D ]<<8);
    if( size_w==0U || size_w==0xFFFFU ) continue; /* empty or unknown slot */
    if( size_w==0x7FFFU && fmt_len>=0x20UL ) {
      uint ext = (uint)raw[ 0x1C ] | ((uint)raw[ 0x1D ]<<8) | ((uint)raw[ 0x1E ]<<16) | ((uint)raw[ 0x1F ]<<24);
      size_bytes = (ulong)( ext&0x7FFFFFFFU )<<20;
    } else if( size_w&0x8000U ) size_bytes = (ulong)( size_w&0x7FFFU )<<10;
    else                        size_bytes = (ulong)size_w<<20;

    fd_boot_report_dimm_t * d = &r->dmi_dimms[ r->dmi_dimms_cnt++ ];
    d->size_bytes = size_bytes;

    switch( raw[ 0x12 ] ) {
      case 0x12: FD_TEST( fd_cstr_printf_check( d->mem_type, sizeof(d->mem_type), NULL, "%s", "DDR"    ) ); break;
      case 0x13: FD_TEST( fd_cstr_printf_check( d->mem_type, sizeof(d->mem_type), NULL, "%s", "DDR2"   ) ); break;
      case 0x18: FD_TEST( fd_cstr_printf_check( d->mem_type, sizeof(d->mem_type), NULL, "%s", "DDR3"   ) ); break;
      case 0x1A: FD_TEST( fd_cstr_printf_check( d->mem_type, sizeof(d->mem_type), NULL, "%s", "DDR4"   ) ); break;
      case 0x1E: FD_TEST( fd_cstr_printf_check( d->mem_type, sizeof(d->mem_type), NULL, "%s", "LPDDR4" ) ); break;
      case 0x22: FD_TEST( fd_cstr_printf_check( d->mem_type, sizeof(d->mem_type), NULL, "%s", "DDR5"   ) ); break;
      case 0x23: FD_TEST( fd_cstr_printf_check( d->mem_type, sizeof(d->mem_type), NULL, "%s", "LPDDR5" ) ); break;
      default:   FD_TEST( fd_cstr_printf_check( d->mem_type, sizeof(d->mem_type), NULL, "%s", "other"  ) ); break;
    }

    d->rated_speed_mts = (ulong)raw[ 0x15 ] | ((ulong)raw[ 0x16 ]<<8);
    if( fmt_len>=0x22UL ) d->speed_mts = (ulong)raw[ 0x20 ] | ((ulong)raw[ 0x21 ]<<8);
    if( fmt_len>=0x18UL ) fd_cstr_printf( d->manufacturer, sizeof(d->manufacturer), NULL, "%s", smbios_string( raw, raw_sz, raw[ 0x17 ] ) );
    if( fmt_len>=0x1BUL ) fd_cstr_printf( d->part_number, sizeof(d->part_number), NULL, "%s", smbios_string( raw, raw_sz, raw[ 0x1A ] ) );
    ulong n = strlen( d->part_number );
    while( n && d->part_number[ n-1UL ]==' ' ) d->part_number[ --n ] = '\0';
    n = strlen( d->manufacturer );
    while( n && d->manufacturer[ n-1UL ]==' ' ) d->manufacturer[ --n ] = '\0';
  }
}

static int
ethtool_ioc( int          fd,
             char const * ifname,
             void *       data ) {
  struct ifreq ifr = {0};
  FD_TEST( fd_cstr_printf_check( ifr.ifr_name, IFNAMSIZ, NULL, "%s", ifname ) );
  ifr.ifr_data = data;
  return ioctl( fd, SIOCETHTOOL, &ifr );
}

static void
readlink_base( char const * path,
               char *       out,
               ulong        out_sz ) {
  out[ 0 ] = '\0';
  char target[ PATH_MAX ];
  long n = readlink( path, target, sizeof(target)-1UL );
  if( n<=0L ) return;
  target[ n ] = '\0';
  char * base = strrchr( target, '/' );
  fd_cstr_printf( out, out_sz, NULL, "%s", base ? base+1 : target );
}

static void
collect_one_nic( fd_boot_report_t * r,
                 int                fd,
                 char const *       name,
                 int                is_bond ) {
  if( r->nic_devices_cnt>=16UL ) return;
  fd_boot_report_nic_t * nic = &r->nic_devices[ r->nic_devices_cnt++ ];
  fd_memset( nic, 0, sizeof(*nic) );
  FD_TEST( fd_cstr_printf_check( nic->name, sizeof(nic->name), NULL, "%s", name ) );
  nic->is_bond_master = is_bond;

  char buf[ 256 ];
  char path[ PATH_MAX ];

  FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "/sys/class/net/%s/device/driver", name ) );
  readlink_base( path, nic->driver, sizeof(nic->driver) );

  struct ethtool_drvinfo drv = { .cmd = ETHTOOL_GDRVINFO };
  if( !ethtool_ioc( fd, name, &drv ) ) {
    if( !nic->driver[ 0 ] ) FD_TEST( fd_cstr_printf_check( nic->driver, sizeof(nic->driver), NULL, "%s", drv.driver ) );
    FD_TEST( fd_cstr_printf_check( nic->driver_version,   sizeof(nic->driver_version), NULL, "%s",   drv.version ) );
    FD_TEST( fd_cstr_printf_check( nic->firmware_version, sizeof(nic->firmware_version), NULL, "%s", drv.fw_version ) );
    FD_TEST( fd_cstr_printf_check( nic->bus_info,         sizeof(nic->bus_info), NULL, "%s",         drv.bus_info ) );
  }

  ulong v;
  FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "/sys/class/net/%s/device/current_link_width", name ) );
  if( !read_ulong( path, &v ) ) nic->pcie_current_link_width = (uchar)fd_ulong_min( v, UCHAR_MAX );
  FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "/sys/class/net/%s/device/max_link_width", name ) );
  if( !read_ulong( path, &v ) ) nic->pcie_max_link_width = (uchar)fd_ulong_min( v, UCHAR_MAX );
  FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "/sys/class/net/%s/device/current_link_speed", name ) );
  if( !read_cstr( path, buf, sizeof(buf) ) ) fd_cstr_printf( nic->pcie_current_link_speed, sizeof(nic->pcie_current_link_speed), NULL, "%s", buf );
  FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "/sys/class/net/%s/device/max_link_speed", name ) );
  if( !read_cstr( path, buf, sizeof(buf) ) ) fd_cstr_printf( nic->pcie_max_link_speed, sizeof(nic->pcie_max_link_speed), NULL, "%s", buf );

  FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "/sys/class/net/%s/device/device", name ) );
  if( !read_ulong( path, &v ) ) nic->pci_device_id = (ushort)v;
  FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "/sys/class/net/%s/device/vendor", name ) );
  if( !read_ulong( path, &v ) ) nic->pci_vendor_id = (ushort)v;
  FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "/sys/class/net/%s/device/subsystem_vendor", name ) );
  if( !read_ulong( path, &v ) ) nic->pci_subsystem_vendor_id = (ushort)v;
  FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "/sys/class/net/%s/device/subsystem_device", name ) );
  if( !read_ulong( path, &v ) ) nic->pci_subsystem_device_id = (ushort)v;

  long l;
  nic->numa_node = ULONG_MAX;
  FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "/sys/class/net/%s/device/numa_node", name ) );
  if( !read_long( path, &l ) && l>=0L ) nic->numa_node = (ulong)l;

  FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "/sys/class/net/%s/mtu", name ) );
  read_ulong( path, &nic->mtu );
  FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "/sys/class/net/%s/speed", name ) );
  if( !read_long( path, &l ) && l>0L ) nic->link_speed_mbps = (ulong)l;
  FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "/sys/class/net/%s/carrier", name ) );
  nic->carrier = !read_ulong( path, &v ) && v==1UL;
  FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "/sys/class/net/%s/flags", name ) );
  if( !read_ulong( path, &v ) ) nic->promiscuous = !!( v&0x100UL ); /* IFF_PROMISC */

  struct ethtool_channels ch = { .cmd = ETHTOOL_GCHANNELS };
  if( !ethtool_ioc( fd, name, &ch ) ) {
    nic->channels_current = (ushort)fd_uint_min( ch.combined_count ? ch.combined_count : ch.rx_count, USHORT_MAX );
    nic->channels_max     = (ushort)fd_uint_min( ch.max_combined   ? ch.max_combined   : ch.max_rx,   USHORT_MAX );
  }

  struct ethtool_ringparam ring = { .cmd = ETHTOOL_GRINGPARAM };
  if( !ethtool_ioc( fd, name, &ring ) ) {
    nic->rx_ring_size = ring.rx_pending;
    nic->tx_ring_size = ring.tx_pending;
    nic->rx_ring_max  = ring.rx_max_pending;
    nic->tx_ring_max  = ring.tx_max_pending;
  }

  /* enabled kernel device features, under their kernel names */
  union { struct ethtool_sset_info hdr; uchar pad[ sizeof(struct ethtool_sset_info)+sizeof(uint) ]; } sset = {0};
  sset.hdr.cmd       = ETHTOOL_GSSET_INFO;
  sset.hdr.sset_mask = 1UL<<ETH_SS_FEATURES;
  uint feat_cnt = 0U;
  if( !ethtool_ioc( fd, name, &sset ) && sset.hdr.sset_mask ) feat_cnt = fd_uint_min( sset.hdr.data[ 0 ], 128U );
  if( feat_cnt ) {
    union { struct ethtool_gstrings hdr; uchar pad[ sizeof(struct ethtool_gstrings)+128UL*ETH_GSTRING_LEN ]; } strs = {0};
    strs.hdr.cmd        = ETHTOOL_GSTRINGS;
    strs.hdr.string_set = ETH_SS_FEATURES;
    strs.hdr.len        = feat_cnt;
    union { struct ethtool_gfeatures hdr; uchar pad[ sizeof(struct ethtool_gfeatures)+4UL*sizeof(struct ethtool_get_features_block) ]; } feats = {0};
    feats.hdr.cmd  = ETHTOOL_GFEATURES;
    feats.hdr.size = fd_uint_min( ( feat_cnt+31U )/32U, 4U );
    if( !ethtool_ioc( fd, name, &strs ) && !ethtool_ioc( fd, name, &feats ) ) {
      for( uint i=0U; i<feat_cnt && i/32U<feats.hdr.size && nic->offloads_cnt<64UL; i++ ) {
        if( !( feats.hdr.features[ i/32U ].active & (1U<<(i%32U)) ) ) continue;
        char fname[ ETH_GSTRING_LEN+1 ];
        fd_memcpy( fname, strs.hdr.data+i*ETH_GSTRING_LEN, ETH_GSTRING_LEN );
        fname[ ETH_GSTRING_LEN ] = '\0';
        if( !fname[ 0 ] ) continue;
        FD_TEST( fd_cstr_printf_check( nic->offloads[ nic->offloads_cnt++ ], sizeof(nic->offloads[ 0 ]), NULL, "%s", fname ) );
      }
    }
  }

  struct ethtool_rxnfc rxfh = { .cmd = ETHTOOL_GRXFH, .flow_type = UDP_V4_FLOW };
  if( !ethtool_ioc( fd, name, &rxfh ) )
    nic->rss_flow_hash_udp4 = ( rxfh.data&(RXH_L4_B_0_1|RXH_L4_B_2_3) )==(RXH_L4_B_0_1|RXH_L4_B_2_3);

  struct ethtool_coalesce coal = { .cmd = ETHTOOL_GCOALESCE };
  if( !ethtool_ioc( fd, name, &coal ) ) {
    nic->coalesce_rx_usecs    = coal.rx_coalesce_usecs;
    nic->coalesce_adaptive_rx = !!coal.use_adaptive_rx_coalesce;
  }

  struct ethtool_rxfh rssh = { .cmd = ETHTOOL_GRSSH };
  if( !ethtool_ioc( fd, name, &rssh ) ) {
    if(      rssh.hfunc&(1U<<0) ) FD_TEST( fd_cstr_printf_check( nic->rss_hash_func, sizeof(nic->rss_hash_func), NULL, "%s", "toeplitz" ) );
    else if( rssh.hfunc&(1U<<1) ) FD_TEST( fd_cstr_printf_check( nic->rss_hash_func, sizeof(nic->rss_hash_func), NULL, "%s", "xor" ) );
    else if( rssh.hfunc&(1U<<2) ) FD_TEST( fd_cstr_printf_check( nic->rss_hash_func, sizeof(nic->rss_hash_func), NULL, "%s", "crc32" ) );
  }

  struct ethtool_rxnfc cnt = { .cmd = ETHTOOL_GRXCLSRLCNT };
  if( !ethtool_ioc( fd, name, &cnt ) ) nic->ntuple_rule_count = cnt.rule_cnt;
}

static void
collect_net( fd_boot_report_t * r,
             char const *       iface ) {
  int fd = socket( AF_INET, SOCK_DGRAM|SOCK_CLOEXEC, 0 );

  DIR * dir = opendir( "/sys/class/net" );
  if( FD_LIKELY( dir ) ) {
    struct dirent * ent;
    while( (ent = readdir( dir )) ) {
      if( ent->d_name[ 0 ]=='.' ) continue;
      char path[ PATH_MAX ];
      FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "/sys/class/net/%s/device", ent->d_name ) );
      int physical = 0==access( path, F_OK );
      FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "/sys/class/net/%s/bonding", ent->d_name ) );
      int is_bond = 0==access( path, F_OK );
      if( !physical && !is_bond ) continue;
      if( fd>=0 ) collect_one_nic( r, fd, ent->d_name, is_bond );
    }
    closedir( dir );
  }

  /* bond membership of the bound interface, and its inventory index */
  r->bond_mode = 1; /* none */
  if( iface[ 0 ] ) {
    char path[ PATH_MAX ], buf[ 512 ];
    FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "/sys/class/net/%s/bonding/mode", iface ) );
    if( !read_cstr( path, buf, sizeof(buf) ) ) {
      if(      !strncmp( buf, "active-backup", 13UL ) ) r->bond_mode = 2;
      else if( !strncmp( buf, "802.3ad",        7UL ) ) r->bond_mode = 3;
      else if( !strncmp( buf, "balance-xor",   11UL ) ) r->bond_mode = 4;
      else                                              r->bond_mode = 5;
      FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "/sys/class/net/%s/bonding/slaves", iface ) );
      if( !read_cstr( path, buf, sizeof(buf) ) ) {
        char * saveptr = NULL;
        for( char * slave = strtok_r( buf, " ", &saveptr ); slave && r->nic_bond_slaves_cnt<16UL; slave = strtok_r( NULL, " ", &saveptr ) ) {
          FD_TEST( fd_cstr_printf_check( r->nic_bond_slaves[ r->nic_bond_slaves_cnt ], 17UL, NULL, "%s", slave ) );
          r->nic_bond_slaves_cnt++;
        }
      }
    }
  }
  r->bound_nic_idx = 255;
  for( ulong i=0UL; i<r->nic_devices_cnt; i++ )
    if( !strcmp( r->nic_devices[ i ].name, iface ) ) { r->bound_nic_idx = (uchar)i; break; }

  ulong v;
  if( !read_ulong( "/proc/sys/net/core/bpf_jit_enable", &v ) ) r->net_bpf_jit_enable = (uchar)fd_ulong_min( v, UCHAR_MAX );

  if( fd>=0 ) close( fd );
}

/* platform: dmi identity, chassis, iommu, hypervisor */

static void
collect_platform( fd_boot_report_t * r,
                  char const *       iface ) {
  read_cstr( "/sys/class/dmi/id/sys_vendor",   r->dmi_sys_vendor,   sizeof(r->dmi_sys_vendor)   );
  read_cstr( "/sys/class/dmi/id/product_name", r->dmi_product_name, sizeof(r->dmi_product_name) );
  read_cstr( "/sys/class/dmi/id/bios_version", r->dmi_bios_version, sizeof(r->dmi_bios_version) );
  read_cstr( "/sys/class/dmi/id/bios_date",    r->dmi_bios_date,    sizeof(r->dmi_bios_date)    );
  read_cstr( "/sys/class/dmi/id/board_vendor", r->dmi_board_vendor, sizeof(r->dmi_board_vendor) );
  read_cstr( "/sys/class/dmi/id/board_name",   r->dmi_board_name,   sizeof(r->dmi_board_name)   );

  r->dmi_chassis_type = 1; /* unknown */
  ulong chassis;
  if( !read_ulong( "/sys/class/dmi/id/chassis_type", &chassis ) ) {
    switch( chassis ) { /* SMBIOS system enclosure types */
      case  3: case  4: case 13: case 15: r->dmi_chassis_type =  2; break; /* desktop */
      case  9:                            r->dmi_chassis_type =  3; break; /* laptop */
      case 10: case 14:                   r->dmi_chassis_type =  4; break; /* notebook */
      case  6: case  7:                   r->dmi_chassis_type =  5; break; /* tower */
      case 17: case 23:                   r->dmi_chassis_type =  6; break; /* rack_mount */
      case 28:                            r->dmi_chassis_type =  7; break; /* blade */
      case 29:                            r->dmi_chassis_type =  8; break; /* blade_enclosure */
      case 35:                            r->dmi_chassis_type =  9; break; /* mini_pc */
      case 36:                            r->dmi_chassis_type = 10; break; /* stick_pc */
      case 33: case 34:                   r->dmi_chassis_type = 11; break; /* embedded */
      case 24:                            r->dmi_chassis_type = 12; break; /* sealed_case_pc */
      case 31:                            r->dmi_chassis_type = 13; break; /* convertible */
      case 32:                            r->dmi_chassis_type = 14; break; /* detachable */
      default:                                                     break;
    }
  }

  /* iommu: no groups means off; the bound NIC's group default domain
     type distinguishes passthrough from translated */
  r->iommu_mode = 1; /* off */
  DIR * groups = opendir( "/sys/kernel/iommu_groups" );
  if( groups ) {
    struct dirent * ent;
    int have_group = 0;
    while( (ent = readdir( groups )) ) {
      if( ent->d_name[ 0 ]!='.' ) { have_group = 1; break; }
    }
    closedir( groups );
    if( have_group ) {
      r->iommu_mode = 4; /* unknown */
      char path[ PATH_MAX ], buf[ 64 ];
      /* a bonded interface is virtual and has no iommu group; fall
         back to the first member */
      for( int attempt=0; attempt<2 && r->iommu_mode==4; attempt++ ) {
        char const * nic = attempt ? ( r->nic_bond_slaves_cnt ? r->nic_bond_slaves[ 0 ] : "" ) : iface;
        if( !nic[ 0 ] ) continue;
        FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "/sys/class/net/%s/device/iommu_group/type", nic ) );
        if( read_cstr( path, buf, sizeof(buf) ) ) continue;
        if(      !strcmp ( buf, "identity" )    ) r->iommu_mode = 2; /* passthrough */
        else if( !strncmp( buf, "DMA", 3UL )    ) r->iommu_mode = 3; /* translated */
      }
    }
  }

  r->hypervisor_vendor = 1; /* none */
# if defined(__x86_64__)
  uint eax, ebx, ecx, edx;
  if( __get_cpuid( 1U, &eax, &ebx, &ecx, &edx ) && ( ecx&(1U<<31) ) ) {
    r->hypervisor_vendor = 13; /* unknown */
    __cpuid( 0x40000000U, eax, ebx, ecx, edx ); /* __get_cpuid rejects hypervisor leaves */
    char sig[ 13 ];
    fd_memcpy( sig,   &ebx, 4UL );
    fd_memcpy( sig+4, &ecx, 4UL );
    fd_memcpy( sig+8, &edx, 4UL );
    sig[ 12 ] = '\0';
    if( !strncmp( sig, "KVMKVMKVM", 9UL ) ) {
      r->hypervisor_vendor = 2; /* kvm */
      if(      strcasestr( r->dmi_sys_vendor,   "amazon" ) ) r->hypervisor_vendor = 7; /* amazon_nitro */
      else if( strcasestr( r->dmi_product_name, "google" ) ) r->hypervisor_vendor = 8; /* kvm_gce */
    }
    else if( !strncmp( sig, "TCGTCGTCG",    9UL ) ) r->hypervisor_vendor =  3; /* qemu */
    else if( !strncmp( sig, "VMwareVMware", 12UL ) ) r->hypervisor_vendor =  4; /* vmware */
    else if( !strncmp( sig, "Microsoft Hv", 12UL ) ) r->hypervisor_vendor =  5; /* microsoft_hyperv */
    else if( !strncmp( sig, "XenVMMXenVMM", 12UL ) ) r->hypervisor_vendor =  6; /* xen */
    else if( !strncmp( sig, "bhyve bhyve",  11UL ) ) r->hypervisor_vendor =  9; /* bhyve */
    else if( strstr( sig, "prl hyperv" )           ) r->hypervisor_vendor = 10; /* parallels */
    else if( !strncmp( sig, "VBoxVBoxVBox", 12UL ) ) r->hypervisor_vendor = 11; /* virtualbox */
    if( r->hypervisor_vendor==13 && strcasestr( r->dmi_product_name, "bochs" ) ) r->hypervisor_vendor = 12;
  }
# endif /* defined(__x86_64__) */

  /* virtualized hosts override the chassis form factor: a recognized
     cloud platform reports cloud, any other hypervisor virtual (bare
     metal providers leave no identifier on the machine) */
  if( r->hypervisor_vendor!=1 ) {
    static char const * const cloud_tbl[] = { "amazon", "google", "microsoft", "alibaba", "digitalocean", "vultr", "ovh", "hetzner", "oracle", "equinix", "latitude", "scaleway" };
    int cloud = 0;
    for( ulong i=0UL; i<sizeof(cloud_tbl)/sizeof(cloud_tbl[0]); i++ ) {
      if( strcasestr( r->dmi_sys_vendor,   cloud_tbl[ i ] ) ||
          strcasestr( r->dmi_product_name, cloud_tbl[ i ] ) ||
          strcasestr( r->dmi_board_vendor, cloud_tbl[ i ] ) ) { cloud = 1; break; }
    }
    r->dmi_chassis_type = cloud ? 16 : 15; /* cloud : virtual */
  }
}

static void
collect_container( fd_boot_report_t * r ) {
  char cgroup[ 4096 ] = {0};
  read_file( "/proc/self/cgroup", cgroup, sizeof(cgroup), NULL );

  r->cgroup_swap_limit_bytes = ULONG_MAX;

  r->container_type = 1; /* none */
  char buf[ 128 ];
  if( !read_cstr( "/run/systemd/container", buf, sizeof(buf) ) ) {
    if(      !strcmp( buf, "docker"         ) ) r->container_type = 2;
    else if( !strcmp( buf, "podman"         ) ) r->container_type = 3;
    else if( !strcmp( buf, "lxc"            ) ) r->container_type = 6;
    else if( !strcmp( buf, "systemd-nspawn" ) ) r->container_type = 7;
    else                                        r->container_type = 8; /* unknown runtime */
  }
  else if( 0==access( "/.dockerenv"       , F_OK ) ) r->container_type = 2;
  else if( 0==access( "/run/.containerenv", F_OK ) ) r->container_type = 3;
  else if( strstr( cgroup, "cri-containerd" ) )  r->container_type = 4;
  else if( strstr( cgroup, "crio" ) )            r->container_type = 5;
  else if( strstr( cgroup, "docker" ) )          r->container_type = 2;
  else if( strstr( cgroup, "libpod" ) )          r->container_type = 3;
  else if( strstr( cgroup, "lxc" ) )             r->container_type = 6;

  r->kubernetes_pod = !!getenv( "KUBERNETES_SERVICE_HOST" ) || !!strstr( cgroup, "kubepods" );

  /* cgroup v2 limits along our own cgroup path */
  char const * v2 = strstr( cgroup, "0::" );
  if( v2 ) {
    char cgpath[ PATH_MAX ];
    FD_TEST( fd_cstr_printf_check( cgpath, sizeof(cgpath), NULL, "%s", v2+3 ) );
    char * nl = strchr( cgpath, '\n' );
    if( nl ) *nl = '\0';

    char path[ PATH_MAX+32 ], val[ 64 ];
    FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "/sys/fs/cgroup%s/memory.max", cgpath ) );
    if( !read_cstr( path, val, sizeof(val) ) && strcmp( val, "max" ) ) r->cgroup_memory_limit_bytes = strtoul( val, NULL, 10 );
    FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "/sys/fs/cgroup%s/memory.high", cgpath ) );
    if( !read_cstr( path, val, sizeof(val) ) && strcmp( val, "max" ) ) r->cgroup_memory_high_bytes = strtoul( val, NULL, 10 );
    FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "/sys/fs/cgroup%s/memory.swap.max", cgpath ) );
    if( !read_cstr( path, val, sizeof(val) ) ) r->cgroup_swap_limit_bytes = strcmp( val, "max" ) ? strtoul( val, NULL, 10 ) : ULONG_MAX;
    FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "/sys/fs/cgroup%s/cpu.max", cgpath ) );
    if( !read_cstr( path, val, sizeof(val) ) ) {
      ulong quota, period;
      if( 2==sscanf( val, "%lu %lu", &quota, &period ) && period ) r->cgroup_cpu_quota_millicores = (uint)( quota*1000UL/period );
    }
  }

  /* cgroup v1: per-controller hierarchies, used by v1-only and hybrid
     hosts; v2 wins where it already produced a value.  v1 encodes
     unlimited as a page-rounded LLONG_MAX and swap only as the
     combined memory+swap limit */
  for( char const * line=cgroup; *line; ) {
    char const * nl   = strchr( line, '\n' );
    ulong        llen = nl ? (ulong)( nl-line ) : strlen( line );
    char const * c1 = memchr( line, ':', llen );
    char const * c2 = c1 ? memchr( c1+1, ':', (ulong)( line+llen-(c1+1) ) ) : NULL;
    if( c2 ) {
      char ctl[ 64 ];
      fd_cstr_printf( ctl, fd_ulong_min( (ulong)( c2-(c1+1) )+1UL, sizeof(ctl) ), NULL, "%s", c1+1 );
      char cgpath[ PATH_MAX ];
      fd_cstr_printf( cgpath, fd_ulong_min( (ulong)( line+llen-(c2+1) )+1UL, sizeof(cgpath) ), NULL, "%s", c2+1 );
      int mem = 0, cpu = 0;
      char * sp = NULL;
      for( char * tok = strtok_r( ctl, ",", &sp ); tok; tok = strtok_r( NULL, ",", &sp ) ) {
        mem |= !strcmp( tok, "memory" );
        cpu |= !strcmp( tok, "cpu" );
      }
      char path[ PATH_MAX+64 ];
      ulong l;
      if( mem && !r->cgroup_memory_limit_bytes ) {
        FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "/sys/fs/cgroup/memory%s/memory.limit_in_bytes", cgpath ) );
        if( !read_ulong( path, &l ) && l<(1UL<<60) ) r->cgroup_memory_limit_bytes = l;
        FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "/sys/fs/cgroup/memory%s/memory.memsw.limit_in_bytes", cgpath ) );
        if( !read_ulong( path, &l ) && l<(1UL<<60) && r->cgroup_memory_limit_bytes ) r->cgroup_swap_limit_bytes = l-r->cgroup_memory_limit_bytes;
      }
      if( cpu && !r->cgroup_cpu_quota_millicores ) {
        long quota;
        FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "/sys/fs/cgroup/cpu%s/cpu.cfs_quota_us", cgpath ) );
        if( !read_long( path, &quota ) && quota>0L ) {
          FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "/sys/fs/cgroup/cpu%s/cpu.cfs_period_us", cgpath ) );
          if( !read_ulong( path, &l ) && l ) r->cgroup_cpu_quota_millicores = (uint)( (ulong)quota*1000UL/l );
        }
      }
    }
    if( !nl ) break;
    line = nl+1;
  }
}

/* storage: block device inventory, nvme health, mdraid, and the
   filesystems backing the validator's directories */

static void
collect_block_devices( fd_boot_report_t * r ) {
  DIR * dir = opendir( "/sys/block" );
  if( FD_UNLIKELY( !dir ) ) return;
  struct dirent * ent;
  while( (ent = readdir( dir )) && r->block_devices_cnt<24UL ) {
    char const * n = ent->d_name;
    if( n[ 0 ]=='.' ) continue;
    if( !strncmp( n, "loop", 4UL ) || !strncmp( n, "ram", 3UL ) || !strncmp( n, "zram", 4UL ) ||
        !strncmp( n, "sr", 2UL )   || !strncmp( n, "fd", 2UL )  || !strncmp( n, "nbd", 3UL )  ||
        !strncmp( n, "dm-", 3UL ) ) continue;

    fd_boot_report_block_device_t * d = &r->block_devices[ r->block_devices_cnt++ ];
    fd_memset( d, 0, sizeof(*d) );
    fd_cstr_printf( d->name, sizeof(d->name), NULL, "%s", n );

    char path[ PATH_MAX ], buf[ 256 ];
    FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "/sys/block/%s/device/model", n ) );
    if( !read_cstr( path, buf, sizeof(buf) ) ) fd_cstr_printf( d->model, sizeof(d->model), NULL, "%s", buf );

    ulong v;
    FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "/sys/block/%s/size", n ) );
    if( !read_ulong( path, &v ) ) d->capacity_bytes = v*512UL;
    FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "/sys/block/%s/queue/rotational", n ) );
    if( !read_ulong( path, &v ) ) d->rotational = !!v;

    if(      !strncmp( n, "nvme",   4UL ) ) FD_TEST( fd_cstr_printf_check( d->transport, sizeof(d->transport), NULL, "%s", "nvme" ) );
    else if( !strncmp( n, "vd",     2UL ) ) FD_TEST( fd_cstr_printf_check( d->transport, sizeof(d->transport), NULL, "%s", "virtio" ) );
    else if( !strncmp( n, "xvd",    3UL ) ) FD_TEST( fd_cstr_printf_check( d->transport, sizeof(d->transport), NULL, "%s", "xen" ) );
    else if( !strncmp( n, "mmcblk", 6UL ) ) FD_TEST( fd_cstr_printf_check( d->transport, sizeof(d->transport), NULL, "%s", "mmc" ) );
    else if( !strncmp( n, "md",     2UL ) ) FD_TEST( fd_cstr_printf_check( d->transport, sizeof(d->transport), NULL, "%s", "md" ) );
    else {
      char target[ PATH_MAX ];
      FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "/sys/block/%s", n ) );
      long tn = readlink( path, target, sizeof(target)-1UL );
      if( tn>0L ) target[ tn ] = '\0'; else target[ 0 ] = '\0';
      if(      strstr( target, "/usb" ) ) FD_TEST( fd_cstr_printf_check( d->transport, sizeof(d->transport), NULL, "%s", "usb" ) );
      else if( strstr( target, "/ata" ) ) FD_TEST( fd_cstr_printf_check( d->transport, sizeof(d->transport), NULL, "%s", "sata" ) );
      else                                FD_TEST( fd_cstr_printf_check( d->transport, sizeof(d->transport), NULL, "%s", "scsi" ) );
    }

    FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "/sys/block/%s/queue/scheduler", n ) );
    if( !read_cstr( path, buf, sizeof(buf) ) ) {
      char * lb = strchr( buf, '[' );
      char * rb = lb ? strchr( lb, ']' ) : NULL;
      if( lb && rb ) { *rb = '\0'; fd_cstr_printf( d->scheduler, sizeof(d->scheduler), NULL, "%s", lb+1 ); }
      else           fd_cstr_printf( d->scheduler, sizeof(d->scheduler), NULL, "%s", buf );
    }
  }
  closedir( dir );
}

/* nvme get log page: local definitions to avoid kernel header drift */

struct nvme_admin_cmd_ioc {
  uchar  opcode; uchar flags; ushort rsvd1;
  uint   nsid;   uint cdw2; uint cdw3;
  ulong  metadata; ulong addr;
  uint   metadata_len; uint data_len;
  uint   cdw10; uint cdw11; uint cdw12; uint cdw13; uint cdw14; uint cdw15;
  uint   timeout_ms; uint result;
};

#define NVME_IOCTL_ADMIN_CMD_ _IOWR( 'N', 0x41, struct nvme_admin_cmd_ioc )

static void
collect_nvme( fd_boot_report_t * r ) {
  for( ulong i=0UL; i<r->block_devices_cnt && r->nvme_devices_cnt<16UL; i++ ) {
    char const * n = r->block_devices[ i ].name;
    uint ctrl_num, ns_num;
    if( 2!=sscanf( n, "nvme%un%u", &ctrl_num, &ns_num ) ) continue;

    fd_boot_report_nvme_t * d = &r->nvme_devices[ r->nvme_devices_cnt++ ];
    fd_memset( d, 0, sizeof(*d) );
    d->device_idx           = (uchar)i;
    d->namespace_size_bytes = r->block_devices[ i ].capacity_bytes;
    d->numa_node            = 255;

    char path[ PATH_MAX ], buf[ 256 ];
    FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "/sys/block/%s/device/firmware_rev", n ) );
    if( !read_cstr( path, buf, sizeof(buf) ) ) fd_cstr_printf( d->firmware_rev, sizeof(d->firmware_rev), NULL, "%s", buf );
    long l;
    FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "/sys/block/%s/device/device/numa_node", n ) );
    if( !read_long( path, &l ) && l>=0L && l<255L ) d->numa_node = (uchar)l;

    char ctrl[ 64 ];
    FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "/sys/block/%s/device", n ) );
    readlink_base( path, ctrl, sizeof(ctrl) );
    if( !ctrl[ 0 ] ) FD_TEST( fd_cstr_printf_check( ctrl, sizeof(ctrl), NULL, "nvme%u", ctrl_num ) );

    FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "/dev/%s", ctrl ) );
    int fd = open( path, O_RDONLY|O_CLOEXEC );
    if( fd<0 ) continue;
    uchar log[ 512 ] __attribute__((aligned(8))) = {0};
    struct nvme_admin_cmd_ioc cmd = {
      .opcode   = 0x02, /* get log page */
      .nsid     = 0xFFFFFFFFU,
      .addr     = (ulong)log,
      .data_len = 512U,
      .cdw10    = 0x02U | ( ( 512U/4U-1U )<<16 ), /* smart / health, numdl */
    };
    if( 0==ioctl( fd, NVME_IOCTL_ADMIN_CMD_, &cmd ) ) {
      d->critical_warning    = log[ 0 ];
      d->available_spare_pct = log[ 3 ];
      d->percentage_used     = log[ 5 ];
      fd_memcpy( &d->media_errors, log+160, 8UL ); /* low 64 bits of le128 */
    }
    close( fd );
  }
}

static void
collect_mdraid( fd_boot_report_t * r ) {
  for( ulong i=0UL; i<r->block_devices_cnt && r->mdraid_arrays_cnt<16UL; i++ ) {
    char const * n = r->block_devices[ i ].name;
    if( strncmp( n, "md", 2UL ) ) continue;
    char path[ PATH_MAX ], buf[ 64 ];
    FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "/sys/block/%s/md/level", n ) );
    if( read_cstr( path, buf, sizeof(buf) ) ) continue;

    fd_boot_report_mdraid_t * d = &r->mdraid_arrays[ r->mdraid_arrays_cnt++ ];
    fd_memset( d, 0, sizeof(*d) );
    fd_cstr_printf( d->name, sizeof(d->name), NULL, "%s", n );
    fd_cstr_printf( d->level, sizeof(d->level), NULL, "%s", buf );
    ulong v;
    FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "/sys/block/%s/md/raid_disks", n ) );
    if( !read_ulong( path, &v ) ) d->device_count = (uchar)fd_ulong_min( v, UCHAR_MAX );
    FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "/sys/block/%s/md/degraded", n ) );
    if( !read_ulong( path, &v ) ) d->degraded = !!v;
  }
}

/* filesystems: resolve each configured directory to its mount via
   longest-prefix match over mountinfo, dedupe mounts into the
   filesystems array, and link each mount back to its disk */

struct mount_ent {
  char  mount_point[ PATH_MAX ];
  char  fs_type[ 17 ];
  char  options[ 257 ];
  uint  dev_major;
  uint  dev_minor;
};

static ulong
parse_mountinfo( struct mount_ent * mounts,
                 ulong              max,
                 int *              truncated ) {
  static char buf[ 1048576 ];
  ulong len;
  *truncated = 0;
  if( read_file( "/proc/self/mountinfo", buf, sizeof(buf), &len ) ) return 0UL;
  if( len==sizeof(buf)-1UL ) *truncated = 1;
  ulong cnt = 0UL;
  char * saveptr = NULL;
  char * line = strtok_r( buf, "\n", &saveptr );
  for( ; line && cnt<max; line = strtok_r( NULL, "\n", &saveptr ) ) {
    char * f[ 32 ]; ulong nf = 0UL;
    char * sp = NULL;
    for( char * tok = strtok_r( line, " ", &sp ); tok && nf<32UL; tok = strtok_r( NULL, " ", &sp ) ) f[ nf++ ] = tok;
    if( nf<10UL ) continue;
    ulong dash = 6UL;
    while( dash<nf && strcmp( f[ dash ], "-" ) ) dash++;
    if( dash+2UL>=nf ) continue;

    struct mount_ent * m = &mounts[ cnt++ ];
    fd_memset( m, 0, sizeof(*m) );
    sscanf( f[ 2 ], "%u:%u", &m->dev_major, &m->dev_minor );
    fd_cstr_printf( m->mount_point, sizeof(m->mount_point), NULL, "%s", f[ 4 ] );
    /* mountinfo octal-escapes space, tab, newline and backslash */
    char * w = m->mount_point;
    for( char const * q=m->mount_point; *q; q++ ) {
      if( q[0]=='\\' && q[1]>='0' && q[1]<='3' && q[2]>='0' && q[2]<='7' && q[3]>='0' && q[3]<='7' ) {
        *w++ = (char)( ((q[1]-'0')<<6) | ((q[2]-'0')<<3) | (q[3]-'0') );
        q += 3;
      } else *w++ = *q;
    }
    *w = '\0';
    fd_cstr_printf( m->fs_type,     sizeof(m->fs_type), NULL, "%s",     f[ dash+1UL ] );
    /* per-mount flags then superblock options; superblock option
       values can embed paths, addresses and usernames (overlayfs
       lowerdir, nfs addr, cifs username), so values are kept only for
       allowlisted keys */
    static char const * const opt_val_keys[] = {
      "allocsize", "barrier", "commit", "compress", "compress-force", "data", "discard", "errors", "huge",
      "logbsize", "logbufs", "mode", "nr_inodes", "size", "space_cache", "stripe", "subvolid", "sunit", "swidth",
    };
    char * out = m->options;
    ulong  rem = sizeof(m->options);
    for( ulong s=0UL; s<2UL && nf>dash+3UL*s; s++ ) {
      char * osp = NULL;
      for( char * opt = strtok_r( s ? f[ dash+3UL ] : f[ 5 ], ",", &osp ); opt; opt = strtok_r( NULL, ",", &osp ) ) {
        char const * eq = strchr( opt, '=' );
        int redact = !!eq;
        for( ulong k=0UL; eq && k<sizeof(opt_val_keys)/sizeof(opt_val_keys[0]); k++ ) {
          if( (ulong)( eq-opt )==strlen( opt_val_keys[ k ] ) && !strncmp( opt, opt_val_keys[ k ], (ulong)( eq-opt ) ) ) redact = 0;
        }
        ulong n;
        int fit = redact ? fd_cstr_printf_check( out, rem, &n, "%s%.*s=[redacted]", out==m->options ? "" : ",", (int)( eq-opt ), opt )
                         : fd_cstr_printf_check( out, rem, &n, "%s%s",              out==m->options ? "" : ",", opt );
        if( !fit ) { *out = '\0'; break; } /* capped at the schema length */
        out += n; rem -= n;
      }
    }
  }
  if( line ) *truncated = 1; /* stopped at the entry cap */
  return cnt;
}

static long
mount_for_path( char const *             path,
                struct mount_ent const * mounts,
                ulong                    mount_cnt ) {
  long  best     = -1L;
  ulong best_len = 0UL;
  for( ulong i=0UL; i<mount_cnt; i++ ) {
    char const * mp = mounts[ i ].mount_point;
    ulong len = strlen( mp );
    if( strncmp( path, mp, len ) ) continue;
    if( len>1UL && path[ len ]!='\0' && path[ len ]!='/' ) continue;
    if( len>=best_len ) { best = (long)i; best_len = len; }
  }
  return best;
}

/* parent_disk resolves a block device name to its whole-disk name,
   stripping a partition suffix via the sysfs hierarchy */

static void
parent_disk( char const * dev,
             char *       out,
             ulong        out_sz ) {
  char path[ PATH_MAX+32 ], resolved[ PATH_MAX ];
  FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "/sys/class/block/%s", dev ) );
  if( !realpath( path, resolved ) ) { fd_cstr_printf( out, out_sz, NULL, "%s", dev ); return; }
  FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "%s/partition", resolved ) );
  if( 0==access( path, F_OK ) ) {
    char * base = strrchr( resolved, '/' );
    if( base ) *base = '\0'; /* partition -> parent disk */
  }
  char const * name = strrchr( resolved, '/' );
  fd_cstr_printf( out, out_sz, NULL, "%s", name ? name+1 : resolved );
}

static uchar
device_idx_for_mount( fd_boot_report_t const * r,
                      struct mount_ent const * m ) {
  char path[ PATH_MAX+32 ], resolved[ PATH_MAX ], name[ 72 ];
  FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "/sys/dev/block/%u:%u", m->dev_major, m->dev_minor ) );
  if( !realpath( path, resolved ) ) return 255;
  char const * base = strrchr( resolved, '/' );
  parent_disk( base ? base+1 : resolved, name, sizeof(name) );

  /* virtual devices not in the inventory (lvm volumes, partitioned
     raid) descend through their first slave until a real device */
  for( int depth=0; depth<4; depth++ ) {
    for( ulong i=0UL; i<r->block_devices_cnt; i++ )
      if( !strcmp( r->block_devices[ i ].name, name ) ) return (uchar)i;

    FD_TEST( fd_cstr_printf_check( path, sizeof(path), NULL, "/sys/class/block/%s/slaves", name ) );
    DIR * dir = opendir( path );
    if( !dir ) return 255;
    char slave[ 72 ] = {0};
    struct dirent * ent;
    while( (ent = readdir( dir )) ) if( ent->d_name[ 0 ]!='.' ) { fd_cstr_printf( slave, sizeof(slave), NULL, "%s", ent->d_name ); break; }
    closedir( dir );
    if( !slave[ 0 ] ) return 255;
    parent_disk( slave, name, sizeof(name) );
  }
  return 255;
}

static long fs_mount_idx[ 8 ]; /* mountinfo index behind each filesystems entry */

static uchar
fs_idx_for_path( fd_boot_report_t *       r,
                 char const *             path,
                 struct mount_ent const * mounts,
                 ulong                    mount_cnt ) {
  if( !path[ 0 ] ) return 255;
  /* canonicalize; a path not created yet attributes its deepest
     existing ancestor, the same mount once it is */
  char real[ PATH_MAX ], trunc[ PATH_MAX ];
  FD_TEST( fd_cstr_printf_check( trunc, sizeof(trunc), NULL, "%s", path ) );
  for(;;) {
    if( realpath( trunc, real ) ) { path = real; break; }
    char * slash = strrchr( trunc, '/' );
    if( !slash ) break; /* relative and missing: unresolvable */
    if( slash==trunc ) { if( trunc[ 1 ]=='\0' ) break; trunc[ 1 ] = '\0'; }
    else *slash = '\0';
  }
  long mi = mount_for_path( path, mounts, mount_cnt );
  if( mi<0L ) return 255;
  struct mount_ent const * m = &mounts[ mi ];

  for( ulong i=0UL; i<r->filesystems_cnt; i++ ) if( fs_mount_idx[ i ]==mi ) return (uchar)i;
  if( r->filesystems_cnt>=8UL ) return 255;
  fs_mount_idx[ r->filesystems_cnt ] = mi;

  fd_boot_report_fs_t * fs = &r->filesystems[ r->filesystems_cnt ];
  fd_memset( fs, 0, sizeof(*fs) );
  fs->device_idx = device_idx_for_mount( r, m );
  FD_TEST( fd_cstr_printf_check( fs->fs_type,       sizeof(fs->fs_type), NULL, "%s",       m->fs_type ) );
  FD_TEST( fd_cstr_printf_check( fs->mount_options, sizeof(fs->mount_options), NULL, "%s", m->options ) );
  struct statvfs sv;
  if( 0==statvfs( m->mount_point, &sv ) ) {
    fs->capacity_bytes = sv.f_blocks*sv.f_frsize;
    fs->free_bytes     = sv.f_bavail*sv.f_frsize;
  }
  return (uchar)r->filesystems_cnt++;
}

static void
collect_filesystems( fd_boot_report_t *     r,
                     fd_topo_tile_t const * tile ) {
  static struct mount_ent mounts[ 512 ];
  int truncated;
  ulong mount_cnt = parse_mountinfo( mounts, 512UL, &truncated );
  /* a mount past a truncated table could be the longest prefix; report
     unresolved rather than a wrong ancestor */
  if( FD_UNLIKELY( truncated ) ) mount_cnt = 0UL;

  r->accounts_fs_idx  = fs_idx_for_path( r, tile->event.accounts_path,  mounts, mount_cnt );
  r->snapshots_fs_idx = fs_idx_for_path( r, tile->event.snapshots_path, mounts, mount_cnt );
  r->log_fs_idx       = fs_idx_for_path( r, tile->event.log_path,       mounts, mount_cnt );
  r->shredb_fs_idx    = fs_idx_for_path( r, tile->event.shredb_path,    mounts, mount_cnt );
  r->guidb_fs_idx     = fs_idx_for_path( r, tile->event.guidb_path,     mounts, mount_cnt );
}

void
fd_boot_report_collect( fd_boot_report_t *     r,
                        fd_topo_t const *      topo,
                        fd_topo_tile_t const * tile ) {
  fd_memset( r, 0, sizeof(*r) );

  /* rendered by the app during topology construction */
  if( FD_UNLIKELY( !topo->resolved_config_json_len ) )
    FD_LOG_ERR(( "boot report config documents were not rendered into the topology" ));
  FD_TEST( topo->resolved_config_json_len<sizeof(r->resolved_config_json) );
  FD_TEST( topo->user_config_json_len    <sizeof(r->user_config_json)     );
  fd_memcpy( r->resolved_config_json, topo->resolved_config_json, topo->resolved_config_json_len );
  r->resolved_config_json_len = topo->resolved_config_json_len;
  fd_memcpy( r->user_config_json, topo->user_config_json, topo->user_config_json_len );
  r->user_config_json_len = topo->user_config_json_len;

  collect_os( r );
  collect_cpu( r );
  collect_mem( r );
  collect_dimms( r );
  collect_net( r, tile->event.net_interface );
  collect_platform( r, tile->event.net_interface );
  collect_container( r );
  collect_block_devices( r );
  collect_nvme( r );
  collect_mdraid( r );
  collect_filesystems( r, tile );
  /* stamped at command start in the parent; the tile clone comes later */
  r->process_start_time_nanos = (ulong)tile->event.boot_timestamp_nanos;
  r->feature_set_id = FD_FEATURE_SET_ID;
}

/* topology json: tiles, links and workspaces from the live topo */

static void
render_topology_json( fd_boot_report_t * r,
                      fd_topo_t const *  topo ) {
  char * cur = r->topology_json;
  ulong  rem = sizeof(r->topology_json);

#define PRINT( ... ) do {                                          \
    ulong _n;                                                      \
    FD_TEST( fd_cstr_printf_check( cur, rem, &_n, __VA_ARGS__ ) ); \
    cur += _n; rem -= _n;                                          \
  } while( 0 )

  PRINT( "{\"tiles\":[" );
  for( ulong i=0UL; i<topo->tile_cnt; i++ ) {
    fd_topo_tile_t const * tile = &topo->tiles[ i ];
    PRINT( "%s{\"kind\":\"%s\",\"kind_id\":%lu,\"cpu_idx\":%ld,\"in\":[",
           i ? "," : "", tile->name, tile->kind_id,
           tile->cpu_idx<FD_TILE_MAX ? (long)tile->cpu_idx : -1L );
    for( ulong in=0UL; in<tile->in_cnt; in++ ) PRINT( "%s%lu", in ? "," : "", tile->in_link_id[ in ] );
    PRINT( "],\"out\":[" );
    for( ulong out=0UL; out<tile->out_cnt; out++ ) PRINT( "%s%lu", out ? "," : "", tile->out_link_id[ out ] );
    PRINT( "],\"event_link\":%ld,\"obj_cnt\":%lu}",
           tile->event_link_id!=ULONG_MAX ? (long)tile->event_link_id : -1L, tile->uses_obj_cnt );
  }
  PRINT( "],\"links\":[" );
  for( ulong i=0UL; i<topo->link_cnt; i++ ) {
    /* referenced from the tile in/out lists by array position */
    fd_topo_link_t const * link = &topo->links[ i ];
    PRINT( "%s{\"kind\":\"%s\",\"kind_id\":%lu,\"depth\":%lu,\"mtu\":%lu,\"burst\":%lu}",
           i ? "," : "", link->name, link->kind_id, link->depth, link->mtu, link->burst );
  }
  PRINT( "],\"workspaces\":[" );
  for( ulong i=0UL; i<topo->wksp_cnt; i++ ) {
    fd_topo_wksp_t const * wksp = &topo->workspaces[ i ];
    PRINT( "%s{\"name\":\"%s\",\"numa_idx\":%lu,\"page_sz\":%lu,\"page_cnt\":%lu,\"footprint\":%lu,\"loose\":%lu}",
           i ? "," : "", wksp->name, wksp->numa_idx, wksp->page_sz, wksp->page_cnt,
           wksp->known_footprint, wksp->total_footprint-wksp->known_footprint );
  }
  PRINT( "]}" );

#undef PRINT

  r->topology_json_len = (ulong)( cur-r->topology_json );
}

/* protobuf encode: field numbers are 1-based positions in
   schema/boot.json, tuple subfield numbers 1-based positions within
   the tuple, enum values 1-based variant positions */

static int
push_cstr( fd_pb_encoder_t * e,
           uint              id,
           char const *      s ) {
  ulong len = strlen( s );
  if( !len ) return 1;
  char clean[ 512 ];
  FD_TEST( len<sizeof(clean) );
  for( ulong i=0UL; i<len; i++ ) clean[ i ] = ( s[ i ]<0x20 || s[ i ]>0x7e ) ? '?' : s[ i ];
  return !!fd_pb_push_bytes( e, id, clean, len );
}

void
fd_boot_report_publish( fd_boot_report_t *  r,
                        fd_topo_t const *   topo,
                        fd_circq_t *        circq,
                        fd_event_client_t * client ) {
  render_topology_json( r, topo );

  r->tile_count = (ushort)fd_ulong_min( topo->tile_cnt, USHORT_MAX );
  ulong stack_bytes  = topo->tile_cnt*FD_SHMEM_HUGE_PAGE_SZ*( (FD_TILE_PRIVATE_STACK_SZ/FD_SHMEM_HUGE_PAGE_SZ)+2UL );
  ulong normal_bytes = fd_topo_normal_page_cnt( topo )*FD_SHMEM_NORMAL_PAGE_SZ;
  r->memory_total = fd_topo_mlock( topo )+stack_bytes+normal_bytes;
  for( ulong i=0UL; i<fd_shmem_numa_cnt(); i++ ) {
    r->memory_gigantic_pages += fd_topo_gigantic_page_cnt( topo, i );
    r->memory_huge_pages     += fd_topo_huge_page_cnt( topo, i, 0 );
  }
  r->memory_normal_pages = fd_topo_normal_page_cnt( topo );

  uchar * buffer = fd_circq_push_back( circq, 1UL, FD_EVENT_BOOT_BUF_MAX );
  FD_TEST( buffer );

  ulong event_id = fd_event_client_id_reserve( client );

  fd_pb_encoder_t encoder[1];
  fd_pb_encoder_init( encoder, buffer, FD_EVENT_BOOT_BUF_MAX );

  int ok = 1;

  FD_TEST( circq->cursor_push_seq );
  ok &= !!fd_pb_push_uint64( encoder, 1U, circq->cursor_push_seq-1UL );
  ok &= !!fd_pb_push_uint64( encoder, 2U, event_id );
  ok &= !!fd_pb_push_uint64( encoder, 3U, 0UL ); /* link_seq */
  ok &= !!fd_pb_push_uint64( encoder, 4U, (ulong)fd_log_wallclock() );

  ok &= !!fd_pb_submsg_open( encoder, 5U );  /* Event */
  ok &= !!fd_pb_submsg_open( encoder, 10U ); /* Boot */

  ok &= push_cstr( encoder, 1U, r->kernel_release );
  ok &= push_cstr( encoder, 2U, r->kernel_version );
  for( ulong i=0UL; i<r->mitigations_cnt; i++ ) ok &= push_cstr( encoder, 3U, r->mitigations[ i ] );
  ok &= push_cstr( encoder, 4U, r->distro_id );
  ok &= push_cstr( encoder, 5U, r->distro_version_id );
  ok &= push_cstr( encoder, 6U, r->distro_id_like );
  if( r->libc_kind ) ok &= !!fd_pb_push_int32( encoder, 7U, r->libc_kind );
  ok &= push_cstr( encoder, 8U, r->libc_version );
  if( r->build_machine_target ) ok &= !!fd_pb_push_int32( encoder, 9U, r->build_machine_target );
  ok &= push_cstr( encoder, 10U, r->build_extras );
  if( r->build_git_dirty ) ok &= !!fd_pb_push_bool( encoder, 11U, r->build_git_dirty );
  if( r->compiler ) ok &= !!fd_pb_push_int32( encoder, 12U, r->compiler );
  ok &= push_cstr( encoder, 13U, r->compiler_version );
  if( r->build_timestamp_nanos ) ok &= !!fd_pb_push_uint64( encoder, 14U, r->build_timestamp_nanos );
  for( ulong i=0UL; i<r->build_features_cnt; i++ ) ok &= push_cstr( encoder, 15U, r->build_features[ i ] );

  if( r->cpu_arch )   ok &= !!fd_pb_push_int32( encoder, 16U, r->cpu_arch );
  if( r->cpu_vendor ) ok &= !!fd_pb_push_int32( encoder, 17U, r->cpu_vendor );
  ok &= push_cstr( encoder, 18U, r->cpu_model_name );
  if( r->cpu_family )            ok &= !!fd_pb_push_uint32( encoder, 19U, r->cpu_family );
  if( r->cpu_model_id )          ok &= !!fd_pb_push_uint32( encoder, 20U, r->cpu_model_id );
  if( r->cpu_stepping )          ok &= !!fd_pb_push_uint32( encoder, 21U, r->cpu_stepping );
  if( r->cpu_microcode_version ) ok &= !!fd_pb_push_uint64( encoder, 22U, r->cpu_microcode_version );
  if( r->cpu_logical_count )       ok &= !!fd_pb_push_uint32( encoder, 23U, r->cpu_logical_count );
  if( r->cpu_physical_core_count ) ok &= !!fd_pb_push_uint32( encoder, 24U, r->cpu_physical_core_count );
  if( r->cpu_socket_count )        ok &= !!fd_pb_push_uint32( encoder, 25U, r->cpu_socket_count );
  if( r->smt_active )          ok &= !!fd_pb_push_bool( encoder, 26U, 1 );
  if( r->cpufreq_governor )           ok &= !!fd_pb_push_int32( encoder, 27U, r->cpufreq_governor );
  if( r->cpufreq_driver )             ok &= !!fd_pb_push_int32( encoder, 28U, r->cpufreq_driver );
  if( r->cpu_energy_perf_preference ) ok &= !!fd_pb_push_int32( encoder, 29U, r->cpu_energy_perf_preference );
  if( r->cpu_idle_driver )            ok &= !!fd_pb_push_int32( encoder, 30U, r->cpu_idle_driver );
  ok &= push_cstr( encoder, 31U, r->cpu_max_enabled_cstate );

  if( r->host_memory_bytes )     ok &= !!fd_pb_push_uint64( encoder, 32U, r->host_memory_bytes );
  if( r->host_memory_available_bytes ) ok &= !!fd_pb_push_uint64( encoder, 33U, r->host_memory_available_bytes );
  for( ulong i=0UL; i<r->numa_cpu_to_node_cnt; i++ ) ok &= !!fd_pb_push_uint32( encoder, 34U, r->numa_cpu_to_node[ i ] );
  for( ulong i=0UL; i<r->isolated_cpus_cnt; i++ )    ok &= !!fd_pb_push_uint32( encoder, 35U, r->isolated_cpus[ i ] );

  for( ulong i=0UL; i<r->dmi_dimms_cnt; i++ ) {
    fd_boot_report_dimm_t const * d = &r->dmi_dimms[ i ];
    ok &= !!fd_pb_submsg_open( encoder, 36U );
    if( d->size_bytes ) ok &= !!fd_pb_push_uint64( encoder, 1U, d->size_bytes );
    ok &= push_cstr( encoder, 2U, d->mem_type );
    if( d->speed_mts )       ok &= !!fd_pb_push_uint64( encoder, 3U, d->speed_mts );
    if( d->rated_speed_mts ) ok &= !!fd_pb_push_uint64( encoder, 4U, d->rated_speed_mts );
    ok &= push_cstr( encoder, 5U, d->manufacturer );
    ok &= push_cstr( encoder, 6U, d->part_number );
    ok &= !!fd_pb_submsg_close( encoder );
  }

  for( ulong i=0UL; i<r->nic_devices_cnt; i++ ) {
    fd_boot_report_nic_t const * n = &r->nic_devices[ i ];
    ok &= !!fd_pb_submsg_open( encoder, 37U );
    ok &= push_cstr( encoder, 1U, n->name );
    ok &= push_cstr( encoder, 2U, n->driver );
    ok &= push_cstr( encoder, 3U, n->driver_version );
    ok &= push_cstr( encoder, 4U, n->firmware_version );
    if( n->pcie_current_link_width ) ok &= !!fd_pb_push_uint32( encoder, 5U, n->pcie_current_link_width );
    if( n->pcie_max_link_width )     ok &= !!fd_pb_push_uint32( encoder, 6U, n->pcie_max_link_width );
    ok &= push_cstr( encoder, 7U, n->pcie_current_link_speed );
    ok &= push_cstr( encoder, 8U, n->pcie_max_link_speed );
    ok &= push_cstr( encoder, 9U, n->bus_info );
    if( n->pci_device_id )           ok &= !!fd_pb_push_uint32( encoder, 10U, n->pci_device_id );
    if( n->pci_vendor_id )           ok &= !!fd_pb_push_uint32( encoder, 11U, n->pci_vendor_id );
    if( n->pci_subsystem_vendor_id ) ok &= !!fd_pb_push_uint32( encoder, 12U, n->pci_subsystem_vendor_id );
    if( n->pci_subsystem_device_id ) ok &= !!fd_pb_push_uint32( encoder, 13U, n->pci_subsystem_device_id );
    if( n->numa_node )       ok &= !!fd_pb_push_uint64( encoder, 14U, n->numa_node );
    if( n->mtu )             ok &= !!fd_pb_push_uint64( encoder, 15U, n->mtu );
    if( n->link_speed_mbps ) ok &= !!fd_pb_push_uint64( encoder, 16U, n->link_speed_mbps );
    if( n->carrier )     ok &= !!fd_pb_push_bool( encoder, 17U, 1 );
    if( n->promiscuous ) ok &= !!fd_pb_push_bool( encoder, 18U, 1 );
    if( n->channels_current ) ok &= !!fd_pb_push_uint32( encoder, 19U, n->channels_current );
    if( n->channels_max )     ok &= !!fd_pb_push_uint32( encoder, 20U, n->channels_max );
    if( n->rx_ring_size ) ok &= !!fd_pb_push_uint64( encoder, 21U, n->rx_ring_size );
    if( n->tx_ring_size ) ok &= !!fd_pb_push_uint64( encoder, 22U, n->tx_ring_size );
    if( n->rx_ring_max )  ok &= !!fd_pb_push_uint64( encoder, 23U, n->rx_ring_max );
    if( n->tx_ring_max )  ok &= !!fd_pb_push_uint64( encoder, 24U, n->tx_ring_max );
    for( ulong k=0UL; k<n->offloads_cnt; k++ ) ok &= push_cstr( encoder, 25U, n->offloads[ k ] );
    if( n->rss_flow_hash_udp4 )  ok &= !!fd_pb_push_bool( encoder, 26U, 1 );
    if( n->coalesce_rx_usecs )    ok &= !!fd_pb_push_uint64( encoder, 27U, n->coalesce_rx_usecs );
    if( n->coalesce_adaptive_rx ) ok &= !!fd_pb_push_bool( encoder, 28U, 1 );
    ok &= push_cstr( encoder, 29U, n->rss_hash_func );
    if( n->ntuple_rule_count ) ok &= !!fd_pb_push_uint64( encoder, 30U, n->ntuple_rule_count );
    if( n->is_bond_master )    ok &= !!fd_pb_push_bool( encoder, 31U, 1 );
    ok &= !!fd_pb_submsg_close( encoder );
  }

  for( ulong i=0UL; i<r->nic_bond_slaves_cnt; i++ ) ok &= push_cstr( encoder, 38U, r->nic_bond_slaves[ i ] );
  if( r->bond_mode ) ok &= !!fd_pb_push_int32( encoder, 39U, r->bond_mode );
  if( r->bound_nic_idx ) ok &= !!fd_pb_push_uint32( encoder, 40U, r->bound_nic_idx );
  if( r->net_bpf_jit_enable ) ok &= !!fd_pb_push_uint32( encoder, 41U, r->net_bpf_jit_enable );

  ok &= push_cstr( encoder, 42U, r->dmi_sys_vendor );
  ok &= push_cstr( encoder, 43U, r->dmi_product_name );
  ok &= push_cstr( encoder, 44U, r->dmi_bios_version );
  ok &= push_cstr( encoder, 45U, r->dmi_bios_date );
  ok &= push_cstr( encoder, 46U, r->dmi_board_vendor );
  ok &= push_cstr( encoder, 47U, r->dmi_board_name );
  if( r->dmi_chassis_type )  ok &= !!fd_pb_push_int32( encoder, 48U, r->dmi_chassis_type );
  if( r->iommu_mode )        ok &= !!fd_pb_push_int32( encoder, 49U, r->iommu_mode );
  if( r->hypervisor_vendor ) ok &= !!fd_pb_push_int32( encoder, 50U, r->hypervisor_vendor );
  if( r->container_type ) ok &= !!fd_pb_push_int32( encoder, 51U, r->container_type );
  if( r->kubernetes_pod ) ok &= !!fd_pb_push_bool( encoder, 52U, 1 );
  if( r->cgroup_memory_limit_bytes )   ok &= !!fd_pb_push_uint64( encoder, 53U, r->cgroup_memory_limit_bytes );
  if( r->cgroup_memory_high_bytes )    ok &= !!fd_pb_push_uint64( encoder, 54U, r->cgroup_memory_high_bytes );
  if( r->cgroup_swap_limit_bytes )     ok &= !!fd_pb_push_uint64( encoder, 55U, r->cgroup_swap_limit_bytes );
  if( r->cgroup_cpu_quota_millicores ) ok &= !!fd_pb_push_uint32( encoder, 56U, r->cgroup_cpu_quota_millicores );

  for( ulong i=0UL; i<r->block_devices_cnt; i++ ) {
    fd_boot_report_block_device_t const * d = &r->block_devices[ i ];
    ok &= !!fd_pb_submsg_open( encoder, 57U );
    ok &= push_cstr( encoder, 1U, d->name );
    ok &= push_cstr( encoder, 2U, d->model );
    if( d->capacity_bytes ) ok &= !!fd_pb_push_uint64( encoder, 3U, d->capacity_bytes );
    if( d->rotational )     ok &= !!fd_pb_push_bool( encoder, 4U, 1 );
    ok &= push_cstr( encoder, 5U, d->transport );
    ok &= push_cstr( encoder, 6U, d->scheduler );
    ok &= !!fd_pb_submsg_close( encoder );
  }

  for( ulong i=0UL; i<r->nvme_devices_cnt; i++ ) {
    fd_boot_report_nvme_t const * d = &r->nvme_devices[ i ];
    ok &= !!fd_pb_submsg_open( encoder, 58U );
    if( d->device_idx ) ok &= !!fd_pb_push_uint32( encoder, 1U, d->device_idx );
    ok &= push_cstr( encoder, 2U, d->firmware_rev );
    if( d->critical_warning )    ok &= !!fd_pb_push_uint32( encoder, 3U, d->critical_warning );
    if( d->available_spare_pct ) ok &= !!fd_pb_push_uint32( encoder, 4U, d->available_spare_pct );
    if( d->percentage_used )     ok &= !!fd_pb_push_uint32( encoder, 5U, d->percentage_used );
    if( d->media_errors )        ok &= !!fd_pb_push_uint64( encoder, 6U, d->media_errors );
    if( d->numa_node )           ok &= !!fd_pb_push_uint32( encoder, 7U, d->numa_node );
    if( d->namespace_size_bytes ) ok &= !!fd_pb_push_uint64( encoder, 8U, d->namespace_size_bytes );
    ok &= !!fd_pb_submsg_close( encoder );
  }

  for( ulong i=0UL; i<r->mdraid_arrays_cnt; i++ ) {
    fd_boot_report_mdraid_t const * d = &r->mdraid_arrays[ i ];
    ok &= !!fd_pb_submsg_open( encoder, 59U );
    ok &= push_cstr( encoder, 1U, d->name );
    ok &= push_cstr( encoder, 2U, d->level );
    if( d->device_count ) ok &= !!fd_pb_push_uint32( encoder, 3U, d->device_count );
    if( d->degraded )     ok &= !!fd_pb_push_bool( encoder, 4U, 1 );
    ok &= !!fd_pb_submsg_close( encoder );
  }

  for( ulong i=0UL; i<r->filesystems_cnt; i++ ) {
    fd_boot_report_fs_t const * f = &r->filesystems[ i ];
    ok &= !!fd_pb_submsg_open( encoder, 60U );
    if( f->device_idx ) ok &= !!fd_pb_push_uint32( encoder, 1U, f->device_idx );
    ok &= push_cstr( encoder, 2U, f->fs_type );
    ok &= push_cstr( encoder, 3U, f->mount_options );
    if( f->capacity_bytes ) ok &= !!fd_pb_push_uint64( encoder, 4U, f->capacity_bytes );
    if( f->free_bytes )     ok &= !!fd_pb_push_uint64( encoder, 5U, f->free_bytes );
    ok &= !!fd_pb_submsg_close( encoder );
  }

  if( r->accounts_fs_idx )  ok &= !!fd_pb_push_uint32( encoder, 61U, r->accounts_fs_idx );
  if( r->snapshots_fs_idx ) ok &= !!fd_pb_push_uint32( encoder, 62U, r->snapshots_fs_idx );
  if( r->log_fs_idx )       ok &= !!fd_pb_push_uint32( encoder, 63U, r->log_fs_idx );
  if( r->shredb_fs_idx )    ok &= !!fd_pb_push_uint32( encoder, 64U, r->shredb_fs_idx );
  if( r->guidb_fs_idx )     ok &= !!fd_pb_push_uint32( encoder, 65U, r->guidb_fs_idx );

  if( r->resolved_config_json_len ) ok &= !!fd_pb_push_bytes( encoder, 66U, r->resolved_config_json, r->resolved_config_json_len );
  if( r->user_config_json_len )     ok &= !!fd_pb_push_bytes( encoder, 67U, r->user_config_json,     r->user_config_json_len );
  if( r->topology_json_len ) ok &= !!fd_pb_push_bytes( encoder, 68U, r->topology_json, r->topology_json_len );
  if( r->tile_count )                ok &= !!fd_pb_push_uint32( encoder, 69U, r->tile_count );
  if( r->memory_total ) ok &= !!fd_pb_push_uint64( encoder, 70U, r->memory_total );
  if( r->memory_gigantic_pages )   ok &= !!fd_pb_push_uint64( encoder, 71U, r->memory_gigantic_pages );
  if( r->memory_huge_pages )       ok &= !!fd_pb_push_uint64( encoder, 72U, r->memory_huge_pages );
  if( r->memory_normal_pages )     ok &= !!fd_pb_push_uint64( encoder, 73U, r->memory_normal_pages );
  if( r->process_start_time_nanos ) ok &= !!fd_pb_push_uint64( encoder, 74U, r->process_start_time_nanos );
  if( r->feature_set_id )           ok &= !!fd_pb_push_uint32( encoder, 75U, r->feature_set_id );

  ok &= !!fd_pb_submsg_close( encoder );
  ok &= !!fd_pb_submsg_close( encoder );
  FD_TEST( ok );
  fd_circq_resize_back( circq, fd_pb_encoder_out_sz( encoder ) );
}
