#ifndef HEADER_fd_features_h
#define HEADER_fd_features_h
#include "./fd_acc_mgr.h"
#define FD_FEATURE_ACTIVE(_g, _y)  ((_g->features. _y != 0) && (_g->bank.slot >= _g->features. _y))
typedef struct fd_features {
  ulong account_hash_ignore_slot; // SVn36yVApPLYsa8koK3qUcy14zXDnqkNYWyUh1f4oK1
  ulong add_compute_budget_program; // 4d5AKtxoh93Dwm1vHXUU3iRATuMndx1c431KgT2td52r
  ulong add_get_minimum_delegation_instruction_to_stake_program; // St8k9dVXP97xT6faW24YmRSYConLbhsMJA4TJTBLmMT
  ulong add_get_processed_sibling_instruction_syscall; // CFK1hRCNy8JJuAAY8Pb2GjLFNdCThS2qwZNe3izzBMgn
  ulong add_set_compute_unit_price_ix; // 98std1NSHqXi9WYvFShfVepRdCoq1qvsp8fsR2XZtG8g
  ulong add_set_tx_loaded_accounts_data_size_instruction; // G6vbf1UBok8MWb8m25ex86aoQHeKTzDKzuZADHkShqm6
  ulong add_shred_type_to_shred_seed; // Ds87KVeqhbv7Jw8W6avsS1mqz3Mw5J3pRTpPoDQ2QdiJ
  ulong allow_votes_to_directly_update_vote_state; // Ff8b1fBeB86q8cjq47ZhsQLgv5EkHu3G1C99zjUfAzrq
  ulong apply_cost_tracker_during_replay; // 2ry7ygxiYURULZCrypHhveanvP5tzZ4toRwVp89oCNSj
  ulong bank_transaction_count_fix; // Vo5siZ442SaZBKPXNocthiXysNviW4UYPwRFggmbgAp
  ulong blake3_syscall_enabled; // HTW2pSyErTj4BV6KBM9NZ9VBUJVxt7sacNWcf76wtzb3
  ulong bpf_account_data_direct_mapping; // 9gwzizfABsKUereT6phZZxbTzuAnovkgwpVVpdcSxv9h
  ulong cap_accounts_data_allocations_per_transaction; // 9gxu85LYRAcZL38We8MYJ4A9AwgBBPtVBAqebMcT1241
  ulong cap_accounts_data_len; // capRxUrBjNkkCpjrJxPGfPaWijB7q3JoDfsWXAnt46r
  ulong cap_accounts_data_size_per_block; // qywiJyZmqTKspFg2LeuUHqcA5nNvBgobqb9UprywS9N
  ulong cap_bpf_program_instruction_accounts; // 9k5ijzTbYPtjzu8wj2ErH9v45xecHzQ1x4PMYMMxFgdM
  ulong cap_transaction_accounts_data_size; // DdLwVYuvDz26JohmgSbA7mjpJFgX5zP2dkp8qsF2C33V
  ulong check_init_vote_data; // 3ccR6QpxGYsAbWyfevEtBNGfWV4xBffxRj2tD6A9i39F
  ulong check_physical_overlapping; // nWBqjr3gpETbiaVj3CBJ3HFC5TMdnJDGt21hnvSTvVZ
  ulong check_slice_translation_size; // GmC19j9qLn2RFk5NduX6QXaDhVpGncVVBzyM8e9WMz2F
  ulong check_syscall_outputs_do_not_overlap; // 3uRVPBpyEJRo1emLCrq38eLRFGcu6uKSpUXqGvU8T7SZ
  ulong checked_arithmetic_in_fee_validation; // 5Pecy6ie6XGm22pc9d4P9W5c31BugcFBuy6hsP2zkETv
  ulong clean_up_delegation_errors; // Bj2jmUsM2iRhfdLLDSTkhM5UQRQvQHm57HSmPibPtEyu
  ulong commission_updates_only_allowed_in_first_half_of_epoch; // noRuG2kzACwgaY7TVmLRnUNPLKNVQE1fb7X55YWBehp
  ulong compact_vote_state_updates; // 86HpNqzutEZwLcPxS6EHDcMNYWk6ikhteg9un7Y2PBKE
  ulong credits_auto_rewind; // BUS12ciZ5gCoFafUHWW8qaFMMtwFQGVxjsDheWLdqBE2
  ulong curve25519_syscall_enabled; // 7rcw5UtqgDTBBv2EcynNfYckgdAaH1MAsCjKgXMkN7Ri
  ulong dedupe_config_program_signers; // 8kEuAshXLsgkUEdcFVLqrjCGGHVWFW99ZZpxvAzzMtBp
  ulong default_units_per_instruction; // J2QdYx8crLbTVK8nur1jeLsmc3krDbfjoxoea2V1Uy5Q
  ulong delay_visibility_of_program_deployment; // GmuBvtFb2aHfSfMXpuFeWZGHyDeCLPS79s48fmCWCfM5
  ulong demote_program_write_locks; // 3E3jV7v9VcdJL8iYZUMax9DiDno8j7EWUVbhm9RtShj2
  ulong deprecate_rewards_sysvar; // GaBtBJvmS4Arjj5W1NmFcyvPjsHN38UGYDq2MDwbs9Qu
  ulong disable_bpf_deprecated_load_instructions; // 3XgNukcZWf9o3HdA3fpJbm94XFc4qpvTXc8h1wxYwiPi
  ulong disable_bpf_unresolved_symbols_at_runtime; // 4yuaYAj2jGMGTh1sSmi4G2eFscsDq8qjugJXZoBN6YEa
  ulong disable_builtin_loader_ownership_chains; // 4UDcAfQ6EcA6bdcadkeHpkarkhZGJ7Bpq7wTAiRMjkoi
  ulong disable_cpi_setting_executable_and_rent_epoch; // B9cdB55u4jQsDNsdTK525yE9dmSc5Ga7YBaBrDFvEhM9
  ulong disable_deploy_of_alloc_free_syscall; // 79HWsX9rpnnJBPcdNURVqygpMAfxdrAirzAGAVmf92im
  ulong disable_deprecated_loader; // GTUMCZ8LTNxVfxdrw7ZsDFTxXb7TutYkzJnFwinpE6dg
  ulong disable_fee_calculator; // 2jXx2yDmGysmBKfKYNgLj2DQyAQv6mMk2BPh4eSbyB4H
  ulong disable_fees_sysvar; // JAN1trEUEtZjgXYzNBYHU9DYd7GnThhXfFP7SzPXkPsG
  ulong disable_rehash_for_rent_epoch; // DTVTkmw3JSofd8CJVJte8PXEbxNQ2yZijvVr3pe2APPj
  ulong disable_turbine_fanout_experiments; // Gz1aLrbeQ4Q6PTSafCZcGWZXz91yVRi7ASFzFEr1U4sa
  ulong do_support_realloc; // 75m6ysz33AfLA5DDEzWM1obBrnPQRSsdVQ2nRmc8Vuu1
  ulong drop_merkle_shreds; // 84zy5N23Q9vTZuLc9h1HWUtyM9yCFV2SCmyP9W9C3yHZ
  ulong drop_redundant_turbine_path; // 4Di3y24QFLt5QEUPZtbnjyfQKfm6ZMTfa6Dw1psfoMKU
  ulong ed25519_program_enabled; // 6ppMXNYLhVd7GcsZ5uV11wQEW7spppiMVfqQv5SXhDpX
  ulong enable_alt_bn128_syscall; // A16q37opZdQMCbe5qJ6xpBB9usykfv8jZaMkxvZQi4GJ
  ulong enable_big_mod_exp_syscall; // EBq48m8irRKuE7ZnMTLvLg2UuGSqhe8s8oMqnmja1fJw
  ulong enable_bpf_loader_extend_program_ix; // 8Zs9W7D9MpSEtUWSQdGniZk2cNmV22y6FLJwCx53asme
  ulong enable_bpf_loader_set_authority_checked_ix; // 5x3825XS7M2A3Ekbn5VGGkvFoAg5qrRWkTrY4bARP1GL
  ulong enable_durable_nonce; // 4EJQtF2pkRyawwcTVfQutzq4Sa5hRhibF6QAK1QXhtEX
  ulong enable_early_verification_of_account_modifications; // 7Vced912WrRnfjaiKRiNBcbuFw7RrnLv3E3z95Y4GTNc
  ulong enable_partitioned_epoch_reward; // HCnE3xQoZtDz9dSVm3jKwJXioTb6zMRbgwCmGg3PHHk8
  ulong enable_program_redeployment_cooldown; // J4HFT8usBxpcF63y46t1upYobJgChmKyZPm5uTBRg25Z
  ulong enable_request_heap_frame_ix; // Hr1nUA9b7NJ6eChS26o7Vi8gYYDDwWD3YeBfzJkTbU86
  ulong enable_turbine_fanout_experiments; // D31EFnLgdiysi84Woo3of4JMu7VmasUS3Z7j9HYXCeLY
  ulong epoch_accounts_hash; // 5GpmAKxaGsWWbPp4bNXFLJxZVvG92ctxf7jQnzTQjF3n
  ulong error_on_syscall_bpf_function_hash_collisions; // 8199Q2gMD2kwgfopK5qqVWuDbegLgpuFUFHCcUJQDN8b
  ulong evict_invalid_stakes_cache_entries; // EMX9Q7TVFAmQ9V1CggAkhMzhXSg8ECp7fHrWQX2G1chf
  ulong executables_incur_cpi_data_cost; // 7GUcYgq4tVtaqNCKT3dho9r4665Qp5TxCZ27Qgjx3829
  ulong filter_stake_delegation_accounts; // GE7fRxmW46K6EmCD9AMZSbnaJ2e3LfqCZzdHi9hmYAgi
  ulong filter_votes_outside_slot_hashes; // 3gtZPqvPpsbXZVCx6hceMfWxtsmrjMzmg8C7PLKSxS2d
  ulong fix_recent_blockhashes; // 6iyggb5MTcsvdcugX7bEKbHV8c6jdLbpHwkncrgLMhfo
  ulong fixed_memcpy_nonoverlapping_check; // 36PRUK2Dz6HWYdG9SpjeAsF5F3KxnFCakA2BZMbtMhSb
  ulong full_inflation_devnet_and_testnet; // DT4n6ABDqs6w4bnfwrXT9rsprcPf6cdDga1egctaPkLC
  ulong full_inflation_mainnet_certusone_vote; // BzBBveUDymEYoYzcMWNQCx3cd4jQs7puaVFHLtsbB6fm
  ulong full_inflation_mainnet_certusoneenable; // 7XRJcS5Ud5vxGB54JbK9N2vBZVwnwdBNeJW1ibRgD9gx
  ulong include_account_index_in_rent_error; // 2R72wpcQ7qV7aTJWUumdn8u5wmmTyXbK7qzEy7YSAgyY
  ulong include_loaded_accounts_data_size_in_fee_calculation; // EaQpmC6GtRssaZ3PCUM5YksGqUdMLeZ46BQXYtHYakDS
  ulong increase_tx_account_lock_limit; // 9LZdXeKGeBV6hRLdxS1rHbHoEUsKqesCC2ZAPTPKJAbK
  ulong incremental_snapshot_only_incremental_hash_calculation; // 25vqsfjk7Nv1prsQJmA4Xu1bN61s8LXCBGUPp8Rfy1UF
  ulong instructions_sysvar_owned_by_sysvar; // H3kBSaKdeiUsyHmeHqjJYNc27jesXZ6zWj3zWkowQbkV
  ulong keep_merkle_shreds; // HyNQzc7TMNmRhpVHXqDGjpsHzeQie82mDQXSF9hj7nAH
  ulong last_restart_slot_sysvar; // HooKD5NC9QNxk25QuzCssB8ecrEzGt6eXEPBUxWp1LaR
  ulong leave_nonce_on_success; // E8MkiWZNNPGU6n55jkGzyj8ghUmjCHRmDFdYYFYHxWhQ
  ulong libsecp256k1_0_5_upgrade_enabled; // DhsYfRjxfnh2g7HKJYSzT79r74Afa1wbHkAgHndrA1oy
  ulong libsecp256k1_fail_on_bad_count; // 8aXvSuopd1PUj7UhehfXJRg6619RHp8ZvwTyyJHdUYsj
  ulong libsecp256k1_fail_on_bad_count2; // 54KAoNiUERNoWWUhTWWwXgym94gzoXFVnHyQwPA18V9A
  ulong limit_max_instruction_trace_length; // GQALDaC48fEhZGWRj9iL5Q889emJKcj3aCvHF7VCbbF4
  ulong limit_secp256k1_recovery_id; // 7g9EUwj4j7CS21Yx1wvgWLjSZeh5aPq8x9kpoPwXM8n8
  ulong loosen_cpi_size_restriction; // GDH5TVdbTPUpRnXaRyQqiKUa7uZAbZ28Q2N9bhbKoMLm
  ulong max_tx_account_locks; // CBkDroRDqm8HwHe6ak9cguPjUomrASEkfmxEaZ5CNNxz
  ulong merge_nonce_error_into_system_error; // 21AWDosvp3pBamFW91KB35pNoaoZVTM7ess8nr2nt53B
  ulong move_serialized_len_ptr_in_cpi; // 74CoWuBmt3rUVUrCb2JiSTvh6nXyBWUsK4SaMj3CtE3T
  ulong native_programs_consume_cu; // 8pgXCMNXC8qyEFypuwpXyRxLXZdpM4Qo72gJ6k87A6wL
  ulong no_overflow_rent_distribution; // 4kpdyrcj5jS47CZb2oJGfVxjYbsMm2Kx97gFyZrxxwXz
  ulong nonce_must_be_advanceable; // 3u3Er5Vc2jVcwz4xr2GJeSAXT3fAj6ADHZ4BJMZiScFd
  ulong nonce_must_be_authorized; // HxrEu1gXuH7iD3Puua1ohd5n4iUKJyFNtNxk9DVJkvgr
  ulong nonce_must_be_writable; // BiCU7M5w8ZCMykVSyhZ7Q3m2SWoR2qrEQ86ERcDX77ME
  ulong on_load_preserve_rent_epoch_for_rent_exempt_accounts; // CpkdQmspsaZZ8FVAouQTtTWZkc8eeQ7V3uj7dWz543rZ
  ulong optimize_epoch_boundary_updates; // 265hPS8k8xJ37ot82KEgjRunsUp5w4n4Q4VwwiN9i9ps
  ulong pico_inflation; // 4RWNif6C2WCNiKVW7otP4G7dkmkHGyKQWRpuZ1pxKU5m
  ulong preserve_rent_epoch_for_rent_exempt_accounts; // HH3MUYReL2BvqqA3oEcAa7txju5GY6G4nxJ51zvsEjEZ
  ulong prevent_calling_precompiles_as_programs; // 4ApgRX3ud6p7LNMJmsuaAcZY5HWctGPr5obAsjB3A54d
  ulong prevent_crediting_accounts_that_end_rent_paying; // 812kqX67odAp5NFwM8D2N24cku7WTm9CHUTFUXaDkWPn
  ulong prevent_rent_paying_rent_recipients; // Fab5oP3DmsLYCiQZXdjyqT3ukFFPrsmqhXU4WU1AWVVF
  ulong quick_bail_on_panic; // DpJREPyuMZ5nDfU6H3WTqSqUFSXAfw8u7xqmWtEwJDcP
  ulong record_instruction_in_transaction_context_push; // 3aJdcZqxoLpSBxgeYGjPwaYS1zzcByxUDqJkbzWAH1Zb
  ulong reduce_required_deploy_balance; // EBeznQDjcPG8491sFsKZYBi5S5jTVXMpAKNDJMQPS2kq
  ulong reject_callx_r10; // 3NKRSwpySNwD3TvP5pHnRmkAQRsdkXWRr1WaQh8p4PWX
  ulong reject_empty_instruction_without_program; // 9kdtFSrXHQg3hKkbXkQ6trJ3Ja1xpJ22CTFSNAciEwmL
  ulong reject_non_rent_exempt_vote_withdraws; // 7txXZZD6Um59YoLMF7XUNimbMjsqsWhc7g2EniiTrmp1
  ulong reject_vote_account_close_unless_zero_credit_epoch; // ALBk3EWdeAg2WAGf6GPDUf1nynyNqCdEVmgouG7rpuCj
  ulong relax_authority_signer_check_for_lookup_table_creation; // FKAcEvNgSY79RpqsPNUV5gDyumopH4cEHqUxyfm8b8Ap
  ulong remove_bpf_loader_incorrect_program_id; // 2HmTkCj9tXuPE4ueHzdD7jPeMf9JGCoZh5AsyoATiWEe
  ulong remove_congestion_multiplier_from_fee_calculation; // A8xyMHZovGXFkorFqEmVH2PKGLiBip5JD7jt4zsUWo4H
  ulong remove_deprecated_request_unit_ix; // EfhYd3SafzGT472tYQDUc4dPd2xdEfKs5fwkowUgVt4W
  ulong remove_native_loader; // HTTgmruMYRZEntyL3EdCDdnS6e4D5wRq1FA7kQsb66qq
  ulong rent_for_sysvars; // BKCPBQQBZqggVnFso5nQ8rQ4RwwogYwjuUt9biBjxwNF
  ulong requestable_heap_size; // CCu4boMmfLuqcmfTLPHQiUo22ZdUsXjgzPAURYaWt1Bw
  ulong require_custodian_for_locked_stake_authorize; // D4jsDcXaqdW8tDAWn8H4R25Cdns2YwLneujSL1zvjW6R
  ulong require_rent_exempt_accounts; // BkFDxiJQWZXGTZaJQxH7wVEHkAmwCgSEVkrvswFfRJPD
  ulong require_static_program_ids_in_transaction; // 8FdwgyHFEjhAdjWfV2vfqk7wA1g9X3fQpKH7SBpEv3kC
  ulong return_data_syscall_enabled; // DwScAzPUjuv65TMbDnFY7AgwmotzWy3xpEJMXM3hZFaB
  ulong round_up_heap_size; // CE2et8pqgyQMP2mQRg3CgvX8nJBKUArMu3wfiQiQKY1y
  ulong secp256k1_program_enabled; // E3PHP7w8kB7np3CTQ1qQ2tW3KCtjRSXBQgW9vM2mWv2Y
  ulong secp256k1_recover_syscall_enabled; // 6RvdSWHh8oh72Dp7wMTS2DBkf3fRPtChfNrAo3cZZoXJ
  ulong send_to_tpu_vote_port; // C5fh68nJ7uyKAuYZg2x9sEQ5YrVf3dkW6oojNBSc3Jvo
  ulong separate_nonce_from_blockhash; // Gea3ZkK2N4pHuVZVxWcnAtS6UEDdyumdYt4pFcKjA3ar
  ulong set_exempt_rent_epoch_max; // 5wAGiy15X1Jb2hkHnPDCM8oB9V42VNA9ftNVFK84dEgv
  ulong simplify_writable_program_account_check; // 5ZCcFAzJ1zsFKe1KSZa9K92jhx7gkcKj97ci2DBo1vwj
  ulong skip_rent_rewrites; // CGB2jM8pwZkeeiXQ66kBMyBR6Np61mggL7XUsmLjVcrw
  ulong sol_log_data_syscall_enabled; // 6uaHcKPGUy4J7emLBgUTeufhJdiwhngW6a1R9B7c2ob9
  ulong spl_associated_token_account_v1_0_4; // FaTa4SpiaSNH44PGC4z8bnGVTkSRYaWvrBs3KTu8XQQq
  ulong spl_associated_token_account_v1_1_0; // FaTa17gVKoqbh38HcfiQonPsAaQViyDCCSg71AubYZw8
  ulong spl_token_v2_multisig_fix; // E5JiFDQCwyC6QfT9REFyMpfK2mHcmv1GUDySU1Ue7TYv
  ulong spl_token_v2_self_transfer_fix; // BL99GYhdjjcv6ys22C9wPgn2aTVERDbPHHo4NbS3hgp7
  ulong spl_token_v2_set_authority_fix; // FToKNBYyiF4ky9s8WsmLBXHCht17Ek7RXaLZGHzzQhJ1
  ulong spl_token_v3_3_0_release; // Ftok2jhqAqxUWEiCVRrfRs9DPppWP8cgTB7NQNKL88mS
  ulong spl_token_v3_4_0; // Ftok4njE8b7tDffYkC5bAbCaQv5sL6jispYrprzatUwN
  ulong stake_allow_zero_undelegated_amount; // sTKz343FM8mqtyGvYWvbLpTThw3ixRM4Xk8QvZ985mw
  ulong stake_deactivate_delinquent_instruction; // 437r62HoAdUb63amq3D7ENnBLDhHT2xY8eFkLJYVKK4x
  ulong stake_merge_with_unmatched_credits_observed; // meRgp4ArRPhD3KtCY9c5yAf2med7mBLsjKTPeVUHqBL
  ulong stake_minimum_delegation_for_rewards; // ELjxSXwNsyXGfAh8TqX8ih22xeT8huF6UngQirbLKYKH
  ulong stake_program_advance_activating_credits_observed; // SAdVFw3RZvzbo6DvySbSdBnHN4gkzSTH9dSxesyKKPj
  ulong stake_raise_minimum_delegation_to_1_sol; // GQXzC7YiSNkje6FFUk6sc2p53XRvKoaZ9VMktYzUMnpL
  ulong stake_redelegate_instruction; // 3EPmAX94PvVJCjMeFfRFvj4avqCPL8vv3TGsZQg7ydMx
  ulong stake_split_uses_rent_sysvar; // FQnc7U4koHqWgRvFaBJjZnV8VPg6L6wWK33yJeDp4yvV
  ulong stakes_remove_delegation_if_inactive; // HFpdDDNQjvcXnXKec697HDDsyk6tFoWS2o8fkxuhQZpL
  ulong stop_sibling_instruction_search_at_parent; // EYVpEP7uzH1CoXzbD6PubGhYmnxRXPeq3PPsm1ba3gpo
  ulong stop_truncating_strings_in_syscalls; // 16FMCmgLzCNNz6eTwGanbyN2ZxvTBSLuQ6DZhgeMshg
  ulong switch_to_new_elf_parser; // Cdkc8PPTeTNUPoZEfCY5AyetUrEdkZtNPMgz58nqyaHD
  ulong syscall_saturated_math; // HyrbKftCdJ5CrUfEti6x26Cj7rZLNe32weugk7tLcWb8
  ulong system_transfer_zero_check; // BrTR9hzw4WBGFP65AJMbpAo64DcA3U6jdPSga9fMV5cS
  ulong tx_wide_compute_cap; // 5ekBxc8itEnPv4NzGJtr8BVVQLNMQuLMNQQj7pHoLNZ9
  ulong update_hashes_per_tick; // 3uFHb9oKdGfgZGJK9EHaAXN4USvnQtAFC13Fh5gGFS5B
  ulong update_rewards_from_cached_accounts; // 28s7i3htzhahXQKqmS2ExzbEoUypg9krwvtK2M9UWXh9
  ulong update_syscall_base_costs; // 2h63t332mGCCsWK2nqqqHhN4U9ayyqhLVFvczznHDoTZ
  ulong use_default_units_in_fee_calculation; // 8sKQrMQoUHtQSUP83SPG4ta2JDjSAiWs7t5aJ9uEd6To
  ulong verify_tx_signatures_len; // EVW9B5xD9FFK7vw1SBARwMA4s5eRo5eKJdKpsBikzKBz
  ulong versioned_tx_message_enabled; // 3KZZ6Ks1885aGBQ45fwRcPXVBCtzUvxhUTkwKMR41Tca
  ulong vote_authorize_with_seed; // 6tRxEYKuy2L5nnv5bgn7iT28MxUbYxp5h7F3Ncf1exrT
  ulong vote_stake_checked_instructions; // BcWknVcgvonN8sL4HE4XFuEVgfcee5MwxWPAgP6ZV89X
  ulong vote_state_add_vote_latency; // 7axKe5BTYBDD87ftzWbk5DfzWMGyRvqmWTduuo22Yaqy
  ulong vote_state_update_credit_per_dequeue; // CveezY6FDLVBToHDcvJRmtMouqzsmj4UXYh5ths5G5Uv
  ulong vote_state_update_root_fix; // G74BkWBzmsByZ1kxHy44H3wjwp5hp7JbrGRuDpco22tY
  ulong vote_withdraw_authority_may_change_authorized_voter; // AVZS3ZsN4gi6Rkx2QUibYuSJG3S6QHib7xCYhG6vGJxU
  ulong warp_timestamp_again; // GvDsGDkH5gyzwpDhxNixx8vtx1kwYHH13RiNAPw27zXb
  ulong warp_timestamp_with_a_vengeance; // 3BX6SBeEBibHaVQXywdkcgyUk6evfYZkHdztXiDtEpFS
  ulong zk_token_sdk_enabled; // zk1snxsc6Fh3wsGNbbHAJNHiJoYgF29mMnTSusGx5EJ
} fd_features_t;
void fd_enable_testnet(struct fd_features *);
void fd_enable_devnet(struct fd_features *);
void fd_enable_mainnet(struct fd_features *);
void fd_enable_everything(struct fd_features *);
void fd_update_features(fd_global_ctx_t * global);
void fd_update_feature(fd_global_ctx_t * global, ulong *, const char *key);
#endif
