#ifndef HEADER_fd_src_flamenco_runtime_fd_runtime_h
#define HEADER_fd_src_flamenco_runtime_fd_runtime_h

#include "stdarg.h"

#include "fd_runtime_err.h"
#include "fd_runtime_init.h"
#include "fd_rocksdb.h"
#include "fd_acc_mgr.h"
#include "fd_hashes.h"
#include "../features/fd_features.h"
#include "context/fd_capture_ctx.h"
#include "context/fd_exec_txn_ctx.h"
#include "info/fd_runtime_block_info.h"
#include "info/fd_instr_info.h"
#include "../../disco/pack/fd_microblock.h"
#include "info/fd_microblock_info.h"
#include "../../ballet/sbpf/fd_sbpf_loader.h"
#include "../vm/fd_vm_base.h"

/* Various constant values used by the runtime. */

#define MICRO_LAMPORTS_PER_LAMPORT (1000000UL)

#define DEFAULT_HASHES_PER_TICK  (12500)
#define UPDATED_HASHES_PER_TICK2 (17500)
#define UPDATED_HASHES_PER_TICK3 (27500)
#define UPDATED_HASHES_PER_TICK4 (47500)
#define UPDATED_HASHES_PER_TICK5 (57500)
#define UPDATED_HASHES_PER_TICK6 (62500)

#define FD_RUNTIME_TRACE_NONE   (0)
#define FD_RUNTIME_TRACE_SAVE   (1)
#define FD_RUNTIME_TRACE_REPLAY (2)

#define FD_RUNTIME_OFFLINE_NUM_ROOT_BLOCKS (6UL) /* 6 root blocks for offline replay */

#define FD_RENT_EXEMPT_RENT_EPOCH (ULONG_MAX)

#define SECONDS_PER_YEAR ((double)(365.242199 * 24.0 * 60.0 * 60.0))

/*
 * fd_block_entry_batch_t is a microblock/entry batch within a block.
 * The offset is relative to the start of the block's data region,
 * and indicates where the batch ends.  The (exclusive) end offset of
 * batch i is the (inclusive) start offset of batch i+1.  The 0th batch
 * always starts at offset 0.
 * On the wire, the presence of one of the COMPLETE flags in a data
 * shred marks the end of a batch.
 * In other words, batch ends are aligned with shred ends, and batch
 * starts are aligned with shred starts.  Usually a batch comprises
 * multiple shreds, and a block comprises multiple batches.
 * This information is useful because bincode deserialization needs to
 * be performed on a per-batch basis.  Precisely a single array of
 * microblocks/entries is expected to be deserialized from a batch.
 * Trailing bytes in each batch are ignored by default.
 */
struct fd_block_entry_batch {
  ulong end_off; /* exclusive */
};
typedef struct fd_block_entry_batch fd_block_entry_batch_t;

/* The below logic is used to size out the memory footprint generated by the
   runtime during transaction execution. */

/* The prevailing layout we have in the runtime is the meta followed by
   the account's data. This struct encodes that layout and asserts that
   the alignment requirements of the constituents are satisfied. */
// TODO: Use this struct at allocation sites so it's clear we use this layout
struct __attribute__((packed)) fd_account_rec {
  fd_account_meta_t meta;
  uchar data[] __attribute__((aligned(8)));
};
typedef struct fd_account_rec fd_account_rec_t;
#define FD_ACCOUNT_REC_ALIGN      (8UL)
#define FD_ACCOUNT_REC_DATA_ALIGN (8UL)
FD_STATIC_ASSERT( FD_ACCOUNT_REC_ALIGN>=alignof(fd_account_meta_t), account_rec_meta_align );
FD_STATIC_ASSERT( FD_ACCOUNT_REC_ALIGN>=FD_ACCOUNT_REC_DATA_ALIGN,  account_rec_data_align );
FD_STATIC_ASSERT( (offsetof(fd_account_rec_t, meta)%alignof(fd_account_meta_t))==0, account_rec_meta_offset );
FD_STATIC_ASSERT( (offsetof(fd_account_rec_t, data)%FD_ACCOUNT_REC_DATA_ALIGN )==0, account_rec_data_offset );

#define MAX_PERMITTED_DATA_INCREASE (10240UL) // 10KB
#define FD_BPF_ALIGN_OF_U128        (8UL    )
FD_STATIC_ASSERT( FD_BPF_ALIGN_OF_U128==FD_ACCOUNT_REC_DATA_ALIGN, input_data_align );
#define FD_RUNTIME_INPUT_REGION_ALLOC_ALIGN_UP (16UL)

/******** These macros bound out memory footprint ********/

/* The tight upper bound on borrowed account footprint over the
   execution of a single transaction. */
#define FD_RUNTIME_BORROWED_ACCOUNT_FOOTPRINT (MAX_TX_ACCOUNT_LOCKS * FD_ULONG_ALIGN_UP( FD_ACC_TOT_SZ_MAX, FD_ACCOUNT_REC_ALIGN ))

/* The tight-ish upper bound on input region footprint over the
   execution of a single transaction. See input serialization code for
   reference: fd_bpf_loader_serialization.c

   This bound is based off of the transaction MTU. We consider the
   question of what kind of transaction one would construct to
   maximally bloat the input region.
   The worst case scenario is when every nested instruction references
   all unique accounts in the transaction. A transaction can lock a max
   of MAX_TX_ACCOUNT_LOCKS accounts. Then all remaining input account
   references are going to be duplicates, which cost 1 byte to specify
   offset in payload, and which cost 8 bytes during serialization. Then
   there would be 0 bytes of instruction data, because they exist byte
   for byte in the raw payload, which is not a worthwhile bloat factor.
 */
#define FD_RUNTIME_INPUT_REGION_UNIQUE_ACCOUNT_FOOTPRINT(direct_mapping)                                                                                              \
                                                        (1UL                         /* dup byte          */                                                        + \
                                                         sizeof(uchar)               /* is_signer         */                                                        + \
                                                         sizeof(uchar)               /* is_writable       */                                                        + \
                                                         sizeof(uchar)               /* executable        */                                                        + \
                                                         sizeof(uint)                /* original_data_len */                                                        + \
                                                         sizeof(fd_pubkey_t)         /* key               */                                                        + \
                                                         sizeof(fd_pubkey_t)         /* owner             */                                                        + \
                                                         sizeof(ulong)               /* lamports          */                                                        + \
                                                         sizeof(ulong)               /* data len          */                                                        + \
                                                         (direct_mapping ? FD_BPF_ALIGN_OF_U128 : FD_ULONG_ALIGN_UP( FD_RUNTIME_ACC_SZ_MAX, FD_BPF_ALIGN_OF_U128 )) + \
                                                         MAX_PERMITTED_DATA_INCREASE                                                                                + \
                                                         sizeof(ulong))              /* rent_epoch        */

#define FD_RUNTIME_INPUT_REGION_INSN_FOOTPRINT(account_lock_limit, direct_mapping)                                                                       \
                                              (FD_ULONG_ALIGN_UP( (sizeof(ulong)         /* acct_cnt       */                                          + \
                                                                   account_lock_limit*FD_RUNTIME_INPUT_REGION_UNIQUE_ACCOUNT_FOOTPRINT(direct_mapping) + \
                                                                   sizeof(ulong)         /* instr data len */                                          + \
                                                                                         /* No instr data  */                                            \
                                                                   sizeof(fd_pubkey_t)), /* program id     */                                            \
                                                                   FD_RUNTIME_INPUT_REGION_ALLOC_ALIGN_UP ) + FD_BPF_ALIGN_OF_U128)

#define FD_RUNTIME_INPUT_REGION_TXN_FOOTPRINT(account_lock_limit, direct_mapping)                                                                           \
                                             ((FD_MAX_INSTRUCTION_STACK_DEPTH*FD_RUNTIME_INPUT_REGION_INSN_FOOTPRINT(account_lock_limit, direct_mapping)) + \
                                              ((FD_TXN_MTU-FD_TXN_MIN_SERIALIZED_SZ-account_lock_limit)*8UL)) /* We can have roughly this much duplicate offsets */

/* Bincode valloc footprint over the execution of a single transaction.
   As well as other footprint specific to each native program type.

   N.B. We know that bincode valloc footprint is bounded, because
   whenever we alloc something, we advance our pointer into the binary
   buffer, so eventually we are gonna reach the end of the buffer.
   This buffer is usually backed by and ultimately bounded in size by
   either accounts data or the transaction MTU.

   That being said, it's not obvious what the tight upper bound would
   be for allocations across all possible execution paths of all native
   programs, including possible CPIs from native programs.  The
   footprint estimate here is based on a manual review of our native
   program implementation.  Note that even if the possible paths remain
   steady at the Solana protocol level, the footprint is subject to
   change when we change our implementation.

   ### Native programs
   ALUT (migrated to BPF)
   Loader
     - rodata for bpf program relocation and validation
   Compute budget (0 allocations)
   Config (migrated to BPF)
   Precompile (0 allocations)
   Stake
     - The instruction with the largest footprint is deactivate_delinquent
       - During instruction decode, no allocations
       - During execution, this is (vote account get_state() + vote convert_to_current()) times 2, once for delinquent_vote_account, and once for reference_vote_account
   System
     - system_program_instruction_decode seed
   Vote
     - The instruction with the largest footprint is compact vote state update
       - During instruction decode, this is 9*lockouts_len bytes, MTU bounded
       - During execution, this is vote account get_state() + vote convert_to_current() + 12*lockouts_len bytes + lockouts_len ulong + deq_fd_landed_vote_t_alloc(lockouts_len)
   Zk Elgamal (0 allocations)

   The largest footprint is hence deactivate_delinquent, in which the
   two get_state() calls dominate the footprint.  In particular, the
   authorized_voters treaps bloat 40 bytes (epoch+pubkey) in a vote
   account to 72 bytes (sizeof(fd_vote_authorized_voter_t)) in memory.
 */
#define FD_RUNTIME_BINCODE_AND_NATIVE_FOOTPRINT (2UL*FD_RUNTIME_ACC_SZ_MAX*72UL/40UL)

/* Misc other footprint. */
#define FD_RUNTIME_SYSCALL_TABLE_FOOTPRINT (FD_MAX_INSTRUCTION_STACK_DEPTH*FD_ULONG_ALIGN_UP(FD_SBPF_SYSCALLS_FOOTPRINT, FD_SBPF_SYSCALLS_ALIGN))

#define FD_RUNTIME_VM_TRACE_EVENT_MAX      (128UL<<20)
#define FD_RUNTIME_VM_TRACE_EVENT_DATA_MAX (2048UL)
#define FD_RUNTIME_VM_TRACE_FOOTPRINT      (FD_MAX_INSTRUCTION_STACK_DEPTH*fd_ulong_align_up( fd_vm_trace_footprint( FD_RUNTIME_VM_TRACE_EVENT_MAX, FD_RUNTIME_VM_TRACE_EVENT_DATA_MAX ), fd_vm_trace_align() ))

#define FD_RUNTIME_MISC_FOOTPRINT (FD_RUNTIME_SYSCALL_TABLE_FOOTPRINT)
#define FD_SOLFUZZ_MISC_FOOTPRINT (FD_RUNTIME_SYSCALL_TABLE_FOOTPRINT + FD_RUNTIME_VM_TRACE_FOOTPRINT)

/* Now finally, we bound out the footprint of transaction execution. */
#define FD_RUNTIME_TRANSACTION_EXECUTION_FOOTPRINT(account_lock_limit, direct_mapping)                                         \
                                                  (FD_RUNTIME_BORROWED_ACCOUNT_FOOTPRINT                                     + \
                                                   FD_RUNTIME_INPUT_REGION_TXN_FOOTPRINT(account_lock_limit, direct_mapping) + \
                                                   FD_RUNTIME_BINCODE_AND_NATIVE_FOOTPRINT                                   + \
                                                   FD_RUNTIME_MISC_FOOTPRINT)

/* Convenience macros for common use cases.

   TODO: If account lock limits are increased to 128, this macro will need to be updated. */
#define FD_RUNTIME_TRANSACTION_EXECUTION_FOOTPRINT_FUZZ    FD_RUNTIME_TRANSACTION_EXECUTION_FOOTPRINT(64UL, 0) + FD_SOLFUZZ_MISC_FOOTPRINT
#define FD_RUNTIME_TRANSACTION_EXECUTION_FOOTPRINT_DEFAULT FD_RUNTIME_TRANSACTION_EXECUTION_FOOTPRINT(64UL, 0)

/* Helpers for runtime public frame management. */

/* Helpers for runtime spad frame management. */
struct fd_runtime_spad_verify_handle_private {
  fd_spad_t *         spad;
  fd_exec_txn_ctx_t * txn_ctx;
};
typedef struct fd_runtime_spad_verify_handle_private fd_runtime_spad_verify_handle_private_t;

static inline void
fd_runtime_spad_private_frame_end( fd_runtime_spad_verify_handle_private_t * _spad_handle ) {
  /* fd_spad_verify() returns 0 if everything looks good, and non-zero
     otherwise.

     Since the fast spad alloc API doesn't check for or indicate an OOM
     situation and is going to happily permit an OOB alloc, we need
     some way of detecting that. Moreover, we would also like to detect
     unbalanced frame push/pop or usage of more frames than allowed.
     While surrounding the spad with guard regions will help detect the
     former, it won't necessarily catch the latter.

     On compliant transactions, fd_spad_verify() isn't all that
     expensive.  Nonetheless, We invoke fd_spad_verify() only at the
     peak of memory usage, and not gratuitously everywhere. One peak
     would be right before we do the most deeply nested spad frame pop.
     However, we do pops through compiler-inserted cleanup functions
     that take only a single pointer, so we define this helper function
     to access the needed context info.  The end result is that we do
     super fast spad calls everywhere in the runtime, and every now and
     then we invoke verify to check things. */
  /* -1UL because spad pop is called after instr stack pop. */
  if( FD_UNLIKELY( _spad_handle->txn_ctx->instr_stack_sz>=FD_MAX_INSTRUCTION_STACK_DEPTH-1UL && fd_spad_verify( _spad_handle->txn_ctx->spad ) ) ) {
    uchar const * txn_signature = (uchar const *)fd_txn_get_signatures( TXN( &_spad_handle->txn_ctx->txn ), _spad_handle->txn_ctx->txn.payload );
    FD_BASE58_ENCODE_64_BYTES( txn_signature, sig );
    FD_LOG_ERR(( "spad corrupted or overflown on transaction %s", sig ));
  }
  fd_spad_pop( _spad_handle->spad );
}

#define FD_RUNTIME_TXN_SPAD_FRAME_BEGIN(_spad, _txn_ctx) do {                                                        \
  fd_runtime_spad_verify_handle_private_t _spad_handle __attribute__((cleanup(fd_runtime_spad_private_frame_end))) = \
    (fd_runtime_spad_verify_handle_private_t) { .spad = _spad, .txn_ctx = _txn_ctx };                                \
  fd_spad_push( _spad_handle.spad );                                                                                 \
  do

#define FD_RUNTIME_TXN_SPAD_FRAME_END while(0); } while(0)

FD_PROTOTYPES_BEGIN

/* Runtime Helpers ************************************************************/

/*
   Returns 0 on success, and non zero otherwise.  On failure, the
   out values will not be modified.
 */
int
fd_runtime_compute_max_tick_height( ulong   ticks_per_slot,
                                    ulong   slot,
                                    ulong * out_max_tick_height /* out */ );

void
fd_runtime_update_leaders( fd_bank_t * bank,
                           fd_spad_t * runtime_spad );

/* TODO: Invoked by fd_executor: layering violation. Rent logic is deprecated
   and will be torn out entirely very soon. */
ulong
fd_runtime_collect_rent_from_account( fd_epoch_schedule_t const * schedule,
                                      fd_rent_t const *           rent,
                                      double                      slots_per_year,
                                      fd_txn_account_t *          acc,
                                      ulong                       epoch );

void
fd_runtime_update_slots_per_epoch( fd_bank_t * bank,
                                   ulong       slots_per_epoch );

/* Block Level Execution Prep/Finalize ****************************************/

#define FD_BLOCK_OK                          (0UL)
#define FD_BLOCK_ERR_INCOMPLETE              (1UL)
#define FD_BLOCK_ERR_INVALID_ENTRY_HASH      (2UL)
#define FD_BLOCK_ERR_INVALID_LAST_TICK       (3UL)
#define FD_BLOCK_ERR_TOO_FEW_TICKS           (4UL)
#define FD_BLOCK_ERR_TOO_MANY_TICKS          (5UL)
#define FD_BLOCK_ERR_INVALID_TICK_HASH_COUNT (6UL)
#define FD_BLOCK_ERR_TRAILING_ENTRY          (7UL)
#define FD_BLOCK_ERR_DUPLICATE_BLOCK         (8UL)

/*
   https://github.com/anza-xyz/agave/blob/v2.1.0/ledger/src/blockstore_processor.rs#L1096
   This function assumes a full block.
   This needs to be called after epoch processing to get the up to date
   hashes_per_tick.

   Provide scratch memory >= the max size of a batch to use. This is because we can only
   assemble shreds by batch, so we iterate and assemble shreds by batch in this function
   without needing the caller to do so.
 */
// FD_FN_UNUSED ulong /* FIXME */
// fd_runtime_block_verify_ticks( fd_blockstore_t * blockstore,
//                                ulong             slot,
//                                uchar *           block_data_mem,
//                                ulong             block_data_sz,
//                                ulong             tick_height,
//                                ulong             max_tick_height,
//                                ulong             hashes_per_tick );

/* The following microblock-level functions are exposed and non-static due to also being used for fd_replay.
   The block-level equivalent functions, on the other hand, are mostly static as they are only used
   for offline replay */

/* extra fine-grained streaming tick verification */
// FD_FN_UNUSED int /* FIXME */
// fd_runtime_microblock_verify_ticks( fd_blockstore_t *           blockstore,
//                                     ulong                       slot,
//                                     fd_microblock_hdr_t const * hdr,
//                                     bool               slot_complete,
//                                     ulong              tick_height,
//                                     ulong              max_tick_height,
//                                     ulong              hashes_per_tick );

/*
   fd_runtime_microblock_verify_read_write_conflicts verifies that a
   list of txns (e.g., those in a microblock) do not have read-write
   or write-write conflits. FD_TXN_CONFLICT_MAP_MAX_NACCT defines a
   conservative estimation of the number of accounts touched by txns
   in one slot. Given the conservative estimation, the footprint of
   the account map (fd_conflict_detect_map) is about 2112MB. One can
   certainly use a better estimation leading to a smaller footprint.

   this function corresponds to try_lock_accounts in Agave which
   detects transaction conflicts:
   https://github.com/anza-xyz/agave/blob/v2.2.3/runtime/src/bank.rs
   #L3145

   Specifically, from the replay stage of Agave, the control flow is
   (1) replay_blockstore_into_bank: https://github.com/anza-xyz/agave/
   blob/v2.2.3/core/src/replay_stage.rs#L2232
   (2) confirm_slot: https://github.com/anza-xyz/agave/blob/v2.2.3/
   ledger/src/blockstore_processor.rs#L1561
   (3) confirm_slot_entries: https://github.com/anza-xyz/agave/blob/
   v2.2.3/ledger/src/blockstore_processor.rs#L1609
   (4) process_entries: https://github.com/anza-xyz/agave/blob/v2.2.3/
   ledger/src/blockstore_processor.rs#L704
   (5) queue_batches_with_lock_retry: https://github.com/anza-xyz/agave/
   blob/v2.2.3/ledger/src/blockstore_processor.rs#L789
   (6) bank.try_lock_accounts is called in queue_batches_with_lock_retry
   (7) this try_lock_accounts eventually calls another try_lock_accounts,
       (see https://github.com/anza-xyz/agave/blob/v2.2.3/accounts-db/src
       /account_locks.rs#L24), which acquires the locks and returns
       TransactionError::AccountInUse if r-w or w-w conflict is detected
   (8) when calling try_lock_accounts, function accounts_with_is_writable
   is used to decide whether an account is writable (see https://github.
   com/anza-xyz/agave/blob/v2.2.3/accounts-db/src/accounts.rs#L605) which
   internally calls the is_writable function depending on whether the txn
   is legacy or V0:

   is_writable for legacy: https://github.com/anza-xyz/solana-sdk/blob/
   message%40v2.2.1/message/src/sanitized.rs#L75

   is_writable for V0: https://github.com/anza-xyz/solana-sdk/blob/
   message%40v2.2.1/message/src/versions/v0/loaded.rs#L152

   In both cases, Agave does the following check in addition to whether
   an account has been specified as writable in the transaction message
   (https://github.com/anza-xyz/solana-sdk/blob/message%40v2.2.1/message
   /src/versions/v0/loaded.rs#L146). This additional check is handled by
   function fd_txn_account_is_writable_idx_flat in our code.

   txns is an array containing txn_cnt transactions in fd_txn_p_t type;
   acct_map is used to detect conflicts and acct_arr is used to clear the
   map before the function returns; funk and funk_txn are used to read
   Solana accounts for address lookup tables; slot and slot_hashes are
   needed for checking certain bounds in the address lookup table system
   program; features is needed in fd_txn_account_is_writable_idx_flat to
   decide whether a writable account is demoted to read-only.

   If an error occurs in runtime, the function returns the runtime error.
   If there's no conflict, the return value is FD_RUNTIME_EXECUTE_SUCCESS
   and out_conflict_detected will be 0. If there's a conflict, the return
   value is FD_RUNTIME_TXN_ERR_ACCOUNT_IN_USE and out_conflict_detected
   will be 1 (read-write) or 2 (write-write), and out_conflict_addr_opt,
   if not NULL, will hold the account address causing the conflict.
 */
struct fd_conflict_detect_ele {
  fd_acct_addr_t key;
  uchar          writable;
};
typedef struct fd_conflict_detect_ele fd_conflict_detect_ele_t;
#define FD_TXN_CONFLICT_MAP_SEED        (0UL)
#define FD_TXN_CONFLICT_MAP_MAX_NACCT   (FD_SHRED_DATA_PAYLOAD_MAX_PER_SLOT / FD_TXN_MIN_SERIALIZED_SZ * FD_TXN_ACCT_ADDR_MAX)

static const fd_acct_addr_t fd_acct_addr_null = {.b={0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF}};
#define MAP_NAME              fd_conflict_detect_map
#define MAP_KEY_T             fd_acct_addr_t
#define MAP_T                 fd_conflict_detect_ele_t
#define MAP_HASH_T            ulong
#define MAP_KEY_NULL          (fd_acct_addr_null)
#define MAP_KEY_EQUAL(k0,k1)  (0==memcmp((k0).b,(k1).b,32))
#define MAP_KEY_HASH(key)     fd_hash( FD_TXN_CONFLICT_MAP_SEED, key.b, 32 )
#define MAP_KEY_INVAL(k)      (0==memcmp(&fd_acct_addr_null, (k).b, 32))
#define MAP_KEY_EQUAL_IS_SLOW 0
#define MAP_MEMOIZE           0

#include "../../util/tmpl/fd_map_dynamic.c"

#define FD_RUNTIME_NO_CONFLICT_DETECTED          0
#define FD_RUNTIME_READ_WRITE_CONFLICT_DETECTED  1
#define FD_RUNTIME_WRITE_WRITE_CONFLICT_DETECTED 2

int
fd_runtime_microblock_verify_read_write_conflicts( fd_txn_p_t *               txns,
                                                   ulong                      txn_cnt,
                                                   fd_conflict_detect_ele_t * acct_map,
                                                   fd_acct_addr_t *           acct_arr,
                                                   fd_funk_t *                funk,
                                                   fd_funk_txn_xid_t const *  xid,
                                                   ulong                      slot,
                                                   fd_slot_hash_t *           slot_hashes,
                                                   fd_features_t *            features,
                                                   int *                      out_conflict_detected,
                                                   fd_acct_addr_t *           out_conflict_addr_opt );

/* Load the accounts in the address lookup tables of txn into out_accts_alt */
int
fd_runtime_load_txn_address_lookup_tables(
    fd_txn_t const *          txn,
    uchar const *             payload,
    fd_funk_t *               funk,
    fd_funk_txn_xid_t const * xid,
    ulong                     slot,
    fd_slot_hash_t const *    hashes, /* deque */
    fd_acct_addr_t *          out_accts_alt
);

int
fd_runtime_block_execute_prepare( fd_bank_t *               bank,
                                  fd_funk_t *               funk,
                                  fd_funk_txn_xid_t const * xid,
                                  fd_capture_ctx_t *        capture_ctx,
                                  fd_spad_t *               runtime_spad );

void
fd_runtime_block_execute_finalize( fd_bank_t *               bank,
                                   fd_funk_t *               funk,
                                   fd_funk_txn_xid_t const * xid,
                                   fd_capture_ctx_t *        capture_ctx,
                                   int                       silent );

/* Transaction Level Execution Management *************************************/

int
fd_runtime_pre_execute_check( fd_exec_txn_ctx_t * txn_ctx );

/* fd_runtime_prepare_and_execute_txn is the main entrypoint from the
   executor tile. It is responsible for preparing and executing a single
   transaction. */

int
fd_runtime_prepare_and_execute_txn( fd_banks_t *        banks,
                                    ulong               bank_idx,
                                    fd_exec_txn_ctx_t * txn_ctx,
                                    fd_txn_p_t *        txn,
                                    fd_capture_ctx_t *  capture_ctx,
                                    uchar               do_sigverify );

void
fd_runtime_finalize_txn( fd_funk_t *               funk,
                         fd_txncache_t *           txncache,
                         fd_funk_txn_xid_t const * xid,
                         fd_exec_txn_ctx_t *       txn_ctx,
                         fd_bank_t *               bank,
                         fd_capture_ctx_t *        capture_ctx );

/* Epoch Boundary *************************************************************/

/*
   This is roughly Agave's process_new_epoch() which gets called from
   new_from_parent() for every slot.
   https://github.com/anza-xyz/agave/blob/v1.18.26/runtime/src/bank.rs#L1483
   This needs to be called after funk_txn_prepare() because the accounts
   that we modify when processing a new epoch need to be hashed into
   the bank hash.
 */
void
fd_runtime_block_pre_execute_process_new_epoch( fd_banks_t *              banks,
                                                fd_bank_t *               bank,
                                                fd_funk_t *               funk,
                                                fd_funk_txn_xid_t const * xid,
                                                fd_capture_ctx_t *        capture_ctx,
                                                fd_spad_t *               runtime_spad,
                                                int *                     is_epoch_boundary );

/* `fd_runtime_update_program_cache()` is responsible for updating the
   program cache with any programs referenced in the current
   transaction. See fd_program_cache.h for more details.

   Note that ALUTs must be resolved because programs referenced in ALUTs
   can be invoked via CPI.

   TODO: We need to remove the ALUT resolution from this function
   because it is redundant (ALUTs get resolved again in the exec tile). */
void
fd_runtime_update_program_cache( fd_bank_t *               bank,
                                 fd_funk_t *               funk,
                                 fd_funk_txn_xid_t const * xid,
                                 fd_txn_p_t const *        txn_p,
                                 fd_spad_t *               runtime_spad );

/* Offline Replay *************************************************************/

void
fd_runtime_read_genesis( fd_banks_t *                       banks,
                         fd_bank_t *                        bank,
                         fd_funk_t *                        funk,
                         fd_funk_txn_xid_t const *          xid,
                         fd_capture_ctx_t *                 capture_ctx,
                         fd_hash_t const *                  genesis_hash,
                         fd_lthash_value_t const *          genesis_lthash,
                         fd_genesis_solana_global_t const * genesis_block,
                         fd_spad_t *                        runtime_spad );


/* Returns whether the specified epoch should use the new vote account
   keyed leader schedule (returns 1) or the old validator identity keyed
   leader schedule (returns 0). See SIMD-0180.
   This is the analogous of Agave's Bank::should_use_vote_keyed_leader_schedule():
   https://github.com/anza-xyz/agave/blob/v2.3.1/runtime/src/bank.rs#L6148 */
int
fd_runtime_should_use_vote_keyed_leader_schedule( fd_bank_t * bank );

FD_PROTOTYPES_END

#endif /* HEADER_fd_src_flamenco_runtime_fd_runtime_h */
