#!/usr/bin/env python3
"""Generate the register-resident 32-point GFNI transform schedules."""

from pathlib import Path


N = 32


def gf_mul(a, b):
    out = 0
    while b:
        if b & 1:
            out ^= a
        b >>= 1
        a = (a << 1) ^ (0x11D if a & 0x80 else 0)
    return out


def gf_pow(a, n):
    out = 1
    while n:
        if n & 1:
            out = gf_mul(out, a)
        a = gf_mul(a, a)
        n >>= 1
    return out


def make_sbar():
    svals = [[0] * 256 for _ in range(8)]
    sbar = [[0] * 256 for _ in range(8)]
    for x in range(256):
        svals[0][x] = x
    for j in range(8):
        if j:
            bit = 1 << (j - 1)
            for x in range(256):
                svals[j][x] = gf_mul(svals[j - 1][x], svals[j - 1][x ^ bit])
        scale = gf_pow(svals[j][1 << j], 254)
        for x in range(256):
            sbar[j][x] = gf_mul(svals[j][x], scale)
    return sbar


SBAR = make_sbar()


def ifft_ops(size, shift, i_round=0, r_offset=0):
    if 1 << i_round == size:
        return []
    out = []
    for j in range(size >> (i_round + 1)):
        omega = j << (i_round + 1)
        reg0 = r_offset + omega
        reg1 = r_offset + (1 << i_round) + omega
        out.append((i_round, reg0, reg1, SBAR[i_round][omega ^ shift],
                    (r_offset, i_round, omega),
                    (r_offset, i_round, omega + (1 << i_round)),
                    (r_offset, i_round + 1, omega),
                    (r_offset + (1 << i_round), i_round + 1, omega)))
    out += ifft_ops(size, shift, i_round + 1, r_offset)
    out += ifft_ops(size, shift, i_round + 1, r_offset + (1 << i_round))
    return out


def fft_ops(size, shift, i_round=0, r_offset=0):
    if 1 << i_round == size:
        return []
    out = fft_ops(size, shift, i_round + 1, r_offset)
    out += fft_ops(size, shift, i_round + 1, r_offset + (1 << i_round))
    for j in range(size >> (i_round + 1)):
        omega = j << (i_round + 1)
        reg0 = r_offset + omega
        reg1 = r_offset + (1 << i_round) + omega
        out.append((i_round, reg0, reg1, SBAR[i_round][omega ^ shift],
                    (r_offset, i_round + 1, omega),
                    (r_offset + (1 << i_round), i_round + 1, omega),
                    (r_offset, i_round, omega),
                    (r_offset, i_round, omega + (1 << i_round))))
    return out


def emit_butterfly(lines, kind, reg0, reg1, const, scratch):
    if const:
        lines.append(f"  {kind}_butterfly    {reg0:2}, {reg1:2}, {const:3}, {scratch:2}")
    else:
        lines.append(f"  {kind}_butterfly_c0 {reg0:2}, {reg1:2},      {scratch:2}")


def emit_schedule(input_shift, output_shift):
    lines = [
        "/* Note: This file is auto-generated by generate_gfni_32.py. */",
        f"  /* IFFT(32,{input_shift}) followed by FFT(32,{output_shift}). */",
    ]
    scratch = 31
    current = [(0, 0, i) for i in range(N)]
    for kind, ops in (("ifft", ifft_ops(N, input_shift)),
                      ("fft",  fft_ops(N, output_shift))):
        pending = list(ops)
        while pending:
            for idx, op in enumerate(pending):
                i_round, reg0, reg1, const, in0, in1, out0, out1 = op
                if (reg0 != scratch and reg1 != scratch and
                        current[reg0] == in0 and current[reg1] == in1):
                    break
            else:
                if scratch == 31:
                    lines.append("  spill_reload      14, 31")
                    scratch = 14
                else:
                    lines.append("  spill_reload      31, 14")
                    scratch = 31
                continue
            pending.pop(idx)
            emit_butterfly(lines, kind, reg0, reg1, const, scratch)
            current[reg0], current[reg1] = out0, out1
            if kind == "fft" and i_round == 0:
                lines.append(f"  output_store      {reg0:2}, {scratch:2}")
                lines.append(f"  output_store      {reg1:2}, {scratch:2}")
        if scratch == 14:
            lines.append("  spill_reload      31, 14")
            scratch = 31
    return "\n".join(lines) + "\n"


root = Path(__file__).resolve().parent
(root / "generated").mkdir(exist_ok=True)
(root / "generated" / "fd_reedsol_gfni_32_encode.inc").write_text(
    emit_schedule(0, 32), encoding="utf-8")
(root / "generated" / "fd_reedsol_gfni_32_reverse.inc").write_text(
    emit_schedule(32, 0), encoding="utf-8")
