#!/bin/bash

export PKG_CONFIG_LIBDIR=""
export PKG_CONFIG_PATH="$(pwd)/opt/lib/pkgconfig:$(pwd)/opt/lib64/pkgconfig"

if command -v module; then
  # Jump internal use

  if [ $# -gt 0 ] && [ "$1" = "install" ]; then
    # Install Packages needed for dev hosts
    sudo yum install          \
      jump_module_gcc-9.3.0   \
      jump_module_clang-15.0
  fi

  module purge
  module load gcc-9.3.0
  module load clang-15.0
  module list
fi
