[workspace]
members = ["src/app/fdctl", "ffi/rust/firedancer-sys"] # ", ffi/rust/firedancer-diff"]
default-members = ["src/app/fdctl"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
