{
 "title": "Firedancer Accounts",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(replay_accdb_created_total,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Account Growth",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "expr": "sum(rate(replay_accdb_created_total{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Slot Boundary"
    },
    {
     "expr": "sum(rate(replay_accdb_created_total{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Transactions"
    },
    {
     "expr": "-sum(rate(replay_accdb_garbage_collected_total{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Rooting"
    },
    {
     "expr": "-sum(rate(replay_accdb_reverted_total{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Reverted"
    },
    {
     "expr": "-sum(rate(replay_accdb_reclaimed_total{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Reclaimed"
    }
   ]
  },
  {
   "title": "Account Count",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "(\n    (\n        sum(snapin_account_loaded{instance=\"$instance\"})\n        -\n        (\n            sum(snapin_account_replaced{instance=\"$instance\"}) +\n            sum(snapin_account_ignored{instance=\"$instance\"})\n        )\n    )\n    and on() (snapin_state{instance=\"$instance\"} == 4)\n)",
     "legendFormat": "Snapshot"
    },
    {
     "expr": "(\n    sum(increase(replay_accdb_created_total{instance=\"$instance\"}[$__rate_interval])) + \n    sum(increase(replay_accdb_created_total{instance=\"$instance\"}[$__rate_interval]))\n) -\n(\n    sum(increase(replay_accdb_garbage_collected_total{instance=\"$instance\"}[$__rate_interval])) +\n    sum(increase(replay_accdb_reverted_total{instance=\"$instance\"}[$__rate_interval])) +\n    sum(increase(replay_accdb_reclaimed_total{instance=\"$instance\"}[$__rate_interval]))\n)",
     "legendFormat": "Delta"
    }
   ]
  },
  {
   "title": "Record Pool Changes",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(replay_accdb_created_total{instance=\"$instance\"}[$__range])) +\nsum(increase(replay_accdb_created_total{instance=\"$instance\"}[$__range]))",
     "legendFormat": "Created"
    },
    {
     "expr": "increase(replay_accdb_rooted_total{instance=\"$instance\"}[$__range])",
     "legendFormat": "Rooted"
    },
    {
     "expr": "increase(replay_accdb_garbage_collected_total{instance=\"$instance\"}[$__range])",
     "legendFormat": "Removed"
    },
    {
     "expr": "increase(replay_accdb_reclaimed_total{instance=\"$instance\"}[$__range])",
     "legendFormat": "Reclaimed"
    },
    {
     "expr": "increase(replay_accdb_reverted_total{instance=\"$instance\"}[$__range])",
     "legendFormat": "Reverted"
    },
    {
     "expr": "(\n  sum(increase(replay_accdb_created_total{instance=\"$instance\"}[$__range])) +\n  sum(increase(replay_accdb_created_total{instance=\"$instance\"}[$__range]))\n) -\n(\n  sum(increase(replay_accdb_garbage_collected_total{instance=\"$instance\"}[$__range])) +\n  sum(increase(replay_accdb_reclaimed_total{instance=\"$instance\"}[$__range])) +\n  sum(increase(replay_accdb_reverted_total{instance=\"$instance\"}[$__range]))\n)",
     "legendFormat": "Net Change"
    }
   ]
  },
  {
   "title": "Accounts Revert Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 7, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(replay_accdb_reverted_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Delta"
    }
   ]
  },
  {
   "title": "Accounts Reclaim Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(replay_accdb_reclaimed_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Delta"
    }
   ]
  },
  {
   "title": "Net Account Growth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 12 },
   "targets": [
    {
     "expr": "(\n  sum(increase(replay_accdb_created_total{instance=\"$instance\"}[$__rate_interval])) +\n  sum(increase(replay_accdb_created_total{instance=\"$instance\"}[$__rate_interval]))\n)\n-\n(\n  sum(increase(replay_accdb_garbage_collected_total{instance=\"$instance\"}[$__rate_interval])) +\n  sum(increase(replay_accdb_reverted_total{instance=\"$instance\"}[$__rate_interval])) +\n  sum(increase(replay_accdb_reclaimed_total{instance=\"$instance\"}[$__rate_interval]))\n)",
     "legendFormat": "Delta"
    }
   ]
  }
 ]
}