{
 "title": "Firedancer Bundles",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(bundle_bundle_rx_total,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "status-history",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "min_over_time((bundle_state{instance=\"$instance\"} == bool 2)[$__rate_interval:])",
     "legendFormat": "."
    }
   ]
  },
  {
   "title": "Bundles Per Second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(bundle_pkt_rx_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Transactions"
    },
    {
     "expr": "rate(bundle_bundle_rx_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Bundles"
    }
   ]
  },
  {
   "title": "Bundle Edge RTT",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "bundle_rtt_smoothed_nanos{instance=\"$instance\"}",
     "legendFormat": "Smoothed"
    },
    {
     "expr": "bundle_rtt_sample_nanos{instance=\"$instance\"}",
     "legendFormat": "Latest Sample"
    }
   ]
  }
 ]
}