{
 "title": "Firedancer Gossip",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(gossip_message_tx_total,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CRDS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CRDS insertions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "expr": "rate(gossip_crds_rx_count{instance=\"$instance\",gossip_crds_outcome=~\"upserted.*\"}[$__rate_interval])",
     "legendFormat": "{{gossip_crds_outcome}}"
    }
   ]
  },
  {
   "title": "CRDS deletions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "expr": "rate(gossip_crds_evicted_count{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Evicted"
    },
    {
     "expr": "rate(gossip_crds_expired_count{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Expired"
    },
    {
     "expr": "rate(gossip_crds_purged_evicted_count{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Purged Evicted"
    },
    {
     "expr": "rate(gossip_crds_purged_expired_count{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Purged Expired"
    }
   ]
  },
  {
   "title": "CRDS set size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gossip_crds_occupied{instance=\"$instance\"}",
     "legendFormat": "{{crds_value}}"
    }
   ]
  },
  {
   "title": "CRDS set size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(gossip_crds_occupied{instance=\"$instance\"}) by (crds_value))",
     "legendFormat": "{{crds_value}}"
    }
   ]
  },
  {
   "title": "Purged set size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gossip_crds_purged_occupied{instance=\"$instance\"})",
     "legendFormat": "{{crds_value}}"
    }
   ]
  },
  { "title": "Egress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Packet Egress",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(gossip_message_tx_count{instance=\"$instance\"}[$__rate_interval])) by (gossip_message)",
     "legendFormat": "{{gossip_message}}"
    }
   ]
  },
  {
   "title": "Packet Egress",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "8 * sum(rate(gossip_message_tx_bytes_total{instance=\"$instance\"}[$__rate_interval])) by (gossip_message)",
     "legendFormat": "{{gossip_message}}"
    }
   ]
  },
  {
   "title": "CRDS Pull Response Egress",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "expr": "sum(rate(gossip_crds_tx_pull_response_count{instance=\"$instance\"}[$__rate_interval])) by (crds_value)",
     "legendFormat": "{{crds_value}}"
    }
   ]
  },
  {
   "title": "CRDS Pull Response Egress",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "8 * sum(rate(gossip_crds_tx_pull_response_bytes_total{instance=\"$instance\"}[$__rate_interval])) by (crds_value)",
     "legendFormat": "{{crds_value}}"
    }
   ]
  },
  {
   "title": "CRDS Push Egress",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "expr": "sum(rate(gossip_crds_tx_push_count{instance=\"$instance\"}[$__rate_interval])) by (crds_value)",
     "legendFormat": "{{crds_value}}"
    }
   ]
  },
  {
   "title": "CRDS Push Egress",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "8 * sum(rate(gossip_crds_tx_push_bytes_total{instance=\"$instance\"}[$__rate_interval])) by (crds_value)",
     "legendFormat": "{{crds_value}}"
    }
   ]
  },
  { "title": "Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Packet Ingress",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(gossvf_message_rx_count{instance=\"$instance\"}[$__rate_interval])) by (gossvf_message_outcome) != 0",
     "legendFormat": "{{gossvf_message_outcome}}"
    }
   ]
  },
  {
   "title": "Packet Ingress",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "8 * sum(rate(gossvf_message_rx_bytes_total{instance=\"$instance\"}[$__rate_interval])) by (gossvf_message_outcome)",
     "legendFormat": "{{gossvf_message_outcome}}"
    }
   ]
  },
  {
   "title": "CRDS Ingress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "expr": "rate(gossip_crds_rx_count{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{gossip_crds_outcome}}"
    }
   ]
  }
 ]
}