{
 "title": "Firedancer QUIC",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(quic_conn_state,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "TPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "QUIC packets",
   "type": "timeseries",
   "description": "UDP packet rate handled by all QUIC tiles.\nPositive numbers indicate incoming packets (RX), negative numbers indicate outgoing packets (TX)",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(quic_pkt_rx_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "RX pps"
    },
    {
     "expr": "-sum(rate(quic_pkt_tx_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "TX pps"
    }
   ]
  },
  {
   "title": "QUIC bandwidth",
   "type": "timeseries",
   "description": "UDP line rate received and sent by all QUIC tiles. \nThis includes network headers (Ethernet, IPv4, UDP header, QUIC header, QUIC payload)",
   "gridPos": { "h": 10, "w": 9, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(quic_pkt_rx_bytes_total{instance=~\"$instance\"}[$__rate_interval]))*8",
     "legendFormat": "RX bitrate"
    },
    {
     "expr": "-sum(rate(quic_pkt_tx_bytes_total{instance=~\"$instance\"}[$__rate_interval]))*8",
     "legendFormat": "TX bitrate"
    }
   ]
  },
  {
   "title": "QUIC Txns Recvd",
   "type": "stat",
   "description": "Transaction count received in the current interval",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(quic_txn_rx_total{instance=~\"$instance\",tpu_recv_type=\"quic_fast\"}[$__range])) + sum(increase(quic_txn_rx_total{instance=~\"$instance\",tpu_recv_type=\"quic_frag\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QUIC Txns Failed",
   "type": "stat",
   "description": "Transaction count failed in QUIC stream handling code (abandoned, too large, overrun). Not counting small streams",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(quic_txn_abandoned_total{instance=~\"$instance\"}[$__range])) + sum(increase(quic_txn_oversize_total{instance=~\"$instance\"}[$__range])) + sum(increase(quic_txn_overrun_total{instance=~\"$instance\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stream Complete Rate",
   "type": "gauge",
   "description": "Ratio of streams received vs streams started",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(quic_txn_rx_total{instance=~\"$instance\",tpu_recv_type=\"quic_fast\"}[$__range])) + sum(increase(quic_txn_rx_total{instance=~\"$instance\",tpu_recv_type=\"quic_frag\"}[$__range]))) / (sum(increase(quic_txn_rx_total{instance=~\"$instance\",tpu_recv_type=\"quic_fast\"}[$__range])) + sum(increase(quic_txn_reassembly_started_total{instance=~\"$instance\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QUIC conns",
   "type": "timeseries",
   "description": "Sum of QUIC connection counts across all QUIC tiles",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "conns" } },
   "targets": [
    {
     "expr": "sum(quic_conn_state{instance=~\"$instance\",quic_conn_state=\"active\"})",
     "legendFormat": "Conns"
    }
   ]
  },
  {
   "title": "QUIC Conns Created",
   "type": "stat",
   "description": "Cumulative number of connections created in the current Grafana time range",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(quic_conn_created_total{instance=~\"$instance\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received Frames",
   "type": "timeseries",
   "description": "Number of frames per second for each QUIC frame type.\n\n'stream' frames carry Solana transactions. \n'ping' frames do keep-alive to avoid connection timeouts.\nEverything else is metadata.\n\nUse shift+left click to hide certain frame types.\n",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum by (quic_frame_type) (rate(quic_frame_rx_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{quic_frame_type}}"
    }
   ]
  },
  {
   "title": "QUIC Conns Aborted",
   "type": "stat",
   "description": "Cumulative number of connections killed by QUIC tiles, in the current Grafana time range.\n\nTypical reasons include:\n- TLS handshake failure\n- Internal allocation failure\n\nDoes not include timeouts",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(quic_conn_aborted_total{instance=~\"$instance\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QUIC Conns Gracef. Closed",
   "type": "stat",
   "description": "Cumulative number of connections gracefully closed. AKA normal client disconnects.",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(quic_conn_closed_total{instance=~\"$instance\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TPU Transaction Rate",
   "type": "timeseries",
   "description": "QUIC stream events per second\n(Each QUIC stream corresponds to one Solana transaction)\n\n- QUIC Unfragmented Rcvd: Peer sent an entire transaction in one QUIC frame\n- QUIC Fragmented Rcvd: Peer sent a transaction fragment\n- QUIC Abandoned: Txn dropped because the connection closed\n- QUIC Overrun: Reassembly operation dropped because lack of buffer space\n- QUIC Txn Undersz: Stream fully received but it's smaller than the smallest valid transaction. Some clients abuse undersize streams as a ping mechanism but this is harmless to Firedancer\n- QUIC Txn Oversz: Stream byte received that is beyond the transaction MTU\n- UDP Rcvd: Peer sent an entire transaction in one UDP packet\n- UDP Undersz: UDP packet too small\n- UDP Oversz: UDP packet too large",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (tpu_recv_type) (rate(quic_txn_rx_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "QUIC Rcvd {{tpu_recv_type}}"
    },
    {
     "expr": "sum(rate(quic_txn_abandoned_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "QUIC Abandoned"
    },
    {
     "expr": "sum(rate(quic_txn_overrun_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "QUIC Overrun"
    },
    {
     "expr": "sum(rate(quic_txn_undersize_total{instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "QUIC Txn Undersz"
    },
    {
     "expr": "sum(rate(quic_txn_oversize_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "QUIC Txn Oversz"
    },
    {
     "expr": "sum(rate(quic_pkt_undersize_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "UDP Undersz"
    },
    {
     "expr": "sum(rate(quic_pkt_oversize_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "UDP Oversz"
    }
   ]
  },
  {
   "title": "QUIC Handshake Pool",
   "type": "timeseries",
   "description": "Handshake events per second\n\n- Alloc Fail: Handshake object pool is full (indicates connection attempt spam) \n- Created: Handshake object allocated",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(quic_handshake_error_alloc_fail_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Alloc Fail"
    },
    {
     "expr": "sum(rate(quic_handshake_created_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Created"
    }
   ]
  },
  {
   "title": "QUIC Conn Rejects",
   "type": "timeseries",
   "description": "Connections rejected per second\n\n- Alloc Fail: Aborted because the connection table was full\n- Handshake Alloc Fail: Aborted because handshake state could not be allocated\n- Retry Fail: Client send an expired or invalid retry token (QUIC Retry are comparable to TCP SYN cookies)",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(quic_conn_error_no_slots_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Alloc Fail"
    },
    {
     "expr": "sum(rate(quic_handshake_error_alloc_fail_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Handshake Alloc Fail"
    },
    {
     "expr": "sum(rate(quic_conn_error_retry_failed_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Retry Fail"
    }
   ]
  },
  {
   "title": "QUIC Conn Churn",
   "type": "timeseries",
   "description": "Connection events per second.\n\n- Created: Connection objects created (tracked before the handshake succeeds)\n- Aborted: Connections killed by the validator\n- Graceful Closed: Connections gracefully closed by the peer\n- Timeout: Connections garbage-collected by the validator because no data was seen for the duration of the idle timeout",
   "gridPos": { "h": 7, "w": 7, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(quic_conn_created_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Created"
    },
    {
     "expr": "sum(rate(quic_conn_aborted_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Aborted"
    },
    {
     "expr": "sum(rate(quic_conn_closed_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Graceful Closed"
    },
    {
     "expr": "sum(rate(quic_conn_timed_out_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Timeout"
    }
   ]
  },
  {
   "title": "QUIC RX Drops",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 26 },
   "targets": [
    {
     "expr": "sum(increase(link_frag_polling_overrun_total{instance=~\"$instance\",kind=\"quic\"}[$__rate_interval]))",
     "legendFormat": "QUIC drops"
    },
    {
     "expr": "sum(increase(tile_context_switch_involuntary_total{instance=~\"$instance\",kind=\"quic\"}[$__rate_interval]))",
     "legendFormat": "Involuntary Context Switches"
    },
    {
     "expr": "sum(increase(quic_frame_parse_failed_total{instance=~\"$instance\",kind=\"quic\"}[$__rate_interval]))",
     "legendFormat": "QUIC Parse Fail"
    },
    {
     "expr": "sum by (quic_encryption_level) (increase(quic_pkt_crypto_failed_total{instance=~\"$instance\",kind=\"quic\"}[$__rate_interval])) != 0",
     "legendFormat": "QUIC Crypto Fail ({{quic_encryption_level}})"
    },
    {
     "expr": "sum by (quic_encryption_level) (increase(quic_pkt_no_key_total{instance=~\"$instance\",kind=\"quic\"}[$__rate_interval])) != 0",
     "legendFormat": "QUIC No Key ({{quic_encryption_level}})"
    },
    {
     "expr": "increase(quic_pkt_no_conn_total{instance=~\"$instance\",kind=\"quic\"}[$__rate_interval]) != 0",
     "legendFormat": "QUIC No Conn"
    }
   ]
  },
  {
   "title": "QUIC RX Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (increase(quic_rx_duration_seconds_bucket{instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (increase(quic_rx_duration_seconds_bucket{instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (increase(quic_rx_duration_seconds_bucket{instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (increase(quic_rx_duration_seconds_bucket{instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum by (le) (increase(quic_rx_duration_seconds_bucket{instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "QUIC ACK TX",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (quic_ack_tx_total) (rate(quic_ack_tx_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{quic_ack_tx}}"
    }
   ]
  },
  {
   "title": "Frame Dups",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 33 },
   "targets": [
    {
     "expr": "sum(increase(quic_frag_duplicate_total{instance=~\"$instance\",kind=\"quic\"}[$__rate_interval]))",
     "legendFormat": "Duplicate Frags"
    }
   ]
  },
  {
   "title": "QUIC Frame Retransmits",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(quic_pkt_tx_retransmitted_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}