{
 "title": "Firedancer VM",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(execrp_vm_regime_duration_nanos_total,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Transaction Execution Timings",
   "type": "timeseries",
   "description": "100% equals one CPU core worth of compute",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n    sum(rate(execrp_txn_regime_duration_nanos_total{instance=\"$instance\"}[$__rate_interval])) by (txn_regime) /\n    on () group_left\n    sum(rate(tile_regime_duration_nanos_total{instance=\"$instance\",kind=\"exec\",kind_id=\"0\"}[$__rate_interval]))\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VM Execution Timings",
   "type": "timeseries",
   "description": "100% equals one CPU core worth of compute",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(execrp_vm_regime_duration_nanos_total{instance=\"$instance\"}[$__rate_interval])) by (vm_regime) /\non () group_left\nsum(rate(tile_regime_duration_nanos_total{instance=\"$instance\",kind=\"exec\",kind_id=\"0\"}[$__rate_interval])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction Execution Timings (Normalized)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(execrp_txn_regime_duration_nanos_total{instance=\"$instance\"}[$__rate_interval])) by (txn_regime) /\non () group_left\nsum(rate(execrp_txn_regime_duration_nanos_total{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VM Execution Timings (Normalized)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(execrp_vm_regime_duration_nanos_total{instance=\"$instance\"}[$__rate_interval])) by (vm_regime) /\non () group_left\nsum(rate(execrp_vm_regime_duration_nanos_total{instance=\"$instance\"}[$__rate_interval])) ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}