$(call add-objs,fd_filerd_tile,fd_discof)
$(call add-objs,fd_unzstd_tile,fd_discof)
$(call add-objs,fd_snapin_tile,fd_discof)
$(call add-objs,fd_actalc_tile,fd_discof)
$(call add-objs,fd_actidx_tile,fd_discof)
$(call add-objs,fd_unzstd_tile,fd_discof)
$(call add-objs,fd_httpdl_tile,fd_discof)
$(call add-objs,stream/fd_stream_writer,fd_discof)
$(call add-objs,stream/fd_event_map,fd_discof)
$(call add-objs,stream/fd_stream_ctx,fd_discof)
$(call make-unit-test,test_snapin_tile,test_snapin_tile,fd_discof fd_util)
