$(call add-objs,fd_filerd_tile,fd_discof)
$(call add-objs,fd_snapin_tile,fd_discof)
$(call add-objs,fd_actalc_tile,fd_discof)
$(call add-objs,fd_stream_writer,fd_discof)
$(call add-objs,fd_unzstd_tile,fd_discof)