package(default_visibility = ["//visibility:public"])

constraint_setting(name = "collection")

constraint_value(
    name = "llvm",
    constraint_setting = ":collection",
)

constraint_value(
    name = "gcc",
    constraint_setting = ":collection",
)
