#include "fd_vinyl_data.h"

/* This table autogenerated
     io_block    512
     ctl_sz      8
     key_sz      32
     info_sz     16
     ftr_sz      16
     obj_cnt_min 2
     obj_cnt_max 64
     obj_cnt_lvl 12
     val_min     0
     val_max     10486192 */

fd_vinyl_data_szc_cfg_t const fd_vinyl_data_szc_cfg[ FD_VINYL_DATA_SZC_CNT ] = {
  /*   0 */ {        440U, (ushort)64, (ushort) 58 }, // obj_footprint       1024 sb_footprint      66048
  /*   1 */ {        952U, (ushort)42, (ushort) 58 }, // obj_footprint       1536 sb_footprint      66048
  /*   2 */ {       1464U, (ushort)32, (ushort) 58 }, // obj_footprint       2048 sb_footprint      66048
  /*   3 */ {       1976U, (ushort)25, (ushort) 58 }, // obj_footprint       2560 sb_footprint      66048
  /*   4 */ {       2488U, (ushort)21, (ushort) 58 }, // obj_footprint       3072 sb_footprint      66048
  /*   5 */ {       3000U, (ushort)18, (ushort) 58 }, // obj_footprint       3584 sb_footprint      66048
  /*   6 */ {       3512U, (ushort)16, (ushort) 58 }, // obj_footprint       4096 sb_footprint      66048
  /*   7 */ {       4024U, (ushort)14, (ushort) 58 }, // obj_footprint       4608 sb_footprint      66048
  /*   8 */ {       4536U, (ushort)12, (ushort) 58 }, // obj_footprint       5120 sb_footprint      66048
  /*   9 */ {       5048U, (ushort)11, (ushort) 58 }, // obj_footprint       5632 sb_footprint      66048
  /*  10 */ {       5560U, (ushort)10, (ushort) 58 }, // obj_footprint       6144 sb_footprint      66048
  /*  11 */ {       6584U, (ushort) 9, (ushort) 58 }, // obj_footprint       7168 sb_footprint      66048
  /*  12 */ {       7608U, (ushort) 8, (ushort) 58 }, // obj_footprint       8192 sb_footprint      66048
  /*  13 */ {       8632U, (ushort) 7, (ushort) 58 }, // obj_footprint       9216 sb_footprint      66048
  /*  14 */ {      10168U, (ushort) 6, (ushort) 58 }, // obj_footprint      10752 sb_footprint      66048
  /*  15 */ {      11704U, (ushort)64, (ushort)117 }, // obj_footprint      12288 sb_footprint     793088
  /*  16 */ {      12216U, (ushort) 5, (ushort) 58 }, // obj_footprint      12800 sb_footprint      66048
  /*  17 */ {      12728U, (ushort)59, (ushort)117 }, // obj_footprint      13312 sb_footprint     793088
  /*  18 */ {      13240U, (ushort)57, (ushort)117 }, // obj_footprint      13824 sb_footprint     793088
  /*  19 */ {      13752U, (ushort)55, (ushort)117 }, // obj_footprint      14336 sb_footprint     793088
  /*  20 */ {      14264U, (ushort)53, (ushort)117 }, // obj_footprint      14848 sb_footprint     793088
  /*  21 */ {      14776U, (ushort)51, (ushort)117 }, // obj_footprint      15360 sb_footprint     793088
  /*  22 */ {      15288U, (ushort)49, (ushort)117 }, // obj_footprint      15872 sb_footprint     793088
  /*  23 */ {      15800U, (ushort) 4, (ushort) 58 }, // obj_footprint      16384 sb_footprint      66048
  /*  24 */ {      16312U, (ushort)46, (ushort)117 }, // obj_footprint      16896 sb_footprint     793088
  /*  25 */ {      16824U, (ushort)45, (ushort)117 }, // obj_footprint      17408 sb_footprint     793088
  /*  26 */ {      17336U, (ushort)44, (ushort)117 }, // obj_footprint      17920 sb_footprint     793088
  /*  27 */ {      17848U, (ushort)43, (ushort)117 }, // obj_footprint      18432 sb_footprint     793088
  /*  28 */ {      18360U, (ushort)41, (ushort)117 }, // obj_footprint      18944 sb_footprint     793088
  /*  29 */ {      18872U, (ushort)40, (ushort)117 }, // obj_footprint      19456 sb_footprint     793088
  /*  30 */ {      19384U, (ushort)39, (ushort)117 }, // obj_footprint      19968 sb_footprint     793088
  /*  31 */ {      19896U, (ushort)38, (ushort)117 }, // obj_footprint      20480 sb_footprint     793088
  /*  32 */ {      20408U, (ushort)37, (ushort)117 }, // obj_footprint      20992 sb_footprint     793088
  /*  33 */ {      20920U, (ushort) 3, (ushort) 58 }, // obj_footprint      21504 sb_footprint      66048
  /*  34 */ {      21432U, (ushort)36, (ushort)117 }, // obj_footprint      22016 sb_footprint     793088
  /*  35 */ {      21944U, (ushort)35, (ushort)117 }, // obj_footprint      22528 sb_footprint     793088
  /*  36 */ {      22456U, (ushort)34, (ushort)117 }, // obj_footprint      23040 sb_footprint     793088
  /*  37 */ {      22968U, (ushort)33, (ushort)117 }, // obj_footprint      23552 sb_footprint     793088
  /*  38 */ {      23992U, (ushort)32, (ushort)117 }, // obj_footprint      24576 sb_footprint     793088
  /*  39 */ {      24504U, (ushort)31, (ushort)117 }, // obj_footprint      25088 sb_footprint     793088
  /*  40 */ {      25528U, (ushort)30, (ushort)117 }, // obj_footprint      26112 sb_footprint     793088
  /*  41 */ {      26552U, (ushort)29, (ushort)117 }, // obj_footprint      27136 sb_footprint     793088
  /*  42 */ {      27576U, (ushort)28, (ushort)117 }, // obj_footprint      28160 sb_footprint     793088
  /*  43 */ {      28600U, (ushort)27, (ushort)117 }, // obj_footprint      29184 sb_footprint     793088
  /*  44 */ {      29624U, (ushort)26, (ushort)117 }, // obj_footprint      30208 sb_footprint     793088
  /*  45 */ {      30648U, (ushort)25, (ushort)117 }, // obj_footprint      31232 sb_footprint     793088
  /*  46 */ {      32184U, (ushort) 2, (ushort) 58 }, // obj_footprint      32768 sb_footprint      66048
  /*  47 */ {      33720U, (ushort)23, (ushort)117 }, // obj_footprint      34304 sb_footprint     793088
  /*  48 */ {      35256U, (ushort)22, (ushort)117 }, // obj_footprint      35840 sb_footprint     793088
  /*  49 */ {      36792U, (ushort)21, (ushort)117 }, // obj_footprint      37376 sb_footprint     793088
  /*  50 */ {      38840U, (ushort)20, (ushort)117 }, // obj_footprint      39424 sb_footprint     793088
  /*  51 */ {      40888U, (ushort)19, (ushort)117 }, // obj_footprint      41472 sb_footprint     793088
  /*  52 */ {      43448U, (ushort)18, (ushort)117 }, // obj_footprint      44032 sb_footprint     793088
  /*  53 */ {      46008U, (ushort)17, (ushort)117 }, // obj_footprint      46592 sb_footprint     793088
  /*  54 */ {      48568U, (ushort)16, (ushort)117 }, // obj_footprint      49152 sb_footprint     793088
  /*  55 */ {      52152U, (ushort)15, (ushort)117 }, // obj_footprint      52736 sb_footprint     793088
  /*  56 */ {      55736U, (ushort)14, (ushort)117 }, // obj_footprint      56320 sb_footprint     793088
  /*  57 */ {      60344U, (ushort)13, (ushort)117 }, // obj_footprint      60928 sb_footprint     793088
  /*  58 */ {      65464U, (ushort)12, (ushort)117 }, // obj_footprint      66048 sb_footprint     793088
  /*  59 */ {      71096U, (ushort)11, (ushort)117 }, // obj_footprint      71680 sb_footprint     793088
  /*  60 */ {      78264U, (ushort)10, (ushort)117 }, // obj_footprint      78848 sb_footprint     793088
  /*  61 */ {      87480U, (ushort) 9, (ushort)117 }, // obj_footprint      88064 sb_footprint     793088
  /*  62 */ {      98232U, (ushort) 8, (ushort)117 }, // obj_footprint      98816 sb_footprint     793088
  /*  63 */ {     112568U, (ushort) 7, (ushort)117 }, // obj_footprint     113152 sb_footprint     793088
  /*  64 */ {     131512U, (ushort) 6, (ushort)117 }, // obj_footprint     132096 sb_footprint     793088
  /*  65 */ {     147896U, (ushort)64, (ushort)176 }, // obj_footprint     148480 sb_footprint    9517568
  /*  66 */ {     150456U, (ushort)63, (ushort)176 }, // obj_footprint     151040 sb_footprint    9517568
  /*  67 */ {     152504U, (ushort)62, (ushort)176 }, // obj_footprint     153088 sb_footprint    9517568
  /*  68 */ {     155064U, (ushort)61, (ushort)176 }, // obj_footprint     155648 sb_footprint    9517568
  /*  69 */ {     157624U, (ushort) 5, (ushort)117 }, // obj_footprint     158208 sb_footprint     793088
  /*  70 */ {     160696U, (ushort)59, (ushort)176 }, // obj_footprint     161280 sb_footprint    9517568
  /*  71 */ {     163256U, (ushort)58, (ushort)176 }, // obj_footprint     163840 sb_footprint    9517568
  /*  72 */ {     166328U, (ushort)57, (ushort)176 }, // obj_footprint     166912 sb_footprint    9517568
  /*  73 */ {     168888U, (ushort)56, (ushort)176 }, // obj_footprint     169472 sb_footprint    9517568
  /*  74 */ {     171960U, (ushort)55, (ushort)176 }, // obj_footprint     172544 sb_footprint    9517568
  /*  75 */ {     175544U, (ushort)54, (ushort)176 }, // obj_footprint     176128 sb_footprint    9517568
  /*  76 */ {     178616U, (ushort)53, (ushort)176 }, // obj_footprint     179200 sb_footprint    9517568
  /*  77 */ {     182200U, (ushort)52, (ushort)176 }, // obj_footprint     182784 sb_footprint    9517568
  /*  78 */ {     185784U, (ushort)51, (ushort)176 }, // obj_footprint     186368 sb_footprint    9517568
  /*  79 */ {     189368U, (ushort)50, (ushort)176 }, // obj_footprint     189952 sb_footprint    9517568
  /*  80 */ {     193464U, (ushort)49, (ushort)176 }, // obj_footprint     194048 sb_footprint    9517568
  /*  81 */ {     197560U, (ushort) 4, (ushort)117 }, // obj_footprint     198144 sb_footprint     793088
  /*  82 */ {     201656U, (ushort)47, (ushort)176 }, // obj_footprint     202240 sb_footprint    9517568
  /*  83 */ {     206264U, (ushort)46, (ushort)176 }, // obj_footprint     206848 sb_footprint    9517568
  /*  84 */ {     210872U, (ushort)45, (ushort)176 }, // obj_footprint     211456 sb_footprint    9517568
  /*  85 */ {     215480U, (ushort)44, (ushort)176 }, // obj_footprint     216064 sb_footprint    9517568
  /*  86 */ {     220600U, (ushort)43, (ushort)176 }, // obj_footprint     221184 sb_footprint    9517568
  /*  87 */ {     225720U, (ushort)42, (ushort)176 }, // obj_footprint     226304 sb_footprint    9517568
  /*  88 */ {     231352U, (ushort)41, (ushort)176 }, // obj_footprint     231936 sb_footprint    9517568
  /*  89 */ {     236984U, (ushort)40, (ushort)176 }, // obj_footprint     237568 sb_footprint    9517568
  /*  90 */ {     243128U, (ushort)39, (ushort)176 }, // obj_footprint     243712 sb_footprint    9517568
  /*  91 */ {     249784U, (ushort)38, (ushort)176 }, // obj_footprint     250368 sb_footprint    9517568
  /*  92 */ {     256440U, (ushort)37, (ushort)176 }, // obj_footprint     257024 sb_footprint    9517568
  /*  93 */ {     263608U, (ushort) 3, (ushort)117 }, // obj_footprint     264192 sb_footprint     793088
  /*  94 */ {     271288U, (ushort)35, (ushort)176 }, // obj_footprint     271872 sb_footprint    9517568
  /*  95 */ {     278968U, (ushort)34, (ushort)176 }, // obj_footprint     279552 sb_footprint    9517568
  /*  96 */ {     287672U, (ushort)33, (ushort)176 }, // obj_footprint     288256 sb_footprint    9517568
  /*  97 */ {     296376U, (ushort)32, (ushort)176 }, // obj_footprint     296960 sb_footprint    9517568
  /*  98 */ {     306104U, (ushort)31, (ushort)176 }, // obj_footprint     306688 sb_footprint    9517568
  /*  99 */ {     316344U, (ushort)30, (ushort)176 }, // obj_footprint     316928 sb_footprint    9517568
  /* 100 */ {     327096U, (ushort)29, (ushort)176 }, // obj_footprint     327680 sb_footprint    9517568
  /* 101 */ {     338872U, (ushort)28, (ushort)176 }, // obj_footprint     339456 sb_footprint    9517568
  /* 102 */ {     351672U, (ushort)27, (ushort)176 }, // obj_footprint     352256 sb_footprint    9517568
  /* 103 */ {     364984U, (ushort)26, (ushort)176 }, // obj_footprint     365568 sb_footprint    9517568
  /* 104 */ {     379832U, (ushort)25, (ushort)176 }, // obj_footprint     380416 sb_footprint    9517568
  /* 105 */ {     395704U, (ushort) 2, (ushort)117 }, // obj_footprint     396288 sb_footprint     793088
  /* 106 */ {     413112U, (ushort)23, (ushort)176 }, // obj_footprint     413696 sb_footprint    9517568
  /* 107 */ {     431544U, (ushort)22, (ushort)176 }, // obj_footprint     432128 sb_footprint    9517568
  /* 108 */ {     452536U, (ushort)21, (ushort)176 }, // obj_footprint     453120 sb_footprint    9517568
  /* 109 */ {     475064U, (ushort)20, (ushort)176 }, // obj_footprint     475648 sb_footprint    9517568
  /* 110 */ {     500152U, (ushort)19, (ushort)176 }, // obj_footprint     500736 sb_footprint    9517568
  /* 111 */ {     527800U, (ushort)18, (ushort)176 }, // obj_footprint     528384 sb_footprint    9517568
  /* 112 */ {     559032U, (ushort)17, (ushort)176 }, // obj_footprint     559616 sb_footprint    9517568
  /* 113 */ {     593848U, (ushort)16, (ushort)176 }, // obj_footprint     594432 sb_footprint    9517568
  /* 114 */ {     633784U, (ushort)15, (ushort)176 }, // obj_footprint     634368 sb_footprint    9517568
  /* 115 */ {     678840U, (ushort)14, (ushort)176 }, // obj_footprint     679424 sb_footprint    9517568
  /* 116 */ {     731064U, (ushort)13, (ushort)176 }, // obj_footprint     731648 sb_footprint    9517568
  /* 117 */ {     792504U, (ushort)12, (ushort)176 }, // obj_footprint     793088 sb_footprint    9517568
  /* 118 */ {     864184U, (ushort)11, (ushort)176 }, // obj_footprint     864768 sb_footprint    9517568
  /* 119 */ {     950712U, (ushort)10, (ushort)176 }, // obj_footprint     951296 sb_footprint    9517568
  /* 120 */ {    1056696U, (ushort) 9, (ushort)176 }, // obj_footprint    1057280 sb_footprint    9517568
  /* 121 */ {    1188792U, (ushort) 8, (ushort)176 }, // obj_footprint    1189376 sb_footprint    9517568
  /* 122 */ {    1358776U, (ushort) 7, (ushort)176 }, // obj_footprint    1359360 sb_footprint    9517568
  /* 123 */ {    1585592U, (ushort) 6, (ushort)176 }, // obj_footprint    1586176 sb_footprint    9517568
  /* 124 */ {    1783736U, (ushort)64, (ushort)188 }, // obj_footprint    1784320 sb_footprint  114211328
  /* 125 */ {    1811896U, (ushort)63, (ushort)188 }, // obj_footprint    1812480 sb_footprint  114211328
  /* 126 */ {    1841080U, (ushort)62, (ushort)188 }, // obj_footprint    1841664 sb_footprint  114211328
  /* 127 */ {    1871288U, (ushort)61, (ushort)188 }, // obj_footprint    1871872 sb_footprint  114211328
  /* 128 */ {    1902520U, (ushort) 5, (ushort)176 }, // obj_footprint    1903104 sb_footprint    9517568
  /* 129 */ {    1934776U, (ushort)59, (ushort)188 }, // obj_footprint    1935360 sb_footprint  114211328
  /* 130 */ {    1968568U, (ushort)58, (ushort)188 }, // obj_footprint    1969152 sb_footprint  114211328
  /* 131 */ {    2002872U, (ushort)57, (ushort)188 }, // obj_footprint    2003456 sb_footprint  114211328
  /* 132 */ {    2038712U, (ushort)56, (ushort)188 }, // obj_footprint    2039296 sb_footprint  114211328
  /* 133 */ {    2075576U, (ushort)55, (ushort)188 }, // obj_footprint    2076160 sb_footprint  114211328
  /* 134 */ {    2113976U, (ushort)54, (ushort)188 }, // obj_footprint    2114560 sb_footprint  114211328
  /* 135 */ {    2153912U, (ushort)53, (ushort)188 }, // obj_footprint    2154496 sb_footprint  114211328
  /* 136 */ {    2195384U, (ushort)52, (ushort)188 }, // obj_footprint    2195968 sb_footprint  114211328
  /* 137 */ {    2238392U, (ushort)51, (ushort)188 }, // obj_footprint    2238976 sb_footprint  114211328
  /* 138 */ {    2283448U, (ushort)50, (ushort)188 }, // obj_footprint    2284032 sb_footprint  114211328
  /* 139 */ {    2330040U, (ushort)49, (ushort)188 }, // obj_footprint    2330624 sb_footprint  114211328
  /* 140 */ {    2378680U, (ushort) 4, (ushort)176 }, // obj_footprint    2379264 sb_footprint    9517568
  /* 141 */ {    2429368U, (ushort)47, (ushort)188 }, // obj_footprint    2429952 sb_footprint  114211328
  /* 142 */ {    2482104U, (ushort)46, (ushort)188 }, // obj_footprint    2482688 sb_footprint  114211328
  /* 143 */ {    2537400U, (ushort)45, (ushort)188 }, // obj_footprint    2537984 sb_footprint  114211328
  /* 144 */ {    2594744U, (ushort)44, (ushort)188 }, // obj_footprint    2595328 sb_footprint  114211328
  /* 145 */ {    2655160U, (ushort)43, (ushort)188 }, // obj_footprint    2655744 sb_footprint  114211328
  /* 146 */ {    2718648U, (ushort)42, (ushort)188 }, // obj_footprint    2719232 sb_footprint  114211328
  /* 147 */ {    2784696U, (ushort)41, (ushort)188 }, // obj_footprint    2785280 sb_footprint  114211328
  /* 148 */ {    2854328U, (ushort)40, (ushort)188 }, // obj_footprint    2854912 sb_footprint  114211328
  /* 149 */ {    2927544U, (ushort)39, (ushort)188 }, // obj_footprint    2928128 sb_footprint  114211328
  /* 150 */ {    3004856U, (ushort)38, (ushort)188 }, // obj_footprint    3005440 sb_footprint  114211328
  /* 151 */ {    3085752U, (ushort)37, (ushort)188 }, // obj_footprint    3086336 sb_footprint  114211328
  /* 152 */ {    3171768U, (ushort) 3, (ushort)176 }, // obj_footprint    3172352 sb_footprint    9517568
  /* 153 */ {    3262392U, (ushort)35, (ushort)188 }, // obj_footprint    3262976 sb_footprint  114211328
  /* 154 */ {    3358136U, (ushort)34, (ushort)188 }, // obj_footprint    3358720 sb_footprint  114211328
  /* 155 */ {    3460024U, (ushort)33, (ushort)188 }, // obj_footprint    3460608 sb_footprint  114211328
  /* 156 */ {    3568056U, (ushort)32, (ushort)188 }, // obj_footprint    3568640 sb_footprint  114211328
  /* 157 */ {    3683256U, (ushort)31, (ushort)188 }, // obj_footprint    3683840 sb_footprint  114211328
  /* 158 */ {    3806136U, (ushort)30, (ushort)188 }, // obj_footprint    3806720 sb_footprint  114211328
  /* 159 */ {    3937720U, (ushort)29, (ushort)188 }, // obj_footprint    3938304 sb_footprint  114211328
  /* 160 */ {    4078008U, (ushort)28, (ushort)188 }, // obj_footprint    4078592 sb_footprint  114211328
  /* 161 */ {    4229048U, (ushort)27, (ushort)188 }, // obj_footprint    4229632 sb_footprint  114211328
  /* 162 */ {    4391864U, (ushort)26, (ushort)188 }, // obj_footprint    4392448 sb_footprint  114211328
  /* 163 */ {    4567480U, (ushort)25, (ushort)188 }, // obj_footprint    4568064 sb_footprint  114211328
  /* 164 */ {    4757944U, (ushort) 2, (ushort)176 }, // obj_footprint    4758528 sb_footprint    9517568
  /* 165 */ {    4964792U, (ushort)23, (ushort)188 }, // obj_footprint    4965376 sb_footprint  114211328
  /* 166 */ {    5190584U, (ushort)22, (ushort)188 }, // obj_footprint    5191168 sb_footprint  114211328
  /* 167 */ {    5437880U, (ushort)21, (ushort)188 }, // obj_footprint    5438464 sb_footprint  114211328
  /* 168 */ {    5709752U, (ushort)20, (ushort)188 }, // obj_footprint    5710336 sb_footprint  114211328
  /* 169 */ {    6010296U, (ushort)19, (ushort)188 }, // obj_footprint    6010880 sb_footprint  114211328
  /* 170 */ {    6344120U, (ushort)18, (ushort)188 }, // obj_footprint    6344704 sb_footprint  114211328
  /* 171 */ {    6717368U, (ushort)17, (ushort)188 }, // obj_footprint    6717952 sb_footprint  114211328
  /* 172 */ {    7137208U, (ushort)16, (ushort)188 }, // obj_footprint    7137792 sb_footprint  114211328
  /* 173 */ {    7613368U, (ushort)15, (ushort)188 }, // obj_footprint    7613952 sb_footprint  114211328
  /* 174 */ {    8157112U, (ushort)14, (ushort)188 }, // obj_footprint    8157696 sb_footprint  114211328
  /* 175 */ {    8784824U, (ushort)13, (ushort)188 }, // obj_footprint    8785408 sb_footprint  114211328
  /* 176 */ {    9516984U, (ushort)12, (ushort)188 }, // obj_footprint    9517568 sb_footprint  114211328
  /* 177 */ {   10381752U, (ushort)11, (ushort)188 }, // obj_footprint   10382336 sb_footprint  114211328
  /* 178 */ {   10486200U, (ushort)10, (ushort)188 }, // obj_footprint   10486784 sb_footprint  114211328 <- FD_VINYL_VAL_MAX
  /* 179 */ {   11420088U, (ushort)10, (ushort)188 }, // obj_footprint   11420672 sb_footprint  114211328
  /* 180 */ {   12689336U, (ushort) 9, (ushort)188 }, // obj_footprint   12689920 sb_footprint  114211328
  /* 181 */ {   14275512U, (ushort) 8, (ushort)188 }, // obj_footprint   14276096 sb_footprint  114211328
  /* 182 */ {   16314808U, (ushort) 7, (ushort)188 }, // obj_footprint   16315392 sb_footprint  114211328
  /* 183 */ {   19034552U, (ushort) 6, (ushort)188 }, // obj_footprint   19035136 sb_footprint  114211328
  /* 184 */ {   22841272U, (ushort) 5, (ushort)188 }, // obj_footprint   22841856 sb_footprint  114211328
  /* 185 */ {   28552120U, (ushort) 4, (ushort)188 }, // obj_footprint   28552704 sb_footprint  114211328
  /* 186 */ {   38069688U, (ushort) 3, (ushort)188 }, // obj_footprint   38070272 sb_footprint  114211328
  /* 187 */ {   57104824U, (ushort) 2, (ushort)188 }, // obj_footprint   57105408 sb_footprint  114211328
};
