close all
clear all

io_block = 128;

ctl_sz   =   8;
key_sz   =  32;
info_sz  =  16;
ftr_sz   =  16;

pair_framing = ctl_sz + key_sz + info_sz + ftr_sz;

val_min  = 0;
val_max  = 10*2^20 + io_block - pair_framing;

obj_cnt_min       = 4;
obj_cnt_max       = 16;
obj_footprint_min = io_block*ceil( ( io_block + pair_framing + val_min ) / io_block );
obj_footprint_max = io_block*ceil( ( io_block + pair_framing + val_max ) / io_block );
root_sb_footprint = io_block + obj_cnt_min*obj_footprint_max;
gamma             = obj_cnt_max / (obj_cnt_max-1);

szc_cnt = 0;

sb_footprint         = root_sb_footprint;
obj_footprint_target = obj_footprint_max;
while obj_footprint_target>=obj_footprint_min,

  ofp = io_block*round( obj_footprint_target / io_block );
  while 1,
    ocnt = floor( (sb_footprint - io_block) / ofp );
    if ocnt<=obj_cnt_max, break; endif

    % More than obj_cnt_max objects fit into the current superblock.
    % Pick a new superblock size to be the smallest object footprint in
    % an already computed sizeclass sufficient to hold a superblock with
    % obj_cnt_min ofp sized objects.  If there are none (i.e. the needed
    % superblock size is larger than the object footprints for all the
    % already computed sizeclasses), use the already computed sizeclass
    % with the largest object footprint (the resulting superblock for
    % ofp sized objects will have fewer than obj_cnt_min objects but
    % that's unavoidable).

    idx = find( obj_footprint >= io_block + ofp*obj_cnt_min, 1, 'last' );
    if isempty(idx), idx = 1; endif
    sb_footprint = obj_footprint( idx );
  endwhile

  if ~((2<=ocnt) & (ocnt<=64)), error( 'hmmm' ); endif

  szc_cnt++;
  obj_footprint   (szc_cnt) = io_block*floor( (sb_footprint - io_block) / (io_block*ocnt) );
  obj_val_max     (szc_cnt) = obj_footprint(szc_cnt) - io_block - pair_framing;
  obj_cnt         (szc_cnt) = ocnt;
  parent_footprint(szc_cnt) = sb_footprint;

  obj_footprint_target /= gamma;
endwhile

% Sort by object footprint, discarding redundant and/or runt sizeclasses

[~,idx] = unique( obj_footprint, 'first' );
obj_footprint    = obj_footprint   (idx);
obj_val_max      = obj_val_max     (idx);
obj_cnt          = obj_cnt         (idx);
parent_footprint = parent_footprint(idx);

keep = diff(obj_footprint) > 0.25*(gamma-1)*obj_footprint(1:(end-1));
keep(end+1) = 1;

obj_footprint    = obj_footprint   (keep);
obj_val_max      = obj_val_max     (keep);
obj_cnt          = obj_cnt         (keep);
parent_footprint = parent_footprint(keep);

szc_cnt = length(obj_footprint);

% Determine sizeclass nesting

for szc=1:szc_cnt,
  pfp  = io_block + obj_cnt(szc)*obj_footprint(szc);
  pszc = find( pfp<=obj_footprint, 1, 'first' );
  if isempty(pszc),
    parent_footprint(szc) = root_sb_footprint;
    parent_szc(szc)       = szc_cnt+1;
  else
    parent_footprint(szc) = obj_footprint(pszc);
    parent_szc(szc)       = pszc;
  endif
endfor

szc_thresh = szc_cnt;

printf( '#define FD_VINYL_VAL_MAX (%uUL) /* autogenerated */\n', val_max );
printf( '\n' );
printf( '#define FD_VINYL_DATA_VOL_FOOTPRINT (%uUL) /* autogenerated */\n', max( parent_footprint ) );
printf( '#define FD_VINYL_DATA_SZC_CNT       (%uUL) /* autogenerated */\n', szc_cnt );
printf( '#define FD_VINYL_DATA_SZC_ITER_MAX  (%uUL) /* autogenerated */\n', ceil( log2( szc_cnt ) ) );
printf( '\n' );
printf( '######################################################################################################\n' );
printf( '#include \"fd_vinyl_data.h\"\n' );
printf( '\n' );
printf( '/* This table autogenerated\n' );
printf( '     io_block          %i\n',      io_block          );
printf( '     ctl_sz            %i\n',      ctl_sz            );
printf( '     key_sz            %i\n',      key_sz            );
printf( '     info_sz           %i\n',      info_sz           );
printf( '     ftr_sz            %i\n',      ftr_sz            );
printf( '     obj_cnt_min       %i\n',      obj_cnt_min       );
printf( '     obj_cnt_max       %i\n',      obj_cnt_max       );
printf( '     val_min           %i\n',      val_min           );
printf( '     val_max           %i\n',      val_max           );
printf( '     root_sb_footprint %i\n',      root_sb_footprint );
printf( '     gamma             %.6e */\n', gamma             );
printf( '\n' );
printf( 'fd_vinyl_data_szc_cfg_t const fd_vinyl_data_szc_cfg[ FD_VINYL_DATA_SZC_CNT ] = {\n' );
for szc=1:szc_cnt,
  ocnt = obj_cnt         (szc);
  ofp  = obj_footprint   (szc);
  pszc = parent_szc      (szc);
  pfp  = parent_footprint(szc);
  printf( '  /* %3u */ { %10uU, (ushort)%2u, (ushort)%3u }, // obj_footprint %10u parent_footprint %10u slack %5u\n', ...
          szc-1, obj_val_max(szc), ocnt, pszc-1, ofp, pfp, pfp - (io_block+ocnt*ofp) );
endfor
printf( '};\n' );

obj_val_min = shift(obj_val_max,1) + 1; obj_val_min(1) = 1;
obj_val_avg = 0.5*(obj_val_min+obj_val_max);

denom   = io_block./obj_cnt + obj_footprint; % Ideally would have SB nesting accounted too (but its in the noise)
eff_min = obj_val_min./denom;
eff_avg = obj_val_avg./denom;
eff_max = obj_val_max./denom;

szc_idx = 0:(szc_cnt-1);

subplot(2,1,1);
semilogy( szc_idx, [ obj_val_min; obj_val_avg; obj_val_max ] );
axis tight;
grid;
xlabel( 'sizeclass index' );
ylabel( 'object size (min/avg/max)' );

subplot(2,1,2);
semilogy( szc_idx, 1 - [eff_min; eff_avg; eff_max] );
axis tight;
grid;
xlabel( 'sizeclass index' );
ylabel( 'footprint overhead frac (min/avg/max)' );

