ifdef FD_HAS_INT128
$(call add-objs,fd_zktpp_batched_grouped_ciphertext_validity,fd_flamenco)
$(call add-objs,fd_zktpp_batched_range_proof_u128,fd_flamenco)
$(call add-objs,fd_zktpp_batched_range_proof_u256,fd_flamenco)
$(call add-objs,fd_zktpp_batched_range_proof_u64,fd_flamenco)
$(call add-objs,fd_zktpp_ciphertext_ciphertext_equality,fd_flamenco)
$(call add-objs,fd_zktpp_ciphertext_commitment_equality,fd_flamenco)
$(call add-objs,fd_zktpp_fee_sigma,fd_flamenco)
$(call add-objs,fd_zktpp_grouped_ciphertext_validity,fd_flamenco)
$(call add-objs,fd_zktpp_pubkey_validity,fd_flamenco)
$(call add-objs,fd_zktpp_range_proof_u64,fd_flamenco)
$(call add-objs,fd_zktpp_transfer_with_fee,fd_flamenco)
$(call add-objs,fd_zktpp_transfer_without_fee,fd_flamenco)
$(call add-objs,fd_zktpp_withdraw,fd_flamenco)
$(call add-objs,fd_zktpp_zero_balance,fd_flamenco)
endif
