from .types import *
from pathlib import Path


def generate_string_table(traces: Traces) -> StringTable:
    st = StringTable()
    for category in traces.categories.values():
        st.push(category.name)
        for event in category.events.values():
            st.push(event.name)
            for arg in event.args:
                st.push(arg.name)
    return st


def write_string_table(st: StringTable, out_path: Path):
    with open(out_path, "w") as f:
        print(
            "/* THIS FILE IS GENERATED BY gen_tracing.py. DO NOT HAND EDIT. */", file=f
        )
        print("", file=f)
        print("#include <stddef.h>", file=f)
        print("", file=f)
        print("char const * fd_trace_strtab[] = {", file=f)
        for s in st.idx2str:
            print(f'  "{s}",', file=f)
        print("  NULL", file=f)
        print("};", file=f)
