FIREDANCER_VERSION_MAJOR := 1
FIREDANCER_VERSION_MINOR := 0
FIREDANCER_VERSION_PATCH := 0
FIREDANCER_CI_COMMIT := $(shell git rev-parse HEAD)

export FIREDANCER_VERSION_MAJOR
export FIREDANCER_VERSION_MINOR
export FIREDANCER_VERSION_PATCH
export FIREDANCER_CI_COMMIT
