VERSION_MAJOR := 0
VERSION_MINOR := 1
VERSION_PATCH := 1
FIREDANCER_CI_COMMIT := $(shell git rev-parse HEAD)

export FIREDANCER_VERSION_MAJOR
export FIREDANCER_VERSION_MINOR
export FIREDANCER_VERSION_PATCH
export FIREDANCER_CI_COMMIT
