name: hugepages
description: 'Setup 1 GiB gigantic pages'
inputs:
  count_huge:
    description: 'Number of huge pages'
    required: true
    default: '128'
  count_gigantic:
    description: 'Number of gigantic pages'
    required: true
    default: '64'
outputs: {}
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        set -x
        sudo src/util/shmem/fd_shmem_cfg reset || true
        sudo src/util/shmem/fd_shmem_cfg init 0775 $USER "" || true
        [ $(cat /sys/devices/system/node/node0/hugepages/hugepages-1048576kB/nr_hugepages) -lt '${{ inputs.count_gigantic }}' ] && \
          sudo src/util/shmem/fd_shmem_cfg alloc '${{ inputs.count_gigantic }}' gigantic 0
        [ $(cat /sys/devices/system/node/node0/hugepages/hugepages-2048kB/nr_hugepages) -lt '${{ inputs.count_huge }}' ] && \
          sudo src/util/shmem/fd_shmem_cfg alloc '${{ inputs.count_huge }}' huge 0
        sudo chown -R $USER:$USER /mnt/.fd
