name: hugepages
description: 'Setup 2 MiB huge pages'
inputs:
  count:
    description: 'Number of huge pages'
    required: true
    default: '65536'
outputs: {}
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        sudo src/util/shmem/fd_shmem_cfg init 0666 $USER "" || true
        sudo src/util/shmem/fd_shmem_cfg alloc '${{ inputs.count }}' huge 0
        sudo chown -R $USER:$USER /mnt/.fd
