#!/bin/sh

if [ $# -lt 2 ]; then
  echo ""
  echo "        Usage: $0 [APP] [RESERVED_CPUS] [other args]"
  echo ""
  exit 1
fi

APP=$1
RESERVED_CPUS=$2
shift 2

CONF=tmp/$APP.cfg
. $CONF || exit $?

$BUILD/bin/fd_frank_run.bin $RUN_ARGS --tile-cpus f,$RESERVED_CPUS $*

