#!/bin/bash

if [ $# -lt 1 ]; then
  echo ""
  echo "        Usage: $0 [APP] [other args]"
  echo ""
  exit 1
fi

APP=$1
RESERVED_CPUS=$2
shift 1

CONF=tmp/$APP.cfg
. $CONF || exit $?

$BUILD/bin/fd_frank_grp_launcher.bin $RUN_ARGS $*

