telemetry = false
[hugetlbfs]
    gigantic_page_threshold_mib = 64
[net]
    provider = "xdp"
[tiles]
    [tiles.rpc]
        enabled = true
    [tiles.gui]
        enabled = false
[runtime]
    max_live_slots = 256
    max_fork_width = 8
[accounts]
    max_accounts = 4000000
    cache_size_gib = 3
[snapshots]
    max_full_snapshots_to_keep = 1
    max_incremental_snapshots_to_keep = 1
