name: Publish to ClusterFuzz
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Build fuzz artifacts, check default corpus
  make-fuzz:
    runs-on:
      group: github-v1
    env:
      MACHINE: linux_clang_x86_64_fuzz_asan
      EXTRA_CPPFLAGS: -isystem /root/include
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/deps
      - run: sudo apt update && sudo apt install -y zip

      - uses: firedancer-io/fuzzbot-builder@main
        name: Build fuzz tests
        with:
          command: make -j -Otarget fuzz-test

      - name: List Artifacts
        run: |
          ls build/linux/clang/x86_64_fuzz_asan/fuzz-test

      - uses: firedancer-io/clusterfuzz-action@main
        if: ${{ github.ref == 'refs/heads/main' }}
        name: Upload fuzz targets to ClusterFuzz
        with:
          bucket-name: firedancer-builds.isol-clusterfuzz.appspot.com
          artifact-dir: build/linux/clang/x86_64_fuzz_asan/fuzz-test
          object-prefix: main/libfuzzer-asan/firedancer
          project-id: isol-clusterfuzz
          service-account-credentials: ${{ secrets.FUZZ_SERVICE_ACCT_JSON_BUNDLE }}

      - name: Run fuzz tests
        run: make -k -j -Otarget run-fuzz-test
