#include "fd_stem.h"

/* fd_stem provides services to multiplex multiple streams of input
   fragments and present them to a mix of reliable and unreliable
   consumers as though they were generated by multiple different
   multi-stream producers.  The code can be included to generate
   a definition of stem_run which can be called as a tile main run
   loop.

   The template supports various callback functions which can be
   defined like #define STEM_CALLBACK_BEFORE_FRAG before_frag to
   tune the behavior of the stem_run loop.  The callbacks are:

     SHOULD_SHUTDOWN
   It is called at the beginning of each iteration of the stem run loop,
   and if it returns non-zero, the stem will exit the run loop and
   return from the stem_run function.  This is useful for shutting down
   the tile.

     DURING_HOUSEKEEPING
   Is called during the housekeeping routine, which happens infrequently
   on a schedule determined by the stem (based on the lazy parameter,
   see fd_tempo.h for more information).  It is appropriate to do
   slightly expensive things here that wouldn't be OK to do in the main
   loop, like updating sequence numbers that are shared with other tiles
   (e.g. synchronization information), or sending batched information
   somewhere.  The ctx is a user-provided context object from when the
   stem was initialized.

     METRICS_WRITE
   By convention, tiles may wish to accumulate high traffic metrics
   locally so they don't cause a lot of cache coherency traffic, and
   then periodically publish them to external observers.  This callback
   is here to support that use case.  It occurs infrequently during the
   housekeeping loop, and is called inside a compiler fence to ensure
   the writes do not get reordered, which may be important for observers
   or monitoring tools.  The ctx is a user-provided context object from
   when the stem tile was initialized.

     BEFORE_CREDIT
   Is called every iteration of the stem run loop, whether there is a
   new frag ready to receive or not.  This callback is also still
   invoked even if the stem is backpressured and cannot read any new
   fragments while waiting for downstream consumers to catch up.  This
   callback is useful for things that need to occur even if no new frags
   are being handled.  For example, servicing network connections could
   happen here.  The ctx is a user-provided context object from when the
   stem tile was initialized.  The stem is the stem which is invoking
   this callback. The stem should only be used for calling
   fd_stem_publish to publish a fragment to downstream consumers.

   The charge_busy argument is 0 by default, and should be set to 1 if
   the before_credit function is doing work that should be accounted for
   as part of the tiles busy indicator.

     CHECK_CREDIT
   Is called every iteration of the stem run loop. This callback
   overrides the default backpressure check (can the run loop produce
   STEM_BURST frags on any out link without exceeding flow control
   credits).

      AFTER_CREDIT
   Is called every iteration of the stem run loop, whether there is a
   new frag ready to receive or not, except in cases where the stem is
   backpressured by a downstream consumer and would not be able to
   publish.  The callback might be used for publishing new fragments to
   downstream consumers in the main loop which are not in response to an
   incoming fragment.  For example, code that collects incoming
   fragments over a period of 1 second and joins them together before
   publishing a large block fragment downstream, would publish the block
   here. The ctx is a user-provided context object from when the stem
   tile was initialized.  The stem is the stem which is invoking this
   callback. The stem should only be used for calling fd_stem_publish to
   publish a fragment to downstream consumers.

   The opt_poll_in argument determines if the stem should proceed with
   checking for new fragments to consumer, or should `continue` the main
   stem loop to do credit checking again.  This could be used if the
   after_credit function publishes, and the flow control needs to be
   checked again.  By default, opt_poll_in is true and the stem will
   poll for fragments right away without rerunning the loop or checking
   for credits.

   The charge_busy argument is 0 by default, and should be set to 1 if
   the after_credit function is doing work that should be accounted for
   as part of the tiles busy indicator.

      BEFORE_FRAG
   Is called immediately whenever a new fragment has been detected that
   was published by an upstream producer.  The signature and sequence
   number (sig and seq) provided as arguments are read atomically from
   shared memory, so must both match each other from the published
   fragment (aka. they will not be torn or partially overwritten).
   in_idx is an index in [0, num_ins) indicating which producer
   published the fragment. No fragment data has been read yet here, nor
   has other metadata, for example the size or timestamps of the
   fragment.  Mainly this callback is useful for deciding whether to
   filter the fragment based on its signature.  If the return value is
   non-zero, the frag will be skipped completely, no fragment data will
   be read, and the in will be advanced so that we now wait for the next
   fragment.  If the return value is -1, then the frag is returned back
   to the message queue and will be reprocessed.  The ctx is a
   user-provided context object from when the stem tile was initialized.

      DURING_FRAG
   Is called after the stem has received a new frag from an in, but
   before the stem has checked that it was overrun.  This callback is
   not invoked if the stem is backpressured, as it would not try and
   read a frag from an in in the first place (instead, leaving it on the
   in mcache to backpressure the upstream producer).  in_idx will be the
   index of the in that the frag was received from, skipping any unpolled
   links. If the producer of the frags is respecting flow control, it is
   safe to read frag data in any of the callbacks, but it is suggested to
   copy or read frag data within this callback, as if the producer does
   not respect flow control, the frag may be torn or corrupt due to an
   overrun by the reader.  If the frag being read from has been
   overwritten while this callback is running, the frag will be ignored
   and the stem will not call the after_frag function. Instead it will
   recover from the overrun and continue with new frags.  This function
   cannot fail.  The ctx is a user-provided context object from when the
   stem tile was initialized. seq, sig, chunk, and sz are the respective
   fields from the mcache fragment that was received.  If the producer
   is not respecting flow control, these may be corrupt or torn and
   should not be trusted, except for seq which is read atomically.

      RETURNABLE_FRAG
   Is called after the stem has received a new frag from an in, and
   assumes that the stem cannot be overrun.  This special callback can
   instruct the stem not to advance the input sequence number, and
   instead return the fragment to the stem to be processed again.  This
   is useful for processing partial data from fragments without copying
   it.  This callback is unsafe in general contexts, since it assumes
   that the frag will not be overwritten while the callback is running,
   and that the frag data is valid throughout the function call.  It
   should only be used when the stem is guaranteed to not be overrun.
   This callback is not invoked if the stem is backpressured, as it
   would not try and read a frag from an in in the first place (instead,
   leaving it on the in mcache to backpressure the upstream producer).
   in_idx will be the index of the in that the frag was received from.
   seq, sig, chunk, and sz are the respective fields from the mcache
   fragment that was received.  tsorig and tspub are the timestamps of
   the fragment that was received, and are read atomically from shared
   memory, so must both match each other from the published fragment
   (aka. they will not be torn or partially overwritten).  The ctx is a
   user-provided context object from when the stem tile was initialized.
   The callback should return 1 if the fragment was not fully processed
   and should be returned to the stem for further processing, or 0 if
   the fragment was fully processed and the consumer link should be
   advanced.

      AFTER_FRAG
   Is called immediately after the DURING_FRAG, along with an additional
   check that the reader was not overrun while handling the frag.  If
   the reader was overrun, the frag is abandoned and this function is
   not called.  This callback is not invoked if the stem is
   backpressured, as it would not read a frag in the first place.
   in_idx will be the index of the in that the frag was received from,
   skipping any unpolled links. You should not read the frag data directly
   here, as it might still get overrun, instead it should be copied out of
   the frag during the read callback if needed later. This function cannot
   fail. The ctx is a user-provided context object from when the stem tile
   was initialized.  stem should only be used for calling fd_stem_publish
   to publish a fragment to downstream consumers.  seq is the sequence
   number of the fragment that was read from the input mcache. sig, sz,
   tsorig, and tspub are the respective fields from the mcache fragment
   that was received.  If the producer is not respecting flow control,
   these may be corrupt or torn and should not be trusted.

      AFTER_POLL_OVERRUN
   Is called when an overrun is detected while polling for new frags.
   This callback is not called when an overrun is detected in
   during_frag. */

#include "../../util/log/fd_log.h"
#include "../topo/fd_topo.h"
#include "../metrics/fd_metrics.h"
#include "../../tango/fd_tango.h"

#ifndef STEM_NAME
#define STEM_NAME stem
#endif
#define STEM_(n) FD_EXPAND_THEN_CONCAT3(STEM_NAME,_,n)

#ifndef STEM_BURST
#error "STEM_BURST must be defined"
#endif

#ifndef STEM_CALLBACK_CONTEXT_TYPE
#error "STEM_CALLBACK_CONTEXT_TYPE must be defined"
#endif

#ifndef STEM_CALLBACK_CONTEXT_ALIGN
#error "STEM_CALLBACK_CONTEXT_ALIGN must be defined"
#endif

#ifndef STEM_LAZY
#define STEM_LAZY (0L)
#endif

#define STEM_SHUTDOWN_SEQ (ULONG_MAX-1UL)

static inline void
STEM_(in_update)( fd_stem_tile_in_t * in ) {
  __atomic_store_n( in->fseq, in->seq, __ATOMIC_RELEASE );

  volatile ulong * metrics = fd_metrics_link_in( fd_metrics_base_tl, in->idx );

  uint *  accum = in->accum;
  ulong a0 = (ulong)accum[0]; ulong a1 = (ulong)accum[1]; ulong a2 = (ulong)accum[2];
  ulong a3 = (ulong)accum[3]; ulong a4 = (ulong)accum[4]; ulong a5 = (ulong)accum[5];
  FD_COMPILER_MFENCE();
  metrics[0] += a0;           metrics[1] += a1;           metrics[2] += a2;
  metrics[3] += a3;           metrics[4] += a4;           metrics[5] += a5;
  FD_COMPILER_MFENCE();
  accum[0] = 0U;              accum[1] = 0U;              accum[2] = 0U;
  accum[3] = 0U;              accum[4] = 0U;              accum[5] = 0U;
}

FD_FN_PURE static inline ulong
STEM_(scratch_align)( void ) {
  return FD_STEM_SCRATCH_ALIGN;
}

FD_FN_PURE static inline ulong
STEM_(scratch_footprint)( ulong in_cnt,
                          ulong out_cnt,
                          ulong cons_cnt ) {
  ulong l = FD_LAYOUT_INIT;
  l = FD_LAYOUT_APPEND( l, alignof(fd_stem_tile_in_t), in_cnt*sizeof(fd_stem_tile_in_t)     );  /* in */
  l = FD_LAYOUT_APPEND( l, alignof(ulong),             out_cnt*sizeof(ulong)                ); /* cr_avail */
  l = FD_LAYOUT_APPEND( l, alignof(ulong),             out_cnt*sizeof(ulong)                ); /* out_depth */
  l = FD_LAYOUT_APPEND( l, alignof(ulong),             out_cnt*sizeof(ulong)                ); /* out_seq */
  l = FD_LAYOUT_APPEND( l, alignof(int),               out_cnt*sizeof(int)                  ); /* out_reliable */
  l = FD_LAYOUT_APPEND( l, alignof(ulong const *),     cons_cnt*sizeof(ulong const *)       ); /* cons_fseq */
  l = FD_LAYOUT_APPEND( l, alignof(ulong *),           cons_cnt*sizeof(ulong *)             ); /* cons_slow */
  l = FD_LAYOUT_APPEND( l, alignof(ulong),             cons_cnt*sizeof(ulong)               ); /* cons_out */
  l = FD_LAYOUT_APPEND( l, alignof(ulong),             cons_cnt*sizeof(ulong)               ); /* cons_seq */
  const ulong event_cnt = in_cnt + 1UL + cons_cnt;
  l = FD_LAYOUT_APPEND( l, alignof(ushort),            event_cnt*sizeof(ushort)             ); /* event_map */
  return FD_LAYOUT_FINI( l, STEM_(scratch_align)() );
}

#include "fd_stem_run1.c"

FD_FN_UNUSED static void
STEM_(run)( fd_topo_t *      topo,
            fd_topo_tile_t * tile ) {
  const fd_frag_meta_t * in_mcache[ FD_TOPO_MAX_LINKS ];
  ulong * in_fseq[ FD_TOPO_MAX_TILE_IN_LINKS ];

  ulong polled_in_cnt = 0UL;
  for( ulong i=0UL; i<tile->in_cnt; i++ ) {
    if( FD_UNLIKELY( !tile->in_link_poll[ i ] ) ) continue;

    in_mcache[ polled_in_cnt ] = topo->links[ tile->in_link_id[ i ] ].mcache;
    FD_TEST( in_mcache[ polled_in_cnt ] );
    in_fseq[ polled_in_cnt ]   = tile->in_link_fseq[ i ];
    FD_TEST( in_fseq[ polled_in_cnt ] );
    polled_in_cnt += 1;
  }

  fd_frag_meta_t * out_mcache[ FD_TOPO_MAX_LINKS ];
  for( ulong i=0UL; i<tile->out_cnt; i++ ) {
    out_mcache[ i ] = topo->links[ tile->out_link_id[ i ] ].mcache;
    FD_TEST( out_mcache[ i ] );
  }

  ulong   reliable_cons_cnt = 0UL;
  ulong   cons_out[ FD_TOPO_MAX_LINKS ];
  ulong * cons_fseq[ FD_TOPO_MAX_LINKS ];
  volatile ulong * cons_slow[ FD_TOPO_MAX_LINKS ];
  for( ulong i=0UL; i<topo->tile_cnt; i++ ) {
    fd_topo_tile_t * consumer_tile = &topo->tiles[ i ];
    ulong polled_in_idx = 0UL;
    for( ulong j=0UL; j<consumer_tile->in_cnt; j++ ) {
      int is_polled = consumer_tile->in_link_poll[ j ];
      for( ulong k=0UL; k<tile->out_cnt; k++ ) {
        if( FD_UNLIKELY( consumer_tile->in_link_id[ j ]==tile->out_link_id[ k ] && consumer_tile->in_link_reliable[ j ] ) ) {
          cons_out[ reliable_cons_cnt ] = k;
          cons_fseq[ reliable_cons_cnt ] = consumer_tile->in_link_fseq[ j ];
          FD_TEST( cons_fseq[ reliable_cons_cnt ] );
          cons_slow[ reliable_cons_cnt ] = fd_metrics_link_in( consumer_tile->metrics, polled_in_idx ) + FD_METRICS_COUNTER_LINK_SLOW_OFF;
          reliable_cons_cnt++;
          /* Need to test this, since each link may connect to many outs,
             you could construct a topology which has more than this
             consumers of links. */
          FD_TEST( reliable_cons_cnt<FD_TOPO_MAX_LINKS );
        }
      }
      if( FD_LIKELY( is_polled ) ) polled_in_idx++;
    }
  }

  /* The stem rng is only used internally for shuffling event/input
     polling ordering and for setting the housekeeping timer.  It is
     never exposed to tile callbacks.  As a result, no cryptographic
     quality is needed.  fd_tickcount() provides per-run entropy,
     tile->id guarantees per-tile uniqueness, and fd_ulong_hash (a
     Murmur3 finalizer) gives near-perfect avalanche so even a 1-bit
     input difference flips ~50% of output bits.  fd_rng_secure is not
     used here because STEM_(run) executes after the seccomp sandbox
     is applied. */
  fd_rng_t rng[1];
  FD_TEST( fd_rng_join( fd_rng_new( rng, (uint)fd_ulong_hash( (ulong)fd_tickcount() + tile->id ), 0UL ) ) );

  STEM_CALLBACK_CONTEXT_TYPE * ctx = (STEM_CALLBACK_CONTEXT_TYPE*)fd_ulong_align_up( (ulong)fd_topo_obj_laddr( topo, tile->tile_obj_id ), STEM_CALLBACK_CONTEXT_ALIGN );

  uchar __attribute__((aligned(FD_STEM_SCRATCH_ALIGN))) stem_scratch[ STEM_(scratch_footprint)( polled_in_cnt, tile->out_cnt, reliable_cons_cnt ) ];

  STEM_(run1)( polled_in_cnt,
               in_mcache,
               in_fseq,
               tile->out_cnt,
               out_mcache,
               reliable_cons_cnt,
               cons_out,
               cons_fseq,
               cons_slow,
               STEM_BURST,
               STEM_LAZY,
               rng,
               stem_scratch,
               ctx );

#ifdef STEM_CALLBACK_METRICS_WRITE
  /* Write final metrics state before shutting down */
  FD_COMPILER_MFENCE();
  STEM_CALLBACK_METRICS_WRITE( ctx );
  FD_COMPILER_MFENCE();
#endif

  if( FD_LIKELY( tile->allow_shutdown ) ) {
    for( ulong i=0UL; i<tile->in_cnt; i++ ) {
      if( FD_UNLIKELY( !tile->in_link_poll[ i ] || !tile->in_link_reliable[ i ] ) ) continue;

      /* Return infinite credits on any reliable consumer links so that
         producers now no longer expect us to consume. */
      ulong fseq_id = tile->in_link_fseq_obj_id[ i ];
      ulong * fseq = fd_fseq_join( fd_topo_obj_laddr( topo, fseq_id ) );
      FD_TEST( fseq );
      __atomic_store_n( fseq, STEM_SHUTDOWN_SEQ, __ATOMIC_RELEASE );
    }
  }
}

#undef STEM_NAME
#undef STEM_
#undef STEM_BURST
#undef STEM_CALLBACK_CONTEXT_TYPE
#undef STEM_CALLBACK_CONTEXT_ALIGN
#undef STEM_LAZY
#undef STEM_STICKY_POLL_MAX
#undef STEM_CALLBACK_SHOULD_SHUTDOWN
#undef STEM_CALLBACK_DURING_HOUSEKEEPING
#undef STEM_CALLBACK_METRICS_WRITE
#undef STEM_CALLBACK_BEFORE_CREDIT
#undef STEM_CALLBACK_AFTER_CREDIT
#undef STEM_CALLBACK_BEFORE_FRAG
#undef STEM_CALLBACK_DURING_FRAG
#undef STEM_CALLBACK_RETURNABLE_FRAG
#undef STEM_CALLBACK_AFTER_FRAG
#undef STEM_CALLBACK_AFTER_POLL_OVERRUN
