---
version: "3.8"
services:
  firedancer:
    image: firedancer_rocky8:latest
# increment this if building a new version
    image: firedancer_rocky8:0.1
    volumes:
      - /data/firedancer:/home/firedancer/.firedancer:Z
      - /data/firedancer/log:/opt/firedancer/log:Z
    ipc: host
    network_mode: "host"
    privileged: true
    command: fddev --config /opt/firedancer/config/default.toml dev
    build:
      context: ../ubi8
      args:
# Defaults provided both here and in Dockerfile. This will override values in Dockerfile.
        BUILDER_BASE_IMAGE: rockylinux@sha256:72afc2e1a20c9ddf56a81c51148ebcbe927c0a879849efe813bee77d69df1dd8 #8.5.20220308
        RELEASE_BASE_IMAGE: rockylinux@sha256:72afc2e1a20c9ddf56a81c51148ebcbe927c0a879849efe813bee77d69df1dd8 #8.5.20220308
        MACHINE: linux_gcc_x86_64
        RUST_VERSION: 1.73.0
# We can define a release, tag, or branch rather than main. Defaults to main if undefined.
        GITTAG:
