a1: a1.c Makefile
	gcc -g -o a1 -I /home/jsiegel/repos/firedancer/src -I /home/jsiegel/repos/rocksdb/include a1.c -lstdc++ /home/jsiegel/repos/rocksdb/librocksdb.a -L /usr/local/lib -lzstd -lpthread -lbz2 -lz -ldl  -lm
