$(call make-bin,test_funk,test_funk,fd_funk fd_util)
$(call make-bin,test_funk_2,test_funk_2,fd_funk fd_util)
$(call make-bin,test_funk_3,test_funk_3,fd_funk fd_util)
$(call make-bin,test_funk_4,test_funk_4,fd_funk fd_util)
$(call make-bin,test_funk_5,test_funk_5,fd_funk fd_util)
$(call make-bin,test_map_giant,test_map_giant,fd_funk fd_util)
