FROM docker.io/library/debian@sha256:9cb6717929d25e307a23a997a72d99e54de728b289b835ddbd34fd164c305e83 as bullseye

ENV RUST_VERSION=1.73.0

RUN INSTALL_PKGS="git autoconf gettext automake autopoint flex bison build-essential gcc-multilib protobuf-compiler zstd clang" && \
    apt update && \
    apt install -y $INSTALL_PKGS

RUN curl "https://sh.rustup.rs" -sfo /tmp/rustup.sh && \
    sh /tmp/rustup.sh -y --default-toolchain ${RUST_VERSION} && \
    . $HOME/.cargo/env && \
    rustup show
