/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "shredstream.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(shredstream_Heartbeat, shredstream_Heartbeat, AUTO)


PB_BIND(shredstream_HeartbeatResponse, shredstream_HeartbeatResponse, AUTO)



