/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_SHREDSTREAM_SHREDSTREAM_PB_H_INCLUDED
#define PB_SHREDSTREAM_SHREDSTREAM_PB_H_INCLUDED
#include "../../../ballet/nanopb/pb_firedancer.h"
#include "shared.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _shredstream_Heartbeat {
    /* don't trust IP:PORT from tcp header since it can be tampered over the wire
 `socket.ip` must match incoming packet's ip. this prevents spamming an unwitting destination */
    bool has_socket;
    shared_Socket socket;
    /* regions for shredstream proxy to receive shreds from
 list of valid regions: https://jito-labs.gitbook.io/mev/systems/connecting/mainnet */
    pb_size_t regions_count;
    char regions[8][16];
} shredstream_Heartbeat;

typedef struct _shredstream_HeartbeatResponse {
    /* client must respond within `ttl_ms` to keep stream alive */
    uint32_t ttl_ms;
} shredstream_HeartbeatResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define shredstream_Heartbeat_init_default       {false, shared_Socket_init_default, 0, {"", "", "", "", "", "", "", ""}}
#define shredstream_HeartbeatResponse_init_default {0}
#define shredstream_Heartbeat_init_zero          {false, shared_Socket_init_zero, 0, {"", "", "", "", "", "", "", ""}}
#define shredstream_HeartbeatResponse_init_zero  {0}

/* Field tags (for use in manual encoding/decoding) */
#define shredstream_Heartbeat_socket_tag         1
#define shredstream_Heartbeat_regions_tag        2
#define shredstream_HeartbeatResponse_ttl_ms_tag 1

/* Struct field encoding specification for nanopb */
#define shredstream_Heartbeat_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  socket,            1) \
X(a, STATIC,   REPEATED, STRING,   regions,           2)
#define shredstream_Heartbeat_CALLBACK NULL
#define shredstream_Heartbeat_DEFAULT NULL
#define shredstream_Heartbeat_socket_MSGTYPE shared_Socket

#define shredstream_HeartbeatResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ttl_ms,            1)
#define shredstream_HeartbeatResponse_CALLBACK NULL
#define shredstream_HeartbeatResponse_DEFAULT NULL

extern const pb_msgdesc_t shredstream_Heartbeat_msg;
extern const pb_msgdesc_t shredstream_HeartbeatResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define shredstream_Heartbeat_fields &shredstream_Heartbeat_msg
#define shredstream_HeartbeatResponse_fields &shredstream_HeartbeatResponse_msg

/* Maximum encoded size of messages (where known) */
#if defined(shared_Socket_size)
#define SHREDSTREAM_SHREDSTREAM_PB_H_MAX_SIZE    shredstream_Heartbeat_size
#define shredstream_Heartbeat_size               (142 + shared_Socket_size)
#endif
#define shredstream_HeartbeatResponse_size       6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
