/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "fd_trace.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(fd_soltrace_TxnTrace, fd_soltrace_TxnTrace, AUTO)


PB_BIND(fd_soltrace_TxnInput, fd_soltrace_TxnInput, AUTO)


PB_BIND(fd_soltrace_TxnDiff, fd_soltrace_TxnDiff, AUTO)


PB_BIND(fd_soltrace_AccountMeta, fd_soltrace_AccountMeta, AUTO)


PB_BIND(fd_soltrace_Account, fd_soltrace_Account, AUTO)


PB_BIND(fd_soltrace_KeyedAccount, fd_soltrace_KeyedAccount, AUTO)


PB_BIND(fd_soltrace_ImplicitState, fd_soltrace_ImplicitState, AUTO)


PB_BIND(fd_soltrace_ValidatorStake, fd_soltrace_ValidatorStake, AUTO)


PB_BIND(fd_soltrace_RecentBlockhash, fd_soltrace_RecentBlockhash, AUTO)



