#undef FD_TEMPL_DEF_STRUCT_BEGIN
#undef FD_TEMPL_MBR_ELEM
#undef FD_TEMPL_MBR_ELEM_HIDDEN
#undef FD_TEMPL_MBR_ELEM_VARINT
#undef FD_TEMPL_MBR_ELEM_PKTNUM
#undef FD_TEMPL_MBR_ELEM_VAR
#undef FD_TEMPL_MBR_ELEM_VAR_RAW
#undef FD_TEMPL_MBR_ELEM_RAW
#undef FD_TEMPL_MBR_FRAME_TYPE
#undef FD_TEMPL_DEF_STRUCT_END
#undef FD_TEMPL_FRAME_CTX

