/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_GEYSER_GEYSER_PB_H_INCLUDED
#define PB_GEYSER_GEYSER_PB_H_INCLUDED
#include "../../../third_party/nanopb/pb_firedancer.h"
#include "timestamp.pb.h"
#include "solana_storage.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _geyser_CommitmentLevel {
    geyser_CommitmentLevel_PROCESSED = 0,
    geyser_CommitmentLevel_CONFIRMED = 1,
    geyser_CommitmentLevel_FINALIZED = 2
} geyser_CommitmentLevel;

typedef enum _geyser_SlotStatus {
    geyser_SlotStatus_SLOT_PROCESSED = 0,
    geyser_SlotStatus_SLOT_CONFIRMED = 1,
    geyser_SlotStatus_SLOT_FINALIZED = 2,
    geyser_SlotStatus_SLOT_FIRST_SHRED_RECEIVED = 3,
    geyser_SlotStatus_SLOT_COMPLETED = 4,
    geyser_SlotStatus_SLOT_CREATED_BANK = 5,
    geyser_SlotStatus_SLOT_DEAD = 6
} geyser_SlotStatus;

/* Hash algorithm used to build the filter. Carried on the wire so future
 releases can add alternative algorithms (e.g., xxh3) without breaking
 existing clients. Readers should verify this matches a supported algorithm
 before deserializing. */
typedef enum _geyser_CuckooHashAlgorithm {
    geyser_CuckooHashAlgorithm_SIP_HASH = 0
} geyser_CuckooHashAlgorithm;

typedef enum _geyser_TokenAccountExpansionControlFlag {
    /* Match an owner if it owns a pre OR post token balance on the tx. */
    geyser_TokenAccountExpansionControlFlag_ALL = 0,
    /* Match an owner whose token balance changed in amount (per
 `account_index`) or whose token account was closed. */
    geyser_TokenAccountExpansionControlFlag_BALANCE_CHANGED = 1
} geyser_TokenAccountExpansionControlFlag;

/* Struct definitions */
typedef struct _geyser_CuckooFilter {
    pb_callback_t data; /* bucket data */
    uint32_t bucket_count; /* number of buckets */
    uint32_t entries_per_bucket; /* slots per bucket (typically 4) */
    uint32_t fingerprint_bits; /* fingerprint size (8, 12, or 16) */
    uint64_t hash_seed; /* seed for deterministic hashing */
    geyser_CuckooHashAlgorithm hash_algorithm;
} geyser_CuckooFilter;

typedef struct _geyser_SubscribeRequestFilterAccounts {
    pb_callback_t account;
    pb_callback_t owner;
    pb_callback_t filters;
    bool has_nonempty_txn_signature;
    bool nonempty_txn_signature;
    bool has_cuckoo_accounts_filter;
    geyser_CuckooFilter cuckoo_accounts_filter;
} geyser_SubscribeRequestFilterAccounts;

typedef struct _geyser_SubscribeRequest_AccountsEntry {
    pb_callback_t key;
    bool has_value;
    geyser_SubscribeRequestFilterAccounts value;
} geyser_SubscribeRequest_AccountsEntry;

typedef PB_BYTES_ARRAY_T(128) geyser_SubscribeRequestFilterAccountsFilterMemcmp_bytes_t;
typedef struct _geyser_SubscribeRequestFilterAccountsFilterMemcmp {
    uint64_t offset;
    pb_size_t which_data;
    union {
        geyser_SubscribeRequestFilterAccountsFilterMemcmp_bytes_t bytes;
        char base58[177];
        char base64[173];
    } data;
} geyser_SubscribeRequestFilterAccountsFilterMemcmp;

typedef struct _geyser_SubscribeRequestFilterAccountsFilterLamports {
    pb_size_t which_cmp;
    union {
        uint64_t eq;
        uint64_t ne;
        uint64_t lt;
        uint64_t gt;
    } cmp;
} geyser_SubscribeRequestFilterAccountsFilterLamports;

typedef struct _geyser_SubscribeRequestFilterAccountsFilter {
    pb_size_t which_filter;
    union {
        geyser_SubscribeRequestFilterAccountsFilterMemcmp memcmp;
        uint64_t datasize;
        bool token_account_state;
        geyser_SubscribeRequestFilterAccountsFilterLamports lamports;
    } filter;
} geyser_SubscribeRequestFilterAccountsFilter;

typedef struct _geyser_SubscribeRequestFilterSlots {
    bool has_filter_by_commitment;
    bool filter_by_commitment;
    bool has_interslot_updates;
    bool interslot_updates;
} geyser_SubscribeRequestFilterSlots;

typedef struct _geyser_SubscribeRequest_SlotsEntry {
    pb_callback_t key;
    bool has_value;
    geyser_SubscribeRequestFilterSlots value;
} geyser_SubscribeRequest_SlotsEntry;

typedef struct _geyser_SubscribeRequestFilterTransactions {
    bool has_vote;
    bool vote;
    bool has_failed;
    bool failed;
    pb_callback_t account_include;
    pb_callback_t account_exclude;
    bool has_signature;
    char signature[89];
    pb_callback_t account_required;
    bool has_cuckoo_account_include;
    geyser_CuckooFilter cuckoo_account_include;
    /* ATA / token-account expansion control. When set, account_include /
 account_exclude / account_required also match against owners of
 pre/post token balances on each transaction. Absent = no expansion. */
    bool has_token_accounts;
    geyser_TokenAccountExpansionControlFlag token_accounts;
} geyser_SubscribeRequestFilterTransactions;

typedef struct _geyser_SubscribeRequest_TransactionsEntry {
    pb_callback_t key;
    bool has_value;
    geyser_SubscribeRequestFilterTransactions value;
} geyser_SubscribeRequest_TransactionsEntry;

typedef struct _geyser_SubscribeRequest_TransactionsStatusEntry {
    pb_callback_t key;
    bool has_value;
    geyser_SubscribeRequestFilterTransactions value;
} geyser_SubscribeRequest_TransactionsStatusEntry;

typedef struct _geyser_SubscribeRequestFilterBlocks {
    pb_callback_t account_include;
    bool has_include_transactions;
    bool include_transactions;
    bool has_include_accounts;
    bool include_accounts;
    bool has_include_entries;
    bool include_entries;
    bool has_cuckoo_account_include;
    geyser_CuckooFilter cuckoo_account_include;
} geyser_SubscribeRequestFilterBlocks;

typedef struct _geyser_SubscribeRequest_BlocksEntry {
    pb_callback_t key;
    bool has_value;
    geyser_SubscribeRequestFilterBlocks value;
} geyser_SubscribeRequest_BlocksEntry;

typedef struct _geyser_SubscribeRequestFilterBlocksMeta {
    char dummy_field;
} geyser_SubscribeRequestFilterBlocksMeta;

typedef struct _geyser_SubscribeRequest_BlocksMetaEntry {
    pb_callback_t key;
    bool has_value;
    geyser_SubscribeRequestFilterBlocksMeta value;
} geyser_SubscribeRequest_BlocksMetaEntry;

typedef struct _geyser_SubscribeRequestFilterEntry {
    char dummy_field;
} geyser_SubscribeRequestFilterEntry;

typedef struct _geyser_SubscribeRequest_EntryEntry {
    pb_callback_t key;
    bool has_value;
    geyser_SubscribeRequestFilterEntry value;
} geyser_SubscribeRequest_EntryEntry;

/* Filter for deshred transactions (transactions received before execution).
 Deshred transactions are received when entries are formed from shreds,
 BEFORE any execution occurs. No TransactionStatusMeta is available.
 Address lookup tables are resolved, so both static account keys and
 dynamically loaded addresses (from ALTs) are available for filtering. */
typedef struct _geyser_SubscribeRequestFilterDeshredTransactions {
    bool has_vote;
    bool vote;
    pb_callback_t account_include;
    pb_callback_t account_exclude;
    pb_callback_t account_required;
} geyser_SubscribeRequestFilterDeshredTransactions;

typedef struct _geyser_SubscribeRequestAccountsDataSlice {
    uint64_t offset;
    uint64_t length;
} geyser_SubscribeRequestAccountsDataSlice;

typedef struct _geyser_SubscribeRequestPing {
    int32_t id;
} geyser_SubscribeRequestPing;

typedef struct _geyser_SubscribeRequest {
    pb_callback_t accounts;
    pb_callback_t slots;
    pb_callback_t transactions;
    pb_callback_t blocks;
    pb_callback_t blocks_meta;
    bool has_commitment;
    geyser_CommitmentLevel commitment;
    pb_callback_t accounts_data_slice;
    pb_callback_t entry;
    bool has_ping;
    geyser_SubscribeRequestPing ping;
    pb_callback_t transactions_status;
    bool has_from_slot;
    uint64_t from_slot;
} geyser_SubscribeRequest;

/* Request message for the SubscribeDeshred RPC.
 Subscribes to deshred transactions (transactions received before execution).
 Deshred transactions are received when entries are formed from shreds,
 BEFORE any execution occurs. No TransactionStatusMeta is available.
 Address lookup tables are resolved, so both static and loaded addresses
 are available for filtering. */
typedef struct _geyser_SubscribeDeshredRequest {
    pb_callback_t deshred_transactions;
    bool has_ping;
    geyser_SubscribeRequestPing ping;
    pb_callback_t slots;
} geyser_SubscribeDeshredRequest;

typedef struct _geyser_SubscribeDeshredRequest_DeshredTransactionsEntry {
    pb_callback_t key;
    bool has_value;
    geyser_SubscribeRequestFilterDeshredTransactions value;
} geyser_SubscribeDeshredRequest_DeshredTransactionsEntry;

typedef struct _geyser_SubscribeDeshredRequest_SlotsEntry {
    pb_callback_t key;
    bool has_value;
    geyser_SubscribeRequestFilterSlots value;
} geyser_SubscribeDeshredRequest_SlotsEntry;

typedef PB_BYTES_ARRAY_T(32) geyser_SubscribeUpdateAccountInfo_pubkey_t;
typedef PB_BYTES_ARRAY_T(32) geyser_SubscribeUpdateAccountInfo_owner_t;
typedef PB_BYTES_ARRAY_T(64) geyser_SubscribeUpdateAccountInfo_txn_signature_t;
typedef struct _geyser_SubscribeUpdateAccountInfo {
    geyser_SubscribeUpdateAccountInfo_pubkey_t pubkey;
    uint64_t lamports;
    geyser_SubscribeUpdateAccountInfo_owner_t owner;
    bool executable;
    uint64_t rent_epoch;
    pb_callback_t data;
    uint64_t write_version;
    bool has_txn_signature;
    geyser_SubscribeUpdateAccountInfo_txn_signature_t txn_signature;
} geyser_SubscribeUpdateAccountInfo;

typedef struct _geyser_SubscribeUpdateAccount {
    bool has_account;
    geyser_SubscribeUpdateAccountInfo account;
    uint64_t slot;
    bool is_startup;
    /* if is_startup is true, bank id is None. */
    bool has_bank_id;
    uint64_t bank_id;
} geyser_SubscribeUpdateAccount;

typedef struct _geyser_SubscribeUpdateSlot {
    uint64_t slot;
    bool has_parent;
    uint64_t parent;
    geyser_SlotStatus status;
    bool has_dead_error;
    char dead_error[256];
    /* FIRST_SHRED_RECEIVED and COMPLETED slot status does not belong to any bank. */
    bool has_bank_id;
    uint64_t bank_id;
} geyser_SubscribeUpdateSlot;

typedef PB_BYTES_ARRAY_T(64) geyser_SubscribeUpdateTransactionInfo_signature_t;
typedef struct _geyser_SubscribeUpdateTransactionInfo {
    geyser_SubscribeUpdateTransactionInfo_signature_t signature;
    bool is_vote;
    bool has_transaction;
    solana_storage_ConfirmedBlock_Transaction transaction;
    bool has_meta;
    solana_storage_ConfirmedBlock_TransactionStatusMeta meta;
    uint64_t index;
} geyser_SubscribeUpdateTransactionInfo;

typedef struct _geyser_SubscribeUpdateTransaction {
    bool has_transaction;
    geyser_SubscribeUpdateTransactionInfo transaction;
    uint64_t slot;
    uint64_t bank_id;
} geyser_SubscribeUpdateTransaction;

typedef PB_BYTES_ARRAY_T(64) geyser_SubscribeUpdateTransactionStatus_signature_t;
typedef struct _geyser_SubscribeUpdateTransactionStatus {
    uint64_t slot;
    geyser_SubscribeUpdateTransactionStatus_signature_t signature;
    bool is_vote;
    uint64_t index;
    bool has_err;
    solana_storage_ConfirmedBlock_TransactionError err;
    uint64_t bank_id;
} geyser_SubscribeUpdateTransactionStatus;

typedef struct _geyser_SubscribeUpdateBlock {
    uint64_t slot;
    char blockhash[45];
    bool has_rewards;
    solana_storage_ConfirmedBlock_Rewards rewards;
    bool has_block_time;
    solana_storage_ConfirmedBlock_UnixTimestamp block_time;
    bool has_block_height;
    solana_storage_ConfirmedBlock_BlockHeight block_height;
    pb_callback_t transactions;
    uint64_t parent_slot;
    char parent_blockhash[45];
    uint64_t executed_transaction_count;
    uint64_t updated_account_count;
    pb_callback_t accounts;
    uint64_t entries_count;
    pb_callback_t entries;
    uint64_t bank_id;
} geyser_SubscribeUpdateBlock;

typedef struct _geyser_SubscribeUpdateBlockMeta {
    uint64_t slot;
    char blockhash[45];
    bool has_rewards;
    solana_storage_ConfirmedBlock_Rewards rewards;
    bool has_block_time;
    solana_storage_ConfirmedBlock_UnixTimestamp block_time;
    bool has_block_height;
    solana_storage_ConfirmedBlock_BlockHeight block_height;
    uint64_t parent_slot;
    char parent_blockhash[45];
    uint64_t executed_transaction_count;
    uint64_t entries_count;
    uint64_t bank_id;
} geyser_SubscribeUpdateBlockMeta;

typedef PB_BYTES_ARRAY_T(32) geyser_SubscribeUpdateEntry_hash_t;
typedef struct _geyser_SubscribeUpdateEntry {
    uint64_t slot;
    uint64_t index;
    uint64_t num_hashes;
    geyser_SubscribeUpdateEntry_hash_t hash;
    uint64_t executed_transaction_count;
    uint64_t starting_transaction_index; /* added in v1.18, for solana 1.17 value is always 0 */
    uint64_t bank_id;
} geyser_SubscribeUpdateEntry;

typedef PB_BYTES_ARRAY_T(64) geyser_SubscribeUpdateDeshredTransactionInfo_signature_t;
typedef struct _geyser_SubscribeUpdateDeshredTransactionInfo {
    geyser_SubscribeUpdateDeshredTransactionInfo_signature_t signature;
    bool is_vote;
    bool has_transaction;
    solana_storage_ConfirmedBlock_Transaction transaction;
    pb_callback_t loaded_writable_addresses;
    pb_callback_t loaded_readonly_addresses;
    uint32_t completed_data_set_starting_shred_index;
    uint32_t completed_data_set_ending_shred_index_exclusive;
} geyser_SubscribeUpdateDeshredTransactionInfo;

typedef struct _geyser_SubscribeUpdateDeshredTransaction {
    bool has_transaction;
    geyser_SubscribeUpdateDeshredTransactionInfo transaction;
    uint64_t slot;
} geyser_SubscribeUpdateDeshredTransaction;

typedef struct _geyser_SubscribeUpdatePing {
    char dummy_field;
} geyser_SubscribeUpdatePing;

typedef struct _geyser_SubscribeUpdatePong {
    int32_t id;
} geyser_SubscribeUpdatePong;

typedef struct _geyser_SubscribeUpdate {
    pb_callback_t filters;
    pb_size_t which_update_oneof;
    union {
        geyser_SubscribeUpdateAccount account;
        geyser_SubscribeUpdateSlot slot;
        geyser_SubscribeUpdateTransaction transaction;
        geyser_SubscribeUpdateBlock block;
        geyser_SubscribeUpdatePing ping;
        geyser_SubscribeUpdateBlockMeta block_meta;
        geyser_SubscribeUpdateEntry entry;
        geyser_SubscribeUpdatePong pong;
        geyser_SubscribeUpdateTransactionStatus transaction_status;
    } update_oneof;
    bool has_created_at;
    google_protobuf_Timestamp created_at;
} geyser_SubscribeUpdate;

typedef struct _geyser_SubscribeUpdateDeshred {
    pb_callback_t filters;
    pb_size_t which_update_oneof;
    union {
        geyser_SubscribeUpdateDeshredTransaction deshred_transaction;
        geyser_SubscribeUpdatePing ping;
        geyser_SubscribeUpdatePong pong;
        /* field 5 is reserved for created_at (below the oneof) */
        geyser_SubscribeUpdateSlot slot;
    } update_oneof;
    bool has_created_at;
    google_protobuf_Timestamp created_at;
} geyser_SubscribeUpdateDeshred;

typedef struct _geyser_SubscribeGossipRequest {
    char dummy_field;
} geyser_SubscribeGossipRequest;

/* Full copy of the server-side gossip contact info table, sent when a client subscribes. Later `node`/`removed` updates carry `seq > snapshot.seq`. */
typedef struct _geyser_GossipTopology {
    pb_callback_t nodes;
} geyser_GossipTopology;

typedef PB_BYTES_ARRAY_T(32) geyser_SubscribeUpdateContactInfoNode_pubkey_t;
typedef struct _geyser_SubscribeUpdateContactInfoNode {
    geyser_SubscribeUpdateContactInfoNode_pubkey_t pubkey;
    uint64_t wallclock;
    uint64_t outset;
    uint32_t shred_version;
    uint32_t version_major;
    uint32_t version_minor;
    uint32_t version_patch;
    uint32_t version_commit;
    uint32_t version_feature_set;
    uint32_t version_client_id;
    bool has_gossip;
    char gossip[64];
    bool has_tpu_quic;
    char tpu_quic[64];
    bool has_tpu_forwards_quic;
    char tpu_forwards_quic[64];
    bool has_tpu_vote_udp;
    char tpu_vote_udp[64];
    bool has_tpu_vote_quic;
    char tpu_vote_quic[64];
    bool has_tvu_udp;
    char tvu_udp[64];
    bool has_tvu_quic;
    char tvu_quic[64];
    bool has_serve_repair_udp;
    char serve_repair_udp[64];
    bool has_serve_repair_quic;
    char serve_repair_quic[64];
    bool has_rpc;
    char rpc[64];
    bool has_rpc_pubsub;
    char rpc_pubsub[64];
    bool has_alpenglow;
    char alpenglow[64];
} geyser_SubscribeUpdateContactInfoNode;

typedef PB_BYTES_ARRAY_T(32) geyser_SubscribeUpdateContactInfoRemoved_pubkey_t;
typedef struct _geyser_SubscribeUpdateContactInfoRemoved {
    geyser_SubscribeUpdateContactInfoRemoved_pubkey_t pubkey;
} geyser_SubscribeUpdateContactInfoRemoved;

typedef struct _geyser_SubscribeUpdateGossip {
    pb_size_t which_update_oneof;
    union {
        geyser_SubscribeUpdateContactInfoNode node;
        geyser_SubscribeUpdateContactInfoRemoved removed;
        /* Server keepalive; the stream can be silent for minutes on a stable cluster. */
        geyser_SubscribeUpdatePing ping;
        geyser_GossipTopology snapshot;
    } update_oneof;
    bool has_created_at;
    google_protobuf_Timestamp created_at;
    /* Table revision: for `snapshot` the revision copied, for `node`/`removed` the revision applied. Increases by one per change. Unset (0) for `ping`. */
    uint64_t seq;
} geyser_SubscribeUpdateGossip;

typedef struct _geyser_SubscribeReplayInfoRequest {
    char dummy_field;
} geyser_SubscribeReplayInfoRequest;

typedef struct _geyser_SubscribeReplayInfoResponse {
    bool has_first_available;
    uint64_t first_available;
} geyser_SubscribeReplayInfoResponse;

typedef struct _geyser_PingRequest {
    int32_t count;
} geyser_PingRequest;

typedef struct _geyser_PongResponse {
    int32_t count;
} geyser_PongResponse;

typedef struct _geyser_GetLatestBlockhashRequest {
    bool has_commitment;
    geyser_CommitmentLevel commitment;
} geyser_GetLatestBlockhashRequest;

typedef struct _geyser_GetLatestBlockhashResponse {
    uint64_t slot;
    char blockhash[45];
    uint64_t last_valid_block_height;
} geyser_GetLatestBlockhashResponse;

typedef struct _geyser_GetBlockHeightRequest {
    bool has_commitment;
    geyser_CommitmentLevel commitment;
} geyser_GetBlockHeightRequest;

typedef struct _geyser_GetBlockHeightResponse {
    uint64_t block_height;
} geyser_GetBlockHeightResponse;

typedef struct _geyser_GetSlotRequest {
    bool has_commitment;
    geyser_CommitmentLevel commitment;
} geyser_GetSlotRequest;

typedef struct _geyser_GetSlotResponse {
    uint64_t slot;
} geyser_GetSlotResponse;

typedef struct _geyser_GetVersionRequest {
    char dummy_field;
} geyser_GetVersionRequest;

typedef struct _geyser_GetVersionResponse {
    char version[640];
} geyser_GetVersionResponse;

typedef struct _geyser_IsBlockhashValidRequest {
    char blockhash[45];
    bool has_commitment;
    geyser_CommitmentLevel commitment;
} geyser_IsBlockhashValidRequest;

typedef struct _geyser_IsBlockhashValidResponse {
    uint64_t slot;
    bool valid;
} geyser_IsBlockhashValidResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _geyser_CommitmentLevel_MIN geyser_CommitmentLevel_PROCESSED
#define _geyser_CommitmentLevel_MAX geyser_CommitmentLevel_FINALIZED
#define _geyser_CommitmentLevel_ARRAYSIZE ((geyser_CommitmentLevel)(geyser_CommitmentLevel_FINALIZED+1))

#define _geyser_SlotStatus_MIN geyser_SlotStatus_SLOT_PROCESSED
#define _geyser_SlotStatus_MAX geyser_SlotStatus_SLOT_DEAD
#define _geyser_SlotStatus_ARRAYSIZE ((geyser_SlotStatus)(geyser_SlotStatus_SLOT_DEAD+1))

#define _geyser_CuckooHashAlgorithm_MIN geyser_CuckooHashAlgorithm_SIP_HASH
#define _geyser_CuckooHashAlgorithm_MAX geyser_CuckooHashAlgorithm_SIP_HASH
#define _geyser_CuckooHashAlgorithm_ARRAYSIZE ((geyser_CuckooHashAlgorithm)(geyser_CuckooHashAlgorithm_SIP_HASH+1))

#define _geyser_TokenAccountExpansionControlFlag_MIN geyser_TokenAccountExpansionControlFlag_ALL
#define _geyser_TokenAccountExpansionControlFlag_MAX geyser_TokenAccountExpansionControlFlag_BALANCE_CHANGED
#define _geyser_TokenAccountExpansionControlFlag_ARRAYSIZE ((geyser_TokenAccountExpansionControlFlag)(geyser_TokenAccountExpansionControlFlag_BALANCE_CHANGED+1))

#define geyser_SubscribeRequest_commitment_ENUMTYPE geyser_CommitmentLevel








#define geyser_CuckooFilter_hash_algorithm_ENUMTYPE geyser_CuckooHashAlgorithm






#define geyser_SubscribeRequestFilterTransactions_token_accounts_ENUMTYPE geyser_TokenAccountExpansionControlFlag













#define geyser_SubscribeUpdateSlot_status_ENUMTYPE geyser_SlotStatus





















#define geyser_GetLatestBlockhashRequest_commitment_ENUMTYPE geyser_CommitmentLevel


#define geyser_GetBlockHeightRequest_commitment_ENUMTYPE geyser_CommitmentLevel


#define geyser_GetSlotRequest_commitment_ENUMTYPE geyser_CommitmentLevel




#define geyser_IsBlockhashValidRequest_commitment_ENUMTYPE geyser_CommitmentLevel



/* Initializer values for message structs */
#define geyser_SubscribeRequest_init_default     {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, _geyser_CommitmentLevel_MIN, {{NULL}, NULL}, {{NULL}, NULL}, false, geyser_SubscribeRequestPing_init_default, {{NULL}, NULL}, false, 0}
#define geyser_SubscribeRequest_AccountsEntry_init_default {{{NULL}, NULL}, false, geyser_SubscribeRequestFilterAccounts_init_default}
#define geyser_SubscribeRequest_SlotsEntry_init_default {{{NULL}, NULL}, false, geyser_SubscribeRequestFilterSlots_init_default}
#define geyser_SubscribeRequest_TransactionsEntry_init_default {{{NULL}, NULL}, false, geyser_SubscribeRequestFilterTransactions_init_default}
#define geyser_SubscribeRequest_TransactionsStatusEntry_init_default {{{NULL}, NULL}, false, geyser_SubscribeRequestFilterTransactions_init_default}
#define geyser_SubscribeRequest_BlocksEntry_init_default {{{NULL}, NULL}, false, geyser_SubscribeRequestFilterBlocks_init_default}
#define geyser_SubscribeRequest_BlocksMetaEntry_init_default {{{NULL}, NULL}, false, geyser_SubscribeRequestFilterBlocksMeta_init_default}
#define geyser_SubscribeRequest_EntryEntry_init_default {{{NULL}, NULL}, false, geyser_SubscribeRequestFilterEntry_init_default}
#define geyser_CuckooFilter_init_default         {{{NULL}, NULL}, 0, 0, 0, 0, _geyser_CuckooHashAlgorithm_MIN}
#define geyser_SubscribeRequestFilterAccounts_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, geyser_CuckooFilter_init_default}
#define geyser_SubscribeRequestFilterAccountsFilter_init_default {0, {geyser_SubscribeRequestFilterAccountsFilterMemcmp_init_default}}
#define geyser_SubscribeRequestFilterAccountsFilterMemcmp_init_default {0, 0, {{0, {0}}}}
#define geyser_SubscribeRequestFilterAccountsFilterLamports_init_default {0, {0}}
#define geyser_SubscribeRequestFilterSlots_init_default {false, 0, false, 0}
#define geyser_SubscribeRequestFilterTransactions_init_default {false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, "", {{NULL}, NULL}, false, geyser_CuckooFilter_init_default, false, _geyser_TokenAccountExpansionControlFlag_MIN}
#define geyser_SubscribeRequestFilterBlocks_init_default {{{NULL}, NULL}, false, 0, false, 0, false, 0, false, geyser_CuckooFilter_init_default}
#define geyser_SubscribeRequestFilterBlocksMeta_init_default {0}
#define geyser_SubscribeRequestFilterEntry_init_default {0}
#define geyser_SubscribeRequestFilterDeshredTransactions_init_default {false, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define geyser_SubscribeRequestAccountsDataSlice_init_default {0, 0}
#define geyser_SubscribeRequestPing_init_default {0}
#define geyser_SubscribeDeshredRequest_init_default {{{NULL}, NULL}, false, geyser_SubscribeRequestPing_init_default, {{NULL}, NULL}}
#define geyser_SubscribeDeshredRequest_DeshredTransactionsEntry_init_default {{{NULL}, NULL}, false, geyser_SubscribeRequestFilterDeshredTransactions_init_default}
#define geyser_SubscribeDeshredRequest_SlotsEntry_init_default {{{NULL}, NULL}, false, geyser_SubscribeRequestFilterSlots_init_default}
#define geyser_SubscribeUpdate_init_default      {{{NULL}, NULL}, 0, {geyser_SubscribeUpdateAccount_init_default}, false, google_protobuf_Timestamp_init_default}
#define geyser_SubscribeUpdateAccount_init_default {false, geyser_SubscribeUpdateAccountInfo_init_default, 0, 0, false, 0}
#define geyser_SubscribeUpdateAccountInfo_init_default {{0, {0}}, 0, {0, {0}}, 0, 0, {{NULL}, NULL}, 0, false, {0, {0}}}
#define geyser_SubscribeUpdateSlot_init_default  {0, false, 0, _geyser_SlotStatus_MIN, false, "", false, 0}
#define geyser_SubscribeUpdateTransaction_init_default {false, geyser_SubscribeUpdateTransactionInfo_init_default, 0, 0}
#define geyser_SubscribeUpdateTransactionInfo_init_default {{0, {0}}, 0, false, solana_storage_ConfirmedBlock_Transaction_init_default, false, solana_storage_ConfirmedBlock_TransactionStatusMeta_init_default, 0}
#define geyser_SubscribeUpdateTransactionStatus_init_default {0, {0, {0}}, 0, 0, false, solana_storage_ConfirmedBlock_TransactionError_init_default, 0}
#define geyser_SubscribeUpdateBlock_init_default {0, "", false, solana_storage_ConfirmedBlock_Rewards_init_default, false, solana_storage_ConfirmedBlock_UnixTimestamp_init_default, false, solana_storage_ConfirmedBlock_BlockHeight_init_default, {{NULL}, NULL}, 0, "", 0, 0, {{NULL}, NULL}, 0, {{NULL}, NULL}, 0}
#define geyser_SubscribeUpdateBlockMeta_init_default {0, "", false, solana_storage_ConfirmedBlock_Rewards_init_default, false, solana_storage_ConfirmedBlock_UnixTimestamp_init_default, false, solana_storage_ConfirmedBlock_BlockHeight_init_default, 0, "", 0, 0, 0}
#define geyser_SubscribeUpdateEntry_init_default {0, 0, 0, {0, {0}}, 0, 0, 0}
#define geyser_SubscribeUpdateDeshredTransaction_init_default {false, geyser_SubscribeUpdateDeshredTransactionInfo_init_default, 0}
#define geyser_SubscribeUpdateDeshredTransactionInfo_init_default {{0, {0}}, 0, false, solana_storage_ConfirmedBlock_Transaction_init_default, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0}
#define geyser_SubscribeUpdatePing_init_default  {0}
#define geyser_SubscribeUpdatePong_init_default  {0}
#define geyser_SubscribeUpdateDeshred_init_default {{{NULL}, NULL}, 0, {geyser_SubscribeUpdateDeshredTransaction_init_default}, false, google_protobuf_Timestamp_init_default}
#define geyser_SubscribeGossipRequest_init_default {0}
#define geyser_SubscribeUpdateGossip_init_default {0, {geyser_SubscribeUpdateContactInfoNode_init_default}, false, google_protobuf_Timestamp_init_default, 0}
#define geyser_GossipTopology_init_default       {{{NULL}, NULL}}
#define geyser_SubscribeUpdateContactInfoNode_init_default {{0, {0}}, 0, 0, 0, 0, 0, 0, 0, 0, 0, false, "", false, "", false, "", false, "", false, "", false, "", false, "", false, "", false, "", false, "", false, "", false, ""}
#define geyser_SubscribeUpdateContactInfoRemoved_init_default {{0, {0}}}
#define geyser_SubscribeReplayInfoRequest_init_default {0}
#define geyser_SubscribeReplayInfoResponse_init_default {false, 0}
#define geyser_PingRequest_init_default          {0}
#define geyser_PongResponse_init_default         {0}
#define geyser_GetLatestBlockhashRequest_init_default {false, _geyser_CommitmentLevel_MIN}
#define geyser_GetLatestBlockhashResponse_init_default {0, "", 0}
#define geyser_GetBlockHeightRequest_init_default {false, _geyser_CommitmentLevel_MIN}
#define geyser_GetBlockHeightResponse_init_default {0}
#define geyser_GetSlotRequest_init_default       {false, _geyser_CommitmentLevel_MIN}
#define geyser_GetSlotResponse_init_default      {0}
#define geyser_GetVersionRequest_init_default    {0}
#define geyser_GetVersionResponse_init_default   {""}
#define geyser_IsBlockhashValidRequest_init_default {"", false, _geyser_CommitmentLevel_MIN}
#define geyser_IsBlockhashValidResponse_init_default {0, 0}
#define geyser_SubscribeRequest_init_zero        {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, _geyser_CommitmentLevel_MIN, {{NULL}, NULL}, {{NULL}, NULL}, false, geyser_SubscribeRequestPing_init_zero, {{NULL}, NULL}, false, 0}
#define geyser_SubscribeRequest_AccountsEntry_init_zero {{{NULL}, NULL}, false, geyser_SubscribeRequestFilterAccounts_init_zero}
#define geyser_SubscribeRequest_SlotsEntry_init_zero {{{NULL}, NULL}, false, geyser_SubscribeRequestFilterSlots_init_zero}
#define geyser_SubscribeRequest_TransactionsEntry_init_zero {{{NULL}, NULL}, false, geyser_SubscribeRequestFilterTransactions_init_zero}
#define geyser_SubscribeRequest_TransactionsStatusEntry_init_zero {{{NULL}, NULL}, false, geyser_SubscribeRequestFilterTransactions_init_zero}
#define geyser_SubscribeRequest_BlocksEntry_init_zero {{{NULL}, NULL}, false, geyser_SubscribeRequestFilterBlocks_init_zero}
#define geyser_SubscribeRequest_BlocksMetaEntry_init_zero {{{NULL}, NULL}, false, geyser_SubscribeRequestFilterBlocksMeta_init_zero}
#define geyser_SubscribeRequest_EntryEntry_init_zero {{{NULL}, NULL}, false, geyser_SubscribeRequestFilterEntry_init_zero}
#define geyser_CuckooFilter_init_zero            {{{NULL}, NULL}, 0, 0, 0, 0, _geyser_CuckooHashAlgorithm_MIN}
#define geyser_SubscribeRequestFilterAccounts_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, geyser_CuckooFilter_init_zero}
#define geyser_SubscribeRequestFilterAccountsFilter_init_zero {0, {geyser_SubscribeRequestFilterAccountsFilterMemcmp_init_zero}}
#define geyser_SubscribeRequestFilterAccountsFilterMemcmp_init_zero {0, 0, {{0, {0}}}}
#define geyser_SubscribeRequestFilterAccountsFilterLamports_init_zero {0, {0}}
#define geyser_SubscribeRequestFilterSlots_init_zero {false, 0, false, 0}
#define geyser_SubscribeRequestFilterTransactions_init_zero {false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, "", {{NULL}, NULL}, false, geyser_CuckooFilter_init_zero, false, _geyser_TokenAccountExpansionControlFlag_MIN}
#define geyser_SubscribeRequestFilterBlocks_init_zero {{{NULL}, NULL}, false, 0, false, 0, false, 0, false, geyser_CuckooFilter_init_zero}
#define geyser_SubscribeRequestFilterBlocksMeta_init_zero {0}
#define geyser_SubscribeRequestFilterEntry_init_zero {0}
#define geyser_SubscribeRequestFilterDeshredTransactions_init_zero {false, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define geyser_SubscribeRequestAccountsDataSlice_init_zero {0, 0}
#define geyser_SubscribeRequestPing_init_zero    {0}
#define geyser_SubscribeDeshredRequest_init_zero {{{NULL}, NULL}, false, geyser_SubscribeRequestPing_init_zero, {{NULL}, NULL}}
#define geyser_SubscribeDeshredRequest_DeshredTransactionsEntry_init_zero {{{NULL}, NULL}, false, geyser_SubscribeRequestFilterDeshredTransactions_init_zero}
#define geyser_SubscribeDeshredRequest_SlotsEntry_init_zero {{{NULL}, NULL}, false, geyser_SubscribeRequestFilterSlots_init_zero}
#define geyser_SubscribeUpdate_init_zero         {{{NULL}, NULL}, 0, {geyser_SubscribeUpdateAccount_init_zero}, false, google_protobuf_Timestamp_init_zero}
#define geyser_SubscribeUpdateAccount_init_zero  {false, geyser_SubscribeUpdateAccountInfo_init_zero, 0, 0, false, 0}
#define geyser_SubscribeUpdateAccountInfo_init_zero {{0, {0}}, 0, {0, {0}}, 0, 0, {{NULL}, NULL}, 0, false, {0, {0}}}
#define geyser_SubscribeUpdateSlot_init_zero     {0, false, 0, _geyser_SlotStatus_MIN, false, "", false, 0}
#define geyser_SubscribeUpdateTransaction_init_zero {false, geyser_SubscribeUpdateTransactionInfo_init_zero, 0, 0}
#define geyser_SubscribeUpdateTransactionInfo_init_zero {{0, {0}}, 0, false, solana_storage_ConfirmedBlock_Transaction_init_zero, false, solana_storage_ConfirmedBlock_TransactionStatusMeta_init_zero, 0}
#define geyser_SubscribeUpdateTransactionStatus_init_zero {0, {0, {0}}, 0, 0, false, solana_storage_ConfirmedBlock_TransactionError_init_zero, 0}
#define geyser_SubscribeUpdateBlock_init_zero    {0, "", false, solana_storage_ConfirmedBlock_Rewards_init_zero, false, solana_storage_ConfirmedBlock_UnixTimestamp_init_zero, false, solana_storage_ConfirmedBlock_BlockHeight_init_zero, {{NULL}, NULL}, 0, "", 0, 0, {{NULL}, NULL}, 0, {{NULL}, NULL}, 0}
#define geyser_SubscribeUpdateBlockMeta_init_zero {0, "", false, solana_storage_ConfirmedBlock_Rewards_init_zero, false, solana_storage_ConfirmedBlock_UnixTimestamp_init_zero, false, solana_storage_ConfirmedBlock_BlockHeight_init_zero, 0, "", 0, 0, 0}
#define geyser_SubscribeUpdateEntry_init_zero    {0, 0, 0, {0, {0}}, 0, 0, 0}
#define geyser_SubscribeUpdateDeshredTransaction_init_zero {false, geyser_SubscribeUpdateDeshredTransactionInfo_init_zero, 0}
#define geyser_SubscribeUpdateDeshredTransactionInfo_init_zero {{0, {0}}, 0, false, solana_storage_ConfirmedBlock_Transaction_init_zero, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0}
#define geyser_SubscribeUpdatePing_init_zero     {0}
#define geyser_SubscribeUpdatePong_init_zero     {0}
#define geyser_SubscribeUpdateDeshred_init_zero  {{{NULL}, NULL}, 0, {geyser_SubscribeUpdateDeshredTransaction_init_zero}, false, google_protobuf_Timestamp_init_zero}
#define geyser_SubscribeGossipRequest_init_zero  {0}
#define geyser_SubscribeUpdateGossip_init_zero   {0, {geyser_SubscribeUpdateContactInfoNode_init_zero}, false, google_protobuf_Timestamp_init_zero, 0}
#define geyser_GossipTopology_init_zero          {{{NULL}, NULL}}
#define geyser_SubscribeUpdateContactInfoNode_init_zero {{0, {0}}, 0, 0, 0, 0, 0, 0, 0, 0, 0, false, "", false, "", false, "", false, "", false, "", false, "", false, "", false, "", false, "", false, "", false, "", false, ""}
#define geyser_SubscribeUpdateContactInfoRemoved_init_zero {{0, {0}}}
#define geyser_SubscribeReplayInfoRequest_init_zero {0}
#define geyser_SubscribeReplayInfoResponse_init_zero {false, 0}
#define geyser_PingRequest_init_zero             {0}
#define geyser_PongResponse_init_zero            {0}
#define geyser_GetLatestBlockhashRequest_init_zero {false, _geyser_CommitmentLevel_MIN}
#define geyser_GetLatestBlockhashResponse_init_zero {0, "", 0}
#define geyser_GetBlockHeightRequest_init_zero   {false, _geyser_CommitmentLevel_MIN}
#define geyser_GetBlockHeightResponse_init_zero  {0}
#define geyser_GetSlotRequest_init_zero          {false, _geyser_CommitmentLevel_MIN}
#define geyser_GetSlotResponse_init_zero         {0}
#define geyser_GetVersionRequest_init_zero       {0}
#define geyser_GetVersionResponse_init_zero      {""}
#define geyser_IsBlockhashValidRequest_init_zero {"", false, _geyser_CommitmentLevel_MIN}
#define geyser_IsBlockhashValidResponse_init_zero {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define geyser_CuckooFilter_data_tag             1
#define geyser_CuckooFilter_bucket_count_tag     2
#define geyser_CuckooFilter_entries_per_bucket_tag 3
#define geyser_CuckooFilter_fingerprint_bits_tag 4
#define geyser_CuckooFilter_hash_seed_tag        5
#define geyser_CuckooFilter_hash_algorithm_tag   6
#define geyser_SubscribeRequestFilterAccounts_account_tag 2
#define geyser_SubscribeRequestFilterAccounts_owner_tag 3
#define geyser_SubscribeRequestFilterAccounts_filters_tag 4
#define geyser_SubscribeRequestFilterAccounts_nonempty_txn_signature_tag 5
#define geyser_SubscribeRequestFilterAccounts_cuckoo_accounts_filter_tag 6
#define geyser_SubscribeRequest_AccountsEntry_key_tag 1
#define geyser_SubscribeRequest_AccountsEntry_value_tag 2
#define geyser_SubscribeRequestFilterAccountsFilterMemcmp_offset_tag 1
#define geyser_SubscribeRequestFilterAccountsFilterMemcmp_bytes_tag 2
#define geyser_SubscribeRequestFilterAccountsFilterMemcmp_base58_tag 3
#define geyser_SubscribeRequestFilterAccountsFilterMemcmp_base64_tag 4
#define geyser_SubscribeRequestFilterAccountsFilterLamports_eq_tag 1
#define geyser_SubscribeRequestFilterAccountsFilterLamports_ne_tag 2
#define geyser_SubscribeRequestFilterAccountsFilterLamports_lt_tag 3
#define geyser_SubscribeRequestFilterAccountsFilterLamports_gt_tag 4
#define geyser_SubscribeRequestFilterAccountsFilter_memcmp_tag 1
#define geyser_SubscribeRequestFilterAccountsFilter_datasize_tag 2
#define geyser_SubscribeRequestFilterAccountsFilter_token_account_state_tag 3
#define geyser_SubscribeRequestFilterAccountsFilter_lamports_tag 4
#define geyser_SubscribeRequestFilterSlots_filter_by_commitment_tag 1
#define geyser_SubscribeRequestFilterSlots_interslot_updates_tag 2
#define geyser_SubscribeRequest_SlotsEntry_key_tag 1
#define geyser_SubscribeRequest_SlotsEntry_value_tag 2
#define geyser_SubscribeRequestFilterTransactions_vote_tag 1
#define geyser_SubscribeRequestFilterTransactions_failed_tag 2
#define geyser_SubscribeRequestFilterTransactions_account_include_tag 3
#define geyser_SubscribeRequestFilterTransactions_account_exclude_tag 4
#define geyser_SubscribeRequestFilterTransactions_signature_tag 5
#define geyser_SubscribeRequestFilterTransactions_account_required_tag 6
#define geyser_SubscribeRequestFilterTransactions_cuckoo_account_include_tag 7
#define geyser_SubscribeRequestFilterTransactions_token_accounts_tag 30
#define geyser_SubscribeRequest_TransactionsEntry_key_tag 1
#define geyser_SubscribeRequest_TransactionsEntry_value_tag 2
#define geyser_SubscribeRequest_TransactionsStatusEntry_key_tag 1
#define geyser_SubscribeRequest_TransactionsStatusEntry_value_tag 2
#define geyser_SubscribeRequestFilterBlocks_account_include_tag 1
#define geyser_SubscribeRequestFilterBlocks_include_transactions_tag 2
#define geyser_SubscribeRequestFilterBlocks_include_accounts_tag 3
#define geyser_SubscribeRequestFilterBlocks_include_entries_tag 4
#define geyser_SubscribeRequestFilterBlocks_cuckoo_account_include_tag 5
#define geyser_SubscribeRequest_BlocksEntry_key_tag 1
#define geyser_SubscribeRequest_BlocksEntry_value_tag 2
#define geyser_SubscribeRequest_BlocksMetaEntry_key_tag 1
#define geyser_SubscribeRequest_BlocksMetaEntry_value_tag 2
#define geyser_SubscribeRequest_EntryEntry_key_tag 1
#define geyser_SubscribeRequest_EntryEntry_value_tag 2
#define geyser_SubscribeRequestFilterDeshredTransactions_vote_tag 1
#define geyser_SubscribeRequestFilterDeshredTransactions_account_include_tag 2
#define geyser_SubscribeRequestFilterDeshredTransactions_account_exclude_tag 3
#define geyser_SubscribeRequestFilterDeshredTransactions_account_required_tag 4
#define geyser_SubscribeRequestAccountsDataSlice_offset_tag 1
#define geyser_SubscribeRequestAccountsDataSlice_length_tag 2
#define geyser_SubscribeRequestPing_id_tag       1
#define geyser_SubscribeRequest_accounts_tag     1
#define geyser_SubscribeRequest_slots_tag        2
#define geyser_SubscribeRequest_transactions_tag 3
#define geyser_SubscribeRequest_blocks_tag       4
#define geyser_SubscribeRequest_blocks_meta_tag  5
#define geyser_SubscribeRequest_commitment_tag   6
#define geyser_SubscribeRequest_accounts_data_slice_tag 7
#define geyser_SubscribeRequest_entry_tag        8
#define geyser_SubscribeRequest_ping_tag         9
#define geyser_SubscribeRequest_transactions_status_tag 10
#define geyser_SubscribeRequest_from_slot_tag    11
#define geyser_SubscribeDeshredRequest_deshred_transactions_tag 1
#define geyser_SubscribeDeshredRequest_ping_tag  2
#define geyser_SubscribeDeshredRequest_slots_tag 3
#define geyser_SubscribeDeshredRequest_DeshredTransactionsEntry_key_tag 1
#define geyser_SubscribeDeshredRequest_DeshredTransactionsEntry_value_tag 2
#define geyser_SubscribeDeshredRequest_SlotsEntry_key_tag 1
#define geyser_SubscribeDeshredRequest_SlotsEntry_value_tag 2
#define geyser_SubscribeUpdateAccountInfo_pubkey_tag 1
#define geyser_SubscribeUpdateAccountInfo_lamports_tag 2
#define geyser_SubscribeUpdateAccountInfo_owner_tag 3
#define geyser_SubscribeUpdateAccountInfo_executable_tag 4
#define geyser_SubscribeUpdateAccountInfo_rent_epoch_tag 5
#define geyser_SubscribeUpdateAccountInfo_data_tag 6
#define geyser_SubscribeUpdateAccountInfo_write_version_tag 7
#define geyser_SubscribeUpdateAccountInfo_txn_signature_tag 8
#define geyser_SubscribeUpdateAccount_account_tag 1
#define geyser_SubscribeUpdateAccount_slot_tag   2
#define geyser_SubscribeUpdateAccount_is_startup_tag 3
#define geyser_SubscribeUpdateAccount_bank_id_tag 4
#define geyser_SubscribeUpdateSlot_slot_tag      1
#define geyser_SubscribeUpdateSlot_parent_tag    2
#define geyser_SubscribeUpdateSlot_status_tag    3
#define geyser_SubscribeUpdateSlot_dead_error_tag 4
#define geyser_SubscribeUpdateSlot_bank_id_tag   5
#define geyser_SubscribeUpdateTransactionInfo_signature_tag 1
#define geyser_SubscribeUpdateTransactionInfo_is_vote_tag 2
#define geyser_SubscribeUpdateTransactionInfo_transaction_tag 3
#define geyser_SubscribeUpdateTransactionInfo_meta_tag 4
#define geyser_SubscribeUpdateTransactionInfo_index_tag 5
#define geyser_SubscribeUpdateTransaction_transaction_tag 1
#define geyser_SubscribeUpdateTransaction_slot_tag 2
#define geyser_SubscribeUpdateTransaction_bank_id_tag 3
#define geyser_SubscribeUpdateTransactionStatus_slot_tag 1
#define geyser_SubscribeUpdateTransactionStatus_signature_tag 2
#define geyser_SubscribeUpdateTransactionStatus_is_vote_tag 3
#define geyser_SubscribeUpdateTransactionStatus_index_tag 4
#define geyser_SubscribeUpdateTransactionStatus_err_tag 5
#define geyser_SubscribeUpdateTransactionStatus_bank_id_tag 6
#define geyser_SubscribeUpdateBlock_slot_tag     1
#define geyser_SubscribeUpdateBlock_blockhash_tag 2
#define geyser_SubscribeUpdateBlock_rewards_tag  3
#define geyser_SubscribeUpdateBlock_block_time_tag 4
#define geyser_SubscribeUpdateBlock_block_height_tag 5
#define geyser_SubscribeUpdateBlock_transactions_tag 6
#define geyser_SubscribeUpdateBlock_parent_slot_tag 7
#define geyser_SubscribeUpdateBlock_parent_blockhash_tag 8
#define geyser_SubscribeUpdateBlock_executed_transaction_count_tag 9
#define geyser_SubscribeUpdateBlock_updated_account_count_tag 10
#define geyser_SubscribeUpdateBlock_accounts_tag 11
#define geyser_SubscribeUpdateBlock_entries_count_tag 12
#define geyser_SubscribeUpdateBlock_entries_tag  13
#define geyser_SubscribeUpdateBlock_bank_id_tag  14
#define geyser_SubscribeUpdateBlockMeta_slot_tag 1
#define geyser_SubscribeUpdateBlockMeta_blockhash_tag 2
#define geyser_SubscribeUpdateBlockMeta_rewards_tag 3
#define geyser_SubscribeUpdateBlockMeta_block_time_tag 4
#define geyser_SubscribeUpdateBlockMeta_block_height_tag 5
#define geyser_SubscribeUpdateBlockMeta_parent_slot_tag 6
#define geyser_SubscribeUpdateBlockMeta_parent_blockhash_tag 7
#define geyser_SubscribeUpdateBlockMeta_executed_transaction_count_tag 8
#define geyser_SubscribeUpdateBlockMeta_entries_count_tag 9
#define geyser_SubscribeUpdateBlockMeta_bank_id_tag 10
#define geyser_SubscribeUpdateEntry_slot_tag     1
#define geyser_SubscribeUpdateEntry_index_tag    2
#define geyser_SubscribeUpdateEntry_num_hashes_tag 3
#define geyser_SubscribeUpdateEntry_hash_tag     4
#define geyser_SubscribeUpdateEntry_executed_transaction_count_tag 5
#define geyser_SubscribeUpdateEntry_starting_transaction_index_tag 6
#define geyser_SubscribeUpdateEntry_bank_id_tag  7
#define geyser_SubscribeUpdateDeshredTransactionInfo_signature_tag 1
#define geyser_SubscribeUpdateDeshredTransactionInfo_is_vote_tag 2
#define geyser_SubscribeUpdateDeshredTransactionInfo_transaction_tag 3
#define geyser_SubscribeUpdateDeshredTransactionInfo_loaded_writable_addresses_tag 4
#define geyser_SubscribeUpdateDeshredTransactionInfo_loaded_readonly_addresses_tag 5
#define geyser_SubscribeUpdateDeshredTransactionInfo_completed_data_set_starting_shred_index_tag 6
#define geyser_SubscribeUpdateDeshredTransactionInfo_completed_data_set_ending_shred_index_exclusive_tag 7
#define geyser_SubscribeUpdateDeshredTransaction_transaction_tag 1
#define geyser_SubscribeUpdateDeshredTransaction_slot_tag 2
#define geyser_SubscribeUpdatePong_id_tag        1
#define geyser_SubscribeUpdate_filters_tag       1
#define geyser_SubscribeUpdate_account_tag       2
#define geyser_SubscribeUpdate_slot_tag          3
#define geyser_SubscribeUpdate_transaction_tag   4
#define geyser_SubscribeUpdate_block_tag         5
#define geyser_SubscribeUpdate_ping_tag          6
#define geyser_SubscribeUpdate_block_meta_tag    7
#define geyser_SubscribeUpdate_entry_tag         8
#define geyser_SubscribeUpdate_pong_tag          9
#define geyser_SubscribeUpdate_transaction_status_tag 10
#define geyser_SubscribeUpdate_created_at_tag    11
#define geyser_SubscribeUpdateDeshred_filters_tag 1
#define geyser_SubscribeUpdateDeshred_deshred_transaction_tag 2
#define geyser_SubscribeUpdateDeshred_ping_tag   3
#define geyser_SubscribeUpdateDeshred_pong_tag   4
#define geyser_SubscribeUpdateDeshred_slot_tag   6
#define geyser_SubscribeUpdateDeshred_created_at_tag 5
#define geyser_GossipTopology_nodes_tag          1
#define geyser_SubscribeUpdateContactInfoNode_pubkey_tag 1
#define geyser_SubscribeUpdateContactInfoNode_wallclock_tag 2
#define geyser_SubscribeUpdateContactInfoNode_outset_tag 3
#define geyser_SubscribeUpdateContactInfoNode_shred_version_tag 4
#define geyser_SubscribeUpdateContactInfoNode_version_major_tag 5
#define geyser_SubscribeUpdateContactInfoNode_version_minor_tag 6
#define geyser_SubscribeUpdateContactInfoNode_version_patch_tag 7
#define geyser_SubscribeUpdateContactInfoNode_version_commit_tag 8
#define geyser_SubscribeUpdateContactInfoNode_version_feature_set_tag 9
#define geyser_SubscribeUpdateContactInfoNode_version_client_id_tag 10
#define geyser_SubscribeUpdateContactInfoNode_gossip_tag 11
#define geyser_SubscribeUpdateContactInfoNode_tpu_quic_tag 12
#define geyser_SubscribeUpdateContactInfoNode_tpu_forwards_quic_tag 13
#define geyser_SubscribeUpdateContactInfoNode_tpu_vote_udp_tag 14
#define geyser_SubscribeUpdateContactInfoNode_tpu_vote_quic_tag 15
#define geyser_SubscribeUpdateContactInfoNode_tvu_udp_tag 16
#define geyser_SubscribeUpdateContactInfoNode_tvu_quic_tag 17
#define geyser_SubscribeUpdateContactInfoNode_serve_repair_udp_tag 18
#define geyser_SubscribeUpdateContactInfoNode_serve_repair_quic_tag 19
#define geyser_SubscribeUpdateContactInfoNode_rpc_tag 20
#define geyser_SubscribeUpdateContactInfoNode_rpc_pubsub_tag 21
#define geyser_SubscribeUpdateContactInfoNode_alpenglow_tag 22
#define geyser_SubscribeUpdateContactInfoRemoved_pubkey_tag 1
#define geyser_SubscribeUpdateGossip_node_tag    1
#define geyser_SubscribeUpdateGossip_removed_tag 2
#define geyser_SubscribeUpdateGossip_ping_tag    3
#define geyser_SubscribeUpdateGossip_snapshot_tag 6
#define geyser_SubscribeUpdateGossip_created_at_tag 5
#define geyser_SubscribeUpdateGossip_seq_tag     7
#define geyser_SubscribeReplayInfoResponse_first_available_tag 1
#define geyser_PingRequest_count_tag             1
#define geyser_PongResponse_count_tag            1
#define geyser_GetLatestBlockhashRequest_commitment_tag 1
#define geyser_GetLatestBlockhashResponse_slot_tag 1
#define geyser_GetLatestBlockhashResponse_blockhash_tag 2
#define geyser_GetLatestBlockhashResponse_last_valid_block_height_tag 3
#define geyser_GetBlockHeightRequest_commitment_tag 1
#define geyser_GetBlockHeightResponse_block_height_tag 1
#define geyser_GetSlotRequest_commitment_tag     1
#define geyser_GetSlotResponse_slot_tag          1
#define geyser_GetVersionResponse_version_tag    1
#define geyser_IsBlockhashValidRequest_blockhash_tag 1
#define geyser_IsBlockhashValidRequest_commitment_tag 2
#define geyser_IsBlockhashValidResponse_slot_tag 1
#define geyser_IsBlockhashValidResponse_valid_tag 2

/* Struct field encoding specification for nanopb */
#define geyser_SubscribeRequest_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  accounts,          1) \
X(a, CALLBACK, REPEATED, MESSAGE,  slots,             2) \
X(a, CALLBACK, REPEATED, MESSAGE,  transactions,      3) \
X(a, CALLBACK, REPEATED, MESSAGE,  blocks,            4) \
X(a, CALLBACK, REPEATED, MESSAGE,  blocks_meta,       5) \
X(a, STATIC,   OPTIONAL, UENUM,    commitment,        6) \
X(a, CALLBACK, REPEATED, MESSAGE,  accounts_data_slice,   7) \
X(a, CALLBACK, REPEATED, MESSAGE,  entry,             8) \
X(a, STATIC,   OPTIONAL, MESSAGE,  ping,              9) \
X(a, CALLBACK, REPEATED, MESSAGE,  transactions_status,  10) \
X(a, STATIC,   OPTIONAL, UINT64,   from_slot,        11)
#define geyser_SubscribeRequest_CALLBACK pb_default_field_callback
#define geyser_SubscribeRequest_DEFAULT NULL
#define geyser_SubscribeRequest_accounts_MSGTYPE geyser_SubscribeRequest_AccountsEntry
#define geyser_SubscribeRequest_slots_MSGTYPE geyser_SubscribeRequest_SlotsEntry
#define geyser_SubscribeRequest_transactions_MSGTYPE geyser_SubscribeRequest_TransactionsEntry
#define geyser_SubscribeRequest_blocks_MSGTYPE geyser_SubscribeRequest_BlocksEntry
#define geyser_SubscribeRequest_blocks_meta_MSGTYPE geyser_SubscribeRequest_BlocksMetaEntry
#define geyser_SubscribeRequest_accounts_data_slice_MSGTYPE geyser_SubscribeRequestAccountsDataSlice
#define geyser_SubscribeRequest_entry_MSGTYPE geyser_SubscribeRequest_EntryEntry
#define geyser_SubscribeRequest_ping_MSGTYPE geyser_SubscribeRequestPing
#define geyser_SubscribeRequest_transactions_status_MSGTYPE geyser_SubscribeRequest_TransactionsStatusEntry

#define geyser_SubscribeRequest_AccountsEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define geyser_SubscribeRequest_AccountsEntry_CALLBACK pb_default_field_callback
#define geyser_SubscribeRequest_AccountsEntry_DEFAULT NULL
#define geyser_SubscribeRequest_AccountsEntry_value_MSGTYPE geyser_SubscribeRequestFilterAccounts

#define geyser_SubscribeRequest_SlotsEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define geyser_SubscribeRequest_SlotsEntry_CALLBACK pb_default_field_callback
#define geyser_SubscribeRequest_SlotsEntry_DEFAULT NULL
#define geyser_SubscribeRequest_SlotsEntry_value_MSGTYPE geyser_SubscribeRequestFilterSlots

#define geyser_SubscribeRequest_TransactionsEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define geyser_SubscribeRequest_TransactionsEntry_CALLBACK pb_default_field_callback
#define geyser_SubscribeRequest_TransactionsEntry_DEFAULT NULL
#define geyser_SubscribeRequest_TransactionsEntry_value_MSGTYPE geyser_SubscribeRequestFilterTransactions

#define geyser_SubscribeRequest_TransactionsStatusEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define geyser_SubscribeRequest_TransactionsStatusEntry_CALLBACK pb_default_field_callback
#define geyser_SubscribeRequest_TransactionsStatusEntry_DEFAULT NULL
#define geyser_SubscribeRequest_TransactionsStatusEntry_value_MSGTYPE geyser_SubscribeRequestFilterTransactions

#define geyser_SubscribeRequest_BlocksEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define geyser_SubscribeRequest_BlocksEntry_CALLBACK pb_default_field_callback
#define geyser_SubscribeRequest_BlocksEntry_DEFAULT NULL
#define geyser_SubscribeRequest_BlocksEntry_value_MSGTYPE geyser_SubscribeRequestFilterBlocks

#define geyser_SubscribeRequest_BlocksMetaEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define geyser_SubscribeRequest_BlocksMetaEntry_CALLBACK pb_default_field_callback
#define geyser_SubscribeRequest_BlocksMetaEntry_DEFAULT NULL
#define geyser_SubscribeRequest_BlocksMetaEntry_value_MSGTYPE geyser_SubscribeRequestFilterBlocksMeta

#define geyser_SubscribeRequest_EntryEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define geyser_SubscribeRequest_EntryEntry_CALLBACK pb_default_field_callback
#define geyser_SubscribeRequest_EntryEntry_DEFAULT NULL
#define geyser_SubscribeRequest_EntryEntry_value_MSGTYPE geyser_SubscribeRequestFilterEntry

#define geyser_CuckooFilter_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    data,              1) \
X(a, STATIC,   SINGULAR, UINT32,   bucket_count,      2) \
X(a, STATIC,   SINGULAR, UINT32,   entries_per_bucket,   3) \
X(a, STATIC,   SINGULAR, UINT32,   fingerprint_bits,   4) \
X(a, STATIC,   SINGULAR, UINT64,   hash_seed,         5) \
X(a, STATIC,   SINGULAR, UENUM,    hash_algorithm,    6)
#define geyser_CuckooFilter_CALLBACK pb_default_field_callback
#define geyser_CuckooFilter_DEFAULT NULL

#define geyser_SubscribeRequestFilterAccounts_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, STRING,   account,           2) \
X(a, CALLBACK, REPEATED, STRING,   owner,             3) \
X(a, CALLBACK, REPEATED, MESSAGE,  filters,           4) \
X(a, STATIC,   OPTIONAL, BOOL,     nonempty_txn_signature,   5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  cuckoo_accounts_filter,   6)
#define geyser_SubscribeRequestFilterAccounts_CALLBACK pb_default_field_callback
#define geyser_SubscribeRequestFilterAccounts_DEFAULT NULL
#define geyser_SubscribeRequestFilterAccounts_filters_MSGTYPE geyser_SubscribeRequestFilterAccountsFilter
#define geyser_SubscribeRequestFilterAccounts_cuckoo_accounts_filter_MSGTYPE geyser_CuckooFilter

#define geyser_SubscribeRequestFilterAccountsFilter_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (filter,memcmp,filter.memcmp),   1) \
X(a, STATIC,   ONEOF,    UINT64,   (filter,datasize,filter.datasize),   2) \
X(a, STATIC,   ONEOF,    BOOL,     (filter,token_account_state,filter.token_account_state),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (filter,lamports,filter.lamports),   4)
#define geyser_SubscribeRequestFilterAccountsFilter_CALLBACK NULL
#define geyser_SubscribeRequestFilterAccountsFilter_DEFAULT NULL
#define geyser_SubscribeRequestFilterAccountsFilter_filter_memcmp_MSGTYPE geyser_SubscribeRequestFilterAccountsFilterMemcmp
#define geyser_SubscribeRequestFilterAccountsFilter_filter_lamports_MSGTYPE geyser_SubscribeRequestFilterAccountsFilterLamports

#define geyser_SubscribeRequestFilterAccountsFilterMemcmp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   offset,            1) \
X(a, STATIC,   ONEOF,    BYTES,    (data,bytes,data.bytes),   2) \
X(a, STATIC,   ONEOF,    STRING,   (data,base58,data.base58),   3) \
X(a, STATIC,   ONEOF,    STRING,   (data,base64,data.base64),   4)
#define geyser_SubscribeRequestFilterAccountsFilterMemcmp_CALLBACK NULL
#define geyser_SubscribeRequestFilterAccountsFilterMemcmp_DEFAULT NULL

#define geyser_SubscribeRequestFilterAccountsFilterLamports_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    UINT64,   (cmp,eq,cmp.eq),   1) \
X(a, STATIC,   ONEOF,    UINT64,   (cmp,ne,cmp.ne),   2) \
X(a, STATIC,   ONEOF,    UINT64,   (cmp,lt,cmp.lt),   3) \
X(a, STATIC,   ONEOF,    UINT64,   (cmp,gt,cmp.gt),   4)
#define geyser_SubscribeRequestFilterAccountsFilterLamports_CALLBACK NULL
#define geyser_SubscribeRequestFilterAccountsFilterLamports_DEFAULT NULL

#define geyser_SubscribeRequestFilterSlots_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     filter_by_commitment,   1) \
X(a, STATIC,   OPTIONAL, BOOL,     interslot_updates,   2)
#define geyser_SubscribeRequestFilterSlots_CALLBACK NULL
#define geyser_SubscribeRequestFilterSlots_DEFAULT NULL

#define geyser_SubscribeRequestFilterTransactions_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     vote,              1) \
X(a, STATIC,   OPTIONAL, BOOL,     failed,            2) \
X(a, CALLBACK, REPEATED, STRING,   account_include,   3) \
X(a, CALLBACK, REPEATED, STRING,   account_exclude,   4) \
X(a, STATIC,   OPTIONAL, STRING,   signature,         5) \
X(a, CALLBACK, REPEATED, STRING,   account_required,   6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  cuckoo_account_include,   7) \
X(a, STATIC,   OPTIONAL, UENUM,    token_accounts,   30)
#define geyser_SubscribeRequestFilterTransactions_CALLBACK pb_default_field_callback
#define geyser_SubscribeRequestFilterTransactions_DEFAULT NULL
#define geyser_SubscribeRequestFilterTransactions_cuckoo_account_include_MSGTYPE geyser_CuckooFilter

#define geyser_SubscribeRequestFilterBlocks_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, STRING,   account_include,   1) \
X(a, STATIC,   OPTIONAL, BOOL,     include_transactions,   2) \
X(a, STATIC,   OPTIONAL, BOOL,     include_accounts,   3) \
X(a, STATIC,   OPTIONAL, BOOL,     include_entries,   4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  cuckoo_account_include,   5)
#define geyser_SubscribeRequestFilterBlocks_CALLBACK pb_default_field_callback
#define geyser_SubscribeRequestFilterBlocks_DEFAULT NULL
#define geyser_SubscribeRequestFilterBlocks_cuckoo_account_include_MSGTYPE geyser_CuckooFilter

#define geyser_SubscribeRequestFilterBlocksMeta_FIELDLIST(X, a) \

#define geyser_SubscribeRequestFilterBlocksMeta_CALLBACK NULL
#define geyser_SubscribeRequestFilterBlocksMeta_DEFAULT NULL

#define geyser_SubscribeRequestFilterEntry_FIELDLIST(X, a) \

#define geyser_SubscribeRequestFilterEntry_CALLBACK NULL
#define geyser_SubscribeRequestFilterEntry_DEFAULT NULL

#define geyser_SubscribeRequestFilterDeshredTransactions_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     vote,              1) \
X(a, CALLBACK, REPEATED, STRING,   account_include,   2) \
X(a, CALLBACK, REPEATED, STRING,   account_exclude,   3) \
X(a, CALLBACK, REPEATED, STRING,   account_required,   4)
#define geyser_SubscribeRequestFilterDeshredTransactions_CALLBACK pb_default_field_callback
#define geyser_SubscribeRequestFilterDeshredTransactions_DEFAULT NULL

#define geyser_SubscribeRequestAccountsDataSlice_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   offset,            1) \
X(a, STATIC,   SINGULAR, UINT64,   length,            2)
#define geyser_SubscribeRequestAccountsDataSlice_CALLBACK NULL
#define geyser_SubscribeRequestAccountsDataSlice_DEFAULT NULL

#define geyser_SubscribeRequestPing_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    id,                1)
#define geyser_SubscribeRequestPing_CALLBACK NULL
#define geyser_SubscribeRequestPing_DEFAULT NULL

#define geyser_SubscribeDeshredRequest_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  deshred_transactions,   1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  ping,              2) \
X(a, CALLBACK, REPEATED, MESSAGE,  slots,             3)
#define geyser_SubscribeDeshredRequest_CALLBACK pb_default_field_callback
#define geyser_SubscribeDeshredRequest_DEFAULT NULL
#define geyser_SubscribeDeshredRequest_deshred_transactions_MSGTYPE geyser_SubscribeDeshredRequest_DeshredTransactionsEntry
#define geyser_SubscribeDeshredRequest_ping_MSGTYPE geyser_SubscribeRequestPing
#define geyser_SubscribeDeshredRequest_slots_MSGTYPE geyser_SubscribeDeshredRequest_SlotsEntry

#define geyser_SubscribeDeshredRequest_DeshredTransactionsEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define geyser_SubscribeDeshredRequest_DeshredTransactionsEntry_CALLBACK pb_default_field_callback
#define geyser_SubscribeDeshredRequest_DeshredTransactionsEntry_DEFAULT NULL
#define geyser_SubscribeDeshredRequest_DeshredTransactionsEntry_value_MSGTYPE geyser_SubscribeRequestFilterDeshredTransactions

#define geyser_SubscribeDeshredRequest_SlotsEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define geyser_SubscribeDeshredRequest_SlotsEntry_CALLBACK pb_default_field_callback
#define geyser_SubscribeDeshredRequest_SlotsEntry_DEFAULT NULL
#define geyser_SubscribeDeshredRequest_SlotsEntry_value_MSGTYPE geyser_SubscribeRequestFilterSlots

#define geyser_SubscribeUpdate_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, STRING,   filters,           1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (update_oneof,account,update_oneof.account),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (update_oneof,slot,update_oneof.slot),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (update_oneof,transaction,update_oneof.transaction),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (update_oneof,block,update_oneof.block),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (update_oneof,ping,update_oneof.ping),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (update_oneof,block_meta,update_oneof.block_meta),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (update_oneof,entry,update_oneof.entry),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (update_oneof,pong,update_oneof.pong),   9) \
X(a, STATIC,   ONEOF,    MESSAGE,  (update_oneof,transaction_status,update_oneof.transaction_status),  10) \
X(a, STATIC,   OPTIONAL, MESSAGE,  created_at,       11)
#define geyser_SubscribeUpdate_CALLBACK pb_default_field_callback
#define geyser_SubscribeUpdate_DEFAULT NULL
#define geyser_SubscribeUpdate_update_oneof_account_MSGTYPE geyser_SubscribeUpdateAccount
#define geyser_SubscribeUpdate_update_oneof_slot_MSGTYPE geyser_SubscribeUpdateSlot
#define geyser_SubscribeUpdate_update_oneof_transaction_MSGTYPE geyser_SubscribeUpdateTransaction
#define geyser_SubscribeUpdate_update_oneof_block_MSGTYPE geyser_SubscribeUpdateBlock
#define geyser_SubscribeUpdate_update_oneof_ping_MSGTYPE geyser_SubscribeUpdatePing
#define geyser_SubscribeUpdate_update_oneof_block_meta_MSGTYPE geyser_SubscribeUpdateBlockMeta
#define geyser_SubscribeUpdate_update_oneof_entry_MSGTYPE geyser_SubscribeUpdateEntry
#define geyser_SubscribeUpdate_update_oneof_pong_MSGTYPE geyser_SubscribeUpdatePong
#define geyser_SubscribeUpdate_update_oneof_transaction_status_MSGTYPE geyser_SubscribeUpdateTransactionStatus
#define geyser_SubscribeUpdate_created_at_MSGTYPE google_protobuf_Timestamp

#define geyser_SubscribeUpdateAccount_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  account,           1) \
X(a, STATIC,   SINGULAR, UINT64,   slot,              2) \
X(a, STATIC,   SINGULAR, BOOL,     is_startup,        3) \
X(a, STATIC,   OPTIONAL, UINT64,   bank_id,           4)
#define geyser_SubscribeUpdateAccount_CALLBACK NULL
#define geyser_SubscribeUpdateAccount_DEFAULT NULL
#define geyser_SubscribeUpdateAccount_account_MSGTYPE geyser_SubscribeUpdateAccountInfo

#define geyser_SubscribeUpdateAccountInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    pubkey,            1) \
X(a, STATIC,   SINGULAR, UINT64,   lamports,          2) \
X(a, STATIC,   SINGULAR, BYTES,    owner,             3) \
X(a, STATIC,   SINGULAR, BOOL,     executable,        4) \
X(a, STATIC,   SINGULAR, UINT64,   rent_epoch,        5) \
X(a, CALLBACK, SINGULAR, BYTES,    data,              6) \
X(a, STATIC,   SINGULAR, UINT64,   write_version,     7) \
X(a, STATIC,   OPTIONAL, BYTES,    txn_signature,     8)
#define geyser_SubscribeUpdateAccountInfo_CALLBACK pb_default_field_callback
#define geyser_SubscribeUpdateAccountInfo_DEFAULT NULL

#define geyser_SubscribeUpdateSlot_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   slot,              1) \
X(a, STATIC,   OPTIONAL, UINT64,   parent,            2) \
X(a, STATIC,   SINGULAR, UENUM,    status,            3) \
X(a, STATIC,   OPTIONAL, STRING,   dead_error,        4) \
X(a, STATIC,   OPTIONAL, UINT64,   bank_id,           5)
#define geyser_SubscribeUpdateSlot_CALLBACK NULL
#define geyser_SubscribeUpdateSlot_DEFAULT NULL

#define geyser_SubscribeUpdateTransaction_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  transaction,       1) \
X(a, STATIC,   SINGULAR, UINT64,   slot,              2) \
X(a, STATIC,   SINGULAR, UINT64,   bank_id,           3)
#define geyser_SubscribeUpdateTransaction_CALLBACK NULL
#define geyser_SubscribeUpdateTransaction_DEFAULT NULL
#define geyser_SubscribeUpdateTransaction_transaction_MSGTYPE geyser_SubscribeUpdateTransactionInfo

#define geyser_SubscribeUpdateTransactionInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    signature,         1) \
X(a, STATIC,   SINGULAR, BOOL,     is_vote,           2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  transaction,       3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  meta,              4) \
X(a, STATIC,   SINGULAR, UINT64,   index,             5)
#define geyser_SubscribeUpdateTransactionInfo_CALLBACK NULL
#define geyser_SubscribeUpdateTransactionInfo_DEFAULT NULL
#define geyser_SubscribeUpdateTransactionInfo_transaction_MSGTYPE solana_storage_ConfirmedBlock_Transaction
#define geyser_SubscribeUpdateTransactionInfo_meta_MSGTYPE solana_storage_ConfirmedBlock_TransactionStatusMeta

#define geyser_SubscribeUpdateTransactionStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   slot,              1) \
X(a, STATIC,   SINGULAR, BYTES,    signature,         2) \
X(a, STATIC,   SINGULAR, BOOL,     is_vote,           3) \
X(a, STATIC,   SINGULAR, UINT64,   index,             4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  err,               5) \
X(a, STATIC,   SINGULAR, UINT64,   bank_id,           6)
#define geyser_SubscribeUpdateTransactionStatus_CALLBACK NULL
#define geyser_SubscribeUpdateTransactionStatus_DEFAULT NULL
#define geyser_SubscribeUpdateTransactionStatus_err_MSGTYPE solana_storage_ConfirmedBlock_TransactionError

#define geyser_SubscribeUpdateBlock_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   slot,              1) \
X(a, STATIC,   SINGULAR, STRING,   blockhash,         2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  rewards,           3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  block_time,        4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  block_height,      5) \
X(a, CALLBACK, REPEATED, MESSAGE,  transactions,      6) \
X(a, STATIC,   SINGULAR, UINT64,   parent_slot,       7) \
X(a, STATIC,   SINGULAR, STRING,   parent_blockhash,   8) \
X(a, STATIC,   SINGULAR, UINT64,   executed_transaction_count,   9) \
X(a, STATIC,   SINGULAR, UINT64,   updated_account_count,  10) \
X(a, CALLBACK, REPEATED, MESSAGE,  accounts,         11) \
X(a, STATIC,   SINGULAR, UINT64,   entries_count,    12) \
X(a, CALLBACK, REPEATED, MESSAGE,  entries,          13) \
X(a, STATIC,   SINGULAR, UINT64,   bank_id,          14)
#define geyser_SubscribeUpdateBlock_CALLBACK pb_default_field_callback
#define geyser_SubscribeUpdateBlock_DEFAULT NULL
#define geyser_SubscribeUpdateBlock_rewards_MSGTYPE solana_storage_ConfirmedBlock_Rewards
#define geyser_SubscribeUpdateBlock_block_time_MSGTYPE solana_storage_ConfirmedBlock_UnixTimestamp
#define geyser_SubscribeUpdateBlock_block_height_MSGTYPE solana_storage_ConfirmedBlock_BlockHeight
#define geyser_SubscribeUpdateBlock_transactions_MSGTYPE geyser_SubscribeUpdateTransactionInfo
#define geyser_SubscribeUpdateBlock_accounts_MSGTYPE geyser_SubscribeUpdateAccountInfo
#define geyser_SubscribeUpdateBlock_entries_MSGTYPE geyser_SubscribeUpdateEntry

#define geyser_SubscribeUpdateBlockMeta_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   slot,              1) \
X(a, STATIC,   SINGULAR, STRING,   blockhash,         2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  rewards,           3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  block_time,        4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  block_height,      5) \
X(a, STATIC,   SINGULAR, UINT64,   parent_slot,       6) \
X(a, STATIC,   SINGULAR, STRING,   parent_blockhash,   7) \
X(a, STATIC,   SINGULAR, UINT64,   executed_transaction_count,   8) \
X(a, STATIC,   SINGULAR, UINT64,   entries_count,     9) \
X(a, STATIC,   SINGULAR, UINT64,   bank_id,          10)
#define geyser_SubscribeUpdateBlockMeta_CALLBACK NULL
#define geyser_SubscribeUpdateBlockMeta_DEFAULT NULL
#define geyser_SubscribeUpdateBlockMeta_rewards_MSGTYPE solana_storage_ConfirmedBlock_Rewards
#define geyser_SubscribeUpdateBlockMeta_block_time_MSGTYPE solana_storage_ConfirmedBlock_UnixTimestamp
#define geyser_SubscribeUpdateBlockMeta_block_height_MSGTYPE solana_storage_ConfirmedBlock_BlockHeight

#define geyser_SubscribeUpdateEntry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   slot,              1) \
X(a, STATIC,   SINGULAR, UINT64,   index,             2) \
X(a, STATIC,   SINGULAR, UINT64,   num_hashes,        3) \
X(a, STATIC,   SINGULAR, BYTES,    hash,              4) \
X(a, STATIC,   SINGULAR, UINT64,   executed_transaction_count,   5) \
X(a, STATIC,   SINGULAR, UINT64,   starting_transaction_index,   6) \
X(a, STATIC,   SINGULAR, UINT64,   bank_id,           7)
#define geyser_SubscribeUpdateEntry_CALLBACK NULL
#define geyser_SubscribeUpdateEntry_DEFAULT NULL

#define geyser_SubscribeUpdateDeshredTransaction_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  transaction,       1) \
X(a, STATIC,   SINGULAR, UINT64,   slot,              2)
#define geyser_SubscribeUpdateDeshredTransaction_CALLBACK NULL
#define geyser_SubscribeUpdateDeshredTransaction_DEFAULT NULL
#define geyser_SubscribeUpdateDeshredTransaction_transaction_MSGTYPE geyser_SubscribeUpdateDeshredTransactionInfo

#define geyser_SubscribeUpdateDeshredTransactionInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    signature,         1) \
X(a, STATIC,   SINGULAR, BOOL,     is_vote,           2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  transaction,       3) \
X(a, CALLBACK, REPEATED, BYTES,    loaded_writable_addresses,   4) \
X(a, CALLBACK, REPEATED, BYTES,    loaded_readonly_addresses,   5) \
X(a, STATIC,   SINGULAR, UINT32,   completed_data_set_starting_shred_index,   6) \
X(a, STATIC,   SINGULAR, UINT32,   completed_data_set_ending_shred_index_exclusive,   7)
#define geyser_SubscribeUpdateDeshredTransactionInfo_CALLBACK pb_default_field_callback
#define geyser_SubscribeUpdateDeshredTransactionInfo_DEFAULT NULL
#define geyser_SubscribeUpdateDeshredTransactionInfo_transaction_MSGTYPE solana_storage_ConfirmedBlock_Transaction

#define geyser_SubscribeUpdatePing_FIELDLIST(X, a) \

#define geyser_SubscribeUpdatePing_CALLBACK NULL
#define geyser_SubscribeUpdatePing_DEFAULT NULL

#define geyser_SubscribeUpdatePong_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    id,                1)
#define geyser_SubscribeUpdatePong_CALLBACK NULL
#define geyser_SubscribeUpdatePong_DEFAULT NULL

#define geyser_SubscribeUpdateDeshred_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, STRING,   filters,           1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (update_oneof,deshred_transaction,update_oneof.deshred_transaction),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (update_oneof,ping,update_oneof.ping),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (update_oneof,pong,update_oneof.pong),   4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  created_at,        5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (update_oneof,slot,update_oneof.slot),   6)
#define geyser_SubscribeUpdateDeshred_CALLBACK pb_default_field_callback
#define geyser_SubscribeUpdateDeshred_DEFAULT NULL
#define geyser_SubscribeUpdateDeshred_update_oneof_deshred_transaction_MSGTYPE geyser_SubscribeUpdateDeshredTransaction
#define geyser_SubscribeUpdateDeshred_update_oneof_ping_MSGTYPE geyser_SubscribeUpdatePing
#define geyser_SubscribeUpdateDeshred_update_oneof_pong_MSGTYPE geyser_SubscribeUpdatePong
#define geyser_SubscribeUpdateDeshred_created_at_MSGTYPE google_protobuf_Timestamp
#define geyser_SubscribeUpdateDeshred_update_oneof_slot_MSGTYPE geyser_SubscribeUpdateSlot

#define geyser_SubscribeGossipRequest_FIELDLIST(X, a) \

#define geyser_SubscribeGossipRequest_CALLBACK NULL
#define geyser_SubscribeGossipRequest_DEFAULT NULL

#define geyser_SubscribeUpdateGossip_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (update_oneof,node,update_oneof.node),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (update_oneof,removed,update_oneof.removed),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (update_oneof,ping,update_oneof.ping),   3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  created_at,        5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (update_oneof,snapshot,update_oneof.snapshot),   6) \
X(a, STATIC,   SINGULAR, UINT64,   seq,               7)
#define geyser_SubscribeUpdateGossip_CALLBACK NULL
#define geyser_SubscribeUpdateGossip_DEFAULT NULL
#define geyser_SubscribeUpdateGossip_update_oneof_node_MSGTYPE geyser_SubscribeUpdateContactInfoNode
#define geyser_SubscribeUpdateGossip_update_oneof_removed_MSGTYPE geyser_SubscribeUpdateContactInfoRemoved
#define geyser_SubscribeUpdateGossip_update_oneof_ping_MSGTYPE geyser_SubscribeUpdatePing
#define geyser_SubscribeUpdateGossip_created_at_MSGTYPE google_protobuf_Timestamp
#define geyser_SubscribeUpdateGossip_update_oneof_snapshot_MSGTYPE geyser_GossipTopology

#define geyser_GossipTopology_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  nodes,             1)
#define geyser_GossipTopology_CALLBACK pb_default_field_callback
#define geyser_GossipTopology_DEFAULT NULL
#define geyser_GossipTopology_nodes_MSGTYPE geyser_SubscribeUpdateContactInfoNode

#define geyser_SubscribeUpdateContactInfoNode_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    pubkey,            1) \
X(a, STATIC,   SINGULAR, UINT64,   wallclock,         2) \
X(a, STATIC,   SINGULAR, UINT64,   outset,            3) \
X(a, STATIC,   SINGULAR, UINT32,   shred_version,     4) \
X(a, STATIC,   SINGULAR, UINT32,   version_major,     5) \
X(a, STATIC,   SINGULAR, UINT32,   version_minor,     6) \
X(a, STATIC,   SINGULAR, UINT32,   version_patch,     7) \
X(a, STATIC,   SINGULAR, UINT32,   version_commit,    8) \
X(a, STATIC,   SINGULAR, UINT32,   version_feature_set,   9) \
X(a, STATIC,   SINGULAR, UINT32,   version_client_id,  10) \
X(a, STATIC,   OPTIONAL, STRING,   gossip,           11) \
X(a, STATIC,   OPTIONAL, STRING,   tpu_quic,         12) \
X(a, STATIC,   OPTIONAL, STRING,   tpu_forwards_quic,  13) \
X(a, STATIC,   OPTIONAL, STRING,   tpu_vote_udp,     14) \
X(a, STATIC,   OPTIONAL, STRING,   tpu_vote_quic,    15) \
X(a, STATIC,   OPTIONAL, STRING,   tvu_udp,          16) \
X(a, STATIC,   OPTIONAL, STRING,   tvu_quic,         17) \
X(a, STATIC,   OPTIONAL, STRING,   serve_repair_udp,  18) \
X(a, STATIC,   OPTIONAL, STRING,   serve_repair_quic,  19) \
X(a, STATIC,   OPTIONAL, STRING,   rpc,              20) \
X(a, STATIC,   OPTIONAL, STRING,   rpc_pubsub,       21) \
X(a, STATIC,   OPTIONAL, STRING,   alpenglow,        22)
#define geyser_SubscribeUpdateContactInfoNode_CALLBACK NULL
#define geyser_SubscribeUpdateContactInfoNode_DEFAULT NULL

#define geyser_SubscribeUpdateContactInfoRemoved_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    pubkey,            1)
#define geyser_SubscribeUpdateContactInfoRemoved_CALLBACK NULL
#define geyser_SubscribeUpdateContactInfoRemoved_DEFAULT NULL

#define geyser_SubscribeReplayInfoRequest_FIELDLIST(X, a) \

#define geyser_SubscribeReplayInfoRequest_CALLBACK NULL
#define geyser_SubscribeReplayInfoRequest_DEFAULT NULL

#define geyser_SubscribeReplayInfoResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT64,   first_available,   1)
#define geyser_SubscribeReplayInfoResponse_CALLBACK NULL
#define geyser_SubscribeReplayInfoResponse_DEFAULT NULL

#define geyser_PingRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    count,             1)
#define geyser_PingRequest_CALLBACK NULL
#define geyser_PingRequest_DEFAULT NULL

#define geyser_PongResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    count,             1)
#define geyser_PongResponse_CALLBACK NULL
#define geyser_PongResponse_DEFAULT NULL

#define geyser_GetLatestBlockhashRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    commitment,        1)
#define geyser_GetLatestBlockhashRequest_CALLBACK NULL
#define geyser_GetLatestBlockhashRequest_DEFAULT NULL

#define geyser_GetLatestBlockhashResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   slot,              1) \
X(a, STATIC,   SINGULAR, STRING,   blockhash,         2) \
X(a, STATIC,   SINGULAR, UINT64,   last_valid_block_height,   3)
#define geyser_GetLatestBlockhashResponse_CALLBACK NULL
#define geyser_GetLatestBlockhashResponse_DEFAULT NULL

#define geyser_GetBlockHeightRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    commitment,        1)
#define geyser_GetBlockHeightRequest_CALLBACK NULL
#define geyser_GetBlockHeightRequest_DEFAULT NULL

#define geyser_GetBlockHeightResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   block_height,      1)
#define geyser_GetBlockHeightResponse_CALLBACK NULL
#define geyser_GetBlockHeightResponse_DEFAULT NULL

#define geyser_GetSlotRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    commitment,        1)
#define geyser_GetSlotRequest_CALLBACK NULL
#define geyser_GetSlotRequest_DEFAULT NULL

#define geyser_GetSlotResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   slot,              1)
#define geyser_GetSlotResponse_CALLBACK NULL
#define geyser_GetSlotResponse_DEFAULT NULL

#define geyser_GetVersionRequest_FIELDLIST(X, a) \

#define geyser_GetVersionRequest_CALLBACK NULL
#define geyser_GetVersionRequest_DEFAULT NULL

#define geyser_GetVersionResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   version,           1)
#define geyser_GetVersionResponse_CALLBACK NULL
#define geyser_GetVersionResponse_DEFAULT NULL

#define geyser_IsBlockhashValidRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   blockhash,         1) \
X(a, STATIC,   OPTIONAL, UENUM,    commitment,        2)
#define geyser_IsBlockhashValidRequest_CALLBACK NULL
#define geyser_IsBlockhashValidRequest_DEFAULT NULL

#define geyser_IsBlockhashValidResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   slot,              1) \
X(a, STATIC,   SINGULAR, BOOL,     valid,             2)
#define geyser_IsBlockhashValidResponse_CALLBACK NULL
#define geyser_IsBlockhashValidResponse_DEFAULT NULL

extern const pb_msgdesc_t geyser_SubscribeRequest_msg;
extern const pb_msgdesc_t geyser_SubscribeRequest_AccountsEntry_msg;
extern const pb_msgdesc_t geyser_SubscribeRequest_SlotsEntry_msg;
extern const pb_msgdesc_t geyser_SubscribeRequest_TransactionsEntry_msg;
extern const pb_msgdesc_t geyser_SubscribeRequest_TransactionsStatusEntry_msg;
extern const pb_msgdesc_t geyser_SubscribeRequest_BlocksEntry_msg;
extern const pb_msgdesc_t geyser_SubscribeRequest_BlocksMetaEntry_msg;
extern const pb_msgdesc_t geyser_SubscribeRequest_EntryEntry_msg;
extern const pb_msgdesc_t geyser_CuckooFilter_msg;
extern const pb_msgdesc_t geyser_SubscribeRequestFilterAccounts_msg;
extern const pb_msgdesc_t geyser_SubscribeRequestFilterAccountsFilter_msg;
extern const pb_msgdesc_t geyser_SubscribeRequestFilterAccountsFilterMemcmp_msg;
extern const pb_msgdesc_t geyser_SubscribeRequestFilterAccountsFilterLamports_msg;
extern const pb_msgdesc_t geyser_SubscribeRequestFilterSlots_msg;
extern const pb_msgdesc_t geyser_SubscribeRequestFilterTransactions_msg;
extern const pb_msgdesc_t geyser_SubscribeRequestFilterBlocks_msg;
extern const pb_msgdesc_t geyser_SubscribeRequestFilterBlocksMeta_msg;
extern const pb_msgdesc_t geyser_SubscribeRequestFilterEntry_msg;
extern const pb_msgdesc_t geyser_SubscribeRequestFilterDeshredTransactions_msg;
extern const pb_msgdesc_t geyser_SubscribeRequestAccountsDataSlice_msg;
extern const pb_msgdesc_t geyser_SubscribeRequestPing_msg;
extern const pb_msgdesc_t geyser_SubscribeDeshredRequest_msg;
extern const pb_msgdesc_t geyser_SubscribeDeshredRequest_DeshredTransactionsEntry_msg;
extern const pb_msgdesc_t geyser_SubscribeDeshredRequest_SlotsEntry_msg;
extern const pb_msgdesc_t geyser_SubscribeUpdate_msg;
extern const pb_msgdesc_t geyser_SubscribeUpdateAccount_msg;
extern const pb_msgdesc_t geyser_SubscribeUpdateAccountInfo_msg;
extern const pb_msgdesc_t geyser_SubscribeUpdateSlot_msg;
extern const pb_msgdesc_t geyser_SubscribeUpdateTransaction_msg;
extern const pb_msgdesc_t geyser_SubscribeUpdateTransactionInfo_msg;
extern const pb_msgdesc_t geyser_SubscribeUpdateTransactionStatus_msg;
extern const pb_msgdesc_t geyser_SubscribeUpdateBlock_msg;
extern const pb_msgdesc_t geyser_SubscribeUpdateBlockMeta_msg;
extern const pb_msgdesc_t geyser_SubscribeUpdateEntry_msg;
extern const pb_msgdesc_t geyser_SubscribeUpdateDeshredTransaction_msg;
extern const pb_msgdesc_t geyser_SubscribeUpdateDeshredTransactionInfo_msg;
extern const pb_msgdesc_t geyser_SubscribeUpdatePing_msg;
extern const pb_msgdesc_t geyser_SubscribeUpdatePong_msg;
extern const pb_msgdesc_t geyser_SubscribeUpdateDeshred_msg;
extern const pb_msgdesc_t geyser_SubscribeGossipRequest_msg;
extern const pb_msgdesc_t geyser_SubscribeUpdateGossip_msg;
extern const pb_msgdesc_t geyser_GossipTopology_msg;
extern const pb_msgdesc_t geyser_SubscribeUpdateContactInfoNode_msg;
extern const pb_msgdesc_t geyser_SubscribeUpdateContactInfoRemoved_msg;
extern const pb_msgdesc_t geyser_SubscribeReplayInfoRequest_msg;
extern const pb_msgdesc_t geyser_SubscribeReplayInfoResponse_msg;
extern const pb_msgdesc_t geyser_PingRequest_msg;
extern const pb_msgdesc_t geyser_PongResponse_msg;
extern const pb_msgdesc_t geyser_GetLatestBlockhashRequest_msg;
extern const pb_msgdesc_t geyser_GetLatestBlockhashResponse_msg;
extern const pb_msgdesc_t geyser_GetBlockHeightRequest_msg;
extern const pb_msgdesc_t geyser_GetBlockHeightResponse_msg;
extern const pb_msgdesc_t geyser_GetSlotRequest_msg;
extern const pb_msgdesc_t geyser_GetSlotResponse_msg;
extern const pb_msgdesc_t geyser_GetVersionRequest_msg;
extern const pb_msgdesc_t geyser_GetVersionResponse_msg;
extern const pb_msgdesc_t geyser_IsBlockhashValidRequest_msg;
extern const pb_msgdesc_t geyser_IsBlockhashValidResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define geyser_SubscribeRequest_fields &geyser_SubscribeRequest_msg
#define geyser_SubscribeRequest_AccountsEntry_fields &geyser_SubscribeRequest_AccountsEntry_msg
#define geyser_SubscribeRequest_SlotsEntry_fields &geyser_SubscribeRequest_SlotsEntry_msg
#define geyser_SubscribeRequest_TransactionsEntry_fields &geyser_SubscribeRequest_TransactionsEntry_msg
#define geyser_SubscribeRequest_TransactionsStatusEntry_fields &geyser_SubscribeRequest_TransactionsStatusEntry_msg
#define geyser_SubscribeRequest_BlocksEntry_fields &geyser_SubscribeRequest_BlocksEntry_msg
#define geyser_SubscribeRequest_BlocksMetaEntry_fields &geyser_SubscribeRequest_BlocksMetaEntry_msg
#define geyser_SubscribeRequest_EntryEntry_fields &geyser_SubscribeRequest_EntryEntry_msg
#define geyser_CuckooFilter_fields &geyser_CuckooFilter_msg
#define geyser_SubscribeRequestFilterAccounts_fields &geyser_SubscribeRequestFilterAccounts_msg
#define geyser_SubscribeRequestFilterAccountsFilter_fields &geyser_SubscribeRequestFilterAccountsFilter_msg
#define geyser_SubscribeRequestFilterAccountsFilterMemcmp_fields &geyser_SubscribeRequestFilterAccountsFilterMemcmp_msg
#define geyser_SubscribeRequestFilterAccountsFilterLamports_fields &geyser_SubscribeRequestFilterAccountsFilterLamports_msg
#define geyser_SubscribeRequestFilterSlots_fields &geyser_SubscribeRequestFilterSlots_msg
#define geyser_SubscribeRequestFilterTransactions_fields &geyser_SubscribeRequestFilterTransactions_msg
#define geyser_SubscribeRequestFilterBlocks_fields &geyser_SubscribeRequestFilterBlocks_msg
#define geyser_SubscribeRequestFilterBlocksMeta_fields &geyser_SubscribeRequestFilterBlocksMeta_msg
#define geyser_SubscribeRequestFilterEntry_fields &geyser_SubscribeRequestFilterEntry_msg
#define geyser_SubscribeRequestFilterDeshredTransactions_fields &geyser_SubscribeRequestFilterDeshredTransactions_msg
#define geyser_SubscribeRequestAccountsDataSlice_fields &geyser_SubscribeRequestAccountsDataSlice_msg
#define geyser_SubscribeRequestPing_fields &geyser_SubscribeRequestPing_msg
#define geyser_SubscribeDeshredRequest_fields &geyser_SubscribeDeshredRequest_msg
#define geyser_SubscribeDeshredRequest_DeshredTransactionsEntry_fields &geyser_SubscribeDeshredRequest_DeshredTransactionsEntry_msg
#define geyser_SubscribeDeshredRequest_SlotsEntry_fields &geyser_SubscribeDeshredRequest_SlotsEntry_msg
#define geyser_SubscribeUpdate_fields &geyser_SubscribeUpdate_msg
#define geyser_SubscribeUpdateAccount_fields &geyser_SubscribeUpdateAccount_msg
#define geyser_SubscribeUpdateAccountInfo_fields &geyser_SubscribeUpdateAccountInfo_msg
#define geyser_SubscribeUpdateSlot_fields &geyser_SubscribeUpdateSlot_msg
#define geyser_SubscribeUpdateTransaction_fields &geyser_SubscribeUpdateTransaction_msg
#define geyser_SubscribeUpdateTransactionInfo_fields &geyser_SubscribeUpdateTransactionInfo_msg
#define geyser_SubscribeUpdateTransactionStatus_fields &geyser_SubscribeUpdateTransactionStatus_msg
#define geyser_SubscribeUpdateBlock_fields &geyser_SubscribeUpdateBlock_msg
#define geyser_SubscribeUpdateBlockMeta_fields &geyser_SubscribeUpdateBlockMeta_msg
#define geyser_SubscribeUpdateEntry_fields &geyser_SubscribeUpdateEntry_msg
#define geyser_SubscribeUpdateDeshredTransaction_fields &geyser_SubscribeUpdateDeshredTransaction_msg
#define geyser_SubscribeUpdateDeshredTransactionInfo_fields &geyser_SubscribeUpdateDeshredTransactionInfo_msg
#define geyser_SubscribeUpdatePing_fields &geyser_SubscribeUpdatePing_msg
#define geyser_SubscribeUpdatePong_fields &geyser_SubscribeUpdatePong_msg
#define geyser_SubscribeUpdateDeshred_fields &geyser_SubscribeUpdateDeshred_msg
#define geyser_SubscribeGossipRequest_fields &geyser_SubscribeGossipRequest_msg
#define geyser_SubscribeUpdateGossip_fields &geyser_SubscribeUpdateGossip_msg
#define geyser_GossipTopology_fields &geyser_GossipTopology_msg
#define geyser_SubscribeUpdateContactInfoNode_fields &geyser_SubscribeUpdateContactInfoNode_msg
#define geyser_SubscribeUpdateContactInfoRemoved_fields &geyser_SubscribeUpdateContactInfoRemoved_msg
#define geyser_SubscribeReplayInfoRequest_fields &geyser_SubscribeReplayInfoRequest_msg
#define geyser_SubscribeReplayInfoResponse_fields &geyser_SubscribeReplayInfoResponse_msg
#define geyser_PingRequest_fields &geyser_PingRequest_msg
#define geyser_PongResponse_fields &geyser_PongResponse_msg
#define geyser_GetLatestBlockhashRequest_fields &geyser_GetLatestBlockhashRequest_msg
#define geyser_GetLatestBlockhashResponse_fields &geyser_GetLatestBlockhashResponse_msg
#define geyser_GetBlockHeightRequest_fields &geyser_GetBlockHeightRequest_msg
#define geyser_GetBlockHeightResponse_fields &geyser_GetBlockHeightResponse_msg
#define geyser_GetSlotRequest_fields &geyser_GetSlotRequest_msg
#define geyser_GetSlotResponse_fields &geyser_GetSlotResponse_msg
#define geyser_GetVersionRequest_fields &geyser_GetVersionRequest_msg
#define geyser_GetVersionResponse_fields &geyser_GetVersionResponse_msg
#define geyser_IsBlockhashValidRequest_fields &geyser_IsBlockhashValidRequest_msg
#define geyser_IsBlockhashValidResponse_fields &geyser_IsBlockhashValidResponse_msg

/* Maximum encoded size of messages (where known) */
/* geyser_SubscribeRequest_size depends on runtime parameters */
/* geyser_SubscribeRequest_AccountsEntry_size depends on runtime parameters */
/* geyser_SubscribeRequest_SlotsEntry_size depends on runtime parameters */
/* geyser_SubscribeRequest_TransactionsEntry_size depends on runtime parameters */
/* geyser_SubscribeRequest_TransactionsStatusEntry_size depends on runtime parameters */
/* geyser_SubscribeRequest_BlocksEntry_size depends on runtime parameters */
/* geyser_SubscribeRequest_BlocksMetaEntry_size depends on runtime parameters */
/* geyser_SubscribeRequest_EntryEntry_size depends on runtime parameters */
/* geyser_CuckooFilter_size depends on runtime parameters */
/* geyser_SubscribeRequestFilterAccounts_size depends on runtime parameters */
/* geyser_SubscribeRequestFilterTransactions_size depends on runtime parameters */
/* geyser_SubscribeRequestFilterBlocks_size depends on runtime parameters */
/* geyser_SubscribeRequestFilterDeshredTransactions_size depends on runtime parameters */
/* geyser_SubscribeDeshredRequest_size depends on runtime parameters */
/* geyser_SubscribeDeshredRequest_DeshredTransactionsEntry_size depends on runtime parameters */
/* geyser_SubscribeDeshredRequest_SlotsEntry_size depends on runtime parameters */
/* geyser_SubscribeUpdate_size depends on runtime parameters */
/* geyser_SubscribeUpdateAccount_size depends on runtime parameters */
/* geyser_SubscribeUpdateAccountInfo_size depends on runtime parameters */
/* geyser_SubscribeUpdateBlock_size depends on runtime parameters */
/* geyser_SubscribeUpdateDeshredTransaction_size depends on runtime parameters */
/* geyser_SubscribeUpdateDeshredTransactionInfo_size depends on runtime parameters */
/* geyser_SubscribeUpdateDeshred_size depends on runtime parameters */
/* geyser_SubscribeUpdateGossip_size depends on runtime parameters */
/* geyser_GossipTopology_size depends on runtime parameters */
#define GEYSER_GEYSER_PB_H_MAX_SIZE              geyser_SubscribeUpdateContactInfoNode_size
#define geyser_GetBlockHeightRequest_size        2
#define geyser_GetBlockHeightResponse_size       11
#define geyser_GetLatestBlockhashRequest_size    2
#define geyser_GetLatestBlockhashResponse_size   68
#define geyser_GetSlotRequest_size               2
#define geyser_GetSlotResponse_size              11
#define geyser_GetVersionRequest_size            0
#define geyser_GetVersionResponse_size           642
#define geyser_IsBlockhashValidRequest_size      48
#define geyser_IsBlockhashValidResponse_size     13
#define geyser_PingRequest_size                  11
#define geyser_PongResponse_size                 11
#define geyser_SubscribeGossipRequest_size       0
#define geyser_SubscribeReplayInfoRequest_size   0
#define geyser_SubscribeReplayInfoResponse_size  11
#define geyser_SubscribeRequestAccountsDataSlice_size 22
#define geyser_SubscribeRequestFilterAccountsFilterLamports_size 11
#define geyser_SubscribeRequestFilterAccountsFilterMemcmp_size 190
#define geyser_SubscribeRequestFilterAccountsFilter_size 193
#define geyser_SubscribeRequestFilterBlocksMeta_size 0
#define geyser_SubscribeRequestFilterEntry_size  0
#define geyser_SubscribeRequestFilterSlots_size  4
#define geyser_SubscribeRequestPing_size         11
#define geyser_SubscribeUpdateContactInfoNode_size 885
#define geyser_SubscribeUpdateContactInfoRemoved_size 34
#define geyser_SubscribeUpdateEntry_size         100
#define geyser_SubscribeUpdatePing_size          0
#define geyser_SubscribeUpdatePong_size          11
#define geyser_SubscribeUpdateSlot_size          293
#if defined(solana_storage_ConfirmedBlock_Transaction_size) && defined(solana_storage_ConfirmedBlock_TransactionStatusMeta_size)
#define geyser_SubscribeUpdateTransactionInfo_size (91 + solana_storage_ConfirmedBlock_Transaction_size + solana_storage_ConfirmedBlock_TransactionStatusMeta_size)
#define geyser_SubscribeUpdateTransaction_size   (119 + solana_storage_ConfirmedBlock_Transaction_size + solana_storage_ConfirmedBlock_TransactionStatusMeta_size)
#endif
#if defined(solana_storage_ConfirmedBlock_TransactionError_size)
#define geyser_SubscribeUpdateTransactionStatus_size (107 + solana_storage_ConfirmedBlock_TransactionError_size)
#endif
#if defined(solana_storage_ConfirmedBlock_Rewards_size)
#define geyser_SubscribeUpdateBlockMeta_size     (179 + solana_storage_ConfirmedBlock_Rewards_size)
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
