/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SOLANA_STORAGE_CONFIRMEDBLOCK_SOLANA_STORAGE_PB_H_INCLUDED
#define PB_SOLANA_STORAGE_CONFIRMEDBLOCK_SOLANA_STORAGE_PB_H_INCLUDED
#include "../../../third_party/nanopb/pb_firedancer.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _solana_storage_ConfirmedBlock_RewardType {
    solana_storage_ConfirmedBlock_RewardType_Unspecified = 0,
    solana_storage_ConfirmedBlock_RewardType_Fee = 1,
    solana_storage_ConfirmedBlock_RewardType_Rent = 2,
    solana_storage_ConfirmedBlock_RewardType_Staking = 3,
    solana_storage_ConfirmedBlock_RewardType_Voting = 4,
    solana_storage_ConfirmedBlock_RewardType_DeactivatedStake = 5
} solana_storage_ConfirmedBlock_RewardType;

/* Struct definitions */
/* Inline budget config introduced by the V1 transaction format (SIMD-0385),
 replacing ComputeBudget instructions. Each field is optional; unset fields
 fall back to the runtime defaults.
 https://github.com/solana-foundation/solana-improvement-documents/blob/main/proposals/0385-transaction-v1.md */
typedef struct _solana_storage_ConfirmedBlock_TransactionConfig {
    bool has_priority_fee;
    uint64_t priority_fee;
    bool has_compute_unit_limit;
    uint32_t compute_unit_limit;
    bool has_loaded_accounts_data_size_limit;
    uint32_t loaded_accounts_data_size_limit;
    bool has_heap_size;
    uint32_t heap_size;
} solana_storage_ConfirmedBlock_TransactionConfig;

typedef struct _solana_storage_ConfirmedBlock_MessageHeader {
    uint32_t num_required_signatures;
    uint32_t num_readonly_signed_accounts;
    uint32_t num_readonly_unsigned_accounts;
} solana_storage_ConfirmedBlock_MessageHeader;

typedef struct _solana_storage_ConfirmedBlock_Message {
    bool has_header;
    solana_storage_ConfirmedBlock_MessageHeader header;
    pb_callback_t account_keys;
    pb_callback_t recent_blockhash;
    pb_callback_t instructions;
    bool versioned;
    pb_callback_t address_table_lookups;
    /* Set only for V1 transaction messages (SIMD-0385). Absent for legacy/V0. */
    bool has_config;
    solana_storage_ConfirmedBlock_TransactionConfig config;
} solana_storage_ConfirmedBlock_Message;

typedef struct _solana_storage_ConfirmedBlock_Transaction {
    pb_callback_t signatures;
    bool has_message;
    solana_storage_ConfirmedBlock_Message message;
} solana_storage_ConfirmedBlock_Transaction;

typedef struct _solana_storage_ConfirmedBlock_MessageAddressTableLookup {
    pb_callback_t account_key;
    pb_callback_t writable_indexes;
    pb_callback_t readonly_indexes;
} solana_storage_ConfirmedBlock_MessageAddressTableLookup;

typedef struct _solana_storage_ConfirmedBlock_TransactionError {
    pb_callback_t err;
} solana_storage_ConfirmedBlock_TransactionError;

typedef struct _solana_storage_ConfirmedBlock_InnerInstructions {
    uint32_t index;
    pb_callback_t instructions;
} solana_storage_ConfirmedBlock_InnerInstructions;

typedef struct _solana_storage_ConfirmedBlock_InnerInstruction {
    uint32_t program_id_index;
    pb_callback_t accounts;
    pb_callback_t data;
    /* Invocation stack height of an inner instruction.
 Available since Solana v1.14.6
 Set to `None` for txs executed on earlier versions. */
    bool has_stack_height;
    uint32_t stack_height;
} solana_storage_ConfirmedBlock_InnerInstruction;

typedef struct _solana_storage_ConfirmedBlock_CompiledInstruction {
    uint32_t program_id_index;
    pb_callback_t accounts;
    pb_callback_t data;
} solana_storage_ConfirmedBlock_CompiledInstruction;

typedef struct _solana_storage_ConfirmedBlock_UiTokenAmount {
    double ui_amount;
    uint32_t decimals;
    pb_callback_t amount;
    pb_callback_t ui_amount_string;
} solana_storage_ConfirmedBlock_UiTokenAmount;

typedef struct _solana_storage_ConfirmedBlock_TokenBalance {
    uint32_t account_index;
    pb_callback_t mint;
    bool has_ui_token_amount;
    solana_storage_ConfirmedBlock_UiTokenAmount ui_token_amount;
    pb_callback_t owner;
    pb_callback_t program_id;
} solana_storage_ConfirmedBlock_TokenBalance;

typedef struct _solana_storage_ConfirmedBlock_ReturnData {
    pb_callback_t program_id;
    pb_callback_t data;
} solana_storage_ConfirmedBlock_ReturnData;

typedef struct _solana_storage_ConfirmedBlock_TransactionStatusMeta {
    bool has_err;
    solana_storage_ConfirmedBlock_TransactionError err;
    uint64_t fee;
    pb_callback_t pre_balances;
    pb_callback_t post_balances;
    pb_callback_t inner_instructions;
    pb_callback_t log_messages;
    pb_callback_t pre_token_balances;
    pb_callback_t post_token_balances;
    pb_callback_t rewards;
    bool inner_instructions_none;
    bool log_messages_none;
    pb_callback_t loaded_writable_addresses;
    pb_callback_t loaded_readonly_addresses;
    bool has_return_data;
    solana_storage_ConfirmedBlock_ReturnData return_data;
    bool return_data_none;
    /* Sum of compute units consumed by all instructions.
 Available since Solana v1.10.35 / v1.11.6.
 Set to `None` for txs executed on earlier versions. */
    bool has_compute_units_consumed;
    uint64_t compute_units_consumed;
    /* Total transaction cost */
    bool has_cost_units;
    uint64_t cost_units;
} solana_storage_ConfirmedBlock_TransactionStatusMeta;

typedef struct _solana_storage_ConfirmedBlock_ConfirmedTransaction {
    bool has_transaction;
    solana_storage_ConfirmedBlock_Transaction transaction;
    bool has_meta;
    solana_storage_ConfirmedBlock_TransactionStatusMeta meta;
} solana_storage_ConfirmedBlock_ConfirmedTransaction;

typedef struct _solana_storage_ConfirmedBlock_Reward {
    pb_callback_t pubkey;
    int64_t lamports;
    uint64_t post_balance;
    solana_storage_ConfirmedBlock_RewardType reward_type;
    pb_callback_t commission;
    pb_callback_t commission_bps;
} solana_storage_ConfirmedBlock_Reward;

typedef struct _solana_storage_ConfirmedBlock_UnixTimestamp {
    int64_t timestamp;
} solana_storage_ConfirmedBlock_UnixTimestamp;

typedef struct _solana_storage_ConfirmedBlock_BlockHeight {
    uint64_t block_height;
} solana_storage_ConfirmedBlock_BlockHeight;

typedef struct _solana_storage_ConfirmedBlock_NumPartitions {
    uint64_t num_partitions;
} solana_storage_ConfirmedBlock_NumPartitions;

typedef struct _solana_storage_ConfirmedBlock_ConfirmedBlock {
    pb_callback_t previous_blockhash;
    pb_callback_t blockhash;
    uint64_t parent_slot;
    pb_callback_t transactions;
    pb_callback_t rewards;
    bool has_block_time;
    solana_storage_ConfirmedBlock_UnixTimestamp block_time;
    bool has_block_height;
    solana_storage_ConfirmedBlock_BlockHeight block_height;
    bool has_num_partitions;
    solana_storage_ConfirmedBlock_NumPartitions num_partitions;
} solana_storage_ConfirmedBlock_ConfirmedBlock;

typedef struct _solana_storage_ConfirmedBlock_Rewards {
    pb_callback_t rewards;
    bool has_num_partitions;
    solana_storage_ConfirmedBlock_NumPartitions num_partitions;
} solana_storage_ConfirmedBlock_Rewards;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _solana_storage_ConfirmedBlock_RewardType_MIN solana_storage_ConfirmedBlock_RewardType_Unspecified
#define _solana_storage_ConfirmedBlock_RewardType_MAX solana_storage_ConfirmedBlock_RewardType_DeactivatedStake
#define _solana_storage_ConfirmedBlock_RewardType_ARRAYSIZE ((solana_storage_ConfirmedBlock_RewardType)(solana_storage_ConfirmedBlock_RewardType_DeactivatedStake+1))
















#define solana_storage_ConfirmedBlock_Reward_reward_type_ENUMTYPE solana_storage_ConfirmedBlock_RewardType






/* Initializer values for message structs */
#define solana_storage_ConfirmedBlock_ConfirmedBlock_init_default {{{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, solana_storage_ConfirmedBlock_UnixTimestamp_init_default, false, solana_storage_ConfirmedBlock_BlockHeight_init_default, false, solana_storage_ConfirmedBlock_NumPartitions_init_default}
#define solana_storage_ConfirmedBlock_ConfirmedTransaction_init_default {false, solana_storage_ConfirmedBlock_Transaction_init_default, false, solana_storage_ConfirmedBlock_TransactionStatusMeta_init_default}
#define solana_storage_ConfirmedBlock_Transaction_init_default {{{NULL}, NULL}, false, solana_storage_ConfirmedBlock_Message_init_default}
#define solana_storage_ConfirmedBlock_Message_init_default {false, solana_storage_ConfirmedBlock_MessageHeader_init_default, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}, false, solana_storage_ConfirmedBlock_TransactionConfig_init_default}
#define solana_storage_ConfirmedBlock_TransactionConfig_init_default {false, 0, false, 0, false, 0, false, 0}
#define solana_storage_ConfirmedBlock_MessageHeader_init_default {0, 0, 0}
#define solana_storage_ConfirmedBlock_MessageAddressTableLookup_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define solana_storage_ConfirmedBlock_TransactionStatusMeta_init_default {false, solana_storage_ConfirmedBlock_TransactionError_init_default, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, solana_storage_ConfirmedBlock_ReturnData_init_default, 0, false, 0, false, 0}
#define solana_storage_ConfirmedBlock_TransactionError_init_default {{{NULL}, NULL}}
#define solana_storage_ConfirmedBlock_InnerInstructions_init_default {0, {{NULL}, NULL}}
#define solana_storage_ConfirmedBlock_InnerInstruction_init_default {0, {{NULL}, NULL}, {{NULL}, NULL}, false, 0}
#define solana_storage_ConfirmedBlock_CompiledInstruction_init_default {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define solana_storage_ConfirmedBlock_TokenBalance_init_default {0, {{NULL}, NULL}, false, solana_storage_ConfirmedBlock_UiTokenAmount_init_default, {{NULL}, NULL}, {{NULL}, NULL}}
#define solana_storage_ConfirmedBlock_UiTokenAmount_init_default {0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define solana_storage_ConfirmedBlock_ReturnData_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define solana_storage_ConfirmedBlock_Reward_init_default {{{NULL}, NULL}, 0, 0, _solana_storage_ConfirmedBlock_RewardType_MIN, {{NULL}, NULL}, {{NULL}, NULL}}
#define solana_storage_ConfirmedBlock_Rewards_init_default {{{NULL}, NULL}, false, solana_storage_ConfirmedBlock_NumPartitions_init_default}
#define solana_storage_ConfirmedBlock_UnixTimestamp_init_default {0}
#define solana_storage_ConfirmedBlock_BlockHeight_init_default {0}
#define solana_storage_ConfirmedBlock_NumPartitions_init_default {0}
#define solana_storage_ConfirmedBlock_ConfirmedBlock_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, solana_storage_ConfirmedBlock_UnixTimestamp_init_zero, false, solana_storage_ConfirmedBlock_BlockHeight_init_zero, false, solana_storage_ConfirmedBlock_NumPartitions_init_zero}
#define solana_storage_ConfirmedBlock_ConfirmedTransaction_init_zero {false, solana_storage_ConfirmedBlock_Transaction_init_zero, false, solana_storage_ConfirmedBlock_TransactionStatusMeta_init_zero}
#define solana_storage_ConfirmedBlock_Transaction_init_zero {{{NULL}, NULL}, false, solana_storage_ConfirmedBlock_Message_init_zero}
#define solana_storage_ConfirmedBlock_Message_init_zero {false, solana_storage_ConfirmedBlock_MessageHeader_init_zero, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}, false, solana_storage_ConfirmedBlock_TransactionConfig_init_zero}
#define solana_storage_ConfirmedBlock_TransactionConfig_init_zero {false, 0, false, 0, false, 0, false, 0}
#define solana_storage_ConfirmedBlock_MessageHeader_init_zero {0, 0, 0}
#define solana_storage_ConfirmedBlock_MessageAddressTableLookup_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define solana_storage_ConfirmedBlock_TransactionStatusMeta_init_zero {false, solana_storage_ConfirmedBlock_TransactionError_init_zero, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, solana_storage_ConfirmedBlock_ReturnData_init_zero, 0, false, 0, false, 0}
#define solana_storage_ConfirmedBlock_TransactionError_init_zero {{{NULL}, NULL}}
#define solana_storage_ConfirmedBlock_InnerInstructions_init_zero {0, {{NULL}, NULL}}
#define solana_storage_ConfirmedBlock_InnerInstruction_init_zero {0, {{NULL}, NULL}, {{NULL}, NULL}, false, 0}
#define solana_storage_ConfirmedBlock_CompiledInstruction_init_zero {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define solana_storage_ConfirmedBlock_TokenBalance_init_zero {0, {{NULL}, NULL}, false, solana_storage_ConfirmedBlock_UiTokenAmount_init_zero, {{NULL}, NULL}, {{NULL}, NULL}}
#define solana_storage_ConfirmedBlock_UiTokenAmount_init_zero {0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define solana_storage_ConfirmedBlock_ReturnData_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define solana_storage_ConfirmedBlock_Reward_init_zero {{{NULL}, NULL}, 0, 0, _solana_storage_ConfirmedBlock_RewardType_MIN, {{NULL}, NULL}, {{NULL}, NULL}}
#define solana_storage_ConfirmedBlock_Rewards_init_zero {{{NULL}, NULL}, false, solana_storage_ConfirmedBlock_NumPartitions_init_zero}
#define solana_storage_ConfirmedBlock_UnixTimestamp_init_zero {0}
#define solana_storage_ConfirmedBlock_BlockHeight_init_zero {0}
#define solana_storage_ConfirmedBlock_NumPartitions_init_zero {0}

/* Field tags (for use in manual encoding/decoding) */
#define solana_storage_ConfirmedBlock_TransactionConfig_priority_fee_tag 1
#define solana_storage_ConfirmedBlock_TransactionConfig_compute_unit_limit_tag 2
#define solana_storage_ConfirmedBlock_TransactionConfig_loaded_accounts_data_size_limit_tag 3
#define solana_storage_ConfirmedBlock_TransactionConfig_heap_size_tag 4
#define solana_storage_ConfirmedBlock_MessageHeader_num_required_signatures_tag 1
#define solana_storage_ConfirmedBlock_MessageHeader_num_readonly_signed_accounts_tag 2
#define solana_storage_ConfirmedBlock_MessageHeader_num_readonly_unsigned_accounts_tag 3
#define solana_storage_ConfirmedBlock_Message_header_tag 1
#define solana_storage_ConfirmedBlock_Message_account_keys_tag 2
#define solana_storage_ConfirmedBlock_Message_recent_blockhash_tag 3
#define solana_storage_ConfirmedBlock_Message_instructions_tag 4
#define solana_storage_ConfirmedBlock_Message_versioned_tag 5
#define solana_storage_ConfirmedBlock_Message_address_table_lookups_tag 6
#define solana_storage_ConfirmedBlock_Message_config_tag 7
#define solana_storage_ConfirmedBlock_Transaction_signatures_tag 1
#define solana_storage_ConfirmedBlock_Transaction_message_tag 2
#define solana_storage_ConfirmedBlock_MessageAddressTableLookup_account_key_tag 1
#define solana_storage_ConfirmedBlock_MessageAddressTableLookup_writable_indexes_tag 2
#define solana_storage_ConfirmedBlock_MessageAddressTableLookup_readonly_indexes_tag 3
#define solana_storage_ConfirmedBlock_TransactionError_err_tag 1
#define solana_storage_ConfirmedBlock_InnerInstructions_index_tag 1
#define solana_storage_ConfirmedBlock_InnerInstructions_instructions_tag 2
#define solana_storage_ConfirmedBlock_InnerInstruction_program_id_index_tag 1
#define solana_storage_ConfirmedBlock_InnerInstruction_accounts_tag 2
#define solana_storage_ConfirmedBlock_InnerInstruction_data_tag 3
#define solana_storage_ConfirmedBlock_InnerInstruction_stack_height_tag 4
#define solana_storage_ConfirmedBlock_CompiledInstruction_program_id_index_tag 1
#define solana_storage_ConfirmedBlock_CompiledInstruction_accounts_tag 2
#define solana_storage_ConfirmedBlock_CompiledInstruction_data_tag 3
#define solana_storage_ConfirmedBlock_UiTokenAmount_ui_amount_tag 1
#define solana_storage_ConfirmedBlock_UiTokenAmount_decimals_tag 2
#define solana_storage_ConfirmedBlock_UiTokenAmount_amount_tag 3
#define solana_storage_ConfirmedBlock_UiTokenAmount_ui_amount_string_tag 4
#define solana_storage_ConfirmedBlock_TokenBalance_account_index_tag 1
#define solana_storage_ConfirmedBlock_TokenBalance_mint_tag 2
#define solana_storage_ConfirmedBlock_TokenBalance_ui_token_amount_tag 3
#define solana_storage_ConfirmedBlock_TokenBalance_owner_tag 4
#define solana_storage_ConfirmedBlock_TokenBalance_program_id_tag 5
#define solana_storage_ConfirmedBlock_ReturnData_program_id_tag 1
#define solana_storage_ConfirmedBlock_ReturnData_data_tag 2
#define solana_storage_ConfirmedBlock_TransactionStatusMeta_err_tag 1
#define solana_storage_ConfirmedBlock_TransactionStatusMeta_fee_tag 2
#define solana_storage_ConfirmedBlock_TransactionStatusMeta_pre_balances_tag 3
#define solana_storage_ConfirmedBlock_TransactionStatusMeta_post_balances_tag 4
#define solana_storage_ConfirmedBlock_TransactionStatusMeta_inner_instructions_tag 5
#define solana_storage_ConfirmedBlock_TransactionStatusMeta_log_messages_tag 6
#define solana_storage_ConfirmedBlock_TransactionStatusMeta_pre_token_balances_tag 7
#define solana_storage_ConfirmedBlock_TransactionStatusMeta_post_token_balances_tag 8
#define solana_storage_ConfirmedBlock_TransactionStatusMeta_rewards_tag 9
#define solana_storage_ConfirmedBlock_TransactionStatusMeta_inner_instructions_none_tag 10
#define solana_storage_ConfirmedBlock_TransactionStatusMeta_log_messages_none_tag 11
#define solana_storage_ConfirmedBlock_TransactionStatusMeta_loaded_writable_addresses_tag 12
#define solana_storage_ConfirmedBlock_TransactionStatusMeta_loaded_readonly_addresses_tag 13
#define solana_storage_ConfirmedBlock_TransactionStatusMeta_return_data_tag 14
#define solana_storage_ConfirmedBlock_TransactionStatusMeta_return_data_none_tag 15
#define solana_storage_ConfirmedBlock_TransactionStatusMeta_compute_units_consumed_tag 16
#define solana_storage_ConfirmedBlock_TransactionStatusMeta_cost_units_tag 17
#define solana_storage_ConfirmedBlock_ConfirmedTransaction_transaction_tag 1
#define solana_storage_ConfirmedBlock_ConfirmedTransaction_meta_tag 2
#define solana_storage_ConfirmedBlock_Reward_pubkey_tag 1
#define solana_storage_ConfirmedBlock_Reward_lamports_tag 2
#define solana_storage_ConfirmedBlock_Reward_post_balance_tag 3
#define solana_storage_ConfirmedBlock_Reward_reward_type_tag 4
#define solana_storage_ConfirmedBlock_Reward_commission_tag 5
#define solana_storage_ConfirmedBlock_Reward_commission_bps_tag 6
#define solana_storage_ConfirmedBlock_UnixTimestamp_timestamp_tag 1
#define solana_storage_ConfirmedBlock_BlockHeight_block_height_tag 1
#define solana_storage_ConfirmedBlock_NumPartitions_num_partitions_tag 1
#define solana_storage_ConfirmedBlock_ConfirmedBlock_previous_blockhash_tag 1
#define solana_storage_ConfirmedBlock_ConfirmedBlock_blockhash_tag 2
#define solana_storage_ConfirmedBlock_ConfirmedBlock_parent_slot_tag 3
#define solana_storage_ConfirmedBlock_ConfirmedBlock_transactions_tag 4
#define solana_storage_ConfirmedBlock_ConfirmedBlock_rewards_tag 5
#define solana_storage_ConfirmedBlock_ConfirmedBlock_block_time_tag 6
#define solana_storage_ConfirmedBlock_ConfirmedBlock_block_height_tag 7
#define solana_storage_ConfirmedBlock_ConfirmedBlock_num_partitions_tag 8
#define solana_storage_ConfirmedBlock_Rewards_rewards_tag 1
#define solana_storage_ConfirmedBlock_Rewards_num_partitions_tag 2

/* Struct field encoding specification for nanopb */
#define solana_storage_ConfirmedBlock_ConfirmedBlock_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   previous_blockhash,   1) \
X(a, CALLBACK, SINGULAR, STRING,   blockhash,         2) \
X(a, STATIC,   SINGULAR, UINT64,   parent_slot,       3) \
X(a, CALLBACK, REPEATED, MESSAGE,  transactions,      4) \
X(a, CALLBACK, REPEATED, MESSAGE,  rewards,           5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  block_time,        6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  block_height,      7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  num_partitions,    8)
#define solana_storage_ConfirmedBlock_ConfirmedBlock_CALLBACK pb_default_field_callback
#define solana_storage_ConfirmedBlock_ConfirmedBlock_DEFAULT NULL
#define solana_storage_ConfirmedBlock_ConfirmedBlock_transactions_MSGTYPE solana_storage_ConfirmedBlock_ConfirmedTransaction
#define solana_storage_ConfirmedBlock_ConfirmedBlock_rewards_MSGTYPE solana_storage_ConfirmedBlock_Reward
#define solana_storage_ConfirmedBlock_ConfirmedBlock_block_time_MSGTYPE solana_storage_ConfirmedBlock_UnixTimestamp
#define solana_storage_ConfirmedBlock_ConfirmedBlock_block_height_MSGTYPE solana_storage_ConfirmedBlock_BlockHeight
#define solana_storage_ConfirmedBlock_ConfirmedBlock_num_partitions_MSGTYPE solana_storage_ConfirmedBlock_NumPartitions

#define solana_storage_ConfirmedBlock_ConfirmedTransaction_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  transaction,       1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  meta,              2)
#define solana_storage_ConfirmedBlock_ConfirmedTransaction_CALLBACK NULL
#define solana_storage_ConfirmedBlock_ConfirmedTransaction_DEFAULT NULL
#define solana_storage_ConfirmedBlock_ConfirmedTransaction_transaction_MSGTYPE solana_storage_ConfirmedBlock_Transaction
#define solana_storage_ConfirmedBlock_ConfirmedTransaction_meta_MSGTYPE solana_storage_ConfirmedBlock_TransactionStatusMeta

#define solana_storage_ConfirmedBlock_Transaction_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, BYTES,    signatures,        1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  message,           2)
#define solana_storage_ConfirmedBlock_Transaction_CALLBACK pb_default_field_callback
#define solana_storage_ConfirmedBlock_Transaction_DEFAULT NULL
#define solana_storage_ConfirmedBlock_Transaction_message_MSGTYPE solana_storage_ConfirmedBlock_Message

#define solana_storage_ConfirmedBlock_Message_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, CALLBACK, REPEATED, BYTES,    account_keys,      2) \
X(a, CALLBACK, SINGULAR, BYTES,    recent_blockhash,   3) \
X(a, CALLBACK, REPEATED, MESSAGE,  instructions,      4) \
X(a, STATIC,   SINGULAR, BOOL,     versioned,         5) \
X(a, CALLBACK, REPEATED, MESSAGE,  address_table_lookups,   6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  config,            7)
#define solana_storage_ConfirmedBlock_Message_CALLBACK pb_default_field_callback
#define solana_storage_ConfirmedBlock_Message_DEFAULT NULL
#define solana_storage_ConfirmedBlock_Message_header_MSGTYPE solana_storage_ConfirmedBlock_MessageHeader
#define solana_storage_ConfirmedBlock_Message_instructions_MSGTYPE solana_storage_ConfirmedBlock_CompiledInstruction
#define solana_storage_ConfirmedBlock_Message_address_table_lookups_MSGTYPE solana_storage_ConfirmedBlock_MessageAddressTableLookup
#define solana_storage_ConfirmedBlock_Message_config_MSGTYPE solana_storage_ConfirmedBlock_TransactionConfig

#define solana_storage_ConfirmedBlock_TransactionConfig_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT64,   priority_fee,      1) \
X(a, STATIC,   OPTIONAL, UINT32,   compute_unit_limit,   2) \
X(a, STATIC,   OPTIONAL, UINT32,   loaded_accounts_data_size_limit,   3) \
X(a, STATIC,   OPTIONAL, UINT32,   heap_size,         4)
#define solana_storage_ConfirmedBlock_TransactionConfig_CALLBACK NULL
#define solana_storage_ConfirmedBlock_TransactionConfig_DEFAULT NULL

#define solana_storage_ConfirmedBlock_MessageHeader_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   num_required_signatures,   1) \
X(a, STATIC,   SINGULAR, UINT32,   num_readonly_signed_accounts,   2) \
X(a, STATIC,   SINGULAR, UINT32,   num_readonly_unsigned_accounts,   3)
#define solana_storage_ConfirmedBlock_MessageHeader_CALLBACK NULL
#define solana_storage_ConfirmedBlock_MessageHeader_DEFAULT NULL

#define solana_storage_ConfirmedBlock_MessageAddressTableLookup_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    account_key,       1) \
X(a, CALLBACK, SINGULAR, BYTES,    writable_indexes,   2) \
X(a, CALLBACK, SINGULAR, BYTES,    readonly_indexes,   3)
#define solana_storage_ConfirmedBlock_MessageAddressTableLookup_CALLBACK pb_default_field_callback
#define solana_storage_ConfirmedBlock_MessageAddressTableLookup_DEFAULT NULL

#define solana_storage_ConfirmedBlock_TransactionStatusMeta_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  err,               1) \
X(a, STATIC,   SINGULAR, UINT64,   fee,               2) \
X(a, CALLBACK, REPEATED, UINT64,   pre_balances,      3) \
X(a, CALLBACK, REPEATED, UINT64,   post_balances,     4) \
X(a, CALLBACK, REPEATED, MESSAGE,  inner_instructions,   5) \
X(a, CALLBACK, REPEATED, STRING,   log_messages,      6) \
X(a, CALLBACK, REPEATED, MESSAGE,  pre_token_balances,   7) \
X(a, CALLBACK, REPEATED, MESSAGE,  post_token_balances,   8) \
X(a, CALLBACK, REPEATED, MESSAGE,  rewards,           9) \
X(a, STATIC,   SINGULAR, BOOL,     inner_instructions_none,  10) \
X(a, STATIC,   SINGULAR, BOOL,     log_messages_none,  11) \
X(a, CALLBACK, REPEATED, BYTES,    loaded_writable_addresses,  12) \
X(a, CALLBACK, REPEATED, BYTES,    loaded_readonly_addresses,  13) \
X(a, STATIC,   OPTIONAL, MESSAGE,  return_data,      14) \
X(a, STATIC,   SINGULAR, BOOL,     return_data_none,  15) \
X(a, STATIC,   OPTIONAL, UINT64,   compute_units_consumed,  16) \
X(a, STATIC,   OPTIONAL, UINT64,   cost_units,       17)
#define solana_storage_ConfirmedBlock_TransactionStatusMeta_CALLBACK pb_default_field_callback
#define solana_storage_ConfirmedBlock_TransactionStatusMeta_DEFAULT NULL
#define solana_storage_ConfirmedBlock_TransactionStatusMeta_err_MSGTYPE solana_storage_ConfirmedBlock_TransactionError
#define solana_storage_ConfirmedBlock_TransactionStatusMeta_inner_instructions_MSGTYPE solana_storage_ConfirmedBlock_InnerInstructions
#define solana_storage_ConfirmedBlock_TransactionStatusMeta_pre_token_balances_MSGTYPE solana_storage_ConfirmedBlock_TokenBalance
#define solana_storage_ConfirmedBlock_TransactionStatusMeta_post_token_balances_MSGTYPE solana_storage_ConfirmedBlock_TokenBalance
#define solana_storage_ConfirmedBlock_TransactionStatusMeta_rewards_MSGTYPE solana_storage_ConfirmedBlock_Reward
#define solana_storage_ConfirmedBlock_TransactionStatusMeta_return_data_MSGTYPE solana_storage_ConfirmedBlock_ReturnData

#define solana_storage_ConfirmedBlock_TransactionError_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    err,               1)
#define solana_storage_ConfirmedBlock_TransactionError_CALLBACK pb_default_field_callback
#define solana_storage_ConfirmedBlock_TransactionError_DEFAULT NULL

#define solana_storage_ConfirmedBlock_InnerInstructions_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   index,             1) \
X(a, CALLBACK, REPEATED, MESSAGE,  instructions,      2)
#define solana_storage_ConfirmedBlock_InnerInstructions_CALLBACK pb_default_field_callback
#define solana_storage_ConfirmedBlock_InnerInstructions_DEFAULT NULL
#define solana_storage_ConfirmedBlock_InnerInstructions_instructions_MSGTYPE solana_storage_ConfirmedBlock_InnerInstruction

#define solana_storage_ConfirmedBlock_InnerInstruction_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   program_id_index,   1) \
X(a, CALLBACK, SINGULAR, BYTES,    accounts,          2) \
X(a, CALLBACK, SINGULAR, BYTES,    data,              3) \
X(a, STATIC,   OPTIONAL, UINT32,   stack_height,      4)
#define solana_storage_ConfirmedBlock_InnerInstruction_CALLBACK pb_default_field_callback
#define solana_storage_ConfirmedBlock_InnerInstruction_DEFAULT NULL

#define solana_storage_ConfirmedBlock_CompiledInstruction_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   program_id_index,   1) \
X(a, CALLBACK, SINGULAR, BYTES,    accounts,          2) \
X(a, CALLBACK, SINGULAR, BYTES,    data,              3)
#define solana_storage_ConfirmedBlock_CompiledInstruction_CALLBACK pb_default_field_callback
#define solana_storage_ConfirmedBlock_CompiledInstruction_DEFAULT NULL

#define solana_storage_ConfirmedBlock_TokenBalance_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   account_index,     1) \
X(a, CALLBACK, SINGULAR, STRING,   mint,              2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  ui_token_amount,   3) \
X(a, CALLBACK, SINGULAR, STRING,   owner,             4) \
X(a, CALLBACK, SINGULAR, STRING,   program_id,        5)
#define solana_storage_ConfirmedBlock_TokenBalance_CALLBACK pb_default_field_callback
#define solana_storage_ConfirmedBlock_TokenBalance_DEFAULT NULL
#define solana_storage_ConfirmedBlock_TokenBalance_ui_token_amount_MSGTYPE solana_storage_ConfirmedBlock_UiTokenAmount

#define solana_storage_ConfirmedBlock_UiTokenAmount_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   ui_amount,         1) \
X(a, STATIC,   SINGULAR, UINT32,   decimals,          2) \
X(a, CALLBACK, SINGULAR, STRING,   amount,            3) \
X(a, CALLBACK, SINGULAR, STRING,   ui_amount_string,   4)
#define solana_storage_ConfirmedBlock_UiTokenAmount_CALLBACK pb_default_field_callback
#define solana_storage_ConfirmedBlock_UiTokenAmount_DEFAULT NULL

#define solana_storage_ConfirmedBlock_ReturnData_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    program_id,        1) \
X(a, CALLBACK, SINGULAR, BYTES,    data,              2)
#define solana_storage_ConfirmedBlock_ReturnData_CALLBACK pb_default_field_callback
#define solana_storage_ConfirmedBlock_ReturnData_DEFAULT NULL

#define solana_storage_ConfirmedBlock_Reward_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   pubkey,            1) \
X(a, STATIC,   SINGULAR, INT64,    lamports,          2) \
X(a, STATIC,   SINGULAR, UINT64,   post_balance,      3) \
X(a, STATIC,   SINGULAR, UENUM,    reward_type,       4) \
X(a, CALLBACK, SINGULAR, STRING,   commission,        5) \
X(a, CALLBACK, SINGULAR, STRING,   commission_bps,    6)
#define solana_storage_ConfirmedBlock_Reward_CALLBACK pb_default_field_callback
#define solana_storage_ConfirmedBlock_Reward_DEFAULT NULL

#define solana_storage_ConfirmedBlock_Rewards_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  rewards,           1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  num_partitions,    2)
#define solana_storage_ConfirmedBlock_Rewards_CALLBACK pb_default_field_callback
#define solana_storage_ConfirmedBlock_Rewards_DEFAULT NULL
#define solana_storage_ConfirmedBlock_Rewards_rewards_MSGTYPE solana_storage_ConfirmedBlock_Reward
#define solana_storage_ConfirmedBlock_Rewards_num_partitions_MSGTYPE solana_storage_ConfirmedBlock_NumPartitions

#define solana_storage_ConfirmedBlock_UnixTimestamp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    timestamp,         1)
#define solana_storage_ConfirmedBlock_UnixTimestamp_CALLBACK NULL
#define solana_storage_ConfirmedBlock_UnixTimestamp_DEFAULT NULL

#define solana_storage_ConfirmedBlock_BlockHeight_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   block_height,      1)
#define solana_storage_ConfirmedBlock_BlockHeight_CALLBACK NULL
#define solana_storage_ConfirmedBlock_BlockHeight_DEFAULT NULL

#define solana_storage_ConfirmedBlock_NumPartitions_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   num_partitions,    1)
#define solana_storage_ConfirmedBlock_NumPartitions_CALLBACK NULL
#define solana_storage_ConfirmedBlock_NumPartitions_DEFAULT NULL

extern const pb_msgdesc_t solana_storage_ConfirmedBlock_ConfirmedBlock_msg;
extern const pb_msgdesc_t solana_storage_ConfirmedBlock_ConfirmedTransaction_msg;
extern const pb_msgdesc_t solana_storage_ConfirmedBlock_Transaction_msg;
extern const pb_msgdesc_t solana_storage_ConfirmedBlock_Message_msg;
extern const pb_msgdesc_t solana_storage_ConfirmedBlock_TransactionConfig_msg;
extern const pb_msgdesc_t solana_storage_ConfirmedBlock_MessageHeader_msg;
extern const pb_msgdesc_t solana_storage_ConfirmedBlock_MessageAddressTableLookup_msg;
extern const pb_msgdesc_t solana_storage_ConfirmedBlock_TransactionStatusMeta_msg;
extern const pb_msgdesc_t solana_storage_ConfirmedBlock_TransactionError_msg;
extern const pb_msgdesc_t solana_storage_ConfirmedBlock_InnerInstructions_msg;
extern const pb_msgdesc_t solana_storage_ConfirmedBlock_InnerInstruction_msg;
extern const pb_msgdesc_t solana_storage_ConfirmedBlock_CompiledInstruction_msg;
extern const pb_msgdesc_t solana_storage_ConfirmedBlock_TokenBalance_msg;
extern const pb_msgdesc_t solana_storage_ConfirmedBlock_UiTokenAmount_msg;
extern const pb_msgdesc_t solana_storage_ConfirmedBlock_ReturnData_msg;
extern const pb_msgdesc_t solana_storage_ConfirmedBlock_Reward_msg;
extern const pb_msgdesc_t solana_storage_ConfirmedBlock_Rewards_msg;
extern const pb_msgdesc_t solana_storage_ConfirmedBlock_UnixTimestamp_msg;
extern const pb_msgdesc_t solana_storage_ConfirmedBlock_BlockHeight_msg;
extern const pb_msgdesc_t solana_storage_ConfirmedBlock_NumPartitions_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define solana_storage_ConfirmedBlock_ConfirmedBlock_fields &solana_storage_ConfirmedBlock_ConfirmedBlock_msg
#define solana_storage_ConfirmedBlock_ConfirmedTransaction_fields &solana_storage_ConfirmedBlock_ConfirmedTransaction_msg
#define solana_storage_ConfirmedBlock_Transaction_fields &solana_storage_ConfirmedBlock_Transaction_msg
#define solana_storage_ConfirmedBlock_Message_fields &solana_storage_ConfirmedBlock_Message_msg
#define solana_storage_ConfirmedBlock_TransactionConfig_fields &solana_storage_ConfirmedBlock_TransactionConfig_msg
#define solana_storage_ConfirmedBlock_MessageHeader_fields &solana_storage_ConfirmedBlock_MessageHeader_msg
#define solana_storage_ConfirmedBlock_MessageAddressTableLookup_fields &solana_storage_ConfirmedBlock_MessageAddressTableLookup_msg
#define solana_storage_ConfirmedBlock_TransactionStatusMeta_fields &solana_storage_ConfirmedBlock_TransactionStatusMeta_msg
#define solana_storage_ConfirmedBlock_TransactionError_fields &solana_storage_ConfirmedBlock_TransactionError_msg
#define solana_storage_ConfirmedBlock_InnerInstructions_fields &solana_storage_ConfirmedBlock_InnerInstructions_msg
#define solana_storage_ConfirmedBlock_InnerInstruction_fields &solana_storage_ConfirmedBlock_InnerInstruction_msg
#define solana_storage_ConfirmedBlock_CompiledInstruction_fields &solana_storage_ConfirmedBlock_CompiledInstruction_msg
#define solana_storage_ConfirmedBlock_TokenBalance_fields &solana_storage_ConfirmedBlock_TokenBalance_msg
#define solana_storage_ConfirmedBlock_UiTokenAmount_fields &solana_storage_ConfirmedBlock_UiTokenAmount_msg
#define solana_storage_ConfirmedBlock_ReturnData_fields &solana_storage_ConfirmedBlock_ReturnData_msg
#define solana_storage_ConfirmedBlock_Reward_fields &solana_storage_ConfirmedBlock_Reward_msg
#define solana_storage_ConfirmedBlock_Rewards_fields &solana_storage_ConfirmedBlock_Rewards_msg
#define solana_storage_ConfirmedBlock_UnixTimestamp_fields &solana_storage_ConfirmedBlock_UnixTimestamp_msg
#define solana_storage_ConfirmedBlock_BlockHeight_fields &solana_storage_ConfirmedBlock_BlockHeight_msg
#define solana_storage_ConfirmedBlock_NumPartitions_fields &solana_storage_ConfirmedBlock_NumPartitions_msg

/* Maximum encoded size of messages (where known) */
/* solana_storage_ConfirmedBlock_ConfirmedBlock_size depends on runtime parameters */
/* solana_storage_ConfirmedBlock_ConfirmedTransaction_size depends on runtime parameters */
/* solana_storage_ConfirmedBlock_Transaction_size depends on runtime parameters */
/* solana_storage_ConfirmedBlock_Message_size depends on runtime parameters */
/* solana_storage_ConfirmedBlock_MessageAddressTableLookup_size depends on runtime parameters */
/* solana_storage_ConfirmedBlock_TransactionStatusMeta_size depends on runtime parameters */
/* solana_storage_ConfirmedBlock_TransactionError_size depends on runtime parameters */
/* solana_storage_ConfirmedBlock_InnerInstructions_size depends on runtime parameters */
/* solana_storage_ConfirmedBlock_InnerInstruction_size depends on runtime parameters */
/* solana_storage_ConfirmedBlock_CompiledInstruction_size depends on runtime parameters */
/* solana_storage_ConfirmedBlock_TokenBalance_size depends on runtime parameters */
/* solana_storage_ConfirmedBlock_UiTokenAmount_size depends on runtime parameters */
/* solana_storage_ConfirmedBlock_ReturnData_size depends on runtime parameters */
/* solana_storage_ConfirmedBlock_Reward_size depends on runtime parameters */
/* solana_storage_ConfirmedBlock_Rewards_size depends on runtime parameters */
#define SOLANA_STORAGE_CONFIRMEDBLOCK_SOLANA_STORAGE_PB_H_MAX_SIZE solana_storage_ConfirmedBlock_TransactionConfig_size
#define solana_storage_ConfirmedBlock_BlockHeight_size 11
#define solana_storage_ConfirmedBlock_MessageHeader_size 18
#define solana_storage_ConfirmedBlock_NumPartitions_size 11
#define solana_storage_ConfirmedBlock_TransactionConfig_size 29
#define solana_storage_ConfirmedBlock_UnixTimestamp_size 11

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
