#!/bin/sh
# Run jump/install to install any required dependencies before activating.

module purge
module load gcc-9.3.0
module load clang-14.0
module load java-cacerts-jump
module load buildifier-4.2.0
module load Python-3.9
module list
