close all
clear all

align         = 8;
sb_hdr        = 24;
alloc_hdr     = 4;
lg_cgroup_max = 4;

obj_cnt_min       = 8;
obj_cnt_max       = 64;
obj_footprint_min = align;
obj_footprint_max = 10*2^20;
root_sb_footprint = 2^26;  % Current implementation limits this to <=2^26
gamma             = (obj_cnt_min+1) / obj_cnt_min;

szc_cnt = 0;
sb_lvl  = 0;

sb_footprint         = root_sb_footprint;
obj_footprint_target = obj_footprint_max;
while obj_footprint_target>=obj_footprint_min,

  % Determine the superblock size and object count for this object
  % footprint target

  ofp = align*round( obj_footprint_target / align );
  while 1,
    ocnt = floor( (sb_footprint - sb_hdr) / ofp );
    if ocnt<=obj_cnt_max, break; endif

    % More than obj_cnt_max objects fit into the current superblock.
    % Pick a new superblock size to be the smallest object footprint in
    % an already computed sizeclass sufficient to hold a superblock with
    % obj_cnt_min ofp sized objects.  If there are none (i.e. the needed
    % superblock size is larger than the object footprints for all the
    % already computed sizeclasses), use the already computed sizeclass
    % with the largest object footprint (the resulting superblock for
    % ofp sized objects will have fewer than obj_cnt_min objects but
    % that's unavoidable).

    idx = find( obj_footprint >= sb_hdr + ofp*obj_cnt_min, 1, 'last' );
    if isempty(idx), idx = 1; endif
    sb_footprint = obj_footprint( idx );
    sb_lvl++;
  endwhile

  if ~((2<=ocnt) & (ocnt<=64)), error( 'hmmm' ); endif

  szc_cnt++;
  obj_footprint   (szc_cnt) = align*floor( (sb_footprint - sb_hdr) / (align*ocnt) );
  obj_cnt         (szc_cnt) = ocnt;
  parent_footprint(szc_cnt) = sb_footprint;
  cgroup_mask     (szc_cnt) = 2^min( sb_lvl, lg_cgroup_max ) - 1;

  obj_footprint_target /= gamma;
endwhile

% Sort by object footprint, discarding redundant and/or runt sizeclasses

[~,idx] = unique( obj_footprint, 'first' );
obj_footprint    = obj_footprint   (idx);
obj_cnt          = obj_cnt         (idx);
parent_footprint = parent_footprint(idx);
cgroup_mask      = cgroup_mask     (idx);

keep = diff(obj_footprint) > 0.25*(gamma-1)*obj_footprint(1:(end-1));
keep(end+1) = 1;

obj_footprint    = obj_footprint   (keep);
obj_cnt          = obj_cnt         (keep);
parent_footprint = parent_footprint(keep);
cgroup_mask      = cgroup_mask     (keep);

szc_cnt = length(obj_footprint);

% Determine sizeclass nesting

for szc=1:szc_cnt,
  pfp  = sb_hdr + obj_cnt(szc)*obj_footprint(szc);
  pszc = find( pfp<=obj_footprint, 1, 'first' );
  if isempty(pszc),
    parent_footprint(szc) = root_sb_footprint;
    parent_szc(szc)       = szc_cnt+1;
  else
    parent_footprint(szc) = obj_footprint(pszc);
    parent_szc(szc)       = pszc;
  endif
endfor

szc_thresh = szc_cnt;

printf( '/* This table autogenerated\n'                                        );
printf( '     align             %i\n',      align                              );
printf( '     alloc_hdr         %i\n',      alloc_hdr                          );
printf( '     sb_hdr            %i\n',      sb_hdr                             );
printf( '     lg_cgroup_max     %i\n',      lg_cgroup_max                      );
printf( '     obj_cnt_min       %i\n',      obj_cnt_min                        );
printf( '     obj_cnt_max       %i\n',      obj_cnt_max                        );
printf( '     obj_footprint_min %i\n',      obj_footprint_min                  );
printf( '     obj_footprint_max %i\n',      obj_footprint_max                  );
printf( '     root_sb_footprint %i\n',      root_sb_footprint                  );
printf( '     gamma             %.6e */\n', gamma                              );
printf( '\n'                                                                   );
printf( '#define FD_ALLOC_SUPERBLOCK_ALIGN          (%uUL)\n', align                       );
printf( '#define FD_ALLOC_SUPERBLOCK_LG_ALIGN       (%u)\n',   log2( align )               );
printf( '#define FD_ALLOC_SIZECLASS_CNT             (%uUL)\n', szc_cnt                     );
printf( '#define FD_ALLOC_SIZECLASS_ITER_MAX        (%uUL)\n', ceil( log2( szc_cnt ) )     );
printf( '#define FD_ALLOC_ROOT_SUPERBLOCK_FOOTPRINT (%uUL)\n', max( parent_footprint )     );
printf( '#define FD_ALLOC_FOOTPRINT_SMALL_THRESH    (%uUL)\n', obj_footprint( szc_thresh ) );
printf( '\n' );
printf( 'static fd_alloc_sizeclass_cfg_t const fd_alloc_sizeclass_cfg[ FD_ALLOC_SIZECLASS_CNT ] = {\n' );

overhead = parent_footprint - obj_cnt.*obj_footprint; % superblock header and superblock trailing padding

for szc=1:szc_cnt,
  printf( '  /* %3u */ { %10uU, (ushort)%3u, (uchar)%3u, (uchar)%3u }, // parent_footprint %10u (padding %u) %s\n', szc-1, obj_footprint(szc), parent_szc(szc)-1, obj_cnt(szc), cgroup_mask(szc), parent_footprint(szc), overhead(szc) - sb_hdr, ifelse( szc_thresh==szc, ' <-- SMALL_THRESH', '' ) );
endfor
printf( '};\n' );

obj_val_max = obj_footprint - alloc_hdr;
obj_val_min = shift(obj_val_max,1) + 1; obj_val_min(1) = 1;
obj_val_avg = 0.5*(obj_val_min+obj_val_max);

% Compute the amount of storage used by superblock per object

denom = parent_footprint./obj_cnt;

% Add in superblock nesting overheads (these are practically negligible)

amort = obj_cnt;
szc   = parent_szc;
while 1,
  live = szc<=szc_cnt;
  if ~any( live ), break; endif
  amort( live )  = amort( live ).*obj_cnt( szc( live ) );
  denom( live ) += overhead( szc( live ) ) ./ amort( live );
  szc  ( live )  = parent_szc( szc( live ) );
endwhile

eff_min = obj_val_min./denom;
eff_avg = obj_val_avg./denom;
eff_max = obj_val_max./denom;

szc_idx = 0:(szc_cnt-1);

subplot(2,1,1);
semilogy( szc_idx, [ obj_val_min; obj_val_avg; obj_val_max ] );
axis tight;
grid;
vv = axis; hold on; semilogy( [ szc_thresh szc_thresh ], [vv(3) vv(4)] ); hold off;
xlabel( 'sizeclass index' );
ylabel( 'object size (min/avg/max)' );

subplot(2,1,2);
semilogy( szc_idx, 1 - [eff_min; eff_avg; eff_max] );
axis tight;
grid;
vv = axis; hold on; semilogy( [ szc_thresh szc_thresh ], [vv(3) vv(4)] ); hold off;
xlabel( 'sizeclass index' );
ylabel( 'footprint overhead frac (min/avg/max)' );
