toolchain(
    name = "x86_64_linux_llvm",
    target_compatible_with = ["//bazel/compiler:llvm"],
    toolchain = "@llvm14//:cc-clang-x86_64-linux",
    toolchain_type = "@bazel_tools//tools/cpp:toolchain_type",
    visibility = ["//visibility:public"],
)
