# Script for generating NTT twiddle tables for Falcon-512.
# Ported from: https://github.com/Rexicon226/zk/blob/a2bc12eb229a3f4665f98c1b6dcc9d3b2ea299fa/src/signatures/falcon.zig#L138

Q = 12289
LOGN = 9
N = 1 << 9 # 512

# Show that the field is "NTT friendly"
assert(Q % (2 * N) == 1)

# Computes x^-1 mod Q
def inv(x, m=Q):
    t, new_t = 0, 1
    r, new_r = m, x
    while new_r != 0:
        quo = r // new_r
        t, new_t = new_t, t - quo * new_t
        r, new_r = new_r, r - quo * new_r
    if r > 1:
        raise ValueError(f"could not find inverse of {x} mod {m}")
    if t < 0:
        t += m
    return t

# Computes a primitive 2*N-th root of unity in $\mathbb{Z}_q$.
def find_psi():
  psi = None
  exp = (Q - 1) // (2 * N)
  for i in range(1, Q):
    g  = pow(i, exp, Q)
    if pow(g, N, Q) != 1:
      return g
  raise RuntimeError("no primitive 2*N-th root of unity!")

def bitreverse(x, bits=LOGN):
  result = 0
  for _ in range(bits):
      result = (result << 1) | (x & 1)
      x >>= 1
  return result

# Computes the bit-reversed powers of `x`, from 0 to N - 1.
def powers(x):
  pows = [1] * N
  fqs  = [1] * N
  for i in range(1, N):
    pows[i] = (pows[i - 1] * x) % Q
    fqs[bitreverse(i)] = pows[i]
  return fqs

def format_array(name, values, typename="fd_falcon_fq_t"):
  lines = []
  lines.append(f"static const {typename} {name}[{len(values)}] = {{")
  row = []
  for i, v in enumerate(values):
      row.append(f"{v:5d}")
      if len(row) == 12 or i == len(values) - 1:
          trailing = "," if i < len(values) - 1 else ""
          lines.append("  " + ", ".join(row) + "," if i < len(values) - 1 else "  " + ", ".join(row))
          row = []
  lines.append("};")
  return "\n".join(lines)

psi = find_psi()
positive = powers(psi)
negative = powers(inv(psi))

header = f"""\
/* Auto-generated by generate_fft.py */

#ifndef HEADER_fd_src_ballet_falcon_fd_falcon_twiddle_h
#define HEADER_fd_src_ballet_falcon_fd_falcon_twiddle_h

/* psi_positive[i] = bitrev(i)-th power of psi mod Q */
{format_array("fd_falcon_psi_positive", positive)}

/* psi_negative[i] = bitrev(i)-th power of psi^-1 mod Q */
{format_array("fd_falcon_psi_negative", negative)}

#endif /* HEADER_fd_src_ballet_falcon_fd_falcon_twiddle_h */
"""

outfile = "fd_falcon_twiddle.h"
with open(outfile, "w") as f:
  f.write(header)
