#!/bin/bash

if [ $# -ne 1 ]; then
  echo ""
  echo "        Usage: $0 [APP]"
  echo ""
  exit 1
fi

APP=$1
shift 1

CONF=tmp/$APP.cfg
. "$CONF" || exit $?

FD_LOG_PATH=""
export FD_LOG_PATH

#$BUILD/bin/fd_tango_ctl signal-cnc $MAIN_CNC halt
# FIXME: PKILL?

"$BUILD"/bin/fd_wksp_ctl delete "$WKSP"
rm -fv "$CONF"

echo success
exit 0

