$(call add-hdrs,fd_shred.h)
$(call add-objs,fd_shred,fd_ballet)
$(call add-objs,fd_shredder,fd_ballet)
$(call add-objs,fd_fec_set,fd_ballet)
$(call make-unit-test,test_shred,test_shred,fd_ballet fd_util fd_reedsol)
$(call make-unit-test,test_deshredder,test_deshredder,fd_ballet fd_util)
$(call make-unit-test,test_shredder,test_shredder,fd_ballet fd_util fd_reedsol)
$(call make-unit-test,test_fec_resolver,test_fec_resolver,fd_ballet fd_tango fd_util fd_reedsol)
$(call run-unit-test,test_shred,)
