/* Code generated by gen_features.py. DO NOT EDIT. */

#include "fd_features.h"
#include <stddef.h>

void
fd_features_enable_all( fd_features_t * f ) {
  for( fd_feature_id_t const * id = fd_feature_iter_init();
    !fd_feature_iter_done( id );
    id = fd_feature_iter_next( id ) ) {
    fd_features_set( f, id, 0UL );
  }
}

void
fd_features_disable_all( fd_features_t * f ) {
  for( fd_feature_id_t const * id = fd_feature_iter_init();
    !fd_feature_iter_done( id );
    id = fd_feature_iter_next( id ) ) {
    fd_features_set( f, id, FD_FEATURE_DISABLED );
  }
}

void
fd_features_enable_defaults( fd_features_t * f ) {
  for( fd_feature_id_t const * id = fd_feature_iter_init();
    !fd_feature_iter_done( id );
    id = fd_feature_iter_next( id ) ) {
      if ( id->default_activated == 1) {
        fd_features_set( f, id, 0UL );
      }
    }
}

fd_feature_id_t const ids[] = {
  { .index  = offsetof(fd_features_t, deprecate_rewards_sysvar)>>3,
    .id     = {"\xe7\x5f\xc6\x7c\x5f\x30\x77\x25\xb6\x9e\x15\xbc\x0f\xd3\x26\x29\x0b\x7c\x02\x21\xaf\x9b\x5a\x1d\xfe\xac\x67\x40\x80\x67\x4c\x3a"}
              /* GaBtBJvmS4Arjj5W1NmFcyvPjsHN38UGYDq2MDwbs9Qu */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, pico_inflation)>>3,
    .id     = {"\x32\xda\x36\xc8\x6b\xd3\x95\x70\x85\x28\x50\xc5\x40\xb6\xea\xeb\xda\xf1\xca\x6d\x30\x85\x46\x37\x34\xa2\x73\x4c\xd7\xb3\x83\x80"}
              /* 4RWNif6C2WCNiKVW7otP4G7dkmkHGyKQWRpuZ1pxKU5m */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, devnet_and_testnet)>>3,
    .id     = {"\xb8\xf9\x9d\x82\x20\x0f\x99\x8b\x98\xc4\x89\xbc\x09\x52\xdf\x91\x9e\xf2\xb5\x9b\xe9\xf7\x54\xee\xea\x83\x26\x25\x63\xbb\xec\x05"}
              /* DT4n6ABDqs6w4bnfwrXT9rsprcPf6cdDga1egctaPkLC */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, vote)>>3,
    .id     = {"\xa3\x3a\x7e\xd2\x59\x88\xe1\x47\x3f\x2d\xd4\xb8\xd8\x11\xea\x38\x4d\xf8\x81\x37\x10\xd2\x32\xe0\xaf\xc1\x60\x43\xf1\xbf\xbf\xac"}
              /* BzBBveUDymEYoYzcMWNQCx3cd4jQs7puaVFHLtsbB6fm */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, enable)>>3,
    .id     = {"\x60\xf1\x06\xaa\x86\x1f\x57\xe7\x69\x46\x83\x60\x05\x72\x0e\x3a\xe9\xfb\xb0\x6b\xb0\x66\x90\xe6\x29\xa6\x61\x92\x93\xbe\x01\x7d"}
              /* 7XRJcS5Ud5vxGB54JbK9N2vBZVwnwdBNeJW1ibRgD9gx */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, secp256k1_program_enabled)>>3,
    .id     = {"\xc1\xc4\x49\x57\x9c\x05\x24\xd9\xe1\x68\xa6\x5a\x60\xd6\x93\x3f\x7a\xfc\x55\x08\x10\xf6\x46\x64\x97\x01\xc4\x7e\x18\x6d\x5b\x35"}
              /* E3PHP7w8kB7np3CTQ1qQ2tW3KCtjRSXBQgW9vM2mWv2Y */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, spl_token_v2_multisig_fix)>>3,
    .id     = {"\xc2\x42\x47\x80\xbd\x67\x99\x15\xf7\x8a\x1c\x2d\xbb\x79\x78\x72\x57\x8d\x17\xc3\x31\x54\x76\x9b\x95\x50\x53\x22\x88\x28\x61\x83"}
              /* E5JiFDQCwyC6QfT9REFyMpfK2mHcmv1GUDySU1Ue7TYv */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, no_overflow_rent_distribution)>>3,
    .id     = {"\x37\xcc\xe6\x49\xe2\xfe\x41\x1d\x3a\xe6\xbc\x60\x13\x4d\x6f\xde\xfe\xa7\x6d\x00\xbf\x5c\x39\x18\x30\x8f\xe0\x0c\x54\x97\x7d\x45"}
              /* 4kpdyrcj5jS47CZb2oJGfVxjYbsMm2Kx97gFyZrxxwXz */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, filter_stake_delegation_accounts)>>3,
    .id     = {"\xe2\x3b\x63\x48\xdf\xee\xd8\xa6\xb1\xa0\x60\x8e\x76\xaf\x9e\xac\x8f\x04\x44\xb4\xc5\x26\xcb\x0d\x0e\xaf\xf2\xa6\x51\xbb\xd6\x5b"}
              /* GE7fRxmW46K6EmCD9AMZSbnaJ2e3LfqCZzdHi9hmYAgi */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, require_custodian_for_locked_stake_authorize)>>3,
    .id     = {"\xb3\x41\x74\x3e\x7f\x9c\xb7\x65\xa1\x86\x5b\xac\x72\x3a\x52\xcf\xbe\x72\x16\xea\x00\x36\xae\x50\xca\x19\xe6\x37\xfa\x7a\x7a\x4e"}
              /* D4jsDcXaqdW8tDAWn8H4R25Cdns2YwLneujSL1zvjW6R */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, spl_token_v2_self_transfer_fix)>>3,
    .id     = {"\x99\x7c\x1c\x87\xf2\x9a\x94\x51\x7f\x02\x2a\x51\x9c\xb9\xee\xd4\xac\xd0\x86\xdf\xad\x15\xee\xce\xbb\x56\x25\xd7\x26\x2e\xf8\x28"}
              /* BL99GYhdjjcv6ys22C9wPgn2aTVERDbPHHo4NbS3hgp7 */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, warp_timestamp_again)>>3,
    .id     = {"\xec\x81\xa2\x94\x94\x89\xa4\xfa\xeb\xca\x4d\xb5\x9a\x5f\x29\x03\x7b\xbb\x84\x7e\x8a\x53\xfb\x72\xe2\x35\x5d\xce\xa5\xdc\x04\xb2"}
              /* GvDsGDkH5gyzwpDhxNixx8vtx1kwYHH13RiNAPw27zXb */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, check_init_vote_data)>>3,
    .id     = {"\x26\xd6\xbf\x1a\x22\x53\xab\x30\xc7\xee\x40\x65\x9c\xa3\x5d\xd9\x95\x33\x6d\x11\x41\x80\x06\x9c\x93\xce\xf1\xf6\xa0\x90\x19\xee"}
              /* 3ccR6QpxGYsAbWyfevEtBNGfWV4xBffxRj2tD6A9i39F */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, secp256k1_recover_syscall_enabled)>>3,
    .id     = {"\x50\xad\x03\x00\xb1\xb2\xb8\x4a\x95\x65\xa6\x37\x8b\x00\x7a\x9b\x20\xae\xd5\x18\x05\xfc\xaf\x8f\xfa\x0e\x59\x87\x5e\x6c\x15\xb5"}
              /* 6RvdSWHh8oh72Dp7wMTS2DBkf3fRPtChfNrAo3cZZoXJ */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, system_transfer_zero_check)>>3,
    .id     = {"\xa1\x40\x32\xb0\x82\x73\xf9\xe8\xbf\x3e\xb7\x3f\x14\x51\x73\x4e\xe3\x13\x42\xeb\x1f\xb7\xb8\x7f\x9b\x61\x6b\xeb\xe3\xdb\xe9\x77"}
              /* BrTR9hzw4WBGFP65AJMbpAo64DcA3U6jdPSga9fMV5cS */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, blake3_syscall_enabled)>>3,
    .id     = {"\xf4\x84\xea\xee\xb8\xa4\x94\xe9\x28\x63\x46\xac\x46\x52\xff\x97\xa2\xca\x0d\x75\x29\xce\x59\x81\x14\x6e\x83\x07\x1f\x14\x9d\xb2"}
              /* HTW2pSyErTj4BV6KBM9NZ9VBUJVxt7sacNWcf76wtzb3 */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, dedupe_config_program_signers)>>3,
    .id     = {"\x73\x15\x7f\xdd\x92\xe0\xa1\x10\xaa\xbb\x79\xc2\x61\x81\x1e\xd2\xf7\xd5\x72\x9c\x19\xd7\x3e\x17\xd0\xbb\xb0\x23\xa7\x9d\x86\xaf"}
              /* 8kEuAshXLsgkUEdcFVLqrjCGGHVWFW99ZZpxvAzzMtBp */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, verify_tx_signatures_len)>>3,
    .id     = {"\xc8\x75\x24\x77\x9e\x25\xeb\xc6\xc2\x06\x09\x6b\xf5\x53\xcf\x2f\x25\x71\x64\x39\xad\xd0\xa4\x0d\x97\xc8\xc1\x6d\x53\x94\x30\xbd"}
              /* EVW9B5xD9FFK7vw1SBARwMA4s5eRo5eKJdKpsBikzKBz */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, vote_stake_checked_instructions)>>3,
    .id     = {"\x9d\xad\xd7\x70\x49\x9c\xa6\xfb\x4b\x28\x5d\x39\x39\x90\x51\xc6\xdc\xcf\x23\x49\xea\x0d\x57\x35\xe6\x4b\x0b\x8f\x11\x2e\x5c\x6a"}
              /* BcWknVcgvonN8sL4HE4XFuEVgfcee5MwxWPAgP6ZV89X */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, rent_for_sysvars)>>3,
    .id     = {"\x99\x3e\x31\xa6\xc4\x08\xb5\xb5\x8f\xcf\x29\x40\xbb\x18\x48\xd6\xb9\x5f\xdd\x02\xf5\x82\x52\x1d\x7f\x4c\x29\xb4\xdd\x9b\x2d\x20"}
              /* BKCPBQQBZqggVnFso5nQ8rQ4RwwogYwjuUt9biBjxwNF */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, libsecp256k1_0_5_upgrade_enabled)>>3,
    .id     = {"\xbc\xc4\xa0\xbf\x2a\x1d\xff\xab\xfb\x42\xa2\xef\x03\xf5\x22\x58\x81\x49\xde\x86\x00\xff\x86\x83\xd1\x55\x96\x33\xb8\x1b\x1e\xdc"}
              /* DhsYfRjxfnh2g7HKJYSzT79r74Afa1wbHkAgHndrA1oy */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, tx_wide_compute_cap)>>3,
    .id     = {"\x45\x1a\x12\x50\x21\xe1\x52\xa9\xef\xa5\xf0\xf1\x60\xbb\x15\x33\x4f\x3b\xc0\x13\x88\x23\x17\xa3\x84\x55\xf3\xd5\x61\x09\x27\xd4"}
              /* 5ekBxc8itEnPv4NzGJtr8BVVQLNMQuLMNQQj7pHoLNZ9 */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, spl_token_v2_set_authority_fix)>>3,
    .id     = {"\xd6\xe1\x16\xa1\x46\x5c\x88\x62\xb2\x99\x24\x9c\x29\xf0\x9d\x10\x50\x27\x40\xb8\xa7\x13\x6d\xde\x12\xef\x53\x75\x0e\x3a\xe7\xc2"}
              /* FToKNBYyiF4ky9s8WsmLBXHCht17Ek7RXaLZGHzzQhJ1 */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, merge_nonce_error_into_system_error)>>3,
    .id     = {"\x0e\xe6\x6e\xd3\x90\x03\x83\xd5\xa5\xb2\xec\xe6\xd8\xad\xa3\x60\x5f\x4d\x2a\xb0\xdb\xab\xee\x2e\x9a\x94\x66\x54\x46\xd1\x62\x36"}
              /* 21AWDosvp3pBamFW91KB35pNoaoZVTM7ess8nr2nt53B */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, disable_fees_sysvar)>>3,
    .id     = {"\xfe\xfc\xaa\xcf\xc3\xaa\x00\xff\xf5\xe9\x30\x87\xf9\x49\x49\x4b\x71\x4d\xd3\x7d\x4d\xc5\xd8\x2d\x5e\xa1\xcb\xec\x4d\xfb\x49\x93"}
              /* JAN1trEUEtZjgXYzNBYHU9DYd7GnThhXfFP7SzPXkPsG */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, stake_merge_with_unmatched_credits_observed)>>3,
    .id     = {"\x0b\x6f\xdf\x75\xce\xc4\x22\x6d\xdb\x7c\x88\xf7\xcd\x32\xb5\x2f\xf4\x8f\xba\x47\xce\x7a\x0a\x83\xae\x0e\xfb\x11\x03\x9a\x7e\x07"}
              /* meRgp4ArRPhD3KtCY9c5yAf2med7mBLsjKTPeVUHqBL */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, zk_token_sdk_enabled)>>3,
    .id     = {"\x0e\xca\xbe\x52\x62\x63\x44\xd5\x41\x60\x53\x0c\x35\x83\xe3\xa4\x81\x07\xdf\x19\x47\xbf\xf9\x4e\x80\x6b\x53\x88\x06\x46\x9a\xdb"}
              /* zk1snxsc6Fh3wsGNbbHAJNHiJoYgF29mMnTSusGx5EJ */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, curve25519_syscall_enabled)>>3,
    .id     = {"\x65\xdc\x35\xc6\x6f\x58\x1e\x4b\x7f\x4e\xe4\x3c\x60\x48\x03\x3f\x33\x88\x72\x50\x61\x81\xf7\x08\x47\x16\x9a\x51\xb9\x72\xd2\xe9"}
              /* 7rcw5UtqgDTBBv2EcynNfYckgdAaH1MAsCjKgXMkN7Ri */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, versioned_tx_message_enabled)>>3,
    .id     = {"\x22\x78\xa2\xf5\x73\x65\xa4\x7c\x62\x3b\xfa\x86\xf3\x78\x94\xac\x71\x21\xbc\x8c\x18\x53\xe7\xd5\xed\xee\xda\xec\xa7\x1f\x59\xe7"}
              /* 3KZZ6Ks1885aGBQ45fwRcPXVBCtzUvxhUTkwKMR41Tca */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, libsecp256k1_fail_on_bad_count)>>3,
    .id     = {"\x70\x98\xf0\x2f\xdb\x58\x69\x1a\xba\xa2\xec\x86\xb4\x8a\xcf\x96\xea\x49\x69\xd6\x97\xe7\x06\xfa\x9b\x08\x12\x54\xf9\x3e\x27\x92"}
              /* 8aXvSuopd1PUj7UhehfXJRg6619RHp8ZvwTyyJHdUYsj */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, libsecp256k1_fail_on_bad_count2)>>3,
    .id     = {"\x3c\x48\x08\xa9\xa9\x6b\x76\x15\x09\x65\x48\xc5\x3b\x5c\x2d\x94\xac\x24\xba\x3d\xe3\x96\xb4\xda\x47\x43\xf0\xfe\x52\xe3\xdb\x01"}
              /* 54KAoNiUERNoWWUhTWWwXgym94gzoXFVnHyQwPA18V9A */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, instructions_sysvar_owned_by_sysvar)>>3,
    .id     = {"\xee\x6e\xf9\xea\xd9\x55\x5c\x4b\x5b\x67\xec\x20\x84\x44\xe4\xfb\x95\x77\xbc\x1e\x0e\xb2\xba\x54\x3f\xe7\x19\x5e\x90\xb3\x10\x9a"}
              /* H3kBSaKdeiUsyHmeHqjJYNc27jesXZ6zWj3zWkowQbkV */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, stake_program_advance_activating_credits_observed)>>3,
    .id     = {"\x06\x72\x68\x6a\x60\xe5\x62\xf1\x9c\x80\x56\xf7\x31\x18\x56\x52\x03\x26\x9d\x1a\x9c\x5e\x42\xb7\x76\x73\x32\x21\xe7\x2c\x86\xfe"}
              /* SAdVFw3RZvzbo6DvySbSdBnHN4gkzSTH9dSxesyKKPj */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, credits_auto_rewind)>>3,
    .id     = {"\x9b\x9b\xd1\xb9\xd4\x1e\xdd\x35\x8b\xcf\x42\x55\x5f\xc4\x5c\xd0\x84\xfb\xa8\x2c\x6a\x16\xa5\x5e\x77\xb4\x86\xaf\x50\xa4\x60\xbb"}
              /* BUS12ciZ5gCoFafUHWW8qaFMMtwFQGVxjsDheWLdqBE2 */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, demote_program_write_locks)>>3,
    .id     = {"\x21\x0f\x03\x96\x77\x13\xbf\x30\x1d\xb3\xfc\x8a\x64\xe0\xc6\x24\x2c\xca\x69\x56\x80\x86\x96\x61\xfb\x6a\xe6\xba\xd8\x02\x7a\x3d"}
              /* 3E3jV7v9VcdJL8iYZUMax9DiDno8j7EWUVbhm9RtShj2 */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, ed25519_program_enabled)>>3,
    .id     = {"\x56\x8a\x46\x9d\x0c\xe9\xec\xa5\xc0\x60\x9f\xa0\xf5\xe8\xc8\xb3\xc1\xfb\xd8\xca\x84\xf9\xfa\xcd\x68\xcf\xba\xf1\xc7\x18\x57\xb4"}
              /* 6ppMXNYLhVd7GcsZ5uV11wQEW7spppiMVfqQv5SXhDpX */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, return_data_syscall_enabled)>>3,
    .id     = {"\xc0\x3e\x8f\x61\x16\x40\x08\xf1\xfd\xa9\x49\x58\x8a\x4a\x53\x0c\xb0\x4b\xb1\x0b\x46\xa7\x1e\x77\x15\xd5\x74\xcd\xf2\x3d\xfc\x3c"}
              /* DwScAzPUjuv65TMbDnFY7AgwmotzWy3xpEJMXM3hZFaB */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, reduce_required_deploy_balance)>>3,
    .id     = {"\xc3\xe2\xb3\x5c\xd6\x3c\xbe\x92\x36\xe4\xbb\x17\x1e\xd7\x1a\x11\x85\x1d\xeb\x1f\x6e\xec\x3c\x75\x98\x3c\xc1\x7d\x3c\x1c\xf3\x3a"}
              /* EBeznQDjcPG8491sFsKZYBi5S5jTVXMpAKNDJMQPS2kq */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, sol_log_data_syscall_enabled)>>3,
    .id     = {"\x57\xc2\x46\x11\xf5\xd2\x02\xbd\xd6\xe0\x83\x46\xe7\x7d\xc9\x21\x47\x32\x1b\x9f\xac\x5f\xf4\xf1\x68\x37\x3c\x07\x9a\xb7\x8f\xcc"}
              /* 6uaHcKPGUy4J7emLBgUTeufhJdiwhngW6a1R9B7c2ob9 */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, stakes_remove_delegation_if_inactive)>>3,
    .id     = {"\xf1\x86\xf8\x9c\x94\xef\xd1\xfc\x05\x66\x9f\x41\xf1\x9e\x48\xa4\x47\xb6\xf8\xd1\x26\xb6\x77\x7d\x87\xde\x1c\x74\xe0\x93\xff\x11"}
              /* HFpdDDNQjvcXnXKec697HDDsyk6tFoWS2o8fkxuhQZpL */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, do_support_realloc)>>3,
    .id     = {"\x5a\x5e\x4f\xf5\xe1\x44\x2a\xee\xd4\xd2\xd4\x9e\x6c\x79\x96\x42\x36\xd3\x54\x59\xc0\x34\x49\x13\xd5\xb6\xed\xb1\xdd\x17\x55\xc8"}
              /* 75m6ysz33AfLA5DDEzWM1obBrnPQRSsdVQ2nRmc8Vuu1 */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, prevent_calling_precompiles_as_programs)>>3,
    .id     = {"\x2f\x17\x33\x1d\xb1\xc6\x48\xc5\xae\xfd\x61\x48\xb0\xca\xc9\xf0\x3e\x42\xd4\x6f\x80\x44\x47\x92\xda\x04\x00\x72\xd1\xe8\x0b\xaa"}
              /* 4ApgRX3ud6p7LNMJmsuaAcZY5HWctGPr5obAsjB3A54d */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, optimize_epoch_boundary_updates)>>3,
    .id     = {"\x10\x28\xe6\xaf\xee\x77\xd2\xf1\x33\x5c\x08\x51\xf2\x30\x66\x91\x71\x7e\x84\x6f\x76\xa3\x94\xaf\x67\xb1\x8c\x86\xf1\x40\x4c\x40"}
              /* 265hPS8k8xJ37ot82KEgjRunsUp5w4n4Q4VwwiN9i9ps */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, remove_native_loader)>>3,
    .id     = {"\xf4\x82\x43\xf9\xcd\x6a\xb8\xbd\x79\xb6\x7e\x15\x77\x72\x05\xd6\xff\xb9\xef\x89\xf9\x64\xc1\xdc\x8c\xdb\xc7\xc3\x11\x03\x40\x2c"}
              /* HTTgmruMYRZEntyL3EdCDdnS6e4D5wRq1FA7kQsb66qq */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, send_to_tpu_vote_port)>>3,
    .id     = {"\xa4\xa2\xa0\xaf\xed\x4a\x65\xa7\x9d\xa8\x3c\xf1\xc7\x77\xe0\xd7\x25\xc6\x08\x60\x7c\x5b\xbb\xe3\x12\x19\xd8\x49\xad\xbc\x86\xb4"}
              /* C5fh68nJ7uyKAuYZg2x9sEQ5YrVf3dkW6oojNBSc3Jvo */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, requestable_heap_size)>>3,
    .id     = {"\xa6\x7c\xcf\xd5\xf5\x8e\xb2\x3a\x0c\xcc\xa6\xc3\x5b\x15\x41\x3b\x89\x47\xa2\xd7\x0e\x67\x2d\x02\xa3\x2a\x6a\xf1\x58\x9e\x6f\xa2"}
              /* CCu4boMmfLuqcmfTLPHQiUo22ZdUsXjgzPAURYaWt1Bw */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, disable_fee_calculator)>>3,
    .id     = {"\x19\xc1\x13\x2c\x6a\xd5\x21\x90\x8f\x76\x04\xb4\xeb\x7e\x74\xf4\xf0\x22\x7e\x6c\xe6\x35\xf2\xa9\xa9\xc7\xbb\x97\x0e\x99\xe0\x66"}
              /* 2jXx2yDmGysmBKfKYNgLj2DQyAQv6mMk2BPh4eSbyB4H */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, add_compute_budget_program)>>3,
    .id     = {"\x35\xd0\xac\xad\xb3\x34\x81\x2b\xc2\x6f\x22\x22\x73\xad\x66\x01\xbb\xc9\x5e\x9b\xa8\x4f\x17\x8f\x46\x5d\xf2\x28\xa4\x04\xf0\x6b"}
              /* 4d5AKtxoh93Dwm1vHXUU3iRATuMndx1c431KgT2td52r */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, nonce_must_be_writable)>>3,
    .id     = {"\x9f\x22\xa6\x0f\x43\x25\xec\x1c\x13\x1d\xfc\x40\x8a\x79\x56\xd8\x87\x16\x30\x5c\xc8\xb8\xc0\x9b\x2d\x8d\xb7\x55\x7d\x84\xc5\x7d"}
              /* BiCU7M5w8ZCMykVSyhZ7Q3m2SWoR2qrEQ86ERcDX77ME */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, spl_token_v3_3_0_release)>>3,
    .id     = {"\xdd\x49\x16\xe6\xf1\xc4\x8d\x4c\x6b\x98\xd4\x11\xea\x18\x15\xbc\xef\x97\x90\x40\x59\xd7\x3d\x5a\xb9\xe9\x9a\x22\xf5\x12\xe8\x55"}
              /* Ftok2jhqAqxUWEiCVRrfRs9DPppWP8cgTB7NQNKL88mS */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, leave_nonce_on_success)>>3,
    .id     = {"\xc3\x0a\x76\x46\x54\x06\x9e\xe7\xfd\xe2\x47\xed\xe9\x44\x6b\x05\x85\xe0\x92\x21\x63\x31\x88\xe4\x8c\x5a\x29\x0d\xe6\x01\x10\x33"}
              /* E8MkiWZNNPGU6n55jkGzyj8ghUmjCHRmDFdYYFYHxWhQ */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, reject_empty_instruction_without_program)>>3,
    .id     = {"\x82\x0b\x2c\xb4\x44\xcd\x63\x7a\x12\x05\x77\x50\xa2\x72\x55\x41\x5e\x5f\x34\x66\xab\xbc\x0d\x72\x6e\x1e\x2b\x78\x5f\xec\x19\xdb"}
              /* 9kdtFSrXHQg3hKkbXkQ6trJ3Ja1xpJ22CTFSNAciEwmL */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, fixed_memcpy_nonoverlapping_check)>>3,
    .id     = {"\x1f\x18\xa1\x64\x25\xc5\x8b\x16\x22\xe0\x41\xcf\xbe\x3b\xbc\x24\xfe\x3b\xc5\xea\x7d\xe5\x1d\x35\x34\x3c\xb6\x3d\xe8\x32\xb4\xfc"}
              /* 36PRUK2Dz6HWYdG9SpjeAsF5F3KxnFCakA2BZMbtMhSb */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, reject_non_rent_exempt_vote_withdraws)>>3,
    .id     = {"\x66\x75\x86\xfd\xae\x10\xf0\xe4\xe7\x44\x72\x25\xed\x6a\x21\xf1\xc3\x9f\x3f\xcf\x58\xf0\x54\xbc\x98\x45\xbc\xf5\x37\x15\x74\x7e"}
              /* 7txXZZD6Um59YoLMF7XUNimbMjsqsWhc7g2EniiTrmp1 */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, evict_invalid_stakes_cache_entries)>>3,
    .id     = {"\xc6\x69\xa1\x8d\x1d\x65\x5d\xa8\x4f\x4c\x6b\x6b\x4b\xa2\x16\x11\x68\x2b\xdf\x04\x2d\xb7\x92\xe0\xbd\x76\x7c\x55\x1a\x69\xc2\xb2"}
              /* EMX9Q7TVFAmQ9V1CggAkhMzhXSg8ECp7fHrWQX2G1chf */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, allow_votes_to_directly_update_vote_state)>>3,
    .id     = {"\xd9\xc8\x44\x04\x08\x9a\xc9\x7b\x21\x9b\x5e\x12\x1b\x56\x70\xc5\xc4\xe2\x73\x67\x87\x69\x92\x78\x1e\xd0\xda\x67\xc6\x2e\x6c\xf6"}
              /* Ff8b1fBeB86q8cjq47ZhsQLgv5EkHu3G1C99zjUfAzrq */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, cap_accounts_data_len)>>3,
    .id     = {"\x09\x1d\x90\xf1\x7c\x23\x03\x02\xed\xea\x26\xcc\xf4\x7f\xfa\xeb\xef\x7e\x27\x9f\x24\x13\x11\xef\x36\x3a\x3a\x45\x04\x05\xd7\x27"}
              /* capRxUrBjNkkCpjrJxPGfPaWijB7q3JoDfsWXAnt46r */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, max_tx_account_locks)>>3,
    .id     = {"\xa6\x31\x3c\x36\xed\x67\x8f\x7e\xef\xc9\x44\x42\xce\x35\x41\x3c\x52\xba\x5b\xac\x0f\x39\x32\x63\x68\xae\x73\xed\x85\x07\xc1\x9b"}
              /* CBkDroRDqm8HwHe6ak9cguPjUomrASEkfmxEaZ5CNNxz */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, require_rent_exempt_accounts)>>3,
    .id     = {"\x9f\xa8\xed\x33\x9c\x59\x8b\xf2\x53\x9b\xa2\x71\x37\xcd\x3d\xd2\x01\x2c\x35\xa5\x17\x22\xc2\xec\x0e\x31\xe9\xa5\x67\xcd\xa0\xcc"}
              /* BkFDxiJQWZXGTZaJQxH7wVEHkAmwCgSEVkrvswFfRJPD */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, filter_votes_outside_slot_hashes)>>3,
    .id     = {"\x27\xef\x52\xa3\x5a\x38\xed\xff\xf1\x6f\xe8\xd3\x7a\x86\x20\x86\xce\x9e\x4c\xba\xac\x9a\xc7\x23\xdb\x4b\xe2\xaa\x59\x27\x29\x0a"}
              /* 3gtZPqvPpsbXZVCx6hceMfWxtsmrjMzmg8C7PLKSxS2d */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, update_syscall_base_costs)>>3,
    .id     = {"\x19\x20\xa1\x02\xee\xec\xad\x06\xa7\x5e\x1d\xde\x0a\xcf\xef\xd1\xdb\x39\x73\x65\x8a\xa2\x8e\x23\x01\x75\x83\xeb\x6d\xb7\xa2\x3c"}
              /* 2h63t332mGCCsWK2nqqqHhN4U9ayyqhLVFvczznHDoTZ */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, stake_deactivate_delinquent_instruction)>>3,
    .id     = {"\x2d\x1d\xf6\xab\xa3\x87\x99\xd7\x59\x0a\x3e\x32\x5e\x95\xd2\x09\x38\xfc\xde\x62\x68\x65\xe7\xd3\x6d\x58\xd3\x51\x2f\xaa\x35\x1d"}
              /* 437r62HoAdUb63amq3D7ENnBLDhHT2xY8eFkLJYVKK4x */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, stake_redelegate_instruction)>>3,
    .id     = {"\x13\x8c\xc9\x8d\x70\xc1\x6f\xd5\xd7\x6b\xb7\x3b\xbe\x7d\x24\x10\xb9\x97\x59\xf3\xc7\xf6\x2d\x3e\xf1\x91\x44\x64\x85\x5b\xc4\xa3"}
              /* 2KKG3C6RBnxQo9jVVrbzsoSh41TDXLK7gBc9gduyxSzW */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, vote_withdraw_authority_may_change_authorized_voter)>>3,
    .id     = {"\x8d\x0a\x1d\xa1\x3d\x86\x7a\x31\x73\x4d\xc2\x6f\xbd\x80\x15\x55\x52\x82\x02\xd2\x57\x22\x82\x78\x99\xc6\xfe\x95\xf3\x51\x7f\x7d"}
              /* AVZS3ZsN4gi6Rkx2QUibYuSJG3S6QHib7xCYhG6vGJxU */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, spl_associated_token_account_v1_0_4)>>3,
    .id     = {"\xd8\x95\xd3\x92\x53\x47\xac\x96\x6d\x66\x87\x42\x26\xb1\x5b\xa5\xa6\x9d\x36\x8c\x06\xd2\x22\x9c\x5e\xe4\x57\xff\x5d\x01\x59\xc2"}
              /* FaTa4SpiaSNH44PGC4z8bnGVTkSRYaWvrBs3KTu8XQQq */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, reject_vote_account_close_unless_zero_credit_epoch)>>3,
    .id     = {"\x8a\xa3\x5d\x20\x73\xe2\x79\x94\x19\x3e\xf5\x2e\xad\xbf\x80\x94\xd2\x35\x09\x3a\xbb\x3f\x8b\xd7\xf6\x30\x5b\x78\x14\xda\x00\xe0"}
              /* ALBk3EWdeAg2WAGf6GPDUf1nynyNqCdEVmgouG7rpuCj */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, add_get_processed_sibling_instruction_syscall)>>3,
    .id     = {"\xa7\x1b\x0d\xc3\xa8\xf3\x9e\xd8\x70\xe5\xd0\xbe\xa7\xee\x4c\x46\xe6\x0b\x12\x14\x90\x14\x1b\x3c\x55\x32\x1e\x07\xc1\x10\xda\xd3"}
              /* CFK1hRCNy8JJuAAY8Pb2GjLFNdCThS2qwZNe3izzBMgn */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, bank_transaction_count_fix)>>3,
    .id     = {"\x07\x60\x5e\xbb\x59\x63\x27\xe2\xef\x50\xf5\xc8\x99\xc3\x09\xa6\xce\xf3\x0c\x41\x7c\xc6\x8e\xe4\xf0\xfd\xbd\xd8\x83\xfc\x60\xe5"}
              /* Vo5siZ442SaZBKPXNocthiXysNviW4UYPwRFggmbgAp */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, disable_bpf_deprecated_load_instructions)>>3,
    .id     = {"\x25\x93\x52\x9b\xc1\x85\x23\xf0\x0b\xe7\x62\x26\xce\x45\xc6\x2e\xcf\x5f\x8c\xf8\x25\x10\x00\xae\xbf\x40\xbe\xd7\x81\x5b\x8a\x29"}
              /* 3XgNukcZWf9o3HdA3fpJbm94XFc4qpvTXc8h1wxYwiPi */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, disable_bpf_unresolved_symbols_at_runtime)>>3,
    .id     = {"\x3b\x27\x09\x56\xe4\x2a\x76\xf1\x7a\xbd\xf9\x24\x8a\x04\xe7\xff\x6b\x3c\x1d\x0d\xa0\x75\xc1\x8c\x62\x42\x4e\x25\xbd\x62\x6b\x47"}
              /* 4yuaYAj2jGMGTh1sSmi4G2eFscsDq8qjugJXZoBN6YEa */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, record_instruction_in_transaction_context_push)>>3,
    .id     = {"\x26\x3f\x79\xed\xbf\x52\xf4\xbf\x46\x8e\x6a\xfa\xc1\xd9\xe2\x56\x9e\x5b\x68\x8d\x9a\xbf\x3d\xaf\x55\xd8\x5d\x34\xbb\x4d\xd0\xd2"}
              /* 3aJdcZqxoLpSBxgeYGjPwaYS1zzcByxUDqJkbzWAH1Zb */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, syscall_saturated_math)>>3,
    .id     = {"\xfc\x4b\x96\xf7\x1d\xbd\x05\xe5\x16\xa8\x69\xd1\xb5\xfe\x2f\xff\x89\x07\x77\x53\xc4\xe8\xaf\xc0\x7e\x30\x12\x7a\x35\x09\x4b\x57"}
              /* HyrbKftCdJ5CrUfEti6x26Cj7rZLNe32weugk7tLcWb8 */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, check_physical_overlapping)>>3,
    .id     = {"\x0b\xa8\x23\x5d\x64\x8c\x28\x80\xec\x2d\xf5\x0a\x24\xaf\xfa\x9f\xdf\xa8\x89\x04\x0c\xaf\x8c\x03\xcd\x21\xfe\x9e\x66\x53\xa2\xec"}
              /* nWBqjr3gpETbiaVj3CBJ3HFC5TMdnJDGt21hnvSTvVZ */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, limit_secp256k1_recovery_id)>>3,
    .id     = {"\x63\x2d\x14\xe1\x8f\xb7\x9a\x49\xfc\x41\xbc\x56\xfe\xed\xac\xc0\xa1\xcd\x00\x95\x52\x83\x9a\x6f\xb0\x62\x8f\xc7\x11\x1d\xaa\x75"}
              /* 7g9EUwj4j7CS21Yx1wvgWLjSZeh5aPq8x9kpoPwXM8n8 */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, disable_deprecated_loader)>>3,
    .id     = {"\xe5\xa7\x53\xe4\xca\xd6\x43\x9f\x64\x39\x5a\xd3\xc1\x4d\x38\xe2\x1d\xc7\x04\xf1\xe7\xd8\x80\xf4\x0a\xbc\x86\x38\x5b\xf8\x24\x5b"}
              /* GTUMCZ8LTNxVfxdrw7ZsDFTxXb7TutYkzJnFwinpE6dg */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, check_slice_translation_size)>>3,
    .id     = {"\xea\x31\x4c\xd7\xc6\x76\x2f\x56\x21\x37\x60\xc0\x95\x4d\xc6\x55\x29\x76\x96\x73\xc2\x70\x2a\x55\xc7\x47\x46\x59\xf0\x69\xc8\xfc"}
              /* GmC19j9qLn2RFk5NduX6QXaDhVpGncVVBzyM8e9WMz2F */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, stake_split_uses_rent_sysvar)>>3,
    .id     = {"\xd6\x1b\x8a\xaf\x1d\xe7\x0a\xf7\x21\x06\xb5\x2b\x4b\x9b\x69\xfd\x8d\x3b\x8a\x04\x45\xc3\xeb\xfc\x94\x08\x8a\xa2\xa4\xc7\x91\xa6"}
              /* FQnc7U4koHqWgRvFaBJjZnV8VPg6L6wWK33yJeDp4yvV */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, add_get_minimum_delegation_instruction_to_stake_program)>>3,
    .id     = {"\x06\xa1\x56\x4a\xbf\x71\x63\x7f\x4a\x66\x67\x62\x89\x18\x9b\xd0\x9e\x04\x9b\x64\x09\xb6\xf0\x8a\x44\xd1\xf7\x57\xe6\x33\x38\xea"}
              /* St8k9dVXP97xT6faW24YmRSYConLbhsMJA4TJTBLmMT */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, error_on_syscall_bpf_function_hash_collisions)>>3,
    .id     = {"\x68\x0b\x04\x8f\x62\x8e\xa5\x3c\x7f\xfa\x04\x93\xa4\xd2\x90\xa0\xba\xc9\xbe\xa5\x4a\x03\xa8\x63\x01\xd7\xea\x4f\xa7\x0c\x9e\xdc"}
              /* 8199Q2gMD2kwgfopK5qqVWuDbegLgpuFUFHCcUJQDN8b */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, reject_callx_r10)>>3,
    .id     = {"\x23\x2d\x66\x6d\x5c\x7d\x78\x7e\xf9\x05\x90\x7b\x5c\x5b\xfe\x99\xd2\x8a\x96\xc4\x37\xaa\x40\x2a\x06\x26\x72\x4e\xdd\x3c\x7a\x10"}
              /* 3NKRSwpySNwD3TvP5pHnRmkAQRsdkXWRr1WaQh8p4PWX */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, drop_redundant_turbine_path)>>3,
    .id     = {"\x2f\xd4\x72\x78\xb4\x96\xc4\xff\x58\x4b\x74\x4b\xfc\xec\x33\x90\x63\xd1\x91\xe8\xd1\xa7\xad\x65\xd2\xe2\x5d\xb1\x03\x6f\xd7\x8f"}
              /* 4Di3y24QFLt5QEUPZtbnjyfQKfm6ZMTfa6Dw1psfoMKU */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, executables_incur_cpi_data_cost)>>3,
    .id     = {"\x5d\x1d\x0e\x3f\xf1\x9b\xf2\x2b\x12\x4f\x82\xca\xb7\x35\x84\x0f\x1f\x05\xfe\x3e\x75\x6d\x54\x84\x0a\x12\xc4\xa2\xb8\x85\x18\x7e"}
              /* 7GUcYgq4tVtaqNCKT3dho9r4665Qp5TxCZ27Qgjx3829 */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, fix_recent_blockhashes)>>3,
    .id     = {"\x55\x0b\x57\x3f\x7d\x0a\x3a\x07\xc2\x58\x63\xc5\xbc\xda\x43\x2c\x02\xa0\x84\x0b\x1e\x1a\x2d\xc5\x91\x1f\xa4\xe2\xb8\x7e\x19\xda"}
              /* 6iyggb5MTcsvdcugX7bEKbHV8c6jdLbpHwkncrgLMhfo */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, update_rewards_from_cached_accounts)>>3,
    .id     = {"\x10\xdf\x6b\x25\x2c\xe0\x6a\x4d\x0d\x81\x8a\xa7\xe1\x32\x72\x78\x30\x7b\x44\x13\x29\x55\xff\x2c\x79\xa2\xca\x9d\xd3\x20\xf3\x08"}
              /* 28s7i3htzhahXQKqmS2ExzbEoUypg9krwvtK2M9UWXh9 */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, enable_partitioned_epoch_reward)>>3,
    .id     = {"\x2c\xcd\x49\xd1\x01\x45\x2d\x2e\x60\xc4\x6e\x4a\xe2\xe3\x4b\x6d\x5f\x33\xdc\x75\x97\x0d\x05\x15\x83\xa4\x96\xa7\x3a\x54\x06\x16"}
              /* 41tVp5qR1XwWRt5WifvtSQyuxtqQWJgEK8w91AtBqSwP */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, spl_token_v3_4_0)>>3,
    .id     = {"\xdd\x49\x17\x14\x26\x0f\xf1\xe8\xa1\x87\xe0\x3b\x4b\x80\x5d\xde\xd4\x52\xd3\x90\x4e\x14\x4c\xa2\xc5\x99\x39\x3f\x15\xf2\x37\x85"}
              /* Ftok4njE8b7tDffYkC5bAbCaQv5sL6jispYrprzatUwN */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, spl_associated_token_account_v1_1_0)>>3,
    .id     = {"\xd8\x95\xd3\x48\xf8\xc5\x2a\xe0\x2d\x94\xe2\xa0\xb7\x01\xe6\xc8\x08\x15\xce\x93\x17\x76\x53\xa5\x4a\x7f\x1d\xc3\x19\xe2\xfc\x7b"}
              /* FaTa17gVKoqbh38HcfiQonPsAaQViyDCCSg71AubYZw8 */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, default_units_per_instruction)>>3,
    .id     = {"\xfc\xf2\xfa\x30\x04\x5d\x28\x7b\x6c\xdc\x72\xa5\x33\xff\xa4\x48\x5f\xe4\x00\x16\x31\x6c\x9a\x57\x33\x61\xcf\x2e\x29\x8d\xbe\x57"}
              /* J2QdYx8crLbTVK8nur1jeLsmc3krDbfjoxoea2V1Uy5Q */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, stake_allow_zero_undelegated_amount)>>3,
    .id     = {"\x0c\xec\xcf\x0f\x3b\x1d\xee\xf3\xfc\xd1\xac\x00\xdc\x3f\x98\x31\xae\x6b\xa7\x87\x16\x47\x94\xa5\x77\xba\x87\x40\xf3\x28\x84\x16"}
              /* sTKz343FM8mqtyGvYWvbLpTThw3ixRM4Xk8QvZ985mw */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, require_static_program_ids_in_transaction)>>3,
    .id     = {"\x6b\xc1\xb6\x17\xc3\xb9\x0f\xfc\xe7\x7d\x80\xcb\x58\x53\x93\xc8\xc5\x81\xd1\xbf\x89\xb2\xc7\x16\x31\x03\xc3\x63\x2f\x02\xab\x89"}
              /* 8FdwgyHFEjhAdjWfV2vfqk7wA1g9X3fQpKH7SBpEv3kC */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, stake_raise_minimum_delegation_to_1_sol)>>3,
    .id     = {"\x82\xd9\xad\xdb\xe7\x11\x20\x56\x59\xa5\xb1\x4a\xfe\xf6\x66\x04\x74\x73\x6a\x49\x2c\x1d\x3a\xa0\x92\x59\x3d\x03\x5c\xa8\x16\x39"}
              /* 9onWzzvCzNC2jfhxxeqRgs5q7nFAAKpCUvkj6T6GJK9i */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, stake_minimum_delegation_for_rewards)>>3,
    .id     = {"\xe0\x31\xcd\xc7\x1c\xf7\x58\x54\x9d\x9f\x58\x3b\xa5\xe4\x94\xf7\xc8\x74\xb1\xab\xcf\xed\xe9\x3b\x3b\xce\x1c\xc0\xeb\x2d\xda\xe1"}
              /* G6ANXD6ptCSyNd9znZm7j4dEczAJCfx7Cy43oBx3rKHJ */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, add_set_compute_unit_price_ix)>>3,
    .id     = {"\x78\xe2\x1a\x43\xc1\x90\x64\x60\x36\x9e\x01\x54\xad\x41\x14\x72\x2f\x6b\x2a\x43\xe7\x9b\x9a\x61\xcb\x4b\x37\xa1\x0c\x7f\x4b\xd1"}
              /* 98std1NSHqXi9WYvFShfVepRdCoq1qvsp8fsR2XZtG8g */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, disable_deploy_of_alloc_free_syscall)>>3,
    .id     = {"\x5b\x45\x71\x0e\x10\xc2\x51\xd1\xa1\x7a\xb4\x60\x29\x22\x23\x9c\x36\x0c\xb7\x5a\xd9\x63\x42\x25\x23\x74\xd9\xdc\x01\xaa\x52\x3a"}
              /* 79HWsX9rpnnJBPcdNURVqygpMAfxdrAirzAGAVmf92im */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, include_account_index_in_rent_error)>>3,
    .id     = {"\x15\x08\x72\xd0\x0b\x30\xdc\x2f\x0a\xe0\x27\x5b\x00\xb9\x34\x35\x76\xf1\x2e\xe5\x53\x23\x9e\xf1\x7e\x55\xe1\xbd\x4a\x1e\x56\x23"}
              /* 2R72wpcQ7qV7aTJWUumdn8u5wmmTyXbK7qzEy7YSAgyY */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, add_shred_type_to_shred_seed)>>3,
    .id     = {"\xbf\x23\x52\x59\xab\x2e\x5c\x5a\x43\xb4\x18\xdc\x05\x95\x16\xa5\xc8\x3d\xa3\x9e\x9e\x88\xca\x6d\x8e\xc7\x1c\x40\x7c\x3d\x5c\x73"}
              /* Ds87KVeqhbv7Jw8W6avsS1mqz3Mw5J3pRTpPoDQ2QdiJ */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, warp_timestamp_with_a_vengeance)>>3,
    .id     = {"\x20\x69\x35\x80\x69\xe5\xa7\xdd\xf5\x01\xa4\xd3\x37\x7f\xa7\xa6\x8a\xe9\x93\xe6\x74\x0b\x8d\xfd\x06\xfe\x26\xb0\x9e\xf4\x76\xd9"}
              /* 3BX6SBeEBibHaVQXywdkcgyUk6evfYZkHdztXiDtEpFS */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, separate_nonce_from_blockhash)>>3,
    .id     = {"\xe8\x7f\x28\x34\x34\x97\x58\xc3\xd5\x36\xdd\x4f\x3c\xf7\xd8\x91\x44\x51\x30\x6d\x32\x78\x42\x21\x40\x11\xb5\xd4\x8b\xf0\xe5\xfb"}
              /* Gea3ZkK2N4pHuVZVxWcnAtS6UEDdyumdYt4pFcKjA3ar */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, enable_durable_nonce)>>3,
    .id     = {"\x2f\xfb\x4c\x82\x5c\x65\x10\xe2\x50\x4f\x90\x65\x48\x8d\xe2\x2b\x09\x14\x62\x13\xc9\x6e\x14\x9c\x7b\xce\x06\x85\x91\xf9\x90\xbc"}
              /* 4EJQtF2pkRyawwcTVfQutzq4Sa5hRhibF6QAK1QXhtEX */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, vote_state_update_credit_per_dequeue)>>3,
    .id     = {"\xb1\x2e\xea\x6e\xdc\x3b\xcc\xc3\xcd\x65\x39\xa6\xbc\x49\x71\x55\xd7\x36\xc5\xa3\xc2\xd9\x2f\x0d\x60\x9d\xcd\x37\xa5\x25\x32\x3b"}
              /* CveezY6FDLVBToHDcvJRmtMouqzsmj4UXYh5ths5G5Uv */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, quick_bail_on_panic)>>3,
    .id     = {"\xbe\x6a\x3c\x48\xaf\xd3\x58\x27\xf9\x55\x7f\x90\x79\xad\xad\x74\x63\x47\x6f\x89\xe2\xd9\x43\x3a\xfb\x7f\x55\x53\xdc\xfc\x44\x1c"}
              /* DpJREPyuMZ5nDfU6H3WTqSqUFSXAfw8u7xqmWtEwJDcP */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, nonce_must_be_authorized)>>3,
    .id     = {"\xfc\x09\x9c\x57\xb1\x71\xe5\xb0\x13\x0d\xe7\xa4\x9b\x54\x05\x3b\x8a\x0a\x7f\x93\xdb\xcc\x8f\x9f\x25\x7e\x27\xaf\xc1\xff\x7d\xc3"}
              /* HxrEu1gXuH7iD3Puua1ohd5n4iUKJyFNtNxk9DVJkvgr */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, nonce_must_be_advanceable)>>3,
    .id     = {"\x2b\x0c\x1b\x75\x79\x07\x5d\xcb\x30\xc4\xca\x00\x3c\x94\xa9\x5f\x14\xd9\x92\x5d\x87\xce\xba\x7e\x1f\xd5\xde\xb0\xe0\x90\x50\x34"}
              /* 3u3Er5Vc2jVcwz4xr2GJeSAXT3fAj6ADHZ4BJMZiScFd */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, vote_authorize_with_seed)>>3,
    .id     = {"\x57\x77\x45\x01\x4d\x65\x95\x57\x36\xf5\x6c\xdb\x68\x88\x1a\x5f\x8a\x3e\xa7\xbb\xd2\xfb\x18\x68\x7f\xd8\xfc\xdd\x9b\xf2\x18\xb8"}
              /* 6tRxEYKuy2L5nnv5bgn7iT28MxUbYxp5h7F3Ncf1exrT */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, cap_accounts_data_size_per_block)>>3,
    .id     = {"\x0c\x8c\x43\xcc\xfb\xd3\x99\x67\xa0\x32\x30\xa0\x84\x7b\xfb\x91\xed\xe2\x57\x36\xcb\xaf\xc0\x6a\x1c\x7a\x87\x88\xf5\x81\xbb\x39"}
              /* qywiJyZmqTKspFg2LeuUHqcA5nNvBgobqb9UprywS9N */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, preserve_rent_epoch_for_rent_exempt_accounts)>>3,
    .id     = {"\xf1\xd6\xf1\xbf\x8e\x54\x39\x44\x3d\x29\x52\xb0\xc4\x04\x6d\xf4\x2f\x03\xeb\x95\xc3\x13\xbc\xad\x6c\x1b\x91\x0d\xe3\xbd\x7c\x82"}
              /* HH3MUYReL2BvqqA3oEcAa7txju5GY6G4nxJ51zvsEjEZ */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, enable_bpf_loader_extend_program_ix)>>3,
    .id     = {"\x70\x6d\x18\x65\x6d\x4b\x39\xe5\xf1\xf0\x6a\xaf\x74\xd6\x4c\xc4\x75\xf9\x46\x4d\x36\x80\x64\xf1\x47\x00\xe9\xf2\x4e\x8b\x12\x2d"}
              /* 8Zs9W7D9MpSEtUWSQdGniZk2cNmV22y6FLJwCx53asme */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, enable_early_verification_of_account_modifications)>>3,
    .id     = {"\x60\x7a\xb1\x3a\x4e\x8d\x68\x8f\x13\xba\xcf\xd0\x61\xb5\x93\x07\x83\xc6\x06\x3d\x78\xe8\x67\x55\x90\xa3\x62\xb6\xce\x26\xd6\x75"}
              /* 7Vced912WrRnfjaiKRiNBcbuFw7RrnLv3E3z95Y4GTNc */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, skip_rent_rewrites)>>3,
    .id     = {"\xa7\x53\x9b\xed\x5c\xc7\x64\xe3\x4e\x5c\xb0\x51\xc9\x19\xbf\x17\xbe\x92\xb8\x8b\x5a\x37\x6e\xd2\x33\xa0\xbe\x6b\x31\xa2\x5a\x1c"}
              /* CGB2jM8pwZkeeiXQ66kBMyBR6Np61mggL7XUsmLjVcrw */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, prevent_crediting_accounts_that_end_rent_paying)>>3,
    .id     = {"\x68\x03\xcb\x34\xee\x14\xb9\x41\xe4\x82\x55\xaa\xae\x45\x50\x80\x27\x51\x46\x7f\xc4\x71\xf3\x5a\xf3\x82\x49\xe4\xe9\xfb\xb2\x55"}
              /* 812kqX67odAp5NFwM8D2N24cku7WTm9CHUTFUXaDkWPn */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, cap_bpf_program_instruction_accounts)>>3,
    .id     = {"\x81\xe6\xce\x87\x8e\x3a\xa7\x14\x8e\x5f\x37\x82\xa7\x85\xe7\x8d\xa9\x14\x59\x07\xf5\x22\xf7\x8d\xd4\xa6\x46\x9f\x82\xfa\xec\x58"}
              /* 9k5ijzTbYPtjzu8wj2ErH9v45xecHzQ1x4PMYMMxFgdM */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, loosen_cpi_size_restriction)>>3,
    .id     = {"\xe2\x04\x73\xa5\xa7\x6f\x1e\xe2\x8a\xb6\x64\xde\x46\xec\x20\x34\xdf\xdf\x68\xf9\xe7\x11\x5c\x2c\xe1\x6a\xa6\x27\x91\xec\x3d\xda"}
              /* GDH5TVdbTPUpRnXaRyQqiKUa7uZAbZ28Q2N9bhbKoMLm */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, use_default_units_in_fee_calculation)>>3,
    .id     = {"\x74\xe5\xaa\xa4\x92\x70\x1e\x6d\xdb\xdf\x4d\x06\xd3\x76\x96\x33\x65\x34\xbb\x39\x35\x04\x40\xed\x47\xc9\x90\x52\xd6\xcc\xed\x36"}
              /* 8sKQrMQoUHtQSUP83SPG4ta2JDjSAiWs7t5aJ9uEd6To */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, compact_vote_state_updates)>>3,
    .id     = {"\x69\x5c\xba\x36\x37\x83\xa5\x2c\x1b\xb5\x28\x3d\x3b\xc4\x4b\xc6\x19\xb6\xb5\x14\x1e\x14\xa7\x6a\xf1\xf6\xb8\xb5\x96\xef\xc8\x69"}
              /* 86HpNqzutEZwLcPxS6EHDcMNYWk6ikhteg9un7Y2PBKE */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, incremental_snapshot_only_incremental_hash_calculation)>>3,
    .id     = {"\x10\x1e\xe3\xe6\xb1\x43\x55\x85\x09\x0f\xe0\x6c\xb6\xa5\x1e\xe8\x32\x49\x2a\xec\x96\x74\xe0\x9a\x96\xc7\x86\xc8\x80\x69\x5f\x8c"}
              /* 25vqsfjk7Nv1prsQJmA4Xu1bN61s8LXCBGUPp8Rfy1UF */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, disable_cpi_setting_executable_and_rent_epoch)>>3,
    .id     = {"\x96\xc9\xcb\xaa\x07\x49\x4b\x20\x79\x14\xfa\xee\xb2\x59\xe0\x0f\xdc\x79\xca\x7d\xba\x69\xb2\x5b\x1a\xe8\x15\xd8\x6e\x90\xfa\xc8"}
              /* B9cdB55u4jQsDNsdTK525yE9dmSc5Ga7YBaBrDFvEhM9 */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, on_load_preserve_rent_epoch_for_rent_exempt_accounts)>>3,
    .id     = {"\xaf\xac\x2f\x2c\xdb\xbe\xf1\x80\x0b\x83\x1b\x72\xcd\x82\x2a\x2a\xc2\x80\x87\x59\x79\xca\xd3\xc1\x87\x07\xe9\x67\x10\x2f\x32\x1a"}
              /* CpkdQmspsaZZ8FVAouQTtTWZkc8eeQ7V3uj7dWz543rZ */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, account_hash_ignore_slot)>>3,
    .id     = {"\x06\x88\x0e\xd2\xd7\xba\x96\x67\x8f\x11\x2c\x91\x03\x77\xb7\xc9\xc5\xd4\x04\x96\xe4\xb7\x4c\x8f\x64\xfb\x77\x3f\x84\xd6\x12\xe4"}
              /* SVn36yVApPLYsa8koK3qUcy14zXDnqkNYWyUh1f4oK1 */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, set_exempt_rent_epoch_max)>>3,
    .id     = {"\x49\x4e\x98\x21\x34\x4b\x72\xe0\x04\xd2\x66\xa2\x2e\xf9\xfb\x20\xbd\xba\x5a\xad\xec\xe7\xf6\xbc\x0a\x93\xe4\xd1\x83\xe0\xfd\x8f"}
              /* 5wAGiy15X1Jb2hkHnPDCM8oB9V42VNA9ftNVFK84dEgv */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, relax_authority_signer_check_for_lookup_table_creation)>>3,
    .id     = {"\xd4\xaa\xef\x53\x4b\x5a\xa1\xad\x90\xf8\x49\xb9\x13\x45\x25\x3c\x4c\x39\x46\x28\xb4\xb6\xb4\xfa\x41\x0d\xb5\x1e\xa1\x4f\xa8\xf5"}
              /* FKAcEvNgSY79RpqsPNUV5gDyumopH4cEHqUxyfm8b8Ap */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, stop_sibling_instruction_search_at_parent)>>3,
    .id     = {"\xc9\x39\x83\xfd\x35\x0d\xfd\x41\xbe\x29\x91\x43\x10\x56\xfc\x45\xcf\x1b\x83\x50\x1d\x26\x21\x7f\xf5\x55\x94\xc1\xee\xd6\xb1\xf0"}
              /* EYVpEP7uzH1CoXzbD6PubGhYmnxRXPeq3PPsm1ba3gpo */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, vote_state_update_root_fix)>>3,
    .id     = {"\xe0\x6c\x63\xf3\x55\x30\xb0\x91\xaf\xff\x39\x26\x67\xcb\x54\x16\x02\x4b\x9a\xc7\x1b\x61\xb8\x99\xc6\x41\x30\xe4\xc1\x0b\xac\x79"}
              /* G74BkWBzmsByZ1kxHy44H3wjwp5hp7JbrGRuDpco22tY */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, cap_accounts_data_allocations_per_transaction)>>3,
    .id     = {"\x81\x1a\x5a\x0d\xf1\x24\x2c\x5b\xa0\x2a\x65\x74\xdb\x64\x82\xa1\x77\x98\x85\x5e\x4a\xb0\xe6\x08\xb4\xf7\x34\x9e\xc4\x67\x31\x52"}
              /* 9gxu85LYRAcZL38We8MYJ4A9AwgBBPtVBAqebMcT1241 */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, epoch_accounts_hash)>>3,
    .id     = {"\x3f\x7c\x76\xbc\xf9\xca\x28\x17\x4a\x5a\xf1\x64\x71\x2e\xb4\x6e\x29\x48\x29\x2b\x19\x68\x8e\xf9\xad\x5a\x19\x23\x25\x12\x11\x99"}
              /* 5GpmAKxaGsWWbPp4bNXFLJxZVvG92ctxf7jQnzTQjF3n */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, remove_deprecated_request_unit_ix)>>3,
    .id     = {"\xcb\x11\xd8\x6b\x52\xd0\x9b\x81\xe7\xb7\x56\x74\xa6\x36\x72\x31\x4d\x5f\xb9\x6e\x6e\x87\x1a\x6f\x7a\x87\x4a\x89\xfc\x31\xd4\x27"}
              /* EfhYd3SafzGT472tYQDUc4dPd2xdEfKs5fwkowUgVt4W */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, disable_rehash_for_rent_epoch)>>3,
    .id     = {"\xb9\x15\x86\x82\xd3\x57\x8a\x0d\xd0\xe3\x80\x58\x5a\x23\x9f\x0a\x62\x00\xe7\xf3\x10\xc5\x21\x6c\xd8\xc7\x7f\xb2\xf1\x94\x76\x96"}
              /* DTVTkmw3JSofd8CJVJte8PXEbxNQ2yZijvVr3pe2APPj */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, increase_tx_account_lock_limit)>>3,
    .id     = {"\x7b\xe0\x6c\xe7\xf5\xe5\x27\xb5\x80\x17\x6a\xe2\x84\xd5\xd4\x17\xd6\xf8\x87\xbc\x4b\xbe\xb7\x45\x50\xeb\x91\x07\x48\x35\xe0\x12"}
              /* 9LZdXeKGeBV6hRLdxS1rHbHoEUsKqesCC2ZAPTPKJAbK */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, limit_max_instruction_trace_length)>>3,
    .id     = {"\xe4\xce\x36\xa5\xa6\x94\xc1\x2a\x9b\x4b\x9d\x19\x3e\x5e\x55\x67\x17\x67\x77\x8d\x3e\xe2\xea\x29\xe0\xa4\x04\xed\x88\x25\x26\xf7"}
              /* GQALDaC48fEhZGWRj9iL5Q889emJKcj3aCvHF7VCbbF4 */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, check_syscall_outputs_do_not_overlap)>>3,
    .id     = {"\x2b\x25\x44\x20\xcb\x2b\x86\xa6\xf2\x48\x28\x8b\xc6\x3a\xc5\xd1\x38\x59\x45\xf3\xb3\x68\xcc\xe9\x1b\x2e\x60\x59\x61\xd1\x78\xc2"}
              /* 3uRVPBpyEJRo1emLCrq38eLRFGcu6uKSpUXqGvU8T7SZ */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, enable_bpf_loader_set_authority_checked_ix)>>3,
    .id     = {"\x49\x88\x17\x26\xf7\x23\x43\x9f\xb0\xa3\xf3\x59\xda\xeb\xa1\x8a\x3a\x8e\xd1\xf7\x0c\x15\x1b\x1d\xa4\x92\xb1\x6e\xfa\xe0\xfc\x09"}
              /* 5x3825XS7M2A3Ekbn5VGGkvFoAg5qrRWkTrY4bARP1GL */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, enable_alt_bn128_syscall)>>3,
    .id     = {"\x85\xbf\xc5\xb6\xde\x1e\xef\xaa\xa4\x86\xcc\x6c\x6a\x80\xda\xed\x94\x7b\x18\xac\x7f\x7c\xc2\x5d\xf9\x58\x4a\x86\x98\xb3\xff\x7b"}
              /* A16q37opZdQMCbe5qJ6xpBB9usykfv8jZaMkxvZQi4GJ */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, enable_program_redeployment_cooldown)>>3,
    .id     = {"\xfd\x6d\xcb\x0b\xa2\x88\x5c\x79\xeb\x88\x3d\x86\xf2\xe6\x33\x89\x5a\x3d\x23\x69\x38\x9b\x1f\xa6\xad\xb4\x94\xe2\x3e\xe0\x54\x84"}
              /* J4HFT8usBxpcF63y46t1upYobJgChmKyZPm5uTBRg25Z */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, commission_updates_only_allowed_in_first_half_of_epoch)>>3,
    .id     = {"\x0b\xbb\xa2\x5c\x08\xb9\x8e\x8a\xbc\xe8\xb4\x63\x97\x94\x37\x88\xf2\xa6\xa0\x91\x29\xf3\xc1\x8b\x35\x49\x07\x6a\x1d\x5f\x63\x33"}
              /* noRuG2kzACwgaY7TVmLRnUNPLKNVQE1fb7X55YWBehp */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, enable_turbine_fanout_experiments)>>3,
    .id     = {"\xb2\xcf\xa9\xc3\x4d\xe4\xe6\x33\x25\x4b\x10\xed\xcc\xb9\xf3\x06\xbe\x3b\x9a\xdb\x9c\xed\xc0\x5b\xa2\x9f\xda\x85\x71\xb5\xae\x99"}
              /* D31EFnLgdiysi84Woo3of4JMu7VmasUS3Z7j9HYXCeLY */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, disable_turbine_fanout_experiments)>>3,
    .id     = {"\xed\x7a\x0f\x5d\x50\x53\xdf\xc3\x1a\x51\x89\xb6\x66\xfb\x7e\xb7\xb5\xf8\x91\x7c\xd3\xee\x46\x82\x07\x9e\x28\x44\xb1\xb0\x0d\xf9"}
              /* Gz1aLrbeQ4Q6PTSafCZcGWZXz91yVRi7ASFzFEr1U4sa */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, drop_merkle_shreds)>>3,
    .id     = {"\x69\x08\x18\x1d\x4f\xdb\x4a\x78\x97\x2f\x1b\x4f\x94\xdf\x81\x2b\x60\x4d\x43\xf8\x92\x98\xa4\xdd\x93\xba\x48\xb5\xac\xb8\x3b\xe0"}
              /* 84zy5N23Q9vTZuLc9h1HWUtyM9yCFV2SCmyP9W9C3yHZ */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, keep_merkle_shreds)>>3,
    .id     = {"\xfc\x2b\xba\x88\xd2\xa1\xeb\x71\x75\xdf\x3f\x39\x29\x20\x96\x3b\xfe\xc6\x90\x82\xc6\xbb\xc4\x44\xe3\xde\x9b\x5f\xcc\xbc\xb9\xfe"}
              /* HyNQzc7TMNmRhpVHXqDGjpsHzeQie82mDQXSF9hj7nAH */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, move_serialized_len_ptr_in_cpi)>>3,
    .id     = {"\x59\xf8\x35\x62\xdd\x14\x3d\x82\x30\xdc\x4b\x24\x59\xa9\xa8\xa2\xd6\x12\x67\x7c\x1b\x86\x51\xfd\x02\x1d\x47\x6b\xff\xef\x9b\xca"}
              /* 74CoWuBmt3rUVUrCb2JiSTvh6nXyBWUsK4SaMj3CtE3T */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, update_hashes_per_tick)>>3,
    .id     = {"\x2b\x19\xba\xab\x09\xcd\xf6\xb3\x1b\xf1\x51\xc9\xb4\x3b\x0e\xd7\x89\xcc\x3f\x9a\x80\x21\x94\xfc\xbd\x78\xaf\xab\xe5\x1a\xbd\xf6"}
              /* 3uFHb9oKdGfgZGJK9EHaAXN4USvnQtAFC13Fh5gGFS5B */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, enable_big_mod_exp_syscall)>>3,
    .id     = {"\xc3\xee\x12\xb0\x1a\x5b\x31\x3a\xe4\xe6\xc1\xc1\xb0\x76\x81\xe6\xe4\x62\x1e\xfa\x9e\x71\x16\xfc\x35\x72\xe8\x64\xcd\x4e\xa6\x38"}
              /* EBq48m8irRKuE7ZnMTLvLg2UuGSqhe8s8oMqnmja1fJw */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, disable_builtin_loader_ownership_chains)>>3,
    .id     = {"\x33\x8b\xff\x23\x8a\xab\x0a\x50\xe8\xa3\x35\x8b\x09\x2b\x90\xff\x20\x0b\xde\xe6\x3a\x66\x92\xd7\x6d\x4f\x19\x3d\x10\x52\x93\x31"}
              /* 4UDcAfQ6EcA6bdcadkeHpkarkhZGJ7Bpq7wTAiRMjkoi */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, cap_transaction_accounts_data_size)>>3,
    .id     = {"\xbb\x9b\xb2\xab\xa7\x5e\xe3\xff\x53\x3b\x58\xb3\x2c\x8b\x46\xe9\xfa\x66\xc9\x20\x65\xe4\x90\x65\x5e\xd4\x27\x18\xd9\x85\xef\xe0"}
              /* DdLwVYuvDz26JohmgSbA7mjpJFgX5zP2dkp8qsF2C33V */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, remove_congestion_multiplier_from_fee_calculation)>>3,
    .id     = {"\x87\xc3\x89\x04\xe8\xc4\x22\x8a\x27\x67\xda\xd1\x7b\xe7\x83\xd3\x4e\x0c\x77\xe2\xe2\x94\x79\xbf\x73\xe4\x32\xa6\x91\x44\x90\x6e"}
              /* A8xyMHZovGXFkorFqEmVH2PKGLiBip5JD7jt4zsUWo4H */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, enable_request_heap_frame_ix)>>3,
    .id     = {"\xfa\x49\x56\x3c\xc1\xbc\x82\xce\x81\x12\x31\x04\x9a\xe1\x37\xce\xbe\x3a\xb5\xad\x0d\xd1\xd7\x70\xb8\x8c\x90\xbb\x45\xd3\xc9\xf7"}
              /* Hr1nUA9b7NJ6eChS26o7Vi8gYYDDwWD3YeBfzJkTbU86 */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, prevent_rent_paying_rent_recipients)>>3,
    .id     = {"\xd8\x9e\x52\x37\x85\xcf\xf9\x8f\x7a\x56\x28\x4c\x32\x67\x1e\xe9\x81\xe6\xae\xdd\xca\x67\x66\x9d\x83\xc2\x82\x56\xb8\x4e\xf4\xae"}
              /* Fab5oP3DmsLYCiQZXdjyqT3ukFFPrsmqhXU4WU1AWVVF */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, delay_visibility_of_program_deployment)>>3,
    .id     = {"\xea\x5f\xde\x80\x1b\x0d\x12\xd6\x7b\x51\xc2\xb5\xc6\x08\x33\x59\x68\x07\x4f\x61\x84\x0f\xaf\xfe\xf5\x96\x2c\x58\xbb\xe9\x9f\x4c"}
              /* GmuBvtFb2aHfSfMXpuFeWZGHyDeCLPS79s48fmCWCfM5 */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, apply_cost_tracker_during_replay)>>3,
    .id     = {"\x1b\xa8\x9a\x1c\x70\xb2\x9a\xca\x07\x34\x3d\x0b\xbf\xe2\x48\x67\x97\x3a\xdb\x59\x2e\x5d\x00\xfa\xde\x49\x8b\x33\x77\x3f\x70\xa0"}
              /* 2ry7ygxiYURULZCrypHhveanvP5tzZ4toRwVp89oCNSj */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, bpf_account_data_direct_mapping)>>3,
    .id     = {"\xca\xd6\x68\xb3\x88\x01\x19\x3f\x7e\xd4\xde\x26\xdc\x1c\x53\x2b\xf9\x20\x07\x6e\x3c\xe0\xd5\x2a\x8d\x88\x8b\x25\xda\xb6\x88\xd2"}
              /* EenyoWx9UMXYKpR8mW5Jmfmy2fRjzUtM7NduYMY8bx33 */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, add_set_tx_loaded_accounts_data_size_instruction)>>3,
    .id     = {"\xe0\x63\xcf\x92\xc3\xa0\xd3\x55\x49\xd0\x52\xb1\x0c\xaf\xf1\x3f\x56\xfa\x06\x11\x1c\x63\x6f\x69\x75\x42\xd1\x31\x2a\x1e\xe2\x6d"}
              /* G6vbf1UBok8MWb8m25ex86aoQHeKTzDKzuZADHkShqm6 */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, switch_to_new_elf_parser)>>3,
    .id     = {"\xac\xda\xc5\x37\x50\xa9\x7a\x0e\xb4\x8f\xa3\x40\xa0\xcc\xd2\x80\x94\x20\x2c\xc7\x60\x42\x4a\xd0\xa9\xc0\xd3\x31\xe6\xd6\x62\xf0"}
              /* Cdkc8PPTeTNUPoZEfCY5AyetUrEdkZtNPMgz58nqyaHD */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, round_up_heap_size)>>3,
    .id     = {"\xa6\xc6\xf9\xd5\x39\x30\xd1\xe2\xaa\xfa\xc5\x3d\xd9\x8e\xeb\xc2\xf3\xdb\x6c\x9a\xde\xeb\xf2\x61\x38\x73\x42\x7d\x71\x86\xb9\xb4"}
              /* CE2et8pqgyQMP2mQRg3CgvX8nJBKUArMu3wfiQiQKY1y */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, remove_bpf_loader_incorrect_program_id)>>3,
    .id     = {"\x13\x27\x40\x91\x61\xec\xe3\xca\x4e\x63\x93\xed\xe0\x0c\x11\x78\x1f\x7e\xef\x3f\x56\xe8\xdb\x60\x71\x31\x74\xd2\xe6\x72\xbe\x53"}
              /* 2HmTkCj9tXuPE4ueHzdD7jPeMf9JGCoZh5AsyoATiWEe */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, include_loaded_accounts_data_size_in_fee_calculation)>>3,
    .id     = {"\xc9\xb7\x08\xb6\xbb\xa5\xb1\xa6\xdc\xbf\xd0\x4f\xed\xe7\x28\xa3\x52\xcd\x71\x42\x39\x0c\xa0\x41\x13\x66\xde\xff\x50\x24\xfe\x35"}
              /* EaQpmC6GtRssaZ3PCUM5YksGqUdMLeZ46BQXYtHYakDS */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, native_programs_consume_cu)>>3,
    .id     = {"\x74\x38\xca\xe8\xba\x15\xa6\x50\xd5\x96\x1a\x62\xd9\xba\x14\xc6\x20\x96\xdb\x0f\xa1\x87\x72\x3f\x3c\x59\xc3\xdb\xfb\xdd\x3b\x6b"}
              /* 8pgXCMNXC8qyEFypuwpXyRxLXZdpM4Qo72gJ6k87A6wL */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, simplify_writable_program_account_check)>>3,
    .id     = {"\x43\xae\x75\x5b\x05\xd6\x4d\xda\x6b\x93\x44\x69\xa0\x06\xea\xf0\x99\x27\xf4\xbc\x96\x0e\xc6\x48\x64\x47\xc0\x53\x52\xfb\x1a\x7a"}
              /* 5ZCcFAzJ1zsFKe1KSZa9K92jhx7gkcKj97ci2DBo1vwj */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, stop_truncating_strings_in_syscalls)>>3,
    .id     = {"\x00\x05\xee\xe8\x9f\xd8\x51\x2f\x51\x9c\xc1\x76\xca\xbb\xe0\xf6\x3a\x39\x61\x09\xda\xa5\x4d\x9a\xb7\x98\xa3\x01\x0d\x5a\xb8\x0f"}
              /* 16FMCmgLzCNNz6eTwGanbyN2ZxvTBSLuQ6DZhgeMshg */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, clean_up_delegation_errors)>>3,
    .id     = {"\x9f\x59\x3a\x49\x85\xf1\xaa\x61\x96\x8e\x49\xb3\x45\xce\xea\xed\xbb\x96\x54\x09\xa4\x3d\x8d\xba\xbb\x57\xc7\x64\x0d\xfc\x59\x90"}
              /* Bj2jmUsM2iRhfdLLDSTkhM5UQRQvQHm57HSmPibPtEyu */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, vote_state_add_vote_latency)>>3,
    .id     = {"\x61\xd8\xd7\x1f\x81\x6f\x32\x74\x56\x37\x18\x3c\x8b\x7e\x6e\xaa\x28\x71\xb5\x22\x61\x11\xb0\x39\x6d\xb6\x4f\xad\x75\xad\x77\xc4"}
              /* 7axKe5BTYBDD87ftzWbk5DfzWMGyRvqmWTduuo22Yaqy */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, checked_arithmetic_in_fee_validation)>>3,
    .id     = {"\x41\x3c\x10\x0e\x1d\x39\xd7\x2b\xbe\x35\xa2\xa1\xcb\xff\x4f\xe1\x7d\x4d\x55\xd0\x45\x4d\xf0\x5f\x58\xa4\x96\x7c\xed\x08\x34\x55"}
              /* 5Pecy6ie6XGm22pc9d4P9W5c31BugcFBuy6hsP2zkETv */ ,
    .default_activated = 1
              },

  { .index  = offsetof(fd_features_t, last_restart_slot_sysvar)>>3,
    .id     = {"\xf9\xb8\x13\x4b\x8e\x66\x1b\x40\x28\x1c\xed\xbe\x7c\x78\x8c\x99\x1b\x93\x96\x34\xd6\xc9\x0b\xde\xae\xb8\xdb\x5a\x06\x7d\x87\x8e"}
              /* HooKD5NC9QNxk25QuzCssB8ecrEzGt6eXEPBUxWp1LaR */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, reduce_stake_warmup_cooldown)>>3,
    .id     = {"\xec\xee\x93\x40\x57\x22\xb0\x74\x49\xc1\xf9\xe5\xef\x54\x03\xef\x18\x4d\x87\xf9\x31\x68\x96\x18\xad\x21\xb8\xf7\x00\x3d\x8a\xce"}
              /* GwtDQBghCTBgmX2cpEGNPxTEBUTQRaDMGTr5qychdGMj */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, revise_turbine_epoch_stakes)>>3,
    .id     = {"\x9b\x5f\xa2\xbe\x99\xfd\xb8\x81\x7d\x7d\x2d\xcf\x73\xa0\xf6\x56\x57\xea\x7b\x3c\x6a\xf6\x13\x59\x13\x4a\x2f\x56\x10\x11\xd2\xad"}
              /* BTWmtJC8U5ZLMbBUUA1k6As62sYjPEjAiNAT55xYGdJU */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, enable_poseidon_syscall)>>3,
    .id     = {"\xd4\xeb\x2e\xcb\x2c\x82\xbf\x3c\xc6\xab\x6d\x6c\xbc\x2f\x29\x03\xab\xa5\x57\xd7\x2d\xc4\x4e\xfd\xbc\x5f\xf1\xc0\x6c\xde\xa2\xd7"}
              /* FL9RsQA6TVUoh5xJQ9d936RHSebA1NLQqe3Zv9sXZRpr */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, timely_vote_credits)>>3,
    .id     = {"\x1a\xc7\x41\x11\xf0\x44\xfa\x86\x3f\x13\x7e\xa6\x7a\xb2\xd4\x6e\x16\x10\x57\xe6\x96\x23\x5f\x27\xa8\xe5\xf0\x4c\xe8\xf1\x65\x23"}
              /* 2oXpeh141pPZCTCFHBsvCwG2BtaHZZAtrVhwaxSy6brS */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, remaining_compute_units_syscall_enabled)>>3,
    .id     = {"\x42\x53\x93\xd7\x86\x52\x20\x64\xce\x96\x67\x76\xc0\xb2\x3d\xd2\xe4\xd2\x81\x04\x5e\x7a\xd6\x90\xee\x30\x77\x01\x6a\x54\x6e\x64"}
              /* 5TuppMutoyzhUSfuYdhgzD47F92GL1g89KpCZQKqedxP */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, enable_program_runtime_v2_and_loader_v4)>>3,
    .id     = {"\x73\xd6\xec\x04\xbe\x12\xf9\x97\x7c\x5b\x14\x23\xca\x21\x5f\x5c\xac\x7c\x41\xfa\xd1\xf8\xc7\x7f\x0d\x23\x00\xe1\xb4\xa6\xf1\xd8"}
              /* 8oBxsYqnCvUTGzgEpxPcnVf7MLbWWPYddE33PftFeBBd */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, require_rent_exempt_split_destination)>>3,
    .id     = {"\xb2\xb3\xf3\xc6\xb4\x1c\x24\x4b\xbf\x84\xd9\x21\x6e\x67\x6e\x0b\x45\x16\xb4\xd6\x0c\x48\xe9\x7a\x45\x26\x74\xbc\x9d\x61\x72\xe0"}
              /* D2aip4BBr8NPWtU9vLrwrBvbuaQ8w1zV38zFLxx4pfBV */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, better_error_codes_for_tx_lamport_check)>>3,
    .id     = {"\xd9\xf9\x49\xa8\xea\x6b\x74\x21\x4a\x4c\x14\x84\xd2\x73\x07\x37\xc1\x95\xb5\xdc\xdc\xd0\x07\xd0\x17\x2b\xe1\x2f\xff\x7a\x38\x4f"}
              /* Ffswd3egL3tccB6Rv3XY6oqfdzn913vUcjCSnpvCKpfx */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, enable_alt_bn128_compression_syscall)>>3,
    .id     = {"\xc5\x96\xc3\xf1\x5d\x5b\xb5\x9b\x10\x5f\xf4\xd6\x41\x2c\x69\xe2\xdc\x8c\xa7\xdf\x6f\xba\x27\x60\xfb\x3e\x5b\x98\x46\xe4\xb4\xef"}
              /* EJJewYSddEEtSZHiqugnvhQHiWyZKjkFDQASd7oKSagn */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, programify_feature_gate_program)>>3,
    .id     = {"\x6c\x03\x23\xfe\xae\x55\x9b\x6b\x0f\xa5\x65\xc1\x18\x46\x40\xe3\x6a\x92\x67\xe8\x05\xc2\x7d\x8b\x88\x1b\x5e\xca\xa3\xaf\x6e\x77"}
              /* 8GdovDzVwWU5edz2G697bbB7GZjrUc6aQZLWyNNAtHdg */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, update_hashes_per_tick2)>>3,
    .id     = {"\xc8\xc8\x3f\xaf\x32\xd0\x79\xe7\xc9\x8b\x45\x2f\x6c\x6c\xa4\xaf\xeb\x86\xdd\x45\xc7\x5d\xa9\xf3\x0d\x91\xab\x70\x0d\xdc\x41\x23"}
              /* EWme9uFqfy1ikK1jhJs8fM5hxWnK336QJpbscNtizkTU */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, update_hashes_per_tick3)>>3,
    .id     = {"\x6a\xdb\x81\x96\xaa\x89\x39\x58\xb8\xa9\xd8\xbb\xee\x56\xa6\x5a\x47\x46\xfa\xbd\x4c\x0f\x02\x92\x4c\xbc\x74\xc0\x6a\x05\xf5\xb8"}
              /* 8C8MCtsab5SsfammbzvYz65HHauuUYdbY2DZ4sznH6h5 */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, update_hashes_per_tick4)>>3,
    .id     = {"\x6f\x99\x8d\x05\xe5\xcd\x11\xa5\x69\x28\x27\xa5\xd1\xb4\x93\x29\x32\x39\x50\x4f\xb2\xea\x66\xe1\xb5\x37\x61\xe5\x87\x88\x1f\x41"}
              /* 8We4E7DPwF2WfAN8tRTtWQNhi98B99Qpuj7JoZ3Aikgg */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, update_hashes_per_tick5)>>3,
    .id     = {"\xa1\x78\xa3\x8e\x6a\xb3\x14\xa4\x11\x95\x61\x1e\x9e\xcb\x9a\x75\x42\xa9\x54\xa3\x80\xb9\x59\xc8\x10\xa5\x6d\xdf\x38\xbe\xcb\x59"}
              /* BsKLKAn1WM4HVhPRDsjosmqSg2J8Tq5xP2s2daDS6Ni4 */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, update_hashes_per_tick6)>>3,
    .id     = {"\xd4\xda\xe2\x6a\x8f\xf0\x49\x6c\x64\x64\x3e\x27\x5c\xc8\xc0\x94\x75\x19\xed\x99\xc6\x64\xe7\x3f\x62\xcc\x5c\xd4\x7b\xbc\x67\xe1"}
              /* FKu1qYwLQSiehz644H6Si65U5ZQ2cp9GxsyFUfYcuADv */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, validate_fee_collector_account)>>3,
    .id     = {"\x0c\x42\x9f\xae\x63\x29\x2c\x8c\xaa\x94\x19\xe1\xf6\xb4\xd9\x16\x5e\x43\xb4\xc7\xb1\x1f\xe0\x9d\x01\xd9\x0a\xc5\x1c\x70\x7f\x14"}
              /* prpFrMtgNmzaNzkPJg9o753fVvbHKqNrNTm76foJ2wm */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, enable_zk_transfer_with_fee)>>3,
    .id     = {"\x0e\xcb\x24\x6c\x6b\x32\x42\xcd\x46\xc6\x8d\x16\xca\xd0\x06\xed\x41\x5e\x9f\xc4\x36\x71\x70\xdc\xf6\x59\x14\x25\x3e\x4c\xaa\x12"}
              /* zkNLP7EQALfC1TYeB3biDU7akDckj8iPkvh9y2Mt2K3 */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, drop_legacy_shreds)>>3,
    .id     = {"\xe6\x0f\x1e\xeb\x2f\x39\x7b\xd1\x39\xaa\x31\xee\x23\x84\x80\x69\x51\x99\x93\x80\xc2\x55\x53\xef\xeb\xa2\xe0\x16\x79\xa0\x01\x7c"}
              /* GV49KKQdBNaiv2pgqhS2Dy3GWYJGXMTVYbYkdk91orRy */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, consume_blockstore_duplicate_proofs)>>3,
    .id     = {"\x52\x74\x2c\x7b\x6b\x86\x07\x02\x0c\x27\x5c\x4c\xf2\x6e\xf1\xe3\xcd\x47\xeb\xf2\x78\xe2\x9d\x0b\xfb\x96\xfb\x13\xad\x6f\x8a\xb0"}
              /* 6YsBCejwK96GZCkJ6mkZ4b68oP63z2PLoQmWjC7ggTqZ */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, index_erasure_conflict_duplicate_proofs)>>3,
    .id     = {"\x09\x74\xa1\x2b\x1c\x70\x2e\x59\xf6\x09\xfb\x6d\xaa\x47\x17\x37\xf4\xa5\xc2\xfb\x0b\xd9\x6b\x33\xcb\x93\xc4\x0c\xdd\x46\x4f\x23"}
              /* dupPajaLy2SSn8ko42aZz4mHANDNrLe8Nw8VQgFecLa */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, curve25519_restrict_msm_length)>>3,
    .id     = {"\x28\x38\x50\x19\xf7\x4f\x49\x20\x1a\x80\xc2\xda\x07\x53\xd4\xbb\x4b\x7f\xb5\xf7\x16\xcb\x7b\x19\x72\xff\xa5\xc6\x0c\x4b\x91"}
              /* ca6zf6JJRjQsYYPkBHF3N32MTzur4n2WL4QiiacPCL */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, allow_commission_decrease_at_any_time)>>3,
    .id     = {"\x09\x63\x71\x6c\x93\x25\xce\xfb\xac\xdf\x2e\x42\x3f\xdf\x5d\xf2\x5e\xae\xda\x5d\x77\xf7\x49\xa7\xb6\xf8\x67\x27\xf9\x0d\x29\xe4"}
              /* decoMktMcnmiq6t3u7g5BfgcQu91nKZr6RvMYf9z1Jb */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, merkle_conflict_duplicate_proofs)>>3,
    .id     = {"\x0b\x7d\xce\x55\xcc\x31\x6e\x11\x19\x99\x92\x0c\xf7\x52\x85\x76\xfe\xd0\x5c\xed\x1b\xd8\x8e\x84\x1b\xb6\x3c\xd9\x35\xed\x91\x2f"}
              /* mrkPjRg79B2oK2ZLgd7S3AfEJaX9B6gAF3H9aEykRUS */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, disable_bpf_loader_instructions)>>3,
    .id     = {"\x60\xbe\x49\xea\xb9\xe9\x43\x8c\x58\x9b\x35\x47\xbc\x1b\x1b\x0d\x04\xbc\x74\xd2\x57\xe1\xf2\xa5\x02\x66\x17\xf3\x49\xb5\xe0\xe9"}
              /* 7WeS1vfPRgeeoXArLh7879YcB9mgE9ktjPDtajXeWfXn */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, deprecate_executable_meta_update_in_bpf_loader)>>3,
    .id     = {"\x0b\x0a\xa6\x6d\xae\x07\x63\x9b\x6d\x90\xe0\xf3\x1d\xba\x64\x52\xba\x3d\xc3\x44\x31\x30\xdf\x7e\xab\xd4\x1e\xd3\xab\x4d\x33\x47"}
              /* k6uR1J9VtKJnTukBV2Eo15BEy434MBg8bT6hHQgmU8v */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, enable_zk_proof_from_account)>>3,
    .id     = {"\x0e\xcb\x88\xd6\xe1\xd4\x23\xf4\x20\x62\xde\xc9\x60\x6c\x5a\x68\xc5\x9e\xcd\x3a\x97\x46\xbd\x14\xc5\x00\x9e\x46\x52\x19\x0c\xd9"}
              /* zkiTNuzBKxrCLMKehzuQeKZyLtX2yvFcEKMML8nExU8 */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, cost_model_requested_write_lock_cost)>>3,
    .id     = {"\x0d\xeb\x8b\x43\x43\x80\x51\xa1\x77\x30\xda\xfa\x17\x13\xc7\x34\x05\xe6\xe3\x35\x39\x8a\x57\x63\x96\x99\xb4\x10\xf0\xd6\x5e\x87"}
              /* wLckV1a64ngtcKPRGU4S4grVTestXjmNjxBjaKZrAcn */ ,
    .default_activated = 0
              },

  { .index  = offsetof(fd_features_t, enable_gossip_duplicate_proof_ingestion)>>3,
    .id     = {"\xd5\x79\x63\x4a\x6a\xab\x27\xdb\x57\xae\xfb\x1c\x06\x7c\x34\x8d\xaa\xae\x66\x2f\x5f\x62\x2f\x18\xf4\xb5\x83\x95\xe3\x43\xff\xd5"}
              /* FNKCMBzYUdjhHyPdsKG2LSmdzH8TCHXn3ytj8RNBS4nG */ ,
    .default_activated = 0
              },

  { .index = ULONG_MAX }
};

/* TODO replace this with fd_map_perfect */

FD_FN_CONST fd_feature_id_t const *
fd_feature_id_query( ulong prefix ) {

  switch( prefix ) {
  case 0x2577305f7cc65fe7: return &ids[   0 ];
  case 0x7095d36bc836da32: return &ids[   1 ];
  case 0x8b990f20829df9b8: return &ids[   2 ];
  case 0x47e18859d27e3aa3: return &ids[   3 ];
  case 0xe7571f86aa06f160: return &ids[   4 ];
  case 0xd924059c5749c4c1: return &ids[   5 ];
  case 0x159967bd804742c2: return &ids[   6 ];
  case 0x1d41fee249e6cc37: return &ids[   7 ];
  case 0xa6d8eedf48633be2: return &ids[   8 ];
  case 0x65b79c7f3e7441b3: return &ids[   9 ];
  case 0x51949af2871c7c99: return &ids[  10 ];
  case 0xfaa4899494a281ec: return &ids[  11 ];
  case 0x30ab53221abfd626: return &ids[  12 ];
  case 0x4ab8b2b10003ad50: return &ids[  13 ];
  case 0xe8f97382b03240a1: return &ids[  14 ];
  case 0xe994a4b8eeea84f4: return &ids[  15 ];
  case 0x10a1e092dd7f1573: return &ids[  16 ];
  case 0xc6eb259e772475c8: return &ids[  17 ];
  case 0xfba69c4970d7ad9d: return &ids[  18 ];
  case 0xb5b508c4a6313e99: return &ids[  19 ];
  case 0xabff1d2abfa0c4bc: return &ids[  20 ];
  case 0xa952e12150121a45: return &ids[  21 ];
  case 0x62885c46a116e1d6: return &ids[  22 ];
  case 0xd5830390d36ee60e: return &ids[  23 ];
  case 0xff00aac3cfaafcfe: return &ids[  24 ];
  case 0x6d22c4ce75df6f0b: return &ids[  25 ];
  case 0xd544636252beca0e: return &ids[  26 ];
  case 0x4b1e586fc635dc65: return &ids[  27 ];
  case 0x7ca46573f5a27822: return &ids[  28 ];
  case 0x1a6958db2ff09870: return &ids[  29 ];
  case 0x15766ba9a908483c: return &ids[  30 ];
  case 0x4b5c55d9eaf96eee: return &ids[  31 ];
  case 0xf162e5606a687206: return &ids[  32 ];
  case 0x35dd1ed4b9d19b9b: return &ids[  33 ];
  case 0x30bf137796030f21: return &ids[  34 ];
  case 0xa5ece90c9d468a56: return &ids[  35 ];
  case 0xf1084016618f3ec0: return &ids[  36 ];
  case 0x92be3cd65cb3e2c3: return &ids[  37 ];
  case 0xbd02d2f51146c257: return &ids[  38 ];
  case 0xfcd1ef949cf886f1: return &ids[  39 ];
  case 0xee2a44e1f54f5e5a: return &ids[  40 ];
  case 0xc548c6b11d33172f: return &ids[  41 ];
  case 0xf1d277eeafe62810: return &ids[  42 ];
  case 0xbdb86acdf94382f4: return &ids[  43 ];
  case 0xa7654aedafa0a2a4: return &ids[  44 ];
  case 0x3ab28ef5d5cf7ca6: return &ids[  45 ];
  case 0x9021d56a2c13c119: return &ids[  46 ];
  case 0x2b8134b3adacd035: return &ids[  47 ];
  case 0x1cec25430fa6229f: return &ids[  48 ];
  case 0x4c8dc4f1e61649dd: return &ids[  49 ];
  case 0xe79e065446760ac3: return &ids[  50 ];
  case 0x7a63cd44b42c0b82: return &ids[  51 ];
  case 0x168bc52564a1181f: return &ids[  52 ];
  case 0xe4f010aefd867566: return &ids[  53 ];
  case 0xa85d651d8da169c6: return &ids[  54 ];
  case 0x7bc99a080444c8d9: return &ids[  55 ];
  case 0x0203237cf1901d09: return &ids[  56 ];
  case 0x7e8f67ed363c31a6: return &ids[  57 ];
  case 0xf28b599c33eda89f: return &ids[  58 ];
  case 0xffed385aa352ef27: return &ids[  59 ];
  case 0x06adecee02a12019: return &ids[  60 ];
  case 0xd79987a3abf61d2d: return &ids[  61 ];
  case 0xd56fc1708dc98c13: return &ids[  62 ];
  case 0x317a863da11d0a8d: return &ids[  63 ];
  case 0x96ac475392d395d8: return &ids[  64 ];
  case 0x9479e273205da38a: return &ids[  65 ];
  case 0xd89ef3a8c30d1ba7: return &ids[  66 ];
  case 0xe2276359bb5e6007: return &ids[  67 ];
  case 0xf02385c19b529325: return &ids[  68 ];
  case 0xf1762ae45609273b: return &ids[  69 ];
  case 0xbff452bfed793f26: return &ids[  70 ];
  case 0xe505bd1df7964bfc: return &ids[  71 ];
  case 0x80288c645d23a80b: return &ids[  72 ];
  case 0x499ab78fe1142d63: return &ids[  73 ];
  case 0x9f43d6cae453a7e5: return &ids[  74 ];
  case 0x562f76c6d74c31ea: return &ids[  75 ];
  case 0xf70ae71daf8a1bd6: return &ids[  76 ];
  case 0x7f6371bf4a56a106: return &ids[  77 ];
  case 0x3ca58e628f040b68: return &ids[  78 ];
  case 0x7e787d5c6d662d23: return &ids[  79 ];
  case 0xffc496b47872d42f: return &ids[  80 ];
  case 0x2bf29bf13f0e1d5d: return &ids[  81 ];
  case 0x073a0a7d3f570b55: return &ids[  82 ];
  case 0x4d6ae02c256bdf10: return &ids[  83 ];
  case 0x2e2d4501d149cd2c: return &ids[  84 ];
  case 0xe8f10f26141749dd: return &ids[  85 ];
  case 0xe02ac5f848d395d8: return &ids[  86 ];
  case 0x7b285d0430faf2fc: return &ids[  87 ];
  case 0xf3ee1d3b0fcfec0c: return &ids[  88 ];
  case 0xfc0fb9c317b6c16b: return &ids[  89 ];
  case 0x562011e7dbadd982: return &ids[  90 ];
  case 0x5458f71cc7cd31e0: return &ids[  91 ];
  case 0x606490c1431ae278: return &ids[  92 ];
  case 0xd151c2100e71455b: return &ids[  93 ];
  case 0x2fdc300bd0720815: return &ids[  94 ];
  case 0x5a5c2eab595223bf: return &ids[  95 ];
  case 0xdda7e56980356920: return &ids[  96 ];
  case 0xc358973434287fe8: return &ids[  97 ];
  case 0xe210655c824cfb2f: return &ids[  98 ];
  case 0xc3cc3bdc6eea2eb1: return &ids[  99 ];
  case 0x2758d3af483c6abe: return &ids[ 100 ];
  case 0xb0e571b1579c09fc: return &ids[ 101 ];
  case 0xcb5d0779751b0c2b: return &ids[ 102 ];
  case 0x5795654d01457757: return &ids[ 103 ];
  case 0x6799d3fbcc438c0c: return &ids[ 104 ];
  case 0x4439548ebff1d6f1: return &ids[ 105 ];
  case 0xe5394b6d65186d70: return &ids[ 106 ];
  case 0x8f688d4e3ab17a60: return &ids[ 107 ];
  case 0xe364c75ced9b53a7: return &ids[ 108 ];
  case 0x41b914ee34cb0368: return &ids[ 109 ];
  case 0x14a73a8e87cee681: return &ids[ 110 ];
  case 0xe21e6fa7a57304e2: return &ids[ 111 ];
  case 0x6d1e7092a4aae574: return &ids[ 112 ];
  case 0x2ca5833736ba5c69: return &ids[ 113 ];
  case 0x855543b1e6e31e10: return &ids[ 114 ];
  case 0x204b4907aacbc996: return &ids[ 115 ];
  case 0x80f1bedb2c2facaf: return &ids[ 116 ];
  case 0x6796bad7d20e8806: return &ids[ 117 ];
  case 0xe0724b3421984e49: return &ids[ 118 ];
  case 0xada15a4b53efaad4: return &ids[ 119 ];
  case 0x41fd0d35fd8339c9: return &ids[ 120 ];
  case 0x91b03055f3636ce0: return &ids[ 121 ];
  case 0x5b2c24f10d5a1a81: return &ids[ 122 ];
  case 0x1728caf9bc767c3f: return &ids[ 123 ];
  case 0x819bd0526bd811cb: return &ids[ 124 ];
  case 0x0d8a57d3828615b9: return &ids[ 125 ];
  case 0xb527e5f5e76ce07b: return &ids[ 126 ];
  case 0x2ac194a6a536cee4: return &ids[ 127 ];
  case 0xa6862bcb2044252b: return &ids[ 128 ];
  case 0x9f4323f726178849: return &ids[ 129 ];
  case 0xaaef1edeb6c5bf85: return &ids[ 130 ];
  case 0x795c88a20bcb6dfd: return &ids[ 131 ];
  case 0x8a8eb9085ca2bb0b: return &ids[ 132 ];
  case 0x33e6e44dc3a9cfb2: return &ids[ 133 ];
  case 0xc3df53505d0f7aed: return &ids[ 134 ];
  case 0x784adb4f1d180869: return &ids[ 135 ];
  case 0x71eba1d288ba2bfc: return &ids[ 136 ];
  case 0x823d14dd6235f859: return &ids[ 137 ];
  case 0xb3f6cd09abba192b: return &ids[ 138 ];
  case 0x3a315b1ab012eec3: return &ids[ 139 ];
  case 0x500aab8a23ff8b33: return &ids[ 140 ];
  case 0xffe35ea7abb29bbb: return &ids[ 141 ];
  case 0x8a22c4e80489c387: return &ids[ 142 ];
  case 0xce82bcc13c5649fa: return &ids[ 143 ];
  case 0x8ff9cf8537529ed8: return &ids[ 144 ];
  case 0xd6120d1b80de5fea: return &ids[ 145 ];
  case 0xca9ab2701c9aa81b: return &ids[ 146 ];
  case 0x3f190188b368d6ca: return &ids[ 147 ];
  case 0x55d3a0c392cf63e0: return &ids[ 148 ];
  case 0x0e7aa95037c5daac: return &ids[ 149 ];
  case 0xe2d13039d5f9c6a6: return &ids[ 150 ];
  case 0xcae3ec6191402713: return &ids[ 151 ];
  case 0xa6b1a5bbb608b7c9: return &ids[ 152 ];
  case 0x50a615bae8ca3874: return &ids[ 153 ];
  case 0xda4dd6055b75ae43: return &ids[ 154 ];
  case 0x2f51d89fe8ee0500: return &ids[ 155 ];
  case 0x61aaf185493a599f: return &ids[ 156 ];
  case 0x74326f811fd7d861: return &ids[ 157 ];
  case 0x2bd7391d0e103c41: return &ids[ 158 ];
  case 0x401b668e4b13b8f9: return &ids[ 159 ];
  case 0x74b022574093eeec: return &ids[ 160 ];
  case 0x81b8fd99bea25f9b: return &ids[ 161 ];
  case 0x3cbf822ccb2eebd4: return &ids[ 162 ];
  case 0x86fa44f01141c71a: return &ids[ 163 ];
  case 0x64205286d7935342: return &ids[ 164 ];
  case 0x97f912be04ecd673: return &ids[ 165 ];
  case 0x4b241cb4c6f3b3b2: return &ids[ 166 ];
  case 0x21746beaa849f9d9: return &ids[ 167 ];
  case 0x9bb55b5df1c396c5: return &ids[ 168 ];
  case 0x6b9b55aefe23036c: return &ids[ 169 ];
  case 0xe779d032af3fc8c8: return &ids[ 170 ];
  case 0x583989aa9681db6a: return &ids[ 171 ];
  case 0xa511cde5058d996f: return &ids[ 172 ];
  case 0xa414b36a8ea378a1: return &ids[ 173 ];
  case 0x6c49f08f6ae2dad4: return &ids[ 174 ];
  case 0x8c2c2963ae9f420c: return &ids[ 175 ];
  case 0xcd42326b6c24cb0e: return &ids[ 176 ];
  case 0xd17b392feb1e0fe6: return &ids[ 177 ];
  case 0x0207866b7b2c7452: return &ids[ 178 ];
  case 0x592e701c2ba17409: return &ids[ 179 ];
  case 0x20494ff719503828: return &ids[ 180 ];
  case 0xfbce25936c716309: return &ids[ 181 ];
  case 0x116e31cc55ce7d0b: return &ids[ 182 ];
  case 0x8c43e9b9ea49be60: return &ids[ 183 ];
  case 0x9b6307ae6da60a0b: return &ids[ 184 ];
  case 0xf423d4e1d688cb0e: return &ids[ 185 ];
  case 0xa1518043438beb0d: return &ids[ 186 ];
  case 0xdb27ab6a4a6379d5: return &ids[ 187 ];
  default: break;
  }

  return NULL;
}

/* Verify that offset calculations are correct */

FD_STATIC_ASSERT( offsetof( fd_features_t, deprecate_rewards_sysvar                                )>>3==  0UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, pico_inflation                                          )>>3==  1UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, devnet_and_testnet                                      )>>3==  2UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, vote                                                    )>>3==  3UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, enable                                                  )>>3==  4UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, secp256k1_program_enabled                               )>>3==  5UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, spl_token_v2_multisig_fix                               )>>3==  6UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, no_overflow_rent_distribution                           )>>3==  7UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, filter_stake_delegation_accounts                        )>>3==  8UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, require_custodian_for_locked_stake_authorize            )>>3==  9UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, spl_token_v2_self_transfer_fix                          )>>3== 10UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, warp_timestamp_again                                    )>>3== 11UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, check_init_vote_data                                    )>>3== 12UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, secp256k1_recover_syscall_enabled                       )>>3== 13UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, system_transfer_zero_check                              )>>3== 14UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, blake3_syscall_enabled                                  )>>3== 15UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, dedupe_config_program_signers                           )>>3== 16UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, verify_tx_signatures_len                                )>>3== 17UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, vote_stake_checked_instructions                         )>>3== 18UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, rent_for_sysvars                                        )>>3== 19UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, libsecp256k1_0_5_upgrade_enabled                        )>>3== 20UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, tx_wide_compute_cap                                     )>>3== 21UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, spl_token_v2_set_authority_fix                          )>>3== 22UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, merge_nonce_error_into_system_error                     )>>3== 23UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, disable_fees_sysvar                                     )>>3== 24UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, stake_merge_with_unmatched_credits_observed             )>>3== 25UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, zk_token_sdk_enabled                                    )>>3== 26UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, curve25519_syscall_enabled                              )>>3== 27UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, versioned_tx_message_enabled                            )>>3== 28UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, libsecp256k1_fail_on_bad_count                          )>>3== 29UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, libsecp256k1_fail_on_bad_count2                         )>>3== 30UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, instructions_sysvar_owned_by_sysvar                     )>>3== 31UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, stake_program_advance_activating_credits_observed       )>>3== 32UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, credits_auto_rewind                                     )>>3== 33UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, demote_program_write_locks                              )>>3== 34UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, ed25519_program_enabled                                 )>>3== 35UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, return_data_syscall_enabled                             )>>3== 36UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, reduce_required_deploy_balance                          )>>3== 37UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, sol_log_data_syscall_enabled                            )>>3== 38UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, stakes_remove_delegation_if_inactive                    )>>3== 39UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, do_support_realloc                                      )>>3== 40UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, prevent_calling_precompiles_as_programs                 )>>3== 41UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, optimize_epoch_boundary_updates                         )>>3== 42UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, remove_native_loader                                    )>>3== 43UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, send_to_tpu_vote_port                                   )>>3== 44UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, requestable_heap_size                                   )>>3== 45UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, disable_fee_calculator                                  )>>3== 46UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, add_compute_budget_program                              )>>3== 47UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, nonce_must_be_writable                                  )>>3== 48UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, spl_token_v3_3_0_release                                )>>3== 49UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, leave_nonce_on_success                                  )>>3== 50UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, reject_empty_instruction_without_program                )>>3== 51UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, fixed_memcpy_nonoverlapping_check                       )>>3== 52UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, reject_non_rent_exempt_vote_withdraws                   )>>3== 53UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, evict_invalid_stakes_cache_entries                      )>>3== 54UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, allow_votes_to_directly_update_vote_state               )>>3== 55UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, cap_accounts_data_len                                   )>>3== 56UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, max_tx_account_locks                                    )>>3== 57UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, require_rent_exempt_accounts                            )>>3== 58UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, filter_votes_outside_slot_hashes                        )>>3== 59UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, update_syscall_base_costs                               )>>3== 60UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, stake_deactivate_delinquent_instruction                 )>>3== 61UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, stake_redelegate_instruction                            )>>3== 62UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, vote_withdraw_authority_may_change_authorized_voter     )>>3== 63UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, spl_associated_token_account_v1_0_4                     )>>3== 64UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, reject_vote_account_close_unless_zero_credit_epoch      )>>3== 65UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, add_get_processed_sibling_instruction_syscall           )>>3== 66UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, bank_transaction_count_fix                              )>>3== 67UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, disable_bpf_deprecated_load_instructions                )>>3== 68UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, disable_bpf_unresolved_symbols_at_runtime               )>>3== 69UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, record_instruction_in_transaction_context_push          )>>3== 70UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, syscall_saturated_math                                  )>>3== 71UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, check_physical_overlapping                              )>>3== 72UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, limit_secp256k1_recovery_id                             )>>3== 73UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, disable_deprecated_loader                               )>>3== 74UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, check_slice_translation_size                            )>>3== 75UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, stake_split_uses_rent_sysvar                            )>>3== 76UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, add_get_minimum_delegation_instruction_to_stake_program )>>3== 77UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, error_on_syscall_bpf_function_hash_collisions           )>>3== 78UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, reject_callx_r10                                        )>>3== 79UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, drop_redundant_turbine_path                             )>>3== 80UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, executables_incur_cpi_data_cost                         )>>3== 81UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, fix_recent_blockhashes                                  )>>3== 82UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, update_rewards_from_cached_accounts                     )>>3== 83UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, enable_partitioned_epoch_reward                         )>>3== 84UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, spl_token_v3_4_0                                        )>>3== 85UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, spl_associated_token_account_v1_1_0                     )>>3== 86UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, default_units_per_instruction                           )>>3== 87UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, stake_allow_zero_undelegated_amount                     )>>3== 88UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, require_static_program_ids_in_transaction               )>>3== 89UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, stake_raise_minimum_delegation_to_1_sol                 )>>3== 90UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, stake_minimum_delegation_for_rewards                    )>>3== 91UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, add_set_compute_unit_price_ix                           )>>3== 92UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, disable_deploy_of_alloc_free_syscall                    )>>3== 93UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, include_account_index_in_rent_error                     )>>3== 94UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, add_shred_type_to_shred_seed                            )>>3== 95UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, warp_timestamp_with_a_vengeance                         )>>3== 96UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, separate_nonce_from_blockhash                           )>>3== 97UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, enable_durable_nonce                                    )>>3== 98UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, vote_state_update_credit_per_dequeue                    )>>3== 99UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, quick_bail_on_panic                                     )>>3==100UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, nonce_must_be_authorized                                )>>3==101UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, nonce_must_be_advanceable                               )>>3==102UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, vote_authorize_with_seed                                )>>3==103UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, cap_accounts_data_size_per_block                        )>>3==104UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, preserve_rent_epoch_for_rent_exempt_accounts            )>>3==105UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, enable_bpf_loader_extend_program_ix                     )>>3==106UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, enable_early_verification_of_account_modifications      )>>3==107UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, skip_rent_rewrites                                      )>>3==108UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, prevent_crediting_accounts_that_end_rent_paying         )>>3==109UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, cap_bpf_program_instruction_accounts                    )>>3==110UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, loosen_cpi_size_restriction                             )>>3==111UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, use_default_units_in_fee_calculation                    )>>3==112UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, compact_vote_state_updates                              )>>3==113UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, incremental_snapshot_only_incremental_hash_calculation  )>>3==114UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, disable_cpi_setting_executable_and_rent_epoch           )>>3==115UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, on_load_preserve_rent_epoch_for_rent_exempt_accounts    )>>3==116UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, account_hash_ignore_slot                                )>>3==117UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, set_exempt_rent_epoch_max                               )>>3==118UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, relax_authority_signer_check_for_lookup_table_creation  )>>3==119UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, stop_sibling_instruction_search_at_parent               )>>3==120UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, vote_state_update_root_fix                              )>>3==121UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, cap_accounts_data_allocations_per_transaction           )>>3==122UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, epoch_accounts_hash                                     )>>3==123UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, remove_deprecated_request_unit_ix                       )>>3==124UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, disable_rehash_for_rent_epoch                           )>>3==125UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, increase_tx_account_lock_limit                          )>>3==126UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, limit_max_instruction_trace_length                      )>>3==127UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, check_syscall_outputs_do_not_overlap                    )>>3==128UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, enable_bpf_loader_set_authority_checked_ix              )>>3==129UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, enable_alt_bn128_syscall                                )>>3==130UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, enable_program_redeployment_cooldown                    )>>3==131UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, commission_updates_only_allowed_in_first_half_of_epoch  )>>3==132UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, enable_turbine_fanout_experiments                       )>>3==133UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, disable_turbine_fanout_experiments                      )>>3==134UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, drop_merkle_shreds                                      )>>3==135UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, keep_merkle_shreds                                      )>>3==136UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, move_serialized_len_ptr_in_cpi                          )>>3==137UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, update_hashes_per_tick                                  )>>3==138UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, enable_big_mod_exp_syscall                              )>>3==139UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, disable_builtin_loader_ownership_chains                 )>>3==140UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, cap_transaction_accounts_data_size                      )>>3==141UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, remove_congestion_multiplier_from_fee_calculation       )>>3==142UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, enable_request_heap_frame_ix                            )>>3==143UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, prevent_rent_paying_rent_recipients                     )>>3==144UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, delay_visibility_of_program_deployment                  )>>3==145UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, apply_cost_tracker_during_replay                        )>>3==146UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, bpf_account_data_direct_mapping                         )>>3==147UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, add_set_tx_loaded_accounts_data_size_instruction        )>>3==148UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, switch_to_new_elf_parser                                )>>3==149UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, round_up_heap_size                                      )>>3==150UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, remove_bpf_loader_incorrect_program_id                  )>>3==151UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, include_loaded_accounts_data_size_in_fee_calculation    )>>3==152UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, native_programs_consume_cu                              )>>3==153UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, simplify_writable_program_account_check                 )>>3==154UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, stop_truncating_strings_in_syscalls                     )>>3==155UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, clean_up_delegation_errors                              )>>3==156UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, vote_state_add_vote_latency                             )>>3==157UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, checked_arithmetic_in_fee_validation                    )>>3==158UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, last_restart_slot_sysvar                                )>>3==159UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, reduce_stake_warmup_cooldown                            )>>3==160UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, revise_turbine_epoch_stakes                             )>>3==161UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, enable_poseidon_syscall                                 )>>3==162UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, timely_vote_credits                                     )>>3==163UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, remaining_compute_units_syscall_enabled                 )>>3==164UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, enable_program_runtime_v2_and_loader_v4                 )>>3==165UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, require_rent_exempt_split_destination                   )>>3==166UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, better_error_codes_for_tx_lamport_check                 )>>3==167UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, enable_alt_bn128_compression_syscall                    )>>3==168UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, programify_feature_gate_program                         )>>3==169UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, update_hashes_per_tick2                                 )>>3==170UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, update_hashes_per_tick3                                 )>>3==171UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, update_hashes_per_tick4                                 )>>3==172UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, update_hashes_per_tick5                                 )>>3==173UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, update_hashes_per_tick6                                 )>>3==174UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, validate_fee_collector_account                          )>>3==175UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, enable_zk_transfer_with_fee                             )>>3==176UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, drop_legacy_shreds                                      )>>3==177UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, consume_blockstore_duplicate_proofs                     )>>3==178UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, index_erasure_conflict_duplicate_proofs                 )>>3==179UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, curve25519_restrict_msm_length                          )>>3==180UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, allow_commission_decrease_at_any_time                   )>>3==181UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, merkle_conflict_duplicate_proofs                        )>>3==182UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, disable_bpf_loader_instructions                         )>>3==183UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, deprecate_executable_meta_update_in_bpf_loader          )>>3==184UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, enable_zk_proof_from_account                            )>>3==185UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, cost_model_requested_write_lock_cost                    )>>3==186UL, layout );
FD_STATIC_ASSERT( offsetof( fd_features_t, enable_gossip_duplicate_proof_ingestion                 )>>3==187UL, layout );

FD_STATIC_ASSERT( sizeof( fd_features_t )>>3==FD_FEATURE_ID_CNT, layout );
