$(call add-hdrs,fd_failover_proto.h fd_failover_wire.h fd_failover_channel.h fd_failover_stream.h fd_failover_bus.h)
$(call add-objs,fd_failover_proto,fd_discof)
$(call add-objs,fd_failover_wire,fd_discof)
$(call add-objs,fd_failover_channel,fd_discof)
$(call add-objs,fd_failover_tls,fd_discof)
$(call add-objs,fd_failover_stream,fd_discof)

ifdef FD_HAS_HOSTED
$(call add-objs,fd_failover_tile,fd_discof)
$(call make-unit-test,test_failover_proto,test_failover_proto,fd_discof fd_util)
$(call run-unit-test,test_failover_proto)
$(call make-unit-test,test_failover_wire,test_failover_wire,fd_discof fd_ballet fd_util)
$(call run-unit-test,test_failover_wire)
$(call make-unit-test,test_failover_channel,test_failover_channel,fd_discof fd_disco fd_waltz fd_tls fd_ballet fd_util)
$(call run-unit-test,test_failover_channel)
$(call make-unit-test,test_failover_stream,test_failover_stream,fd_discof fd_choreo fd_flamenco fd_tango fd_ballet fd_util)
$(call run-unit-test,test_failover_stream)
$(call make-unit-test,test_failover_tile,test_failover_tile,fd_discof fd_choreo fd_disco fd_flamenco fd_waltz fd_tls fd_tango fd_ballet fd_util)
$(call run-unit-test,test_failover_tile)
endif
