pub use crate::generated::{
    FD_QUIC_CNC_DIAG_CHUNK_IDX,
    FD_QUIC_CNC_DIAG_TPU_CONN_LIVE_CNT,
    FD_QUIC_CNC_DIAG_TPU_CONN_SEQ,
    FD_QUIC_CNC_DIAG_TPU_PUB_CNT,
    FD_QUIC_CNC_DIAG_TPU_PUB_SZ,
};
