# A suggested configuration for benchmarking on a Zen3 CPU like AMD EPYC
# 7513 or similar.  The configuration expects 64 logical cores, and 32
# physical cores, numbered 0 and 1 for thread 0 and thread 1 on core 0,
# 2 and 3 for thread 0 and thread 1 on core 1, and so on.  In
# production, the configuration would not be correct as cores do not
# need to be dedicated to generating and sending transactions for 
# benchmarking.
[ledger]
  path = "/data/shm/{name}/ledger"

[layout]
  affinity = "15-58,f1"
  solana_labs_affinity = "59-63"
  verify_tile_count = 30
  bank_tile_count = 6

[development.genesis]
  hashes_per_tick = 12500
  fund_initial_accounts = 32768

[development.bench]
  benchg_tile_count = 12
  benchs_tile_count = 1
  affinity = "0-14"
  larger_max_cost_per_block = true
  larger_shred_limits_per_block = true

[rpc]
  transaction_history = false
  extended_tx_metadata_storage = false

[tiles.quic]
    regular_transaction_listen_port = 9001
    quic_transaction_listen_port = 9007
    max_concurrent_connections = 4
    max_concurrent_streams_per_connection = 6000
    stream_pool_cnt = 10000
    txn_reassembly_count = 16384
    max_concurrent_handshakes = 4
    max_inflight_quic_packets = 2000
    tx_buf_size = 4096
    idle_timeout_millis = 10000
    retry = false
