# A suggested configuration for benchmarking on a Zen3 CPU like AMD EPYC
# 7513 or similar.  The configuration expects 64 logical cores, and 32
# physical cores, numbered 0-31 for thread 0 on each core, and 32-63 for
# the hyperthread pairs.  In production, the configuration would not be
# correct as cores do not need to be dedicated to generating and sending
# transactions for benchmarking.
[ledger]
  path = "/data/{name}/ledger"

[layout]
  affinity = "f6,7-17,f2,18,f2"
  solana_labs_affinity = "19-26,51-58"
  verify_tile_count = 2
  bank_tile_count = 8

[development.genesis]
  hashes_per_tick = 12500
  fund_initial_accounts = 8192

[development.bench]
  benchg_tile_count = 12
  affinity = "f1,0-5,32-37,6"
  larger_max_cost_per_block = true
  larger_shred_limits_per_block = true
  