# A suggested configuration for benchmarking on a Zen3 CPU like AMD EPYC
# 7513 or similar.  The configuration expects 64 logical cores, and 32
# physical cores, numbered 0 and 1 for thread 0 and thread 1 on core 0,
# 2 and 3 for thread 0 and thread 1 on core 1, and so on.  In
# production, the configuration would not be correct as cores do not
# need to be dedicated to generating and sending transactions for 
# benchmarking.
[ledger]
  path = "/data/shm/{name}/ledger"

[layout]
  affinity = "14-58,f1"
  solana_labs_affinity = "59-63"
  verify_tile_count = 30
  bank_tile_count = 6

[development.genesis]
  hashes_per_tick = 12500
  fund_initial_accounts = 32768

[development.bench]
  benchg_tile_count = 12
  benchs_tile_count = 2
  affinity = "f1,0-13"
  larger_max_cost_per_block = true
  larger_shred_limits_per_block = true

[rpc]
  transaction_history = false
  extended_tx_metadata_storage = false
