#!/usr/bin/env python3

"""
Downloads latest Wycheproof test vectors and generates C test code.
"""

from contextlib import redirect_stdout
from dataclasses import dataclass
import datetime
import requests
import os
from pathlib import Path
import sys


@dataclass
class EddsaVerify:
    tcId: int
    comment: str
    msg: bytes
    sig: bytes
    pub: bytes
    ok: bool


def _gen_ed25519():
    req = requests.get(
        "https://raw.githubusercontent.com/google/wycheproof/master/testvectors/eddsa_test.json"
    )
    assert req.status_code == 200
    file = req.json()
    assert file["algorithm"] == "EDDSA"
    assert file["schema"] == "eddsa_verify_schema.json"
    verify_tests = []
    for group in file["testGroups"]:
        if group["type"] != "EddsaVerify":
            print(f"Skipping {group['type']} test", file=sys.stderr)
            continue
        pubkey = bytes.fromhex(group["key"]["pk"])
        for test in group["tests"]:
            verify_tests.append(
                EddsaVerify(
                    tcId=test["tcId"],
                    comment=test["comment"],
                    msg=bytes.fromhex(test["msg"]),
                    sig=bytes.fromhex(test["sig"]),
                    pub=pubkey,
                    ok=test["result"] == "valid",
                )
            )

    print("/* Code generated by gen_wycheproofs.py. DO NOT EDIT. */")
    print(
        f"/* Generated at {datetime.datetime.now(datetime.timezone.utc).isoformat()} */"
    )
    print(
        """
#include "../fd_ballet_base.h"

struct fd_ed25519_verify_wycheproof {
  char const *  comment;
  uchar const * msg;
  ulong         msg_sz;
  uchar         pub[32];
  uchar         sig[64];
  uint          tc_id;
  int           ok;
};

typedef struct fd_ed25519_verify_wycheproof fd_ed25519_verify_wycheproof_t;

static fd_ed25519_verify_wycheproof_t const ed25519_verify_wycheproofs[] = {"""
    )

    for test in verify_tests:
        if len(test.sig) != 64:
            continue
        print(f"  {{ .tc_id   = {test.tcId},")
        print(f'    .comment = "{test.comment}",')
        print(
            r'    .msg     = (uchar const *)"'
            + "".join([r"\x%02x" % (x) for x in test.msg])
            + r'",'
        )
        print(f"    .msg_sz  = {len(test.msg)}UL,")
        print(
            r'    .sig     = "' + "".join([r"\x%02x" % (x) for x in test.sig]) + r'",'
        )
        print(
            r'    .pub     = "' + "".join([r"\x%02x" % (x) for x in test.pub]) + r'",'
        )
        print(f"    .ok      = {1 if test.ok else 0} }},")

    print(r"  {0}")
    print(r"};")


def main():
    with open("src/ballet/ed25519/test_ed25519_wycheproof.c", "w") as out:
        with redirect_stdout(out):
            _gen_ed25519()


if __name__ == "__main__":
    root = Path(__file__).parents[2]
    os.chdir(root)
    main()
