# Enable debug assertions
CPPFLAGS+=-DFD_DCHECK_STYLE=1
# Enable heavy checks
CPPFLAGS+=-DFD_SCRATCH_USE_HANDHOLDING=1
CPPFLAGS+=-DFD_SPAD_USE_HANDHOLDING=1
CPPFLAGS+=-DFD_TMPL_USE_HANDHOLDING=1
CPPFLAGS+=-DFD_RUNTIME_ERR_HANDHOLDING=1
CPPFLAGS+=-DFD_GUI_USE_HANDHOLDING=1
CPPFLAGS+=-DFD_REASM_USE_HANDHOLDING=1
