#!/bin/bash

if [ ! -f tmp/test_mux_ipc.conf ]; then
  echo "not initialized"
  exit 1
fi

. tmp/test_mux_ipc.conf
FD_LOG_PATH=""
export FD_LOG_PATH

"$BIN"/fd_wksp_ctl delete "$WKSP" || exit $?
rm tmp/test_mux_ipc.conf

echo pass
