name: Clusterfuzz
on:
  workflow_call:
  workflow_dispatch:
jobs:
  publish:
    name: Build Fuzzers for ${{ matrix.feature_set }} feature set
    strategy:
      matrix:
        feature_set: [modern, highend]
    runs-on:
      group: github-v1
    env:
      MACHINE: linux_clang_combi_${{ matrix.feature_set }}
      EXTRAS: fuzz asan ubsan
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/hugepages
      - uses: ./.github/actions/deps

      - run: sudo apt update && sudo apt install -y zip

      - uses: firedancer-io/fuzzbot-builder@main
        name: Build fuzz tests
        with:
          command: make -j -Otarget fuzz-test

      - uses: firedancer-io/fuzzbot-builder@main
        name: Build rust fuzz tests
        with:
          command: ./.github/workflows/scripts/build_rust_fuzz_highend.sh
        if: ${{ matrix.feature_set == 'highend' }}

      - name: List Artifacts
        run: |
          ls build/linux/clang/combi/${{ matrix.feature_set }}/fuzz-test

      - uses: firedancer-io/clusterfuzz-action@main
        name: Upload fuzz targets to ClusterFuzz
        with:
          bucket-name: firedancer-builds.isol-clusterfuzz.appspot.com
          artifact-dir: build/linux/clang/combi/${{ matrix.feature_set }}/fuzz-test
          object-prefix: main/libfuzzer/${{ matrix.feature_set }}/firedancer
          project-id: isol-clusterfuzz
          qualifier: ${{ matrix.feature_set }}
          service-account-credentials: ${{ secrets.FUZZ_SERVICE_ACCT_JSON_BUNDLE }}
