name: Test Unit
on:
  workflow_call:
  workflow_dispatch:
jobs:
  test-unit:
    continue-on-error: true
    strategy:
      matrix:
        feature_set: [modern, highend]
        compiler: [gcc, clang]
      fail-fast: true
    runs-on:
      group: ${{ matrix.feature_set == 'highend' && 'rhel85-icelake' || 'github-v1' }}
    env:
      MACHINE: linux_clang_combi_${{ matrix.feature_set }}
      CC: ${{ matrix.compiler }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: ./.github/actions/deps

      - name: Build unit tests
        run: make -j unit-test

      - uses: ./.github/actions/hugepages

      - name: Run unit tests
        run: |
          sudo prlimit --pid $$ --memlock=-1:-1
          ./test.sh -j --page-sz gigantic
