name: Test Unit w/ Sanitizers
on:
  workflow_call:
  workflow_dispatch:
jobs:
  test-with-sanitizers:
    # Only run sanitizer tests if the gcc tests passed
    continue-on-error: true
    strategy:
      matrix:
        feature_set: [modern, highend]
    runs-on:
      group: ${{ matrix.feature_set == 'highend' && 'rhel85-icelake' || 'github-v1' }}
    env:
      MACHINE: linux_clang_combi_${{ matrix.feature_set }}
      EXTRAS: asan ubsan
    steps:
      - run: lscpu

      - uses: actions/checkout@v4

      - uses: ./.github/actions/deps
      - uses: ./.github/actions/hugepages

      - name: Build unit tests
        run: make -j -Otarget unit-test

      - name: Run unit tests
        run: |
          sudo prlimit --pid $$ --memlock=-1:-1
          ./test.sh -j --page-sz gigantic
