name: Test Fuzz Regressions
on:
  workflow_call:
  workflow_dispatch:
jobs:
  test-fuzz-regressions:
    name: Test Fuzz Regressions on ${{ matrix.feature_set }}
    strategy:
      matrix:
        feature_set: [modern, highend]
    runs-on:
      group: ${{ matrix.feature_set == 'highend' && 'rhel85-icelake' || 'github-v1' }}
    env:
      MACHINE: linux_clang_combi_${{ matrix.feature_set }}
      EXTRAS: fuzz asan ubsan
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/deps
      - uses: ./.github/actions/hugepages

      - name: Build Fuzz Tests
        run: make -j -Otarget fuzz-test

      - name: Run Fuzz Tests Against Corpora
        run: |
          sudo prlimit --pid $$ --memlock=-1:-1
          make -k -j -Otarget run-fuzz-test
