name: Replay Ledgers
on:
  workflow_call:
    inputs:
      machine:
        type: string
        default: "linux_gcc_zen2"
      extras:
        type: string
        default: "handholding"
      shmem_path:
        type: string
        default: "/data/svc_firedancer/mnt/.fd"
  workflow_dispatch:
jobs:
  backtest-ledger-replay:
    timeout-minutes: 15
    runs-on: [self-hosted, 512G]
    env:
      CC: gcc
      MACHINE: ${{ inputs.machine }}
      EXTRAS: ${{ inputs.extras }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: ./.github/actions/deps
        with:
          extras: +dev

      - uses: ./.github/actions/cpusonline

      - name: build
        run: |
          make -j all firedancer-dev

      - name: find OBJDIR
        run: |
          echo OBJDIR=$(make help | grep OBJDIR | awk '{print $4}') >> $GITHUB_ENV

      - name: test replay ledgers
        env:
          FD_SHMEM_PATH: "${{ inputs.shmem_path }}"
        run: |
          sudo prlimit --pid=$$ --nofile=1048576
          sudo prlimit --pid=$$ --memlock=unlimited
          DUMP_DIR=../dump make run-runtime-backtest

      - name: cleanup shmem pages
        if: always()
        run: |
          CONFIG_TOML=$(ls -lt ../dump/*.toml | head -n1 | awk '{print $NF}')
          sudo $OBJDIR/bin/firedancer-dev configure fini all --config $CONFIG_TOML

      # - name: cleanup shmem pages again
      #   if: always()
      #   uses: ./.github/actions/hugepages
      #   with:
      #     action: cleanup
      #     shmem_path: "${{ inputs.shmem_path }}"
