name: Bazel Build
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  bazel-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: bazelbuild/setup-bazelisk@v2

      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel-build-ubuntu-2204

      - name: Build everything
        run: bazel build //...
