# Builds for all compilers, architectures and targets

name: Builds
on:
  workflow_call:
    inputs:
      cid:
        type: string
        description: Unique identifier to allow concurrency
        default: "0"
      gcc:
        type: string
        description: GCC versions to use
        default: all
      clang:
        type: string
        description: Clang versions to use
        default: all
      machine:
        type: string
        description: Machines to build for
        default: all
      gcc_exceptions:
        type: string
        description: Exception groups for gcc
        default: none
      clang_exceptions:
        type: string
        description: Exception groups for clang
        default: none
      build_arm:
        type: boolean
        description: Run arm builds
        default: false
      dry_run:
        type: boolean
        description: Print build matrix and exit
        default: false
      check_run:
        type: boolean
        description: Run `make check` instead of full builds
        default: false
      exit_on_err:
        type: boolean
        description: Exit on the first error
        default: false
      no_optimization:
        type: boolean
        description: Compile with optimizations disabled
        default: false
      verbose:
        type: boolean
        description: Show output from failed builds
        default: false
      gcc_runner_labels:
        type: string
        description: Runner labels where gcc jobs will get scheduled
        default: '["self-hosted", "X64", "rocky9"]'
      clang_runner_labels:
        type: string
        description: Runner labels where clang jobs will get scheduled
        default: '["self-hosted", "X64", "rocky9"]'
  workflow_dispatch:
    inputs:
      cid:
        type: string
        description: Unique identifier to allow concurrency
        default: "0"
      gcc:
        type: string
        description: GCC versions to use (comma-separated | none | all)
        default: all
      clang:
        type: string
        description: Clang versions to use (comma-separated | none | all)
        default: all
      machine:
        type: string
        description: Machines to build for (comma-separated | all)
        default: all
      gcc_exceptions:
        type: string
        description: Exception groups for gcc (comma-separated and semi-colon delimited | none)
        default: none
      clang_exceptions:
        type: string
        description: Exception groups for clang (comma-separated and semi-colon delimited | none)
        default: none
      build_arm:
        type: boolean
        description: Run arm builds
        default: false
      dry_run:
        type: boolean
        description: Print build matrix and exit
        default: false
      check_run:
        type: boolean
        description: Run `make check` instead of full builds
        default: false
      exit_on_err:
        type: boolean
        description: Exit on the first error
        default: false
      no_optimization:
        type: boolean
        description: Compile with optimizations disabled
        default: false
      verbose:
        type: boolean
        description: Show output from failed builds
        default: false
      gcc_runner_labels:
        type: string
        description: Runner labels where gcc jobs will get scheduled
        default: '["self-hosted", "X64", "rocky9"]'
      clang_runner_labels:
        type: string
        description: Runner labels where clang jobs will get scheduled
        default: '["self-hosted", "X64", "rocky9"]'
concurrency:
  group: builds_${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ inputs.cid }}
  cancel-in-progress: true
jobs:
  build_gcc:
    runs-on:
      labels: ${{ fromJSON(inputs.gcc_runner_labels) }}
      group: fd-public-repo
    if: ${{ inputs.gcc != 'none' }}
    steps:
      - uses: actions/checkout@v7

      - uses: ./.github/actions/submodule-init

      - uses: dtolnay/rust-toolchain@1.95.0

      - uses: ./.github/actions/deps
        with:
          compiler: gcc
          compiler-version: 12.4.0
          extras: +dev

      - name: Build command line args
        env:
          DRY_RUN: ${{ inputs.dry_run }}
          CHECK_RUN: ${{ inputs.check_run }}
          EXIT_ON_ERR: ${{ inputs.exit_on_err }}
          MACHINE: ${{ inputs.machine }}
          GCC: ${{ inputs.gcc }}
          NO_OPTIMIZATION: ${{ inputs.no_optimization }}
          VERBOSE: ${{ inputs.verbose }}
          GCC_EXCEPTIONS: ${{ inputs.gcc_exceptions }}
        run: |
          ARGS=""
          # dry-run
          if [ "$DRY_RUN" == "true" ]; then
            ARGS="$ARGS --dry-run"
          fi
          # check-run
          if [ "$CHECK_RUN" == "true" ]; then
            ARGS="$ARGS --check-run --no-deps"
          fi
          # exit-on-err
          if [ "$EXIT_ON_ERR" == "true" ]; then
            ARGS="$ARGS --exit-on-err"
          fi
          # machine
          if [ ! -z "$MACHINE" ] && [ "$MACHINE" != "all" ]; then
            ARGS="$ARGS --machines $MACHINE"
          fi
          # gcc
          if [ ! -z "$GCC" ] && [ "$GCC" != "all" ]; then
            ARGS="$ARGS --gcc-versions $GCC"
          fi
          # no-optimization
          if [ "$NO_OPTIMIZATION" == "true" ]; then
            ARGS="$ARGS --no-optimization"
          fi
          # verbose
          if [ "$VERBOSE" == "true" ]; then
            ARGS="$ARGS --verbose"
          fi
          # exceptions
          if [ ! -z "$GCC_EXCEPTIONS" ] && [ "$GCC_EXCEPTIONS" != "none" ]; then
            no_spaces=$(tr -d '[:space:]' <<< "$GCC_EXCEPTIONS")
            IFS=';' read -r -a exceptions <<< "$no_spaces"
            for exception in ${exceptions[@]}; do
              ARGS="$ARGS --gcc-except $exception"
            done
          fi
          echo "BUILD_ARGS=$ARGS" >> $GITHUB_ENV

      - name: Run gcc builds
        run: |
          contrib/build.sh --no-rust --no-clang ${{ env.BUILD_ARGS }}

  build_clang:
    runs-on:
      labels: ${{ fromJSON(inputs.clang_runner_labels) }}
      group: fd-public-repo
    if: ${{ inputs.clang != 'none' }}
    steps:
      - uses: actions/checkout@v7

      - uses: ./.github/actions/submodule-init

      - uses: dtolnay/rust-toolchain@1.95.0

      - uses: ./.github/actions/deps
        with:
          compiler: clang
          compiler-version: 18.1.6
          extras: +dev

      - name: Build command line args
        env:
          DRY_RUN: ${{ inputs.dry_run }}
          CHECK_RUN: ${{ inputs.check_run }}
          EXIT_ON_ERR: ${{ inputs.exit_on_err }}
          MACHINE: ${{ inputs.machine }}
          CLANG: ${{ inputs.clang }}
          NO_OPTIMIZATION: ${{ inputs.no_optimization }}
          VERBOSE: ${{ inputs.verbose }}
          CLANG_EXCEPTIONS: ${{ inputs.clang_exceptions }}
        run: |
          ARGS=""
          # dry-run
          if [ "$DRY_RUN" == "true" ]; then
            ARGS="$ARGS --dry-run"
          fi
          # check-run
          if [ "$CHECK_RUN" == "true" ]; then
            ARGS="$ARGS --check-run --no-deps"
          fi
          # exit-on-err
          if [ "$EXIT_ON_ERR" == "true" ]; then
            ARGS="$ARGS --exit-on-err"
          fi
          # machine
          if [ ! -z "$MACHINE" ] && [ "$MACHINE" != "all" ]; then
            ARGS="$ARGS --machines $MACHINE"
          fi
          # clang
          if [ ! -z "$CLANG" ] && [ "$CLANG" != "all" ]; then
            ARGS="$ARGS --clang-versions $CLANG"
          fi
          # no-optimization
          if [ "$NO_OPTIMIZATION" == "true" ]; then
            ARGS="$ARGS --no-optimization"
          fi
          # verbose
          if [ "$VERBOSE" == "true" ]; then
            ARGS="$ARGS --verbose"
          fi
          # exceptions
          if [ ! -z "$CLANG_EXCEPTIONS" ] && [ "$CLANG_EXCEPTIONS" != "none" ]; then
            no_spaces=$(tr -d '[:space:]' <<< "$CLANG_EXCEPTIONS")
            IFS=';' read -r -a exceptions <<< "$no_spaces"
            for exception in ${exceptions[@]}; do
              ARGS="$ARGS --clang-except $exception"
            done
          fi
          echo "BUILD_ARGS=$ARGS" >> $GITHUB_ENV

      - name: Run clang builds
        run: |
          contrib/build.sh --no-rust --no-gcc ${{ env.BUILD_ARGS }}

  build_arm:
    runs-on:
      labels: ARM64
      group: fd-public-repo
    if: ${{ inputs.build_arm }}
    strategy:
      matrix:
        gcc_version: [12]
    steps:
      - uses: actions/checkout@v7

      - uses: ./.github/actions/submodule-init

      - name: Run build
        env:
          MACHINE: linux_gcc_neoverse_n2
        run: |
          if [ "${{ matrix.gcc_version }}" != "8" ]; then
            source /opt/rh/gcc-toolset-${{ matrix.gcc_version }}/enable
          fi
          ./deps.sh fetch install
          make -j clean
          make -j all
