name: CBMC Proofs
on:
  pull_request:

jobs:
  check-cbmc:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Check Proofs
        run: |
          cbmc --version
          make -j proof
        shell: bash
