name: Make Fuzz Artifacts
on:
  pull_request:
  push:
  workflow_dispatch:
  merge_group:
jobs:
  make-with-sanitizer:
    runs-on: ubuntu-latest
    steps:
      - name: Install zip
        run: |
          sudo apt update
          sudo apt install -y zip

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: dtolnay/rust-toolchain@1.69.0

      - uses: firedancer-io/alpine-builder@main
        name: Build with ASAN on Alpine
        env:
          MACHINE: linux_clang_x86_64_fuzz_asan
        with:
          command: make --output-sync=target -j fuzz-test

      - name: List Artifacts
        run: |
          ls build/linux/clang/x86_64_fuzz_asan/fuzz-test

      - uses: firedancer-io/clusterfuzz-action@main
        if: ${{ github.ref == 'refs/heads/main' }}
        name: Publish asan artifacts to ClusterFuzz
        with:
          bucket-name: firedancer-builds.isol-clusterfuzz.appspot.com
          artifact-dir: build/linux/clang/x86_64_fuzz_asan/fuzz-test
          object-prefix: main/libfuzzer-asan/firedancer
          project-id: isol-clusterfuzz
          service-account-credentials: ${{ secrets.FUZZ_SERVICE_ACCT_JSON_BUNDLE }}
