name: Make Fuzz Test
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
  merge_group:
jobs:
  make-fuzz-test:
    runs-on: [self-hosted, Linux, X64]
    defaults:
      run:
        shell: sudo bash --noprofile --norc -eo pipefail -c "set -ex; source /home/runner/firedancer-opts/activate-opt && chmod +x {0} && {0}"
    steps:
      - uses: actions/checkout@v3

      - name: Copy prebuilt deps
        run: "cp -r /home/runner/firedancer-opts/opt . && ls -lah opt"

      - name: Build fuzz tests
        run: MACHINE=linux_clang_x86_64_fuzz_asan make -j fuzz-test

      - uses: firedancer-io/clusterfuzz-action@main
        name: Publish to ClusterFuzz
        with:
          bucket-name: firedancer-builds.isol-clusterfuzz.appspot.com
          artifact-dir: build/linux/clang/x86_64_fuzz_asan/fuzz-test
          object-prefix: main/libfuzzer-asan/firedancer
          project-id: isol-clusterfuzz
          service-account-credentials: ${{ secrets.FUZZ_SERVICE_ACCT_JSON_BUNDLE }}
