name: Make Build
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  make-build:
    strategy:
      matrix:
        compiler: [gcc, clang]
    runs-on: [self-hosted, bare-metal, Linux, X64]
    defaults:
      run:
        shell: nix-shell --command "bash --noprofile --norc -eo pipefail {0}"
    env:
      EXTRAS: libbpf
    steps:
      - uses: actions/checkout@v3

      - name: Build everything
        run: make -j MACHINE=linux_${{ matrix.compiler }}_x86_64
