name: Make Build
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
  merge_group:
jobs:
  make-build:
    strategy:
      matrix:
        compiler: [gcc, clang]
    runs-on: [self-hosted, Linux, X64]
    env:
      CC: ${{ matrix.compiler }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: dtolnay/rust-toolchain@1.69.0

      - uses: ./.github/actions/deps

      - name: Build everything
        run: make -j
