name: Make Fuzz Test
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
  merge_group:
jobs:
  make-fuzz-test:
    runs-on: [self-hosted, Linux, X64]
    defaults:
      run:
        shell: sudo bash --noprofile --norc -eo pipefail -c "set -ex; source /home/runner/firedancer-opts/activate-opt && chmod +x {0} && {0}"
    steps:
      - uses: actions/checkout@v3

      - name: Copy prebuilt deps
        run: "cp -r /home/runner/firedancer-opts/opt . && ls -lah opt"

      - name: Build fuzz tests
        run: MACHINE=linux_clang_fuzz_asan make -j fuzz-test
