name: Make Build
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  make-build:
    strategy:
      matrix:
        compiler: [gcc, clang]
    runs-on: [self-hosted, Linux, X64]
    defaults:
      run:
        shell: nix-shell --pure --run "bash --noprofile --norc -eo pipefail {0}"
    env:
      MACHINE: linux_${{ matrix.compiler }}_x86_64
      EXTRAS: libbpf
    steps:
      - uses: actions/checkout@v3

      - name: Build everything
        run: make -j
