name: Make Build
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  make-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install deps
        run: sudo apt-get install -y libnuma-dev

      - name: Build everything
        run: make -j
