name: Make Build
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  make-build:
    strategy:
      matrix:
        compiler: [gcc, clang]
    runs-on: [self-hosted, Linux, X64]
    defaults:
      run:
        shell: bash --noprofile --norc -eo pipefail -c "set -ex; source /home/runner/firedancer-opts/activate-opt && echo `pwd` && ls -lah {0} && chmod +x {0} && {0}"
        
    env:
      MACHINE: linux_${{ matrix.compiler }}_x86_64
      EXTRAS: libbpf
    steps:
      - uses: actions/checkout@v3
      
      - name: Copy prebuilt deps
        run: "cp -r /home/runner/firedancer-opts/opt . && ls -lah opt"

      - name: Build everything
        run: make -j
