name: Make Coverage
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  make-test-coverage:
    runs-on: [self-hosted, Linux, X64]
    defaults:
      run:
        shell: sudo bash --noprofile --norc -eo pipefail -c "export MACHINE=linux_clang_x86_64; export EXTRAS=llvm-cov; set -ex; source /home/runner/firedancer-opts/activate-opt && chmod +x {0} && {0}"
    steps:
      - uses: actions/checkout@v3

      - name: Copy prebuilt deps
        run: "cp -r /home/runner/firedancer-opts/opt . && ls -lah opt"

      - name: Build everything
        run: make -j

      - name: Run unit tests
        run: make -k -j4 --output-sync=target run-unit-test

      - name: Make coverage report
        run: |
          make cov-report
          mv build/linux/clang/x86_64/cov/html coverage-report

      - name: Upload coverage HTML report as GitHub artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage-report

      - name: Upload coverage report to CodeCov
        uses: codecov/codecov-action@v3
        timeout-minutes: 5
        with:
          files: build/linux/clang/x86_64/cov/cov.lcov
          name: codecov-make-linux_clang-14_x86_64
          fail_ci_if_error: false
          functionalities: search

  publish-coverage:
    runs-on: ubuntu-22.04
    needs: [make-test-coverage]
    if: github.ref == 'refs/heads/main'

    permissions:
      pages: write     # to deploy to Pages
      id-token: write  # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download coverage report
        uses: actions/download-artifact@v3
        with:
          name: coverage-report
          path: _site/coverage-report

      - name: Re-package coverage report
        uses: actions/upload-pages-artifact@v2
        with:
          path: _site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
