# Kick off a daily battery of extended tests.
# Only runs if latest commit was made within today.

name: On Daily Change
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  # Ensures that cron job is skipped if no commit was made on that day.
  check-date:
    runs-on: ubuntu-latest
    name: Check date of last commit
    steps:
      - uses: actions/checkout@v3
      - id: should_run
        continue-on-error: true
        name: check latest commit is less than a day
        if: ${{ github.event_name == 'schedule' }}
        run: test -z $(git rev-list --after="24 hours" ${{ github.sha }}) && echo "::set-output name=should_run::false"
    outputs:
      should_run: ${{ github.event_name != 'schedule' || steps.should_run.outputs.should_run }}

  call-codeql:
    needs: check-date
    if: needs.check-date.outputs.should_run == 'true'
    uses: ./.github/workflows/_codeql.yml
    secrets: inherit
