name: Tests with Sanitizers
on:
  merge_group:
    types: [checks_requested]
  workflow_dispatch:

jobs:
# Tests with AddressSanitizer
  make-test-asan:
    runs-on:
      group: github-v1
    env:
      MACHINE: linux_clang_x86_64_asan
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/deps

      - name: Build unit tests
        run: make -j -Otarget unit-test

      - uses: ./.github/actions/hugepages

      - name: Run unit tests
        run: |
          sudo prlimit --pid $$ --memlock=-1:-1
          ./test.sh -j --page-sz gigantic

  # Tests with UndefinedBehaviorSanitizer
  make-test-ubsan:
    runs-on:
      group: github-v1
    env:
      MACHINE: linux_clang_x86_64_ubsan
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/deps

      - name: Build unit tests
        run: make -j -Otarget unit-test

      - uses: ./.github/actions/hugepages

      - name: Run unit tests
        run: |
          sudo prlimit --pid $$ --memlock=-1:-1
          ./test.sh -j --page-sz gigantic
