name: Firedancer
on:
  workflow_call:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  firedancer-tests:
    runs-on: [self-hosted, 512G]
    if: github.event.pull_request.draft == false
    env:
      CC: gcc
      EXTRAS: no-solana
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: ./.github/actions/deps

      - name: build
        run: |
          ./contrib/make-j fddev

      - name: stop any dead runs - local cluster
        run: |
          sudo killall -9 -q solana-validator || true
          sudo killall -9 -q fddev || true

      - uses: ./.github/actions/hugepages
        with:
          count_gigantic: 128
          count_huge: 500 # TODO: this is required until we can handle anonymouse workspaces and loose huge pages in fddev

      - name: test firedancer - local cluster
        run: |
          sudo prlimit --pid=$$ --nofile=1048576
          sudo prlimit --pid=$$ --memlock=unlimited
          ./contrib/test/test_firedancer.sh
