# Run integration tests.
# When these tests are stable and no longer require Rust, run them as
# part of the regular unit tests.

name: Integration Tests
on:
  workflow_call:
  workflow_dispatch:
jobs:
  test_fddev:
    runs-on:
      group: github-v1
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install ausearch for debugging seccomp/bad syscalls
        run: sudo apt update && sudo apt install -y auditd

      - uses: dtolnay/rust-toolchain@1.73.0

      - uses: ./.github/actions/deps

      - run: contrib/make-j fddev
      - run: make run-integration-test
